### ISSUE TITLE
SQL Alchemy cannot parse CREATE TABLE statement with foreign key constraint

### ISSUE THREAD

**Issue by oscarbatori** [dolthub/dolt#1104]
### Dolt
Create a Dolt database with the following tables, and fire up the server:
```sql
CREATE TABLE `parent` (
  `id` INT,
  `name` VARCHAR(32),
  PRIMARY KEY (`id`)
)

CREATE TABLE `child` (
  `id` INT,
  `parent_id` INT,
  `other_name` VARCHAR(32),
  PRIMARY KEY (`id`),
  CONSTRAINT `parent_ref` FOREIGN KEY (`parent_id`) REFERENCES `parent` (`id`)
)
```

### Python
Install `sqlalchemy` via `pip`, and then execute the following:
```python
engine = sa.create_engine('mysql+mysqlconnector://root@127.0.0.1/<db_name>')
metadata = MetaData(bind=engine)
metadata.reflect()
```

The Python produces the following error:
```
Traceback (most recent call last):
  File "/Users/oscarbatori/anaconda3/envs/doltpy-dev/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1204, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/Users/oscarbatori/anaconda3/envs/doltpy-dev/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 1029, in _init_statement
    self.cursor = self.create_cursor()
  File "/Users/oscarbatori/anaconda3/envs/doltpy-dev/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 1162, in create_cursor
    return self._dbapi_connection.cursor()
  File "/Users/oscarbatori/anaconda3/envs/doltpy-dev/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 1000, in cursor
    return self.connection.cursor(*args, **kwargs)
  File "/Users/oscarbatori/anaconda3/envs/doltpy-dev/lib/python3.8/site-packages/mysql/connector/connection_cext.py", line 541, in cursor
    raise errors.OperationalError("MySQL Connection not available.")
mysql.connector.errors.OperationalError: MySQL Connection not available.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/oscarbatori/Desktop/test_sql_alchemy.py", line 5, in <module>
    metadata.reflect()
  File "/Users/oscarbatori/anaconda3/envs/doltpy-dev/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 4511, in reflect
    Table(name, self, **reflect_opts)
  File "<string>", line 2, in __new__
  File "/Users/oscarbatori/anaconda3/envs/doltpy-dev/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 139, in warned
    return fn(*args, **kwargs)
  File "/Users/oscarbatori/anaconda3/envs/doltpy-dev/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 560, in __new__
    metadata._remove_table(name, schema)
  File "/Users/oscarbatori/anaconda3/envs/doltpy-dev/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/Users/oscarbatori/anaconda3/envs/doltpy-dev/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/Users/oscarbatori/anaconda3/envs/doltpy-dev/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 555, in __new__
    table._init(name, metadata, *args, **kw)
  File "/Users/oscarbatori/anaconda3/envs/doltpy-dev/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 644, in _init
    self._autoload(
  File "/Users/oscarbatori/anaconda3/envs/doltpy-dev/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 667, in _autoload
    autoload_with.run_callable(
  File "/Users/oscarbatori/anaconda3/envs/doltpy-dev/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1653, in run_callable
    return callable_(self, *args, **kwargs)
  File "/Users/oscarbatori/anaconda3/envs/doltpy-dev/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 469, in reflecttable
    return insp.reflecttable(
  File "/Users/oscarbatori/anaconda3/envs/doltpy-dev/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 684, in reflecttable
    self._reflect_fk(
  File "/Users/oscarbatori/anaconda3/envs/doltpy-dev/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 868, in _reflect_fk
    sa_schema.Table(
  File "<string>", line 2, in __new__
  File "/Users/oscarbatori/anaconda3/envs/doltpy-dev/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 139, in warned
    return fn(*args, **kwargs)
  File "/Users/oscarbatori/anaconda3/envs/doltpy-dev/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 560, in __new__
    metadata._remove_table(name, schema)
  File "/Users/oscarbatori/anaconda3/envs/doltpy-dev/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/Users/oscarbatori/anaconda3/envs/doltpy-dev/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/Users/oscarbatori/anaconda3/envs/doltpy-dev/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 555, in __new__
    table._init(name, metadata, *args, **kw)
  File "/Users/oscarbatori/anaconda3/envs/doltpy-dev/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 644, in _init
    self._autoload(
  File "/Users/oscarbatori/anaconda3/envs/doltpy-dev/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 667, in _autoload
    autoload_with.run_callable(
  File "/Users/oscarbatori/anaconda3/envs/doltpy-dev/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1653, in run_callable
    return callable_(self, *args, **kwargs)
  File "/Users/oscarbatori/anaconda3/envs/doltpy-dev/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 469, in reflecttable
    return insp.reflecttable(
  File "/Users/oscarbatori/anaconda3/envs/doltpy-dev/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 647, in reflecttable
    tbl_opts = self.get_table_options(
  File "/Users/oscarbatori/anaconda3/envs/doltpy-dev/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 312, in get_table_options
    return self.dialect.get_table_options(
  File "<string>", line 2, in get_table_options
  File "/Users/oscarbatori/anaconda3/envs/doltpy-dev/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 52, in cache
    ret = fn(self, con, *args, **kw)
  File "/Users/oscarbatori/anaconda3/envs/doltpy-dev/lib/python3.8/site-packages/sqlalchemy/dialects/mysql/base.py", line 2746, in get_table_options
    parsed_state = self._parsed_state_or_create(
  File "/Users/oscarbatori/anaconda3/envs/doltpy-dev/lib/python3.8/site-packages/sqlalchemy/dialects/mysql/base.py", line 2989, in _parsed_state_or_create
    return self._setup_parser(
  File "<string>", line 2, in _setup_parser
  File "/Users/oscarbatori/anaconda3/envs/doltpy-dev/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 52, in cache
    ret = fn(self, con, *args, **kw)
  File "/Users/oscarbatori/anaconda3/envs/doltpy-dev/lib/python3.8/site-packages/sqlalchemy/dialects/mysql/base.py", line 3020, in _setup_parser
    sql = self._show_create_table(
  File "/Users/oscarbatori/anaconda3/envs/doltpy-dev/lib/python3.8/site-packages/sqlalchemy/dialects/mysql/base.py", line 3119, in _show_create_table
    rp = connection.execution_options(
  File "/Users/oscarbatori/anaconda3/envs/doltpy-dev/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1003, in execute
    return self._execute_text(object_, multiparams, params)
  File "/Users/oscarbatori/anaconda3/envs/doltpy-dev/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1172, in _execute_text
    ret = self._execute_context(
  File "/Users/oscarbatori/anaconda3/envs/doltpy-dev/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1206, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/oscarbatori/anaconda3/envs/doltpy-dev/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/Users/oscarbatori/anaconda3/envs/doltpy-dev/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/Users/oscarbatori/anaconda3/envs/doltpy-dev/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1204, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/Users/oscarbatori/anaconda3/envs/doltpy-dev/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 1029, in _init_statement
    self.cursor = self.create_cursor()
  File "/Users/oscarbatori/anaconda3/envs/doltpy-dev/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 1162, in create_cursor
    return self._dbapi_connection.cursor()
  File "/Users/oscarbatori/anaconda3/envs/doltpy-dev/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 1000, in cursor
    return self.connection.cursor(*args, **kwargs)
  File "/Users/oscarbatori/anaconda3/envs/doltpy-dev/lib/python3.8/site-packages/mysql/connector/connection_cext.py", line 541, in cursor
    raise errors.OperationalError("MySQL Connection not available.")
sqlalchemy.exc.OperationalError: (mysql.connector.errors.OperationalError) MySQL Connection not available.
[SQL: SHOW CREATE TABLE `parent`]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
```

**Comment by VinaiRachakonda** [comment]
Reran these queries and they are not fixed.
