### ISSUE TITLE
show indexes crash

### ISSUE THREAD

**Issue by bheni** [dolthub/dolt#1219]
`dolt init` a new database and run `dolt sql`

```~/datasets/test>dolt sql
# Welcome to the DoltSQL shell.
# Statements must be terminated with ';'.
# "exit" or "quit" (or Ctrl-D) to exit.
test> show tables;
+-------+
| Table |
+-------+
+-------+
test> CREATE TABLE dtest1 (
   ->     id INT NOT NULL,
   ->     tiny_int_col TINYINT NOT NULL,
   ->     small_int_col SMALLINT NOT NULL,
   ->     medium_int_col MEDIUMINT NOT NULL,
   ->     int_col INT NOT NULL,
   ->     big_int_col BIGINT NOT NULL,
   ->     decimal_col DECIMAL NOT NULL,
   ->     float_col FLOAT NOT NULL,
   ->     double_col DOUBLE NOT NULL,
   ->     bit_col BIT NOT NULL,
   ->     char_col CHAR NOT NULL,
   ->     var_char_col VARCHAR(64) NOT NULL,
   ->     tiny_text_col TINYTEXT NOT NULL,
   ->     text_col TEXT NOT NULL,
   ->     medium_text_col MEDIUMTEXT NOT NULL,
   ->     long_text_col LONGTEXT NOT NULL,
   ->     enum_col ENUM('enum_val0', 'enum_val1', 'enum_val2') NOT NULL,
   ->     set_col SET('set_val0', 'set_val1', 'set_val2') NOT NULL,
   ->     date_col DATE NOT NULL,
   ->     time_col TIME NOT NULL,
   ->     datetime_col DATETIME NOT NULL,
   ->     timestamp_col TIMESTAMP NOT NULL,
   ->     year_col YEAR NOT NULL,
   ->
   ->     PRIMARY KEY(id),
   ->     INDEX (big_int_col)
   -> );
test> show indexes from dtest1;
panic: runtime error: index out of range [2] with length 2

goroutine 942 [running]:
github.com/dolthub/go-mysql-server/sql/plan.(*indexesToShow).next(0xc000222390, 0x0, 0x288f740, 0xc000078110)
	/Users/brian/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.6.1-0.20210111233644-2521a795ebaf/sql/plan/show_indexes.go:175 +0x22f
github.com/dolthub/go-mysql-server/sql/plan.(*showIndexesIter).Next(0xc0004bdf60, 0xc000799740, 0xc000557e90, 0xc000557d30, 0x105062c, 0xa0)
	/Users/brian/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.6.1-0.20210111233644-2521a795ebaf/sql/plan/show_indexes.go:90 +0x47
github.com/dolthub/go-mysql-server/sql/plan.(*trackedRowIter).Next(0xc0002223c0, 0x0, 0xa, 0xc000469180, 0x288f740, 0xc000078110)
	/Users/brian/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.6.1-0.20210111233644-2521a795ebaf/sql/plan/process.go:203 +0x38
github.com/dolthub/dolt/go/cmd/dolt/commands.getReadStageFunc.func1(0x28be140, 0xc000222540, 0x0, 0x0, 0x0, 0xc000468c80, 0x2, 0xa, 0x0, 0x0)
	/Users/brian/dev/dolt/go/cmd/dolt/commands/sql_print.go:99 +0xc6
github.com/dolthub/dolt/go/libraries/utils/pipeline.(*Stage).runFirstStageInPipeline(0xc00069f260, 0x28be140, 0xc000222540, 0x1, 0xc000388758)
	/Users/brian/dev/dolt/go/libraries/utils/pipeline/stage.go:124 +0xb5
github.com/dolthub/dolt/go/libraries/utils/pipeline.(*Stage).start.func1(0x0, 0x0)
	/Users/brian/dev/dolt/go/libraries/utils/pipeline/stage.go:106 +0xe5
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0002224e0, 0xc000222570)
	/Users/brian/go/pkg/mod/golang.org/x/sync@v0.0.0-20201008141435-b3e1573b7520/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
	/Users/brian/go/pkg/mod/golang.org/x/sync@v0.0.0-20201008141435-b3e1573b7520/errgroup/errgroup.go:54 +0x66```

**Comment by timsehn** [comment]
@zachmu this fixed?

**Comment by bheni** [comment]
@timsehn  it is.
