### ISSUE TITLE
panic: star is just a placeholder node, but Eval was called - 0.22.8

### ISSUE THREAD

**Issue by alexis-evelyn** [dolthub/dolt#1235]
Using the query `select twitter_user_id, count(*) as count from government where count(*)!=1 group by twitter_user_id;` causes Dolt to crash. I now know the proper query is `select twitter_user_id, count(twitter_user_id) as count from government group by twitter_user_id having count!=1;`

dolt version 0.22.8
commit e6852f0bbf4d5f15deb81ccb24a37726ba0a94fa

```
presidential_tweets> select twitter_user_id, count(*) as count from government where count(*)!=1 group by twitter_user_id;
panic: star is just a placeholder node, but Eval was called

goroutine 1 [running]:
github.com/dolthub/go-mysql-server/sql/expression.(*Star).Eval(0xc002018f20, 0xc00063e1b0, 0x0, 0x0, 0x0, 0xc000d82400, 0x10, 0x10, 0x2475940)
	/Users/alexis/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.6.1-0.20210111233644-2521a795ebaf/sql/expression/star.go:55 +0x39
github.com/dolthub/go-mysql-server/sql/analyzer.evalFilter.func1.1(0x28d6d80, 0xc002018f20, 0x0, 0x0, 0x1010518, 0x10)
	/Users/alexis/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.6.1-0.20210111233644-2521a795ebaf/sql/analyzer/optimization_rules.go:279 +0xe8
github.com/dolthub/go-mysql-server/sql/expression.TransformUp(0x28d6d80, 0xc002018f20, 0xc00136e900, 0xc000d82400, 0x1010518, 0x20, 0x2327120)
	/Users/alexis/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.6.1-0.20210111233644-2521a795ebaf/sql/expression/transform.go:16 +0x233
github.com/dolthub/go-mysql-server/sql/expression.TransformUp(0x28d91e0, 0xc000d82270, 0xc00136e900, 0xc00127d8e0, 0x1010518, 0x10, 0x2323e20)
	/Users/alexis/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.6.1-0.20210111233644-2521a795ebaf/sql/expression/transform.go:21 +0xb5
github.com/dolthub/go-mysql-server/sql/expression.TransformUp(0x28d6780, 0xc00127d7c0, 0xc00136e900, 0xc000d823e0, 0xc000d823c0, 0xc00136e888, 0x1010518)
	/Users/alexis/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.6.1-0.20210111233644-2521a795ebaf/sql/expression/transform.go:21 +0xb5
github.com/dolthub/go-mysql-server/sql/expression.TransformUp(0x28d6c00, 0xc000d82280, 0xc00136e900, 0x28d6c00, 0x28d1f80, 0xc000d82280, 0xc0020188f0)
	/Users/alexis/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.6.1-0.20210111233644-2521a795ebaf/sql/expression/transform.go:21 +0xb5
github.com/dolthub/go-mysql-server/sql/analyzer.evalFilter.func1(0x28d1860, 0xc00127d8a0, 0x1, 0x1, 0x28d1860, 0xc00127d8a0)
	/Users/alexis/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.6.1-0.20210111233644-2521a795ebaf/sql/analyzer/optimization_rules.go:233 +0x7b
github.com/dolthub/go-mysql-server/sql/plan.TransformUp(0x28d1860, 0xc00127d880, 0xc00136eac0, 0xc000d823a0, 0x0, 0xc000d82300, 0xc00136ea00)
	/Users/alexis/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.6.1-0.20210111233644-2521a795ebaf/sql/plan/transform.go:34 +0x1e3
github.com/dolthub/go-mysql-server/sql/plan.TransformUp(0x28d1920, 0xc00124d7c0, 0xc00136eac0, 0xc000d82380, 0x0, 0x0, 0xc00127d850)
	/Users/alexis/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.6.1-0.20210111233644-2521a795ebaf/sql/plan/transform.go:22 +0xf3
github.com/dolthub/go-mysql-server/sql/plan.TransformUp(0x28d1e00, 0xc000489380, 0xc00136eac0, 0xc00136ead0, 0x100d45b, 0x10, 0x23172a0)
	/Users/alexis/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.6.1-0.20210111233644-2521a795ebaf/sql/plan/transform.go:22 +0xf3
github.com/dolthub/go-mysql-server/sql/analyzer.evalFilter(0xc00063e1b0, 0xc000180690, 0x28d1e00, 0xc000489380, 0x0, 0x1, 0xc000489380, 0x0, 0x0)
	/Users/alexis/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.6.1-0.20210111233644-2521a795ebaf/sql/analyzer/optimization_rules.go:227 +0x7c
github.com/dolthub/go-mysql-server/sql/analyzer.(*Batch).evalOnce(0xc0003f1890, 0xc00063e1b0, 0xc000180690, 0x28d1920, 0xc00124d100, 0x0, 0x28d1920, 0xc00124d100, 0x0, 0x0)
	/Users/alexis/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.6.1-0.20210111233644-2521a795ebaf/sql/analyzer/batch.go:78 +0x1c5
github.com/dolthub/go-mysql-server/sql/analyzer.(*Batch).Eval(0xc0003f1890, 0xc00063e1b0, 0xc000180690, 0x28d1920, 0xc00124cbc0, 0x0, 0x28d1920, 0xc00124cbc0, 0x0, 0x0)
	/Users/alexis/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.6.1-0.20210111233644-2521a795ebaf/sql/analyzer/batch.go:57 +0x26e
github.com/dolthub/go-mysql-server/sql/analyzer.(*Analyzer).Analyze(0xc000180690, 0xc00063e1b0, 0x28d1920, 0xc00124c980, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/alexis/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.6.1-0.20210111233644-2521a795ebaf/sql/analyzer/analyzer.go:273 +0x32c
github.com/dolthub/go-mysql-server.(*Engine).QueryWithBindings(0xc0003f1a10, 0xc00063e120, 0xc0001f5260, 0x65, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/alexis/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.6.1-0.20210111233644-2521a795ebaf/engine.go:195 +0x2f8
github.com/dolthub/go-mysql-server.(*Engine).Query(...)
	/Users/alexis/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.6.1-0.20210111233644-2521a795ebaf/engine.go:137
github.com/dolthub/dolt/go/cmd/dolt/commands.(*sqlEngine).query(0xc00000f680, 0xc0003ee630, 0xc0001f5260, 0x65, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc00136ef80, ...)
	/Users/alexis/executables/dolt/go/cmd/dolt/commands/sql.go:1203 +0x65
github.com/dolthub/dolt/go/cmd/dolt/commands.processQuery(0xc0003ee630, 0xc0001f5260, 0x65, 0xc00000f680, 0x0, 0x0, 0xffffffffffffffff, 0xc0001f5260, 0x65, 0xc000f8a340, ...)
	/Users/alexis/executables/dolt/go/cmd/dolt/commands/sql.go:818 +0xa14
github.com/dolthub/dolt/go/cmd/dolt/commands.runShell.func3(0xc000f8a340)
	/Users/alexis/executables/dolt/go/cmd/dolt/commands/sql.go:669 +0x1a5
github.com/dolthub/ishell.handleUninterpretedInput(0xc0004bd8c0, 0xc0001f5260, 0x65, 0x0, 0xc0026f4001)
	/Users/alexis/go/pkg/mod/github.com/dolthub/ishell@v0.0.0-20201107004254-1592c0036c8d/ishell.go:282 +0x146
github.com/dolthub/ishell.(*Shell).run(0xc0004bd8c0)
	/Users/alexis/go/pkg/mod/github.com/dolthub/ishell@v0.0.0-20201107004254-1592c0036c8d/ishell.go:242 +0x245
github.com/dolthub/ishell.(*Shell).Run(0xc0004bd8c0)
	/Users/alexis/go/pkg/mod/github.com/dolthub/ishell@v0.0.0-20201107004254-1592c0036c8d/ishell.go:136 +0x39
github.com/dolthub/dolt/go/cmd/dolt/commands.runShell(0xc0003ee630, 0xc00000f680, 0xc0003f14d0, 0xc00061f8b8, 0x0)
	/Users/alexis/executables/dolt/go/cmd/dolt/commands/sql.go:684 +0x64b
github.com/dolthub/dolt/go/cmd/dolt/commands.execShell(0xc0003ee630, 0x4200100, 0xc0003f14d0, 0xc00061f8b8, 0x0, 0x28dd300, 0xc00019d55c, 0x2303720)
	/Users/alexis/executables/dolt/go/cmd/dolt/commands/sql.go:335 +0xf1
github.com/dolthub/dolt/go/cmd/dolt/commands.SqlCmd.Exec(0x26231f3, 0x6, 0x28c6220, 0xc00051cea0, 0xc000164d98, 0x8, 0xc0001a8030, 0x0, 0x0, 0xc00026a0b0, ...)
	/Users/alexis/executables/dolt/go/cmd/dolt/commands/sql.go:308 +0x173d
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.Exec(0x26215a2, 0x4, 0x2636435, 0x11, 0xc0003d2480, 0x24, 0x24, 0x0, 0x28c6220, 0xc00051cea0, ...)
	/Users/alexis/executables/dolt/go/cmd/dolt/cli/command.go:165 +0x4bd
main.runMain(0x0)
	/Users/alexis/executables/dolt/go/cmd/dolt/dolt.go:251 +0xec9
main.main()
	/Users/alexis/executables/dolt/go/cmd/dolt/dolt.go:110 +0x25
```

**Comment by timsehn** [comment]
@doInfinitely is gonna grab this one.

**Comment by zachmu** [comment]
This definitely still exists.
