### ISSUE TITLE
Segmentation Fault when i try run dolt blame

### ISSUE THREAD

**Issue by doInfinitely** [dolthub/dolt#1260]
steps to reproduce:

dolt clone aleph_zero/hospital-price-transparency
cd hospital-price-transparency
dolt blame cpt_hcpcs

**Comment by timsehn** [comment]
I can repro the tip of master of `dolthub/hospital-price-transparency`.
```
PS C:\Users\timse\dolthub\dolt\hospital-price-transparency> dolt blame cpt_hcpcs
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x16166b3]

goroutine 1 [running]:
github.com/dolthub/dolt/go/cmd/dolt/commands.rowChanged(0x1de5540, 0xc0006340c0, 0xc00095d0a0, 0xc000969960, 0x20, 0xc000464850, 0xc000969920, 0x20, 0x1de5740, 0xc000efcf60, ...)
        C:/Users/timse/dolthub/git/dolt/go/cmd/dolt/commands/blame.go:459 +0x2f3
github.com/dolthub/dolt/go/cmd/dolt/commands.blameGraphFromCommit(0x1de5540, 0xc0006340c0, 0xc000694000, 0xc00095c070, 0xc0001140a0, 0x9, 0xc00095c070, 0x0, 0x0)
        C:/Users/timse/dolthub/git/dolt/go/cmd/dolt/commands/blame.go:242 +0x445
github.com/dolthub/dolt/go/cmd/dolt/commands.runBlame(0x1de5540, 0xc0006340c0, 0xc000694000, 0xc0004da450, 0xc0001140a0, 0x9, 0x0, 0x1)
        C:/Users/timse/dolthub/git/dolt/go/cmd/dolt/commands/blame.go:175 +0xe5
github.com/dolthub/dolt/go/cmd/dolt/commands.BlameCmd.Exec(0x1de5540, 0xc0006340c0, 0xc0005008e0, 0xa, 0xc000152020, 0x1, 0x2, 0xc000694000, 0xa)
        C:/Users/timse/dolthub/git/dolt/go/cmd/dolt/commands/blame.go:138 +0x365
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.Exec(0x1b3fc72, 0x4, 0x1b551f7, 0x11, 0xc00016eb40, 0x24, 0x24, 0x0, 0x1de5540, 0xc0006340c0, ...)
        C:/Users/timse/dolthub/git/dolt/go/cmd/dolt/cli/command.go:165 +0x4bd
main.runMain(0x0)
        C:/Users/timse/dolthub/git/dolt/go/cmd/dolt/dolt.go:251 +0xee9
main.main()
        C:/Users/timse/dolthub/git/dolt/go/cmd/dolt/dolt.go:110 +0x29
PS C:\Users\timse\dolthub\dolt\hospital-price-transparency> dolt log -n 1
commit 1qteptoenolq58h2ejavvpojn65o6vjm
Merge: 9182raotrbe9ag2sesi15dged4t2i3hr ia0lscglpfpj8jfven1r13rtbd8fdhf0
Author: aleph_zero <do.infinitely@gmail.com>
Date:   Tue Jan 26 17:07:52 -0800 2021

        Dolthub User: erpawer
        Accepted PR: 17
```

**Comment by timsehn** [comment]
This should be fixed by migrating dolt blame to the SQL path.
