### ISSUE TITLE
dolt table import with --no-gc deadlocks unexpectedly

### ISSUE THREAD

**Issue by alecstein** [dolthub/dolt#1709]
Not sure how to repro, because it doesn't happen all the time, or at any particular point. But, basically, `dolt table import -u --no-gc` intermittently gives up after importing < 500k rows, basically deadlocking, with no sign of what's causing the error.

I've been experimenting with larger amounts of RAM (32-64GB) and number of vCPUs (8-16) but it doesn't seem to be the limiting factor here. I've tried taking off the `--no-gc` flag, but I get issues there too.

My memory usage after ~7 hours of `dolt table import -u --no-gc`:
```
             total       used       free     shared    buffers     cached
Mem:           30G        26G       4.4G        76K       1.0G        19G
-/+ buffers/cache:       6.2G        24G
Swap:           0B         0B         0B
```
Despite the memory usage, no imports actually succeeded  as far as I could tell. 

`top` command:
```
 5466 ec2-user  20   0 5287m 4.5g  27m S 100.1 14.6 427:34.61 dolt                                                                                                                                
15192 root      20   0 2103m  19m 5740 S  0.7  0.1   2:04.15 chronicled                                                                                                                           
12387 ec2-user  20   0 15488 2352 1916 R  0.3  0.0   0:00.01 top                                                                                                                                  
15504 ec2-user  20   0 4007m 122m  10m S  0.3  0.4   1:07.67 jupyter-notebook
```
`df`
```
Filesystem     1K-blocks     Used Available Use% Mounted on
devtmpfs        16049920       76  16049844   1% /dev
tmpfs           16060616        0  16060616   0% /dev/shm
/dev/nvme0n1p1 108305356 89633800  18571308  83% /
/dev/nvme1n1   102687672 52035200  45393208  54% /home/ec2-user/SageMaker
```
Not sure what's going on or how to fix.

**Comment by alecstein** [comment]
Not sure if this related or a separate issue, but while re-running the script dolt crashes with this error, without any obvious cause (not memory related at least.)

```
Thu May 13 13:39:54 UTC 2021
Rows Processed: 73, Additions: 0, Modifications: 0, Had No Effect: 73Import completed successfully.
COMPLETED: JOHNSHOPKINS-1144291899, FILE: PAYERS
Rows Processed: 24810, Additions: 0, Modifications: 0, Had No Effect: 24810Import completed successfully.
COMPLETED: JOHNSHOPKINS-1144291899, FILE: PROCEDURES
Rows Processed: 300000, Additions: 0, Modifications: 0, Had No Effect: 300000

panic: interface conversion: types.Value is nil, not types.Map

goroutine 1 [running]:
github.com/dolthub/dolt/go/store/datas.(*database).Datasets(0xc0001160c0, 0x1df83c0, 0xc0004fc180, 0x4e1b19c8168fc1fa, 0x48e7c862c47c1aa1, 0x464943457a995022, 0x0)
        /src/store/datas/database_common.go:125 +0x2b0
github.com/dolthub/dolt/go/store/datas.(*database).doDelete(0xc0001160c0, 0x1df83c0, 0xc0004fc180, 0xc021593b00, 0x17, 0xc012938f10, 0x40dad0)
        /src/store/datas/database_common.go:537 +0xd8
github.com/dolthub/dolt/go/store/datas.(*database).Delete.func1(0x1e1b7e0, 0xc0001160c0, 0xc021593b00, 0x17, 0x1e17a60, 0xc012ece410, 0x7fabbb95b7d0, 0xc087d980f0)
        /src/store/datas/database_common.go:525 +0x78
github.com/dolthub/dolt/go/store/datas.(*database).doHeadUpdate(0xc0001160c0, 0x1df83c0, 0xc0004fc180, 0x1e1b7e0, 0xc0001160c0, 0xc021593b00, 0x17, 0x1e17a60, 0xc012ece410, 0xc012939058, ...)
        /src/store/datas/database_common.go:688 +0x7d
github.com/dolthub/dolt/go/store/datas.(*database).Delete(0xc0001160c0, 0x1df83c0, 0xc0004fc180, 0x1e1b7e0, 0xc0001160c0, 0xc021593b00, 0x17, 0x1e17a60, 0xc012ece410, 0x0, ...)
        /src/store/datas/database_common.go:525 +0xfb
github.com/dolthub/dolt/go/libraries/doltcore/doltdb.(*DoltDB).GC(0xc000148010, 0x1df83c0, 0xc0004fc180, 0xc01dd5a870, 0x3, 0x4, 0x2, 0x4)
        /src/libraries/doltcore/doltdb/doltdb.go:939 +0x89f
github.com/dolthub/dolt/go/libraries/doltcore/mvdata.(*tableEditorWriteCloser).GC(0xc000920f30, 0x1df83c0, 0xc0004fc180, 0x7fab93a290b0, 0xc000920f30)
        /src/libraries/doltcore/mvdata/table_data_loc.go:307 +0x205
github.com/dolthub/dolt/go/libraries/doltcore/mvdata.(*DataMover).Move.func1(0xc010e1a5d0, 0x1df83c0, 0xc0004fc180, 0xc01157f380)
        /src/libraries/doltcore/mvdata/data_mover.go:115 +0xcc
github.com/dolthub/dolt/go/libraries/doltcore/mvdata.(*DataMover).Move(0xc010e1a5d0, 0x1df83c0, 0xc0004fc180, 0x1dfe4c0, 0xc015b61a40, 0x0, 0x1683, 0x0)
        /src/libraries/doltcore/mvdata/data_mover.go:164 +0x473
github.com/dolthub/dolt/go/libraries/doltcore/mvdata.MoveDataToRoot(0x1df83c0, 0xc0004fc180, 0xc010e1a5d0, 0x1de4640, 0xc0001de900, 0xc00069db00, 0xc0129397e8, 0xc000116580, 0x7ffd5126c767, 0x6, ...)
        /src/libraries/doltcore/mvdata/data_mover.go:208 +0xab
github.com/dolthub/dolt/go/libraries/doltcore/mvdata.MoveData(0x1df83c0, 0xc0004fc180, 0xc0001d80b0, 0xc010e1a5d0, 0x1de4640, 0xc0001de900, 0xc010e1a5d0, 0x0, 0x3)
        /src/libraries/doltcore/mvdata/data_mover.go:258 +0x246
github.com/dolthub/dolt/go/cmd/dolt/commands/tblcmds.ImportCmd.Exec(0x1df83c0, 0xc0004fc180, 0xc000914080, 0x11, 0xc00003a210, 0x3, 0x3, 0xc0001d80b0, 0x11)
        /src/cmd/dolt/commands/tblcmds/import.go:383 +0x6d2
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.Exec(0x1b34223, 0x5, 0x1b9007a, 0x3f, 0xc0003bbe50, 0x5, 0x5, 0x0, 0x1df83c0, 0xc0004fc180, ...)
        /src/cmd/dolt/cli/command.go:165 +0x4bd
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.Exec(0x1b3290f, 0x4, 0x1b48aef, 0x11, 0xc00093eb40, 0x24, 0x24, 0x0, 0x1df8340, 0xc0000420e0, ...)
        /src/cmd/dolt/cli/command.go:165 +0x4bd
main.runMain(0x0)
        /src/cmd/dolt/dolt.go:268 +0x1105
main.main()
        /src/cmd/dolt/dolt.go:110 +0x25
```

**Comment by zachmu** [comment]
Thanks for the report!

Can you upload the file you're trying to import so we can attempt to reproduce the problem?

**Comment by alecstein** [comment]
Sure. Also, it doesn't happen every time for me, or with one specific file, but it has been happening to me consistently for a couple weeks now.

Here is the link: https://send.ioiox.com/download/f278999111d437e8/#LrT1lFHgQNUEmE0kkqwAhw

Also, here's the `strace -p <pid>` output while the deadlock was happening, starting from before the deadlock:
```
rt_sigreturn()                          = 1974
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1974, si_uid=500} ---
rt_sigreturn()                          = 1974
tgkill(1974, 1984, SIGURG)              = 0
getpid()                                = 1974
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1974, si_uid=500} ---
rt_sigreturn()                          = 1974
tgkill(1974, 1984, SIGURG)              = 0
getpid()                                = 1974
tgkill(1974, 1991, SIGURG)              = 0
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1974, si_uid=500} ---
rt_sigreturn()                          = 0
getpid()                                = 1974
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1974, si_uid=500} ---
rt_sigreturn()                          = 1974
tgkill(1974, 1992, SIGURG)              = 0
getpid()                                = 1974
tgkill(1974, 1986, SIGURG)              = 0
getpid()                                = 1974
tgkill(1974, 1992, SIGURG)              = 0
futex(0x296def8, FUTEX_WAKE_PRIVATE, 1) = 1
getpid()                                = 1974
tgkill(1974, 1992, SIGURG)              = 0
futex(0x296def8, FUTEX_WAKE_PRIVATE, 1) = 1
getpid()                                = 1974
tgkill(1974, 1992, SIGURG)              = 0
futex(0x296def8, FUTEX_WAKE_PRIVATE, 1) = 1
epoll_pwait(4, {}, 128, 0, NULL)        = 0
futex(0xc000680948, FUTEX_WAKE_PRIVATE, 1) = 1
getpid()                                = 1974
tgkill(1974, 1992, SIGURG)              = 0
futex(0x296def8, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x296e6c8, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x296e6c8, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x296e6c8, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0xc00007e548, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x296e6c8, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
```
It seems to hang here.

**Comment by alecstein** [comment]
You can repro with these files: https://send.ioiox.com/download/c39416ac0d2e8d19/#rVav9Rz0yD2ryreG216u9Q 

And you will need to clone my repository.

**Comment by zachmu** [comment]
@bheni please confirm that this is better after your changes.

**Comment by timsehn** [comment]
We'll resolve this as we made a bunch of changes to make import better at generating and collecting garbage.
