### ISSUE TITLE
`dolt push` of hospital-price-transparency-v2 segfaults

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#1855]
Repro:

1. `dolt clone dolthub/hospital-rice-transparency-v2`
2. Make a new repo on dolthub. In this case, I made `timsehn/dustin-test`
3. `dolt remote add testing timsehn/dustin-test`
4. `dolt push testing master`

```
hospital-price-transparency-v2 $ dolt push testing master
Tree Level: 161 has 18 new chunks of which 0 already exist in the database. Buffering 18 chunks.
Tree Level: 161. 100.00% of new chunks buffered.
Tree Level: 160 has 31 new chunks of which 0 already exist in the database. Buffering 31 chunks.
Tree Level: 160. 100.00% of new chunks buffered.
Tree Level: 159 has 68 new chunks of which 0 already exist in the database. Buffering 68 chunks.
Tree Level: 159. 100.00% of new chunks buffered.
Tree Level: 157 has 1062 new chunks of which 0 already exist in the database. Buffering 1062 chunks.
Tree Level: 157. 100.00% of new chunks buffered.
Tree Level: 156 has 92518 new chunks of which 0 already exist in the database. Buffering 92518 chunks.
Tree Level: 156. 100.00% of new chunks buffered.
Tree Level: 155 has 3176731 new chunks of which 0 already exist in the database. Buffering 3176731 chunks.
Tree Level: 155. 100.00% of new chunks buffered.
Tree Level: 154 has 3085170 new chunks of which 0 already exist in the database. Buffering 3085170 chunks.
Tree Level: 154. 4.44% of new chunks buffered.panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1d098fa]

goroutine 1 [running]:
github.com/dolthub/dolt/go/store/nbs.(*CmpChunkTableWriter).Size(...)
	/Users/timsehn/liquidata/git/dolt/go/store/nbs/cmp_chunk_table_writer.go:64
github.com/dolthub/dolt/go/store/datas.(*Puller).Pull(0xc045b10e80, 0x2bdd940, 0xc0001e1350, 0x49, 0x40000)
	/Users/timsehn/liquidata/git/dolt/go/store/datas/puller.go:309 +0x57a
github.com/dolthub/dolt/go/libraries/doltcore/doltdb.(*DoltDB).PushChunks(0xc045c7ebd0, 0x2bdd940, 0xc0001e1350, 0xc000b7a3c0, 0x49, 0xc00007eca0, 0x0, 0x0, 0x3a3f5a0, 0xc045c33800, ...)
	/Users/timsehn/liquidata/git/dolt/go/libraries/doltcore/doltdb/doltdb.go:1059 +0x1bd
github.com/dolthub/dolt/go/libraries/doltcore/env/actions.Push(0x2bdd940, 0xc0001e1350, 0xc000280210, 0xc0001d3400, 0xc00059948b, 0x6, 0xc00085d700, 0x7, 0xc00059948b, 0x6, ...)
	/Users/timsehn/liquidata/git/dolt/go/libraries/doltcore/env/actions/remotes.go:52 +0x166
github.com/dolthub/dolt/go/cmd/dolt/commands.pushToRemoteBranch(0x2bdd940, 0xc0001e1350, 0xc000280210, 0xc000042b00, 0x2bce640, 0xc000187240, 0x2bce640, 0xc000187250, 0x2bce6c0, 0xc000863f60, ...)
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/commands/push.go:382 +0x3c6
github.com/dolthub/dolt/go/cmd/dolt/commands.doPush(0x2bdd940, 0xc0001e1350, 0xc000280210, 0xc00018e800, 0xc00018e800, 0x0)
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/commands/push.go:306 +0xce3
github.com/dolthub/dolt/go/cmd/dolt/commands.PushCmd.Exec(0x2bdd940, 0xc0001e1350, 0xc00085d570, 0x9, 0xc000136020, 0x2, 0x2, 0xc000280210, 0x9)
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/commands/push.go:114 +0x284
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.Exec(0x2789de4, 0x4, 0x279fedb, 0x11, 0xc00040e780, 0x25, 0x25, 0x0, 0x2bdd940, 0xc0001e1350, ...)
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/cli/command.go:165 +0x486
main.runMain(0x0)
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/dolt.go:294 +0x122d
main.main()
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/dolt.go:129 +0x27
hospital-price-transparency-v2 $
```

**Comment by timsehn** [comment]
Here's what actually happens. The first time you run it, it blows out memory on the host:

![image](https://user-images.githubusercontent.com/5376236/123344366-8f908580-d508-11eb-9053-39c5e3af0ede.png)

```
hospital-price-transparency-v2 $ dolt push testing master
Tree Level: 161 has 18 new chunks of which 0 already exist in the database. Buffering 18 chunks.
Tree Level: 161. 100.00% of new chunks buffered.
Tree Level: 160 has 31 new chunks of which 0 already exist in the database. Buffering 31 chunks.
Tree Level: 160. 100.00% of new chunks buffered.
Tree Level: 159 has 68 new chunks of which 0 already exist in the database. Buffering 68 chunks.
Tree Level: 159. 100.00% of new chunks buffered.
Tree Level: 157 has 1062 new chunks of which 0 already exist in the database. Buffering 1062 chunks.
Tree Level: 157. 100.00% of new chunks buffered.
Tree Level: 156 has 92518 new chunks of which 0 already exist in the database. Buffering 92518 chunks.
Tree Level: 156. 100.00% of new chunks buffered.
Tree Level: 155 has 3176731 new chunks of which 0 already exist in the database. Buffering 3176731 chunks.
Tree Level: 155. 100.00% of new chunks buffered.
Tree Level: 154 has 3085170 new chunks of which 0 already exist in the database. Buffering 3085170 chunks.
Tree Level: 154. 100.00% of new chunks buffered.
Tree Level: 153 has 3177255 new chunks of which 0 already exist in the database. Buffering 3177255 chunks.
Tree Level: 153. 100.00% of new chunks buffered.
Tree Level: 152 has 999568 new chunks of which 0 already exist in the database. Buffering 999568 chunks.
Tree Level: 152. 100.00% of new chunks buffered.
Tree Level: 151 has 216115 new chunks of which 0 already exist in the database. Buffering 216115 chunks.
Tree Level: 151. 100.00% of new chunks buffered.
Tree Level: 150 has 312140 new chunks of which 0 already exist in the database. Buffering 312140 chunks.
Tree Level: 150. 100.00% of new chunks buffered.
Tree Level: 149 has 253854 new chunks of which 0 already exist in the database. Buffering 253854 chunks.
Tree Level: 149. 100.00% of new chunks buffered.
Tree Level: 148 has 314447 new chunks of which 0 already exist in the database. Buffering 314447 chunks.
Tree Level: 148. 100.00% of new chunks buffered.
Tree Level: 139 has 515622 new chunks of which 0 already exist in the database. Buffering 515622 chunks.
Tree Level: 139. 100.00% of new chunks buffered.
Tree Level: 138 has 382536 new chunks of which 0 already exist in the database. Buffering 382536 chunks.
Tree Level: 138. 100.00% of new chunks buffered.
Tree Level: 137 has 591770 new chunks of which 0 already exist in the database. Buffering 591770 chunks.
Tree Level: 137. 100.00% of new chunks buffered.
Tree Level: 136 has 940490 new chunks of which 0 already exist in the database. Buffering 940490 chunks.
Tree Level: 136. 100.00% of new chunks buffered.
Tree Level: 135 has 664385 new chunks of which 0 already exist in the database. Buffering 664385 chunks.
Tree Level: 135. 100.00% of new chunks buffered.
Tree Level: 134 has 721816 new chunks of which 0 already exist in the database. Buffering 721816 chunks.
Tree Level: 134. 100.00% of new chunks buffered.
Tree Level: 133 has 601524 new chunks of which 0 already exist in the database. Buffering 601524 chunks.
Tree Level: 133. 100.00% of new chunks buffered.
Tree Level: 132 has 664312 new chunks of which 0 already exist in the database. Buffering 664312 chunks.
Tree Level: 132. 100.00% of new chunks buffered.
Tree Level: 131 has 1146201 new chunks of which 0 already exist in the database. Buffering 1146201 chunks.
Tree Level: 131. 100.00% of new chunks buffered.
Tree Level: 123 has 2032473 new chunks of which 0 already exist in the database. Buffering 2032473 chunks.
Tree Level: 123. 100.00% of new chunks buffered.
Tree Level: 122 has 601550 new chunks of which 0 already exist in the database. Buffering 601550 chunks.
Tree Level: 122. 100.00% of new chunks buffered.
Tree Level: 121 has 318099 new chunks of which 0 already exist in the database. Buffering 318099 chunks.
Tree Level: 121. 100.00% of new chunks buffered.
Tree Level: 120 has 583697 new chunks of which 0 already exist in the database. Buffering 583697 chunks.
Tree Level: 120. 100.00% of new chunks buffered.
Tree Level: 119 has 501279 new chunks of which 0 already exist in the database. Buffering 501279 chunks.
Tree Level: 119. 100.00% of new chunks buffered.
Tree Level: 118 has 414278 new chunks of which 0 already exist in the database. Buffering 414278 chunks.
Tree Level: 118. 100.00% of new chunks buffered.
Tree Level: 117 has 487090 new chunks of which 0 already exist in the database. Buffering 487090 chunks.
Tree Level: 117. 100.00% of new chunks buffered.
Tree Level: 116 has 420264 new chunks of which 0 already exist in the database. Buffering 420264 chunks.
Tree Level: 116. 100.00% of new chunks buffered.
Tree Level: 115 has 650353 new chunks of which 0 already exist in the database. Buffering 650353 chunks.
Tree Level: 115. 17.53% of new chunks buffered.panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1d098fa]

goroutine 1 [running]:
github.com/dolthub/dolt/go/store/nbs.(*CmpChunkTableWriter).Size(...)
	/Users/timsehn/liquidata/git/dolt/go/store/nbs/cmp_chunk_table_writer.go:64
github.com/dolthub/dolt/go/store/datas.(*Puller).Pull(0xc000196600, 0x2bdd940, 0xc00086c630, 0x49, 0x40000)
	/Users/timsehn/liquidata/git/dolt/go/store/datas/puller.go:309 +0x57a
github.com/dolthub/dolt/go/libraries/doltcore/doltdb.(*DoltDB).PushChunks(0xc045c07740, 0x2bdd940, 0xc00086c630, 0xc00059a230, 0x49, 0xc0004263e0, 0x0, 0x0, 0x3a3f5a0, 0xc045b83800, ...)
	/Users/timsehn/liquidata/git/dolt/go/libraries/doltcore/doltdb/doltdb.go:1059 +0x1bd
github.com/dolthub/dolt/go/libraries/doltcore/env/actions.Push(0x2bdd940, 0xc00086c630, 0xc0002f8160, 0xc045c20600, 0xc0004c4f0b, 0x6, 0xc00084b300, 0x7, 0xc0004c4f0b, 0x6, ...)
	/Users/timsehn/liquidata/git/dolt/go/libraries/doltcore/env/actions/remotes.go:52 +0x166
github.com/dolthub/dolt/go/cmd/dolt/commands.pushToRemoteBranch(0x2bdd940, 0xc00086c630, 0xc0002f8160, 0xc00019e700, 0x2bce640, 0xc000782cc0, 0x2bce640, 0xc000782cd0, 0x2bce6c0, 0xc00053bec0, ...)
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/commands/push.go:382 +0x3c6
github.com/dolthub/dolt/go/cmd/dolt/commands.doPush(0x2bdd940, 0xc00086c630, 0xc0002f8160, 0xc00004ab80, 0xc00004ab80, 0x0)
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/commands/push.go:306 +0xce3
github.com/dolthub/dolt/go/cmd/dolt/commands.PushCmd.Exec(0x2bdd940, 0xc00086c630, 0xc00084b170, 0x9, 0xc000136020, 0x2, 0x2, 0xc0002f8160, 0x9)
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/commands/push.go:114 +0x284
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.Exec(0x2789de4, 0x4, 0x279fedb, 0x11, 0xc000368000, 0x25, 0x25, 0x0, 0x2bdd940, 0xc00086c630, ...)
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/cli/command.go:165 +0x486
main.runMain(0x0)
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/dolt.go:294 +0x122d
main.main()
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/dolt.go:129 +0x27
```

That puts it in a bad state when you try and push again.

**Comment by timsehn** [comment]
OK. On Andy's branch it now fails with:
```
hospital-price-transparency-v2 $ dolt push testing master
Tree Level: 161 has 18 new chunks of which 0 already exist in the database. Buffering 18 chunks.
Tree Level: 161. 100.00% of new chunks buffered.
Tree Level: 160 has 31 new chunks of which 0 already exist in the database. Buffering 31 chunks.
Tree Level: 160. 100.00% of new chunks buffered.
Tree Level: 159 has 68 new chunks of which 0 already exist in the database. Buffering 68 chunks.
Tree Level: 159. 100.00% of new chunks buffered.
Tree Level: 157 has 1062 new chunks of which 0 already exist in the database. Buffering 1062 chunks.
Tree Level: 157. 100.00% of new chunks buffered.
Tree Level: 156 has 92518 new chunks of which 0 already exist in the database. Buffering 92518 chunks.
Tree Level: 156. 100.00% of new chunks buffered.
Tree Level: 155 has 3176731 new chunks of which 0 already exist in the database. Buffering 3176731 chunks.
Tree Level: 155. 100.00% of new chunks buffered.
Tree Level: 154 has 3085170 new chunks of which 0 already exist in the database. Buffering 3085170 chunks.
Tree Level: 154. 4.44% of new chunks buffered.
error: push failed
cause: open /Users/timsehn/liquidata/dolt/hospital-price-transparency-v2/.dolt/temptf/buffered_file_byte_sink_110469012: no space left on device
```

My disk was full of temp files created on push. I have 100Gb of space. This is not great.

```
hospital-price-transparency-v2 $ ls .dolt/temptf/
1e55jbquksaipp2jofru0s3cpjkevdk3  919t769808rckj6bj2tkes32vd11qiig  k1nv82hn830c3k2hji2vjpnpkq6cc1e6  qecv9im80upeaqvhadq1pc0si9337jf6
1n838ubnjfnnp909t0ce0idc8mdpjc20  9fjju6244h5o2vpvi00ma6c1gbs7q7ch  k6j1tvc4m6ftjeki6e2plo1q3fa2oe8f  qete9bmq07t3j5fm24agi6tobor3pir7
1vi5hmdnejgmlbs8d88nk9ps1srm2dbe  9ui5flc70vuetrjo1gep8lga2i5pi1m3  kj0gvj4tssg8kqqbnrb38n42j6htgrh2  qgeua9joqr3dsaefukniodn45cs3g0lr
2a6gmlakhdcton3bj0q6naqeloc4rteg  a4v8nn3jfrusq6leeklfra7odufcc46e  l7r64n1r0htijrrgv7pgn7pnjlq60jru  qip79lmcqjbvmni3t1dkf6tvubg161kd
2djuvhgli999kd2fp7c202chd7naiqiu  akpojocqcqqao4ldi0o4c8ss13410gie  le5ueupebtb8jdlccnopaj5lgnott2o6  qverkc9j6d05pte868htb16i8te9bjah
2hjadgtve53cms51ft6jlr77nb3taijp  bfog93pr33opn65d8pstfeou4du3rki3  lqjreqipsqo6225cs64mfc8o5elqktkd  ri0nelvi3eupgp04ckknnafid34amvfp
2li5a4p07pu9t70h145j1q16stpkealg  bi2dimjhnfllilcjtmgpvk75nleec1ac  lstjjvu7tg2kmbti5f52o8jf39vo9qbb  rsfii0etcqeeomogd09f83eqo6mv107t
2ojcfpfp7oi94m2jah5j2l8ah2stgf50  c3fpvv75146j0hitolaq3tkro1sfe8pa  m052qk5cgnofpufabgh15c73rskv45d2  sf6g2sp13qpcmp8p3ocgn7aq5c4geup0
2sqis5gdg196jkeujt23eun2p3chh5ue  c7gii64tq9lump71kiv66489sba89vtq  m1vh4gqmc6gv9gb1igf4dehd6tu7lt0a  su12ivjlom4bkuih2ev6t393lg4d7f9m
38uatldqad57jjt3bju1kqd5ni9vc985  d4ec6dno5fn1gggc5rj1er8st3p3bgm9  m23hds2aq6a39e69cd838p02n1nhge66  t33ppu39q6ir226emrioltsasbj5mpdh
3d4uhuofgvi39eo3d82al5ul9d3sn29p  dodbts6phj2ei289mr3iqdd4p5tcefr8  m9kb6glha48939omk4cqqs1hskoq1uks  t61uerue88c6tauivfr1d2c8pcjqhdh4
3oigcjabqvfdh5ar2n3kqudhu2meftcv  ect3053900e43hb7uh03tl1hg9vtkb07  ma3ot8v0hqf0ne9quflhebu9bn4jd139  u8ddslm292f2sn2sf4ti3n84hlq19ksf
3qdhua10lu21oig0v52jo42mub0nrk7c  epj6sirmm10codqkn14kqpg5jh35d846  n7nsef61hhfhrm27ib3ddaajn0fq9j63  u917bmilq92rl80dmap5q0vuh06bte2s
40hi4q383knjv542kcvdl2582gqv76rv  f0g39eqkuukchi98jek30l6p9e4t0arl  ncoo1crub0kv66h4np878jmbji7ka1i6  uma5qo91p8pm02mlnepvd5ee9squ65fl
4s2i5680ro1e328l84c1c9nt43tboi4h  fk269fg862issijtjfsia43ukoj2bc0q  nulc150l0db05ui36peo68hog0pb51ma  v1rs778b9sr6pos07n2na5rhdvfoinip
57m8g3vmg1u894ampifulh19civ1jh77  fmn4j52s7qimu1sulp0r9uk6dmf6ce9g  ocv2jli6as8vncovioqokikbbaqpvo77  v6q877mal5d4m89qolbba0mokrov9gsn
71ld9r4261fnkijldur25ghd98r0cinp  gtafi2ais4e26rpocqst2qs63i9gal2m  oerm1g131sr0ifidm47lbfudobgfhiu1  vtmg0j74kbn2lg1a6mm7p1lmj23b49dp
7d5c3j991cplic1j2bihdiq9es99bubu  gtiq30cuccap2bdj0j3r6t3cft7ekm3f  omplb0jopnski59llg7j0e2i1dc8362s  vv7rv2lru9qttuetg6d0uk2nl1d67ivf
7qncg6i5h4u833ifp05fp9din90utojr  h6kb0sc8vtuk5v42550cpnhjj0kmlgcq  pa32rb1ks7a22brscg5g5q57uq1umhqi  
85bcahf3smgp6jns6gop7vr01niiuk8l  j8kjqcdrktf6kb13b2lqgekoee9o7es6  pns5rmuvkfjga6uf2ohin6vb0h0fuorf  
8kdocbpc0rusq9dmslpgbi8fsus4gp1v  jpuae6ffo1kma20e1akh906q1nq1uepm  q63us8ro6lmqq2dajgc3uthalqqb1q5c  
```

**Comment by timsehn** [comment]
I'm able to get further when I delete the tempf directory:
```
hospital-price-transparency-v2 $ dolt push testing master
Tree Level: 161 has 18 new chunks of which 0 already exist in the database. Buffering 18 chunks.
Tree Level: 161. 100.00% of new chunks buffered.
Tree Level: 160 has 31 new chunks of which 0 already exist in the database. Buffering 31 chunks.
Tree Level: 160. 100.00% of new chunks buffered.
Tree Level: 159 has 68 new chunks of which 0 already exist in the database. Buffering 68 chunks.
Tree Level: 159. 100.00% of new chunks buffered.
Tree Level: 157 has 1062 new chunks of which 0 already exist in the database. Buffering 1062 chunks.
Tree Level: 157. 100.00% of new chunks buffered.
Tree Level: 156 has 92518 new chunks of which 0 already exist in the database. Buffering 92518 chunks.
Tree Level: 156. 100.00% of new chunks buffered.
Tree Level: 155 has 3176731 new chunks of which 0 already exist in the database. Buffering 3176731 chunks.
Tree Level: 155. 100.00% of new chunks buffered.
Tree Level: 154 has 3085170 new chunks of which 0 already exist in the database. Buffering 3085170 chunks.
Tree Level: 154. 100.00% of new chunks buffered.
Tree Level: 153 has 3177255 new chunks of which 0 already exist in the database. Buffering 3177255 chunks.
Tree Level: 153. 100.00% of new chunks buffered.
Tree Level: 152 has 999568 new chunks of which 0 already exist in the database. Buffering 999568 chunks.
Tree Level: 152. 100.00% of new chunks buffered.
Tree Level: 151 has 216115 new chunks of which 0 already exist in the database. Buffering 216115 chunks.
Tree Level: 151. 100.00% of new chunks buffered.
Tree Level: 150 has 312140 new chunks of which 0 already exist in the database. Buffering 312140 chunks.
Tree Level: 150. 100.00% of new chunks buffered.
Tree Level: 149 has 253854 new chunks of which 0 already exist in the database. Buffering 253854 chunks.
Tree Level: 149. 100.00% of new chunks buffered.
Tree Level: 148 has 314447 new chunks of which 0 already exist in the database. Buffering 314447 chunks.
Tree Level: 148. 100.00% of new chunks buffered.
Tree Level: 139 has 515622 new chunks of which 0 already exist in the database. Buffering 515622 chunks.
Tree Level: 139. 100.00% of new chunks buffered.
Tree Level: 138 has 382536 new chunks of which 0 already exist in the database. Buffering 382536 chunks.
Tree Level: 138. 100.00% of new chunks buffered.
Tree Level: 137 has 591770 new chunks of which 0 already exist in the database. Buffering 591770 chunks.
Tree Level: 137. 100.00% of new chunks buffered.
Tree Level: 136 has 940490 new chunks of which 0 already exist in the database. Buffering 940490 chunks.
Tree Level: 136. 100.00% of new chunks buffered.
Tree Level: 135 has 664385 new chunks of which 0 already exist in the database. Buffering 664385 chunks.
Tree Level: 135. 100.00% of new chunks buffered.
Tree Level: 134 has 721816 new chunks of which 0 already exist in the database. Buffering 721816 chunks.
Tree Level: 134. 100.00% of new chunks buffered.
Tree Level: 133 has 601524 new chunks of which 0 already exist in the database. Buffering 601524 chunks.
Tree Level: 133. 100.00% of new chunks buffered.
Tree Level: 132 has 664312 new chunks of which 0 already exist in the database. Buffering 664312 chunks.
Tree Level: 132. 100.00% of new chunks buffered.
Tree Level: 131 has 1146201 new chunks of which 0 already exist in the database. Buffering 1146201 chunks.
Tree Level: 131. 100.00% of new chunks buffered.
Tree Level: 123 has 2032473 new chunks of which 0 already exist in the database. Buffering 2032473 chunks.
Tree Level: 123. 88.71% of new chunks buffered.
error: push failed
cause: write /Users/timsehn/liquidata/dolt/hospital-price-transparency-v2/.dolt/temptf/buffered_file_byte_sink_035248645: no space left on device
```

But I am running out of disk space. Can we clean some of these up incrementally?

**Comment by bheni** [comment]
https://github.com/dolthub/dolt/pull/1885

```
~/datasets/hospitals2>time dolt push origin master
| Tree Level: 1, Percent Buffered: 98.64%, Files Written: 119, Files Uploaded: 120, Current Upload Speed: 4.5 MB/s

real	587m48.888s
user	43m0.458s
sys	67m4.784s
```
