### ISSUE TITLE
Panic on `ALTER TABLE restaurants AUTO_INCREMENT = 2;`

### ISSUE THREAD

**Issue by katiemcculloch** [dolthub/dolt#1856]
schema that i'm trying to modify: 
```
+-------+--------------+------+-----+---------+-------+
| Field | Type         | Null | Key | Default | Extra |
+-------+--------------+------+-----+---------+-------+
| id    | int          | NO   | PRI |         |       |
| name  | varchar(255) | NO   |     |         |       |
| type  | int          | NO   | MUL |         |       |
+-------+--------------+------+-----+---------+-------+
```

Panic:
```
menus> ALTER TABLE restaurants AUTO_INCREMENT = 2;
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x21766d8]

goroutine 1 [running]:
github.com/dolthub/dolt/go/libraries/doltcore/sqle.(*sqlTableEditor).SetAutoIncrementValue(0xc0009120f0, 0xc0007935f0, 0x24688c0, 0x3560a90, 0xc00081d140, 0x1)
        /Users/katiemcculloch/Documents/dolt/go/libraries/doltcore/sqle/table_editor.go:140 +0x138
github.com/dolthub/go-mysql-server/sql/plan.(*AlterAutoIncrement).Execute(0xc000725698, 0xc0007935f0, 0xc000a9ede0, 0x218c733)
        /Users/katiemcculloch/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.10.1-0.20210623170540-c0b4e3e5599a/sql/plan/alter_auto_increment.go:47 +0x10d
github.com/dolthub/go-mysql-server/sql/plan.(*AlterAutoIncrement).RowIter(0xc000725698, 0xc0007935f0, 0x0, 0x0, 0x0, 0x365b168, 0x365b168, 0x0, 0x0)
        /Users/katiemcculloch/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.10.1-0.20210623170540-c0b4e3e5599a/sql/plan/alter_auto_increment.go:52 +0x39
github.com/dolthub/go-mysql-server/sql/plan.(*QueryProcess).RowIter(0xc0007256b0, 0xc0007935f0, 0x0, 0x0, 0x0, 0x5, 0x0, 0x0, 0x0)
        /Users/katiemcculloch/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.10.1-0.20210623170540-c0b4e3e5599a/sql/plan/process.go:49 +0x68
github.com/dolthub/go-mysql-server.(*Engine).QueryNodeWithBindings(0xc0007bb350, 0xc0007935f0, 0xc000712c30, 0x2b, 0x2a99298, 0xc000724cc0, 0x0, 0xc000a9ef70, 0x13341e6, 0x361ed60, ...)
        /Users/katiemcculloch/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.10.1-0.20210623170540-c0b4e3e5599a/engine.go:172 +0x1e5
github.com/dolthub/go-mysql-server.(*Engine).QueryWithBindings(...)
        /Users/katiemcculloch/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.10.1-0.20210623170540-c0b4e3e5599a/engine.go:126
github.com/dolthub/go-mysql-server.(*Engine).Query(0xc0007bb350, 0xc0007935f0, 0xc000712c30, 0x2b, 0x0, 0x0, 0x40000000000002c, 0x2a94d78, 0x2b, 0x203000, ...)
        /Users/katiemcculloch/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.10.1-0.20210623170540-c0b4e3e5599a/engine.go:117 +0x6a
github.com/dolthub/dolt/go/cmd/dolt/commands.(*sqlEngine).query(...)
        /Users/katiemcculloch/Documents/dolt/go/cmd/dolt/commands/sql.go:1453
github.com/dolthub/dolt/go/cmd/dolt/commands.processQuery(0xc0007935f0, 0xc000712c30, 0x2b, 0xc0007a9520, 0x0, 0x0, 0xffffffffffffffff, 0xc000712c30, 0x2b, 0xc000a9f210, ...)
        /Users/katiemcculloch/Documents/dolt/go/cmd/dolt/commands/sql.go:931 +0x126
github.com/dolthub/dolt/go/cmd/dolt/commands.runShell.func3(0xc000741450)
        /Users/katiemcculloch/Documents/dolt/go/cmd/dolt/commands/sql.go:738 +0x2b8
github.com/dolthub/ishell.handleUninterpretedInput(0xc0007366c0, 0xc000712c30, 0x2b, 0x0, 0x2)
        /Users/katiemcculloch/go/pkg/mod/github.com/dolthub/ishell@v0.0.0-20210205014355-16a4ce758446/ishell.go:282 +0x146
github.com/dolthub/ishell.(*Shell).run(0xc0007366c0)
        /Users/katiemcculloch/go/pkg/mod/github.com/dolthub/ishell@v0.0.0-20210205014355-16a4ce758446/ishell.go:242 +0x245
github.com/dolthub/ishell.(*Shell).Run(0xc0007366c0)
        /Users/katiemcculloch/go/pkg/mod/github.com/dolthub/ishell@v0.0.0-20210205014355-16a4ce758446/ishell.go:136 +0x39
github.com/dolthub/dolt/go/cmd/dolt/commands.runShell(0xc0007935f0, 0xc0007a9520, 0xc0007bad50, 0xc0007bb050, 0x10f0100, 0xc0007c00a0)
        /Users/katiemcculloch/Documents/dolt/go/cmd/dolt/commands/sql.go:761 +0x68a
github.com/dolthub/dolt/go/cmd/dolt/commands.execShell(0xc0007935f0, 0x4200100, 0xc0007bad50, 0xc0007bb050, 0x0, 0x3560a00, 0x0)
        /Users/katiemcculloch/Documents/dolt/go/cmd/dolt/commands/sql.go:377 +0xd8
github.com/dolthub/dolt/go/cmd/dolt/commands.SqlCmd.Exec(0x2796c41, 0x6, 0x2a8e418, 0xc000727230, 0xc000744320, 0x8, 0xc0001a2010, 0x0, 0x0, 0xc0002c2210, ...)
        /Users/katiemcculloch/Documents/dolt/go/cmd/dolt/commands/sql.go:344 +0x16f7
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.Exec(0x2794f97, 0x4, 0x27ab2a7, 0x11, 0xc00035ef00, 0x25, 0x25, 0x0, 0x2a8e418, 0xc000727230, ...)
        /Users/katiemcculloch/Documents/dolt/go/cmd/dolt/cli/command.go:165 +0x4c2
main.runMain(0x0)
        /Users/katiemcculloch/Documents/dolt/go/cmd/dolt/dolt.go:294 +0x136c
main.main()
        /Users/katiemcculloch/Documents/dolt/go/cmd/dolt/dolt.go:129 +0x2a
```

Is this a user error, like you can't run this once the primary key column has been created? In either case I'd expect it to not panic

Let me know re: the user error/flow and I can write a bats test for it.

**Comment by andrew-wm-arthur** [comment]
@VinaiRachakonda where are we at with this?
