### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by toby1991** [dolthub/dolt#2141]
[fatal error: concurrent map read and map write.txt](https://github.com/dolthub/dolt/files/7166358/fatal.error.concurrent.map.read.and.map.write.txt)

**Comment by andrew-wm-arthur** [comment]
@toby1991 thanks for the bug report. Looks like we're missing some locks on in session state management

**Comment by andrew-wm-arthur** [comment]
Inlining the top of the thread dump for context:
```
fatal error: concurrent map read and map write

goroutine 6509 [running]:
runtime.throw({0x25122cf, 0x28098b0})
	/usr/local/go/src/runtime/panic.go:1198 +0x71 fp=0xc000bfa9c8 sp=0xc000bfa998 pc=0x1034cd1
runtime.mapaccess1_faststr(0xc000bfaa60, 0x1f1f414, {0x24ec82b, 0xe})
	/usr/local/go/src/runtime/map_faststr.go:21 +0x3a5 fp=0xc000bfaa30 sp=0xc000bfa9c8 pc=0x1012245
github.com/dolthub/go-mysql-server/sql.(*BaseSession).GetLastQueryInfo(0xc000bfaa90, {0x24ec82b, 0x21f7200})
	/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.10.1-0.20210903190613-4c25c32c3883/sql/session.go:379 +0x35 fp=0xc000bfaa60 sp=0xc000bfaa30 pc=0x15ec435
github.com/dolthub/dolt/go/libraries/doltcore/sqle/dsess.(*Session).GetLastQueryInfo(0xc0022f21e0, {0x24ec82b, 0x205ff45})
	<autogenerated>:1 +0x34 fp=0xc000bfaa88 sp=0xc000bfaa60 pc=0x1f1f334
github.com/dolthub/go-mysql-server/server.setResultInfo(0xc005aa9710, 0xc00156e000, 0xc00c464300, {0x27f6918, 0xc004d8b320})
	/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.10.1-0.20210903190613-4c25c32c3883/server/handler.go:476 +0x53 fp=0xc000bfaab8 sp=0xc000bfaa88 pc=0x2060013
github.com/dolthub/go-mysql-server/server.(*Handler).doQuery(0xc00071e040, 0xc00156e000, {0xc003733110, 0xc8}, 0xc0032860c0, 0xc005861d80)
	/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.10.1-0.20210903190613-4c25c32c3883/server/handler.go:425 +0x148b fp=0xc000bfb428 sp=0xc000bfaab8 pc=0x205f5cb
github.com/dolthub/go-mysql-server/server.(*Handler).errorWrappedDoQuery(0x4d168570cbd8, 0xc000bfb498, {0xc003733110, 0x20}, 0x23ace00, 0x1088901)
	/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.10.1-0.20210903190613-4c25c32c3883/server/handler.go:519 +0x1e fp=0xc000bfb468 sp=0xc000bfb428 pc=0x206015e
github.com/dolthub/go-mysql-server/server.(*Handler).ComStmtExecute(0xc00156e000, 0xc003c35b80, 0xc00000b461, 0xc8)
	/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.10.1-0.20210903190613-4c25c32c3883/server/handler.go:102 +0x2e fp=0xc000bfb4a8 sp=0xc000bfb468 pc=0x205cace
github.com/dolthub/vitess/go/mysql.(*Conn).handleNextCommand(0xc00156e000, {0x28101d0, 0xc00071e040})
	/go/pkg/mod/github.com/dolthub/vitess@v0.0.0-20210802203534-01de666843ce/go/mysql/conn.go:1060 +0x24d8 fp=0xc000bfb9f8 sp=0xc000bfb4a8 pc=0x14e4118
github.com/dolthub/vitess/go/mysql.(*Listener).handle(0xc00062d290, {0x2810388, 0xc0000b4068}, 0x3, {0xc0484a00240c1e70, 0x22d661d420, 0x34e3120})
	/go/pkg/mod/github.com/dolthub/vitess@v0.0.0-20210802203534-01de666843ce/go/mysql/server.go:472 +0x19f4 fp=0xc000bfbf98 sp=0xc000bfb9f8 pc=0x14fb374
github.com/dolthub/vitess/go/mysql.(*Listener).Accept·dwrap·11()
	/go/pkg/mod/github.com/dolthub/vitess@v0.0.0-20210802203534-01de666843ce/go/mysql/server.go:266 +0x3d fp=0xc000bfbfe0 sp=0xc000bfbf98 pc=0x14f995d
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000bfbfe8 sp=0xc000bfbfe0 pc=0x1068721
created by github.com/dolthub/vitess/go/mysql.(*Listener).Accept
	/go/pkg/mod/github.com/dolthub/vitess@v0.0.0-20210802203534-01de666843ce/go/mysql/server.go:266 +0x29
```

**Comment by andrew-wm-arthur** [comment]
Specifically, we're reading without locking here:
https://github.com/dolthub/go-mysql-server/blob/9c29a8f521f4652686c68757fd4ca0bed161b158/sql/session.go#L379

**Comment by andrew-wm-arthur** [comment]
Addressed in https://github.com/dolthub/go-mysql-server/pull/554
