### ISSUE TITLE
Panic running dolt if home directory does not exist

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#2147]
Reported by a windows user. Probably also broken on other platforms.

**Comment by timsehn** [comment]
Easy repro:
```
us-schools $ export HOME=/this/is/garbage
us-schools $ echo $HOME
/this/is/garbage
us-schools $ dolt
panic: mkdir /this: read-only file system

goroutine 1 [running]:
github.com/dolthub/dolt/go/libraries/events.NewFileBackedProc({0x2839848, 0x3507820}, {0xc000042065, 0x2839848}, {0x24f48e4, 0xc0001c0900}, 0x257ef68, 0x257ef60)
	/Users/timsehn/liquidata/git/dolt/go/libraries/events/file_backed_proc.go:129 +0x2f7
github.com/dolthub/dolt/go/libraries/events.NewFileEmitter(...)
	/Users/timsehn/liquidata/git/dolt/go/libraries/events/emitter.go:135
main.runMain()
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/dolt.go:242 +0x1e5
main.main()
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/dolt.go:118 +0x19
```

**Comment by timsehn** [comment]
Resolved by the above PR.
