### ISSUE TITLE
dolt_status is panicking after changes

### ISSUE THREAD

**Issue by perok** [dolthub/dolt#2554]
Hi!

I don't have an easily shareable example yet, but this seems to be happening consistently. Running `SELECT table_name, staged, status FROM DOLT_STATUS` after adding a table results in Dolt crashing. 

```
2022-01-03T22:12:03Z TRACE [conn 17] beginning execution {connectTime=2022-01-03T22:12:03Z, query=SELECT table_name, staged, status FROM DOLT_STATUS}
panic: unexpected type

goroutine 1298 [running]:
github.com/dolthub/go-mysql-server/sql.mustInt64(...)
	/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20211228223405-58fc9dc84069/sql/numbertype.go:662
github.com/dolthub/go-mysql-server/sql.numberTypeImpl.SQL({0x60}, {0x17c45e0, 0x2bc1d20})
	/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20211228223405-58fc9dc84069/sql/numbertype.go:347 +0x45e
github.com/dolthub/go-mysql-server/server.rowToSQL({0xc0000da4e0, 0x3, 0x0}, {0xc000adf6b0, 0x3, 0x1})
	/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20211228223405-58fc9dc84069/server/handler.go:673 +0x10d
github.com/dolthub/go-mysql-server/server.(*Handler).doQuery.func5()
	/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20211228223405-58fc9dc84069/server/handler.go:431 +0x385
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x92
```
The current error is from dolt 0.35.0, but the error first appeared in version 0.34.7. Running dolt sql-server and communicating with mysql-connector-java 8.0.27.

Let me know if any other data is needed.

**Comment by VinaiRachakonda** [comment]
I've been unable to reproduce. Please let me know when you have some clearer or feel free to link me to your repo

**Comment by timsehn** [comment]
From the error, it may be related to the schema of the table you are changing. Mind including the output of `dolt schema show`?

**Comment by ndepaola** [comment]
I'm running Dolt with docker and connecting with SQLAlchemy through pymysql - encountering the same issue after executing an Alembic migration and trying to query `dolt_status`. The command line equivalent `dolt status` works fine.

Example schema for which I can consistently reproduce the error:

```py
class UUIDColumn(TypeDecorator):
    """
    Platform-independent UUID type.
    Uses Postgresql's UUID type, otherwise uses CHAR(32), storing as stringified hex values.
    Borrowed from sqlalchemy docs: https://docs.sqlalchemy.org/en/14/core/custom_types.html#backend-agnostic-guid-type
    """

    impl = CHAR
    cache_ok = True

    def load_dialect_impl(self, dialect):
        if dialect.name == "postgresql":
            return dialect.type_descriptor(UUID())
        else:
            return dialect.type_descriptor(CHAR(32))

    def process_bind_param(self, value, dialect):
        if value is None:
            return value
        elif dialect.name == "postgresql":
            return str(value)
        else:
            if not isinstance(value, uuid.UUID):
                return uuid.UUID(value).hex
            else:
                # hexstring
                return value.hex

    def process_result_value(self, value, dialect):
        if value is None:
            return value
        else:
            return uuid.UUID(value)

class TestModel(db.Model):
    id = db.Column(
        UUIDColumn(),
        primary_key=True,
        default=lambda: uuid.uuid4().hex,
    )
    name = db.Column(sa.String(60), unique=True)
    description = db.Column(sa.String(200))
```

```
# dolt schema show
alembic_version @ working
CREATE TABLE `alembic_version` (
  `version_num` varchar(32) NOT NULL,
  PRIMARY KEY (`version_num`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

test_table @ working
CREATE TABLE `test_table` (
  `id` char(32) NOT NULL,
  `name` varchar(60),
  `description` varchar(200),
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

```
# dolt status
On branch main
Untracked files:
  (use "dolt add <table|doc>" to include in what will be committed)
        new table:      alembic_version
        new table:      test_table
```

When querying `dolt_status`:

```
db_1  | 2022-01-06T05:33:04Z INFO [conn 2] NewConnection {DisableClientMultiStatements=false}
db_1  | 2022-01-06T05:33:04Z DEBUG [conn 2] Starting query {connectTime=2022-01-06T05:33:04Z, query=SET NAMES utf8mb4}
db_1  | 2022-01-06T05:33:04Z DEBUG [conn 2] returning result &{[] 1 0  [[]] <nil>} {connectTime=2022-01-06T05:33:04Z, query=SET NAMES utf8mb4}
db_1  | 2022-01-06T05:33:04Z DEBUG [conn 2] Query took 3ms {connectTime=2022-01-06T05:33:04Z, query=SET NAMES utf8mb4}
db_1  | 2022-01-06T05:33:04Z DEBUG [conn 2] Starting query {connectTime=2022-01-06T05:33:04Z, query=SHOW VARIABLES LIKE 'sql_mode'}
db_1  | 2022-01-06T05:33:04Z DEBUG [conn 2] returning result &{[name:"Variable_name" type:TEXT charset:33  name:"Value" type:TEXT charset:33 ] 1 0  [[TEXT("sql_mode") TEXT("STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION")]] <nil>} {connectTime=2022-01-06T05:33:04Z, query=SHOW VARIABLES LIKE 'sql_mode'}
db_1  | 2022-01-06T05:33:04Z DEBUG [conn 2] Query took 6ms {connectTime=2022-01-06T05:33:04Z, query=SHOW VARIABLES LIKE 'sql_mode'}
db_1  | 2022-01-06T05:33:04Z DEBUG [conn 2] Starting query {connectTime=2022-01-06T05:33:04Z, query=SHOW VARIABLES LIKE 'lower_case_table_names'}
db_1  | 2022-01-06T05:33:04Z DEBUG [conn 2] returning result &{[name:"Variable_name" type:TEXT charset:33  name:"Value" type:TEXT charset:33 ] 1 0  [[TEXT("lower_case_table_names") TEXT("0")]] <nil>} {connectTime=2022-01-06T05:33:04Z, query=SHOW VARIABLES LIKE 'lower_case_table_names'}
db_1  | 2022-01-06T05:33:04Z DEBUG [conn 2] Query took 7ms {connectTime=2022-01-06T05:33:04Z, query=SHOW VARIABLES LIKE 'lower_case_table_names'}
db_1  | 2022-01-06T05:33:04Z DEBUG [conn 2] Starting query {connectTime=2022-01-06T05:33:04Z, query=SELECT VERSION()}
db_1  | 2022-01-06T05:33:04Z DEBUG [conn 2] returning result &{[name:"VERSION()" type:TEXT charset:33 ] 1 0  [[TEXT("8.0.11")]] <nil>} {connectTime=2022-01-06T05:33:04Z, query=SELECT VERSION()}
db_1  | 2022-01-06T05:33:04Z DEBUG [conn 2] Query took 4ms {connectTime=2022-01-06T05:33:04Z, query=SELECT VERSION()}
db_1  | 2022-01-06T05:33:04Z DEBUG [conn 2] Starting query {connectTime=2022-01-06T05:33:04Z, query=SELECT DATABASE()}
db_1  | 2022-01-06T05:33:04Z DEBUG [conn 2] returning result &{[name:"DATABASE()" type:TEXT charset:33 ] 1 0  [[TEXT("test")]] <nil>} {connectTime=2022-01-06T05:33:04Z, query=SELECT DATABASE()}
db_1  | 2022-01-06T05:33:04Z DEBUG [conn 2] Query took 4ms {connectTime=2022-01-06T05:33:04Z, query=SELECT DATABASE()}
db_1  | 2022-01-06T05:33:04Z DEBUG [conn 2] Starting query {connectTime=2022-01-06T05:33:04Z, query=SELECT @@transaction_isolation}
db_1  | 2022-01-06T05:33:04Z DEBUG [conn 2] returning result &{[name:"@@SESSION.transaction_isolation" type:VARCHAR charset:33 ] 1 0  [[VARCHAR("REPEATABLE-READ")]] <nil>} {connectTime=2022-01-06T05:33:04Z, query=SELECT @@transaction_isolation}
db_1  | 2022-01-06T05:33:04Z DEBUG [conn 2] Query took 4ms {connectTime=2022-01-06T05:33:04Z, query=SELECT @@transaction_isolation}
db_1  | 2022-01-06T05:33:04Z DEBUG [conn 2] Starting query {connectTime=2022-01-06T05:33:04Z, query=ROLLBACK}
db_1  | 2022-01-06T05:33:04Z DEBUG [conn 2] returning empty result {connectTime=2022-01-06T05:33:04Z, query=ROLLBACK}
db_1  | 2022-01-06T05:33:04Z DEBUG [conn 2] Query took 4ms {connectTime=2022-01-06T05:33:04Z, query=ROLLBACK}
db_1  | 2022-01-06T05:33:04Z DEBUG [conn 2] Starting query {connectTime=2022-01-06T05:33:04Z, query=SELECT dolt_status.table_name AS dolt_status_table_name, dolt_status.staged AS dolt_status_staged, dolt_status.status AS dolt_status_status FROM dolt_status}
db_1  | panic: unexpected type
db_1  |
db_1  | goroutine 503 [running]:
db_1  | github.com/dolthub/go-mysql-server/sql.mustInt64(...)
db_1  |         /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20211228223405-58fc9dc84069/sql/numbertype.go:662
db_1  | github.com/dolthub/go-mysql-server/sql.numberTypeImpl.SQL({0x60}, {0x17c45e0, 0x2bc1d20})
db_1  |         /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20211228223405-58fc9dc84069/sql/numbertype.go:347 +0x45e
db_1  | github.com/dolthub/go-mysql-server/server.rowToSQL({0xc0005d9c08, 0x3, 0x0}, {0xc000852db0, 0x3, 0xc00073ea01})
db_1  |         /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20211228223405-58fc9dc84069/server/handler.go:673 +0x10d
db_1  | github.com/dolthub/go-mysql-server/server.(*Handler).doQuery.func5()
db_1  |         /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20211228223405-58fc9dc84069/server/handler.go:431 +0x385
db_1  | golang.org/x/sync/errgroup.(*Group).Go.func1()
db_1  |         /go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
db_1  | created by golang.org/x/sync/errgroup.(*Group).Go
db_1  |         /go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x92
```

**Comment by VinaiRachakonda** [comment]
Thanks for the followup here, we're on it

**Comment by jennifersp** [comment]
It's [fixed](https://github.com/dolthub/go-mysql-server/pull/696) for the latest release, v0.35.1
