### ISSUE TITLE
Panic on SIGINT during commit log

### ISSUE THREAD

**Issue by CaptainStabs** [dolthub/dolt#2779]
1. Have terminal not fullscreen
2. ```dolt commit -n 5```
3. Press `CTRL+C` while `-- More  --` is displayed

Panic:
```
panic:
        Error Trace:    page_output.go:80
                                                asm_amd64.s:1581
        Error:          Received unexpected error:
                        exit status 0xc000013a


goroutine 247 [running]:
github.com/dolthub/dolt/go/store/d.panicker.Errorf(...)
        /src/store/d/try.go:42
github.com/stretchr/testify/assert.Fail({0x263b0c0, 0x3555dc8}, {0xc000638140, 0x31}, {0x0, 0x0, 0x0})
        /go/pkg/mod/github.com/stretchr/testify@v1.7.0/assert/assertions.go:262 +0x384
github.com/stretchr/testify/assert.NoError({0x263b0c0, 0x3555dc8}, {0x263e080, 0xc0005920a0}, {0x0, 0x0, 0x0})
        /go/pkg/mod/github.com/stretchr/testify@v1.7.0/assert/assertions.go:1332 +0x105
github.com/stretchr/testify/assert.(*Assertions).NoError(0xc0003c8610, {0x263e080, 0xc0005920a0}, {0x0, 0x0, 0x0})
        /go/pkg/mod/github.com/stretchr/testify@v1.7.0/assert/assertion_forward.go:966 +0x87
github.com/dolthub/dolt/go/store/util/outputpager.Start.func1()
        /src/store/util/outputpager/page_output.go:80 +0x48
created by github.com/dolthub/dolt/go/store/util/outputpager.Start
        /src/store/util/outputpager/page_output.go:78 +0x32f
```
![image](https://user-images.githubusercontent.com/40151222/153222343-4a77f3e7-e1ef-4174-83df-414ccc94c586.png)

**Comment by timsehn** [comment]
@jennifersp is looking into this one.
