### ISSUE TITLE
Panic on `information_schema.tables`

### ISSUE THREAD

**Issue by VinaiRachakonda** [dolthub/dolt#2855]
Running a `SELECT` query on the information_schema.tables table is causing a bad panic

```bash
2022-02-22T10:46:27-08:00 DEBUG [conn 1] Starting query {connectTime=2022-02-22T10:46:24-08:00, query=SELECT * FROM `information_schema`.`tables` LIMIT 300 OFFSET 0}
panic: unexpected type

goroutine 339 [running]:
github.com/dolthub/go-mysql-server/sql.mustUint64(...)
	/Users/vinairachakonda/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220221232748-4fd62f0df488/sql/numbertype.go:691
github.com/dolthub/go-mysql-server/sql.numberTypeImpl.SQL({0x2a0}, {0x24a7120, 0x3975fe8})
	/Users/vinairachakonda/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220221232748-4fd62f0df488/sql/numbertype.go:349 +0x4ea
github.com/dolthub/go-mysql-server/server.rowToSQL({0xc01589bb80, 0x15, 0x2810dea}, {0xc015903a20, 0x15, 0x1})
	/Users/vinairachakonda/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220221232748-4fd62f0df488/server/handler.go:631 +0x10d
github.com/dolthub/go-mysql-server/server.(*Handler).doQuery.func4()
	/Users/vinairachakonda/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220221232748-4fd62f0df488/server/handler.go:421 +0x385
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/Users/vinairachakonda/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
	/Users/vinairachakonda/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x92
```

**Comment by jennifersp** [comment]
it works against latest changes on Dolt
