### ISSUE TITLE
Panic on weird Like Condition

### ISSUE THREAD

**Issue by VinaiRachakonda** [dolthub/dolt#2992]
Found this while playing around with ORMs.

```
dsimple> create table t(var text);
dsimple> insert into t values ("yolo"),("yak"),("yamaha");
Query OK, 3 rows affected
dsimple> select var from t where var LIKE (('%' || 'dsads') || '%');
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1d00128]

goroutine 275 [running]:
github.com/dolthub/go-mysql-server/sql/expression.(*Like).Eval(0xc000aae000, 0xc00027c480, {0xc000742080, 0x1, 0x2})
	/Users/vinairachakonda/go/src/dolthub/go-mysql-server/sql/expression/like.go:113 +0x3c8
github.com/dolthub/go-mysql-server/sql.EvaluateCondition(0xc00004f2c0, {0x2ba5460, 0xc000aae000}, {0xc000742080, 0xc00027dc20, 0xc00027dec0})
	/Users/vinairachakonda/go/src/dolthub/go-mysql-server/sql/core.go:950 +0x3c
github.com/dolthub/go-mysql-server/sql/plan.(*FilterIter).Next(0xc00004f2e0, 0x6481658)
	/Users/vinairachakonda/go/src/dolthub/go-mysql-server/sql/plan/filter.go:118 +0x7d
github.com/dolthub/go-mysql-server/sql/plan.(*trackedRowIter).Next(0xc000aae370, 0x0)
	/Users/vinairachakonda/go/src/dolthub/go-mysql-server/sql/plan/process.go:372 +0x2e
github.com/dolthub/go-mysql-server.transactionCommittingIter.Next(...)
	/Users/vinairachakonda/go/src/dolthub/go-mysql-server/engine.go:397
github.com/dolthub/dolt/go/cmd/dolt/commands/engine.getReadStageFunc.func1({0xc0006381e0, 0xc000503860}, {0xc000503b00, 0xc0004fb220, 0xc0002a0030})
	/Users/vinairachakonda/go/src/dolthub/dolt/go/cmd/dolt/commands/engine/sql_print.go:150 +0x1a3
github.com/dolthub/dolt/go/libraries/utils/pipeline.(*Stage).runFirstStageInPipeline(0xc000810de0, {0x2b81f10, 0xc0006381e0})
	/Users/vinairachakonda/go/src/dolthub/dolt/go/libraries/utils/pipeline/stage.go:124 +0xa5
github.com/dolthub/dolt/go/libraries/utils/pipeline.(*Stage).start.func1()
	/Users/vinairachakonda/go/src/dolthub/dolt/go/libraries/utils/pipeline/stage.go:106 +0xf7
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/Users/vinairachakonda/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
	/Users/vinairachakonda/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x92
```

Mysql will return an empty set.

**Comment by VinaiRachakonda** [comment]
This is now fixed.
