### ISSUE TITLE
dolt errors and crashes when trying to use DBeaver

### ISSUE THREAD

**Issue by alecstein** [dolthub/dolt#3071]
DBeaver is an open source database GUI. I'm using version 22.0.1.202203181646. You can install it on mac with 

```
brew install --cask dbeaver-community 
```

DBeaver has failed in two important cases for me in the last couple days when trying to use dolt.

1. Simply opening the `hospital-price-transparency-v3` database causes `dolt sql-server` to crash after connecting.
2. Trying to create a table with DBeaver (after doing `dolt init` and then `dolt sql-server`) crashes with
```
2022-03-23T16:16:43-04:00 WARN [conn 2] error running query {connectTime=2022-03-23T16:13:18-04:00, error=column "Tables_in_my_database" could not be found in any table in scope, query=/* ApplicationName=DBeaver 22.0.1 - Metadata */ SHOW FULL TABLES FROM my_database WHERE Tables_in_my_database LIKE 'NewTable'}
```

For (1) this is what is logged after running with `loglevel=debug`:

```
alecstein@Alecs-MacBook-Pro ~/d/b/hospital-price-transparency-v3> dolt sql-server --loglevel=debug                                         (base) 
Starting server with Config HP="localhost:3306"|U="root"|P=""|T="28800000"|R="false"|L="debug"
2022-03-23T16:24:36-04:00 INFO [conn 1] NewConnection {DisableClientMultiStatements=false}
2022-03-23T16:24:36-04:00 DEBUG [conn 1] Starting query {connectTime=2022-03-23T16:24:36-04:00, query=/* mysql-connector-java-8.0.17 (Revision: 16a712ddb3f826a1933ab42b0039f7fb9eebc6ec) */SELECT @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@collation_connection AS collation_connection, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_write_timeout AS net_write_timeout, @@performance_schema AS performance_schema, @@query_cache_size AS query_cache_size, @@query_cache_type AS query_cache_type, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, @@tx_isolation AS transaction_isolation, @@wait_timeout AS wait_timeout}
2022-03-23T16:24:36-04:00 DEBUG [conn 1] returning result &{[name:"auto_increment_increment" type:INT64 charset:33 name:"character_set_client" type:VARCHAR charset:33 name:"character_set_connection" type:VARCHAR charset:33 name:"character_set_results" type:VARCHAR charset:33 name:"character_set_server" type:VARCHAR charset:33 name:"collation_server" type:VARCHAR charset:33 name:"collation_connection" type:VARCHAR charset:33 name:"init_connect" type:VARCHAR charset:33 name:"interactive_timeout" type:INT64 charset:33 name:"license" type:VARCHAR charset:33 name:"lower_case_table_names" type:INT64 charset:33 name:"max_allowed_packet" type:INT64 charset:33 name:"net_write_timeout" type:INT64 charset:33 name:"performance_schema" type:INT8 charset:33 name:"query_cache_size" type:UINT64 charset:33 name:"query_cache_type" type:VARCHAR charset:33 name:"sql_mode" type:VARCHAR charset:33 name:"system_time_zone" type:VARCHAR charset:33 name:"time_zone" type:VARCHAR charset:33 name:"transaction_isolation" type:VARCHAR charset:33 name:"wait_timeout" type:INT64 charset:33] 1 0  [[INT64(1) VARCHAR("utf8mb4") VARCHAR("utf8mb4") VARCHAR("utf8mb4") VARCHAR("utf8mb4") VARCHAR("utf8mb4_0900_bin") VARCHAR("utf8mb4_0900_bin") VARCHAR("") INT64(28800) VARCHAR("GPL") INT64(0) INT64(1073741824) INT64(60) INT8(1) UINT64(1) VARCHAR("OFF") VARCHAR("NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES") VARCHAR("UTC") VARCHAR("SYSTEM") VARCHAR("REPEATABLE-READ") INT64(28800)]] <nil>} {connectTime=2022-03-23T16:24:36-04:00, query=/* mysql-connector-java-8.0.17 (Revision: 16a712ddb3f826a1933ab42b0039f7fb9eebc6ec) */SELECT @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@collation_connection AS collation_connection, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_write_timeout AS net_write_timeout, @@performance_schema AS performance_schema, @@query_cache_size AS query_cache_size, @@query_cache_type AS query_cache_type, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, @@tx_isolation AS transaction_isolation, @@wait_timeout AS wait_timeout}
2022-03-23T16:24:36-04:00 DEBUG [conn 1] Query took 3ms {connectTime=2022-03-23T16:24:36-04:00, query=/* mysql-connector-java-8.0.17 (Revision: 16a712ddb3f826a1933ab42b0039f7fb9eebc6ec) */SELECT @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@collation_connection AS collation_connection, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_write_timeout AS net_write_timeout, @@performance_schema AS performance_schema, @@query_cache_size AS query_cache_size, @@query_cache_type AS query_cache_type, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, @@tx_isolation AS transaction_isolation, @@wait_timeout AS wait_timeout}
2022-03-23T16:24:36-04:00 DEBUG [conn 1] Starting query {connectTime=2022-03-23T16:24:36-04:00, query=SET NAMES utf8mb4}
2022-03-23T16:24:36-04:00 DEBUG [conn 1] returning result &{[] 1 0  [[]] <nil>} {connectTime=2022-03-23T16:24:36-04:00, query=SET NAMES utf8mb4}
2022-03-23T16:24:36-04:00 DEBUG [conn 1] Query took 0ms {connectTime=2022-03-23T16:24:36-04:00, query=SET NAMES utf8mb4}
2022-03-23T16:24:36-04:00 DEBUG [conn 1] Starting query {connectTime=2022-03-23T16:24:36-04:00, query=SET character_set_results = NULL}
2022-03-23T16:24:36-04:00 DEBUG [conn 1] returning result &{[] 1 0  [[]] <nil>} {connectTime=2022-03-23T16:24:36-04:00, query=SET character_set_results = NULL}
2022-03-23T16:24:36-04:00 DEBUG [conn 1] Query took 0ms {connectTime=2022-03-23T16:24:36-04:00, query=SET character_set_results = NULL}
2022-03-23T16:24:36-04:00 DEBUG [conn 1] Starting query {connectTime=2022-03-23T16:24:36-04:00, query=SET autocommit=1}
2022-03-23T16:24:36-04:00 DEBUG [conn 1] returning result &{[] 1 0  [[]] <nil>} {connectTime=2022-03-23T16:24:36-04:00, query=SET autocommit=1}
2022-03-23T16:24:36-04:00 DEBUG [conn 1] Query took 0ms {connectTime=2022-03-23T16:24:36-04:00, query=SET autocommit=1}
2022-03-23T16:24:36-04:00 DEBUG [conn 1] Starting query {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Main */ SET autocommit=1}
2022-03-23T16:24:36-04:00 DEBUG [conn 1] returning result &{[] 1 0  [[]] <nil>} {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Main */ SET autocommit=1}
2022-03-23T16:24:36-04:00 DEBUG [conn 1] Query took 0ms {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Main */ SET autocommit=1}
2022-03-23T16:24:36-04:00 DEBUG [conn 1] Starting query {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Main */ SELECT DATABASE()}
2022-03-23T16:24:36-04:00 DEBUG [conn 1] returning result &{[name:"DATABASE()" type:TEXT charset:33] 1 0  [[NULL]] <nil>} {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Main */ SELECT DATABASE()}
2022-03-23T16:24:36-04:00 DEBUG [conn 1] Query took 0ms {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Main */ SELECT DATABASE()}
2022-03-23T16:24:36-04:00 INFO [conn 2] NewConnection {DisableClientMultiStatements=false}
2022-03-23T16:24:36-04:00 DEBUG [conn 2] Starting query {connectTime=2022-03-23T16:24:36-04:00, query=/* mysql-connector-java-8.0.17 (Revision: 16a712ddb3f826a1933ab42b0039f7fb9eebc6ec) */SELECT @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@collation_connection AS collation_connection, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_write_timeout AS net_write_timeout, @@performance_schema AS performance_schema, @@query_cache_size AS query_cache_size, @@query_cache_type AS query_cache_type, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, @@tx_isolation AS transaction_isolation, @@wait_timeout AS wait_timeout}
2022-03-23T16:24:36-04:00 DEBUG [conn 2] returning result &{[name:"auto_increment_increment" type:INT64 charset:33 name:"character_set_client" type:VARCHAR charset:33 name:"character_set_connection" type:VARCHAR charset:33 name:"character_set_results" type:VARCHAR charset:33 name:"character_set_server" type:VARCHAR charset:33 name:"collation_server" type:VARCHAR charset:33 name:"collation_connection" type:VARCHAR charset:33 name:"init_connect" type:VARCHAR charset:33 name:"interactive_timeout" type:INT64 charset:33 name:"license" type:VARCHAR charset:33 name:"lower_case_table_names" type:INT64 charset:33 name:"max_allowed_packet" type:INT64 charset:33 name:"net_write_timeout" type:INT64 charset:33 name:"performance_schema" type:INT8 charset:33 name:"query_cache_size" type:UINT64 charset:33 name:"query_cache_type" type:VARCHAR charset:33 name:"sql_mode" type:VARCHAR charset:33 name:"system_time_zone" type:VARCHAR charset:33 name:"time_zone" type:VARCHAR charset:33 name:"transaction_isolation" type:VARCHAR charset:33 name:"wait_timeout" type:INT64 charset:33] 1 0  [[INT64(1) VARCHAR("utf8mb4") VARCHAR("utf8mb4") VARCHAR("utf8mb4") VARCHAR("utf8mb4") VARCHAR("utf8mb4_0900_bin") VARCHAR("utf8mb4_0900_bin") VARCHAR("") INT64(28800) VARCHAR("GPL") INT64(0) INT64(1073741824) INT64(60) INT8(1) UINT64(1) VARCHAR("OFF") VARCHAR("NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES") VARCHAR("UTC") VARCHAR("SYSTEM") VARCHAR("REPEATABLE-READ") INT64(28800)]] <nil>} {connectTime=2022-03-23T16:24:36-04:00, query=/* mysql-connector-java-8.0.17 (Revision: 16a712ddb3f826a1933ab42b0039f7fb9eebc6ec) */SELECT @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@collation_connection AS collation_connection, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_write_timeout AS net_write_timeout, @@performance_schema AS performance_schema, @@query_cache_size AS query_cache_size, @@query_cache_type AS query_cache_type, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, @@tx_isolation AS transaction_isolation, @@wait_timeout AS wait_timeout}
2022-03-23T16:24:36-04:00 DEBUG [conn 2] Query took 1ms {connectTime=2022-03-23T16:24:36-04:00, query=/* mysql-connector-java-8.0.17 (Revision: 16a712ddb3f826a1933ab42b0039f7fb9eebc6ec) */SELECT @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@collation_connection AS collation_connection, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_write_timeout AS net_write_timeout, @@performance_schema AS performance_schema, @@query_cache_size AS query_cache_size, @@query_cache_type AS query_cache_type, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, @@tx_isolation AS transaction_isolation, @@wait_timeout AS wait_timeout}
2022-03-23T16:24:36-04:00 DEBUG [conn 2] Starting query {connectTime=2022-03-23T16:24:36-04:00, query=SET NAMES utf8mb4}
2022-03-23T16:24:36-04:00 DEBUG [conn 2] returning result &{[] 1 0  [[]] <nil>} {connectTime=2022-03-23T16:24:36-04:00, query=SET NAMES utf8mb4}
2022-03-23T16:24:36-04:00 DEBUG [conn 2] Query took 0ms {connectTime=2022-03-23T16:24:36-04:00, query=SET NAMES utf8mb4}
2022-03-23T16:24:36-04:00 DEBUG [conn 2] Starting query {connectTime=2022-03-23T16:24:36-04:00, query=SET character_set_results = NULL}
2022-03-23T16:24:36-04:00 DEBUG [conn 2] returning result &{[] 1 0  [[]] <nil>} {connectTime=2022-03-23T16:24:36-04:00, query=SET character_set_results = NULL}
2022-03-23T16:24:36-04:00 DEBUG [conn 2] Query took 0ms {connectTime=2022-03-23T16:24:36-04:00, query=SET character_set_results = NULL}
2022-03-23T16:24:36-04:00 DEBUG [conn 2] Starting query {connectTime=2022-03-23T16:24:36-04:00, query=SET autocommit=1}
2022-03-23T16:24:36-04:00 DEBUG [conn 2] returning result &{[] 1 0  [[]] <nil>} {connectTime=2022-03-23T16:24:36-04:00, query=SET autocommit=1}
2022-03-23T16:24:36-04:00 DEBUG [conn 2] Query took 0ms {connectTime=2022-03-23T16:24:36-04:00, query=SET autocommit=1}
2022-03-23T16:24:36-04:00 DEBUG [conn 2] Starting query {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Metadata */ SET autocommit=1}
2022-03-23T16:24:36-04:00 DEBUG [conn 2] returning result &{[] 1 0  [[]] <nil>} {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Metadata */ SET autocommit=1}
2022-03-23T16:24:36-04:00 DEBUG [conn 2] Query took 0ms {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Metadata */ SET autocommit=1}
2022-03-23T16:24:36-04:00 DEBUG [conn 2] Starting query {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Metadata */ SELECT DATABASE()}
2022-03-23T16:24:36-04:00 DEBUG [conn 2] returning result &{[name:"DATABASE()" type:TEXT charset:33] 1 0  [[NULL]] <nil>} {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Metadata */ SELECT DATABASE()}
2022-03-23T16:24:36-04:00 DEBUG [conn 2] Query took 0ms {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Metadata */ SELECT DATABASE()}
2022-03-23T16:24:36-04:00 DEBUG [conn 2] Starting query {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Metadata */ SHOW ENGINES}
2022-03-23T16:24:36-04:00 DEBUG [conn 2] returning result &{[name:"engine" type:VARCHAR charset:33 name:"support" type:VARCHAR charset:33 name:"comment" type:VARCHAR charset:33 name:"transactions" type:VARCHAR charset:33 name:"xa" type:VARCHAR charset:33 name:"savepoints" type:VARCHAR charset:33] 1 0  [[VARCHAR("InnoDB") VARCHAR("DEFAULT") VARCHAR("Supports transactions, row-level locking, and foreign keys") VARCHAR("YES") VARCHAR("YES") VARCHAR("YES")]] <nil>} {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Metadata */ SHOW ENGINES}
2022-03-23T16:24:36-04:00 DEBUG [conn 2] Query took 0ms {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Metadata */ SHOW ENGINES}
2022-03-23T16:24:36-04:00 DEBUG [conn 2] Starting query {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Metadata */ SHOW CHARSET}
2022-03-23T16:24:36-04:00 DEBUG [conn 2] returning result &{[name:"Charset" type:VARCHAR charset:33 name:"Description" type:VARCHAR charset:33 name:"Default collation" type:VARCHAR charset:33 name:"Maxlen" type:UINT64 charset:33] 1 0  [[VARCHAR("utf8mb4") VARCHAR("UTF-8 Unicode") VARCHAR("utf8mb4_0900_ai_ci") UINT64(4)]] <nil>} {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Metadata */ SHOW CHARSET}
2022-03-23T16:24:36-04:00 DEBUG [conn 2] Query took 0ms {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Metadata */ SHOW CHARSET}
2022-03-23T16:24:36-04:00 DEBUG [conn 2] Starting query {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Metadata */ SHOW COLLATION}
2022-03-23T16:24:36-04:00 DEBUG [conn 2] Query took 1ms {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Metadata */ SHOW COLLATION}
2022-03-23T16:24:36-04:00 DEBUG [conn 2] Starting query {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Metadata */ SELECT @@GLOBAL.character_set_server,@@GLOBAL.collation_server}
2022-03-23T16:24:36-04:00 DEBUG [conn 2] returning result &{[name:"@@GLOBAL.character_set_server" type:VARCHAR charset:33 name:"@@GLOBAL.collation_server" type:VARCHAR charset:33] 1 0  [[VARCHAR("utf8mb4") VARCHAR("utf8mb4_0900_bin")]] <nil>} {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Metadata */ SELECT @@GLOBAL.character_set_server,@@GLOBAL.collation_server}
2022-03-23T16:24:36-04:00 DEBUG [conn 2] Query took 0ms {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Metadata */ SELECT @@GLOBAL.character_set_server,@@GLOBAL.collation_server}
2022-03-23T16:24:36-04:00 DEBUG [conn 2] Starting query {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Metadata */ SHOW PLUGINS}
2022-03-23T16:24:36-04:00 WARN [conn 2] error running query {connectTime=2022-03-23T16:24:36-04:00, error=unsupported feature: SHOW PLUGINS, query=/* ApplicationName=DBeaver 22.0.1 - Metadata */ SHOW PLUGINS}
2022-03-23T16:24:36-04:00 DEBUG [conn 2] Starting query {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Metadata */ SHOW VARIABLES LIKE 'lower_case_table_names'}
2022-03-23T16:24:36-04:00 DEBUG [conn 2] returning result &{[name:"Variable_name" type:TEXT charset:33 name:"Value" type:TEXT charset:33] 1 0  [[TEXT("lower_case_table_names") TEXT("0")]] <nil>} {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Metadata */ SHOW VARIABLES LIKE 'lower_case_table_names'}
2022-03-23T16:24:36-04:00 DEBUG [conn 2] Query took 7ms {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Metadata */ SHOW VARIABLES LIKE 'lower_case_table_names'}
2022-03-23T16:24:36-04:00 DEBUG [conn 2] Starting query {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Metadata */ show databases}
2022-03-23T16:24:36-04:00 DEBUG [conn 2] Query took 0ms {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Metadata */ show databases}
2022-03-23T16:24:36-04:00 DEBUG [conn 2] Starting query {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Metadata */ SELECT * FROM information_schema.TABLES t WHERE t.TABLE_SCHEMA = 'information_schema' AND t.TABLE_NAME = 'CHECK_CONSTRAINTS'}
2022-03-23T16:24:36-04:00 DEBUG [conn 2] returning empty result {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Metadata */ SELECT * FROM information_schema.TABLES t WHERE t.TABLE_SCHEMA = 'information_schema' AND t.TABLE_NAME = 'CHECK_CONSTRAINTS'}
2022-03-23T16:24:36-04:00 DEBUG [conn 2] Query took 6ms {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Metadata */ SELECT * FROM information_schema.TABLES t WHERE t.TABLE_SCHEMA = 'information_schema' AND t.TABLE_NAME = 'CHECK_CONSTRAINTS'}
2022-03-23T16:24:38-04:00 DEBUG [conn 1] Starting query {connectTime=2022-03-23T16:24:36-04:00, query=SELECT @@session.tx_isolation}
2022-03-23T16:24:38-04:00 DEBUG [conn 1] returning result &{[name:"@@SESSION.tx_isolation" type:VARCHAR charset:33] 1 0  [[VARCHAR("REPEATABLE-READ")]] <nil>} {connectTime=2022-03-23T16:24:36-04:00, query=SELECT @@session.tx_isolation}
2022-03-23T16:24:38-04:00 DEBUG [conn 1] Query took 0ms {connectTime=2022-03-23T16:24:36-04:00, query=SELECT @@session.tx_isolation}
2022-03-23T16:24:38-04:00 DEBUG [conn 2] Starting query {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Metadata */ SELECT * FROM information_schema.SCHEMATA WHERE SCHEMA_NAME='hospital_price_transparency_v3'}
2022-03-23T16:24:38-04:00 DEBUG [conn 2] returning result &{[name:"catalog_name" type:TEXT charset:33 name:"schema_name" type:TEXT charset:33 name:"default_character_set_name" type:TEXT charset:33 name:"default_collation_name" type:TEXT charset:33 name:"sql_path" type:TEXT charset:33] 1 0  [[TEXT("def") TEXT("hospital_price_transparency_v3") TEXT("utf8mb4") TEXT("utf8mb4_0900_bin") NULL]] <nil>} {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Metadata */ SELECT * FROM information_schema.SCHEMATA WHERE SCHEMA_NAME='hospital_price_transparency_v3'}
2022-03-23T16:24:38-04:00 DEBUG [conn 2] Query took 0ms {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Metadata */ SELECT * FROM information_schema.SCHEMATA WHERE SCHEMA_NAME='hospital_price_transparency_v3'}
2022-03-23T16:24:38-04:00 DEBUG [conn 1] Starting query {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Main */ SELECT SUM((DATA_LENGTH+INDEX_LENGTH)) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='hospital_price_transparency_v3'}
2022-03-23T16:24:38-04:00 DEBUG [conn 1] returning result &{[name:"SUM((DATA_LENGTH+INDEX_LENGTH))" type:FLOAT64 charset:33] 1 0  [[NULL]] <nil>} {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Main */ SELECT SUM((DATA_LENGTH+INDEX_LENGTH)) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='hospital_price_transparency_v3'}
2022-03-23T16:24:38-04:00 DEBUG [conn 1] Query took 2ms {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Main */ SELECT SUM((DATA_LENGTH+INDEX_LENGTH)) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='hospital_price_transparency_v3'}
2022-03-23T16:24:38-04:00 DEBUG [conn 2] Starting query {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Metadata */ SELECT * FROM information_schema.SCHEMATA WHERE SCHEMA_NAME='rl1987'}
2022-03-23T16:24:38-04:00 DEBUG [conn 2] returning result &{[name:"catalog_name" type:TEXT charset:33 name:"schema_name" type:TEXT charset:33 name:"default_character_set_name" type:TEXT charset:33 name:"default_collation_name" type:TEXT charset:33 name:"sql_path" type:TEXT charset:33] 1 0  [[TEXT("def") TEXT("rl1987") TEXT("utf8mb4") TEXT("utf8mb4_0900_bin") NULL]] <nil>} {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Metadata */ SELECT * FROM information_schema.SCHEMATA WHERE SCHEMA_NAME='rl1987'}
2022-03-23T16:24:38-04:00 DEBUG [conn 2] Query took 0ms {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Metadata */ SELECT * FROM information_schema.SCHEMATA WHERE SCHEMA_NAME='rl1987'}
2022-03-23T16:24:38-04:00 DEBUG [conn 1] Starting query {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Main */ SELECT SUM((DATA_LENGTH+INDEX_LENGTH)) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='rl1987'}
2022-03-23T16:24:38-04:00 DEBUG [conn 1] returning result &{[name:"SUM((DATA_LENGTH+INDEX_LENGTH))" type:FLOAT64 charset:33] 1 0  [[NULL]] <nil>} {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Main */ SELECT SUM((DATA_LENGTH+INDEX_LENGTH)) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='rl1987'}
2022-03-23T16:24:38-04:00 DEBUG [conn 1] Query took 3ms {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Main */ SELECT SUM((DATA_LENGTH+INDEX_LENGTH)) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='rl1987'}
2022-03-23T16:24:40-04:00 DEBUG [conn 2] Starting query {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Metadata */ SHOW FULL TABLES FROM hospital_price_transparency_v3}
2022-03-23T16:24:40-04:00 DEBUG [conn 2] Query took 0ms {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Metadata */ SHOW FULL TABLES FROM hospital_price_transparency_v3}
2022-03-23T16:24:40-04:00 DEBUG [conn 2] Starting query {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Metadata */ SHOW TABLE STATUS FROM hospital_price_transparency_v3}
2022-03-23T16:24:40-04:00 DEBUG [conn 2] Query took 0ms {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Metadata */ SHOW TABLE STATUS FROM hospital_price_transparency_v3}
2022-03-23T16:24:41-04:00 DEBUG [conn 2] Starting query {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Metadata */ SELECT * FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='hospital_price_transparency_v3' AND TABLE_NAME='prices' ORDER BY ORDINAL_POSITION}
2022-03-23T16:24:41-04:00 DEBUG [conn 2] Query took 5ms {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Metadata */ SELECT * FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='hospital_price_transparency_v3' AND TABLE_NAME='prices' ORDER BY ORDINAL_POSITION}
2022-03-23T16:24:44-04:00 DEBUG [conn 1] Starting query {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Main */ SELECT * FROM hospital_price_transparency_v3.prices LIMIT 0, 200}
2022-03-23T16:24:44-04:00 DEBUG [conn 1] Query took 74ms {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Main */ SELECT * FROM hospital_price_transparency_v3.prices LIMIT 0, 200}
2022-03-23T16:24:44-04:00 DEBUG [conn 2] Starting query {connectTime=2022-03-23T16:24:36-04:00, query=/* ApplicationName=DBeaver 22.0.1 - Metadata */ SELECT * FROM information_schema.STATISTICS WHERE TABLE_SCHEMA='hospital_price_transparency_v3' AND TABLE_NAME='prices' ORDER BY TABLE_NAME,INDEX_NAME,SEQ_IN_INDEX}
panic: unexpected type

goroutine 13350 [running]:
github.com/dolthub/go-mysql-server/sql.mustInt64(...)
	/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220311194643-f7ae1605f60b/sql/numbertype.go:669
github.com/dolthub/go-mysql-server/sql.numberTypeImpl.SQL({0x109}, {0x0, 0x0, 0x0}, {0x101e61280, 0x140180fd468})
	/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220311194643-f7ae1605f60b/sql/numbertype.go:347 +0x68c
github.com/dolthub/go-mysql-server/server.rowToSQL({0x103099a20, 0x12, 0x12}, {0x1401814f560, 0x12, 0x12})
	/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220311194643-f7ae1605f60b/server/handler.go:640 +0x12c
github.com/dolthub/go-mysql-server/server.(*Handler).doQuery.func4()
	/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220311194643-f7ae1605f60b/server/handler.go:421 +0x338
golang.org/x/sync/errgroup.(*Group).Go.func1(0x14013d78b10, 0x14013ec8480)
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x58
created by golang.org/x/sync/errgroup.(*Group).Go
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x60
```

**Comment by jennifersp** [comment]
issues are fixed https://github.com/dolthub/go-mysql-server/pull/907
