### ISSUE TITLE
Inserting into foreign key table causes crash

### ISSUE THREAD

**Issue by alecstein** [dolthub/dolt#3088]
I have two tables: `facility` and `facility_type`.

Trying to insert a value into `facility_type` table causes an instant crash:

```
bug_repro> INSERT INTO `bug_repro`.`facility_type` (`facility_type`) VALUES ('5 MINUTE CRAFTS VIDEOSLAVE CLONING FACILITY');
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x60 pc=0x101d9fdd4]

goroutine 1 [running]:
github.com/dolthub/dolt/go/libraries/doltcore/sqle/writer.(*nomsWriteSession).getTableEditor(0x1400061edb0, {0x102918568, 0x14000452460}, {0x1400069062d, 0xd}, {0x102937c80, 0x1400009acd0})
	/src/libraries/doltcore/sqle/writer/noms_write_session.go:232 +0x74
github.com/dolthub/dolt/go/libraries/doltcore/sqle/writer.(*nomsWriteSession).GetTableWriter(0x1400061edb0, {0x102918568, 0x14000452460}, {0x1400069062d, 0xd}, {0x140006d4240, 0x14}, {0x1028fcc70, 0x1400065a7a0}, 0x1400065a9c0, ...)
	/src/libraries/doltcore/sqle/writer/noms_write_session.go:103 +0x138
github.com/dolthub/dolt/go/libraries/doltcore/sqle.(*WritableDoltTable).getTableEditor(0x14000157170, 0x14000452460)
	/src/libraries/doltcore/sqle/tables.go:449 +0x37c
github.com/dolthub/dolt/go/libraries/doltcore/sqle.(*WritableDoltTable).GetNextAutoIncrementValue(0x14000157170, 0x14000452460, {0x10256d000, 0x1400065a9b0})
	/src/libraries/doltcore/sqle/tables.go:570 +0x40
github.com/dolthub/go-mysql-server/sql/expression.(*AutoIncrement).Eval(0x140008bdfb0, 0x14000452460, {0x1400065a9a0, 0x1, 0x1})
	/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220311194643-f7ae1605f60b/sql/expression/auto_increment.go:101 +0x160
github.com/dolthub/go-mysql-server/sql/plan.ProjectRow(0x14000452460, {0x14000559d10, 0x1, 0x1}, {0x1400065a9a0, 0x1, 0x1})
	/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220311194643-f7ae1605f60b/sql/plan/project.go:166 +0x398
github.com/dolthub/go-mysql-server/sql/plan.(*iter).Next(0x140006954a0, 0x14000452460)
	/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220311194643-f7ae1605f60b/sql/plan/project.go:138 +0xac
github.com/dolthub/go-mysql-server/sql/plan.(*insertIter).Next(0x140005ada00, 0x14000452460)
	/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220311194643-f7ae1605f60b/sql/plan/insert.go:320 +0x44
github.com/dolthub/go-mysql-server/sql/plan.(*tableEditorIter).Next(0x1400005fe00, 0x14000452460)
	/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220311194643-f7ae1605f60b/sql/plan/table_editor.go:51 +0x7c
github.com/dolthub/go-mysql-server/sql/plan.(*accumulatorIter).Next(0x140006954d0, 0x14000452460)
	/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220311194643-f7ae1605f60b/sql/plan/row_update_accumulator.go:309 +0x194
github.com/dolthub/go-mysql-server/sql/plan.(*trackedRowIter).Next(0x1400009ab40, 0x14000452460)
	/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220311194643-f7ae1605f60b/sql/plan/process.go:372 +0x3c
github.com/dolthub/go-mysql-server.transactionCommittingIter.Next(...)
	/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220311194643-f7ae1605f60b/engine.go:397
github.com/dolthub/dolt/go/cmd/dolt/commands/engine.printOKResult(0x14000452460, {0x1028fbf40, 0x14000695500})
	/src/cmd/dolt/commands/engine/sql_print.go:87 +0x38
github.com/dolthub/dolt/go/cmd/dolt/commands/engine.PrettyPrintResults(0x14000452460, 0x0, {0x103776c68, 0x1, 0x1}, {0x1028fbf40, 0x14000695500}, 0x0)
	/src/cmd/dolt/commands/engine/sql_print.go:61 +0x2b4
github.com/dolthub/dolt/go/cmd/dolt/commands.runShell.func3.1({0x102917c70, 0x1400062f140}, 0x1400061f230, 0x140006f41e8, 0x1400018c2b0, 0x1400016c000, {0x140005aa5a0, 0x5c}, 0x14000907270, 0x14000907230, ...)
	/src/cmd/dolt/commands/sql.go:843 +0x39c
github.com/dolthub/dolt/go/cmd/dolt/commands.runShell.func3(0x1400053e000)
	/src/cmd/dolt/commands/sql.go:851 +0x478
github.com/dolthub/ishell.handleUninterpretedInput(0x1400016c000, {0x140005aa5a0, 0x5d})
	/go/pkg/mod/github.com/dolthub/ishell@v0.0.0-20220112232610-14e753f0f371/ishell.go:288 +0x18c
github.com/dolthub/ishell.(*Shell).run(0x1400016c000)
	/go/pkg/mod/github.com/dolthub/ishell@v0.0.0-20220112232610-14e753f0f371/ishell.go:245 +0x34c
github.com/dolthub/ishell.(*Shell).Run(0x1400016c000)
	/go/pkg/mod/github.com/dolthub/ishell@v0.0.0-20220112232610-14e753f0f371/ishell.go:139 +0x34
github.com/dolthub/dolt/go/cmd/dolt/commands.runShell({0x102917c70, 0x1400062f140}, 0x1400061f230, 0x14000692800)
	/src/cmd/dolt/commands/sql.go:861 +0x740
github.com/dolthub/dolt/go/cmd/dolt/commands.execShell({0x102917c70, 0x1400062f140}, 0x14000692800, 0x0, {0x140006d4240, 0x14})
	/src/cmd/dolt/commands/sql.go:383 +0xc0
github.com/dolthub/dolt/go/cmd/dolt/commands.SqlCmd.Exec({{0x102151532, 0x6}}, {0x102917c70, 0x1400062f140}, {0x14000054b78, 0x8}, {0x14000136010, 0x0, 0x0}, 0x140006e80b0)
	/src/cmd/dolt/commands/sql.go:233 +0x71c
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.handleCommand({{0x10214f599, 0x4}, {0x1021686a0, 0x11}, {0x0, 0x0}, {0x140001fd8c0, 0x2b, 0x2b}, 0x0}, ...)
	/src/cmd/dolt/cli/command.go:222 +0x2ac
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.Exec({{0x10214f599, 0x4}, {0x1021686a0, 0x11}, {0x0, 0x0}, {0x140001fd8c0, 0x2b, 0x2b}, 0x0}, ...)
	/src/cmd/dolt/cli/command.go:179 +0x418
main.runMain()
	/src/cmd/dolt/dolt.go:345 +0x72c
main.main()
	/src/cmd/dolt/dolt.go:131 +0x20
```

**Comment by zachmu** [comment]
@alecstein can you get us a full repro for this? We need the schema of both those tables (via `show create table`) and any data necessary to trigger the panic.

**Comment by timsehn** [comment]
@alecstein needs to make better more reproducible bugs. 

Without the schema we can't figure out what's going on here.
