### ISSUE TITLE
`ALTER TABLE ADD COLUMN` with default value referring to non-existent column panics

### ISSUE THREAD

**Issue by VinaiRachakonda** [dolthub/dolt#3107]
Consider the following table

```
CREATE TABLE `test` (
  `pk` bigint NOT NULL,
  `mycol` int NOT NULL DEFAULT "100",
  `v3` int DEFAULT ((mycol + 1)),
  PRIMARY KEY (`pk`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
```

and the query

```
ALTER TABLE test ADD COLUMN (v6 int DEFAULT v2);
```

```
panic: unresolved column is a placeholder node, but Eval was called

goroutine 1 [running]:
github.com/dolthub/go-mysql-server/sql/expression.(*UnresolvedColumn).Eval(0xc00056c2f8, 0x100ef27?, {0x0?, 0x2716be0?, 0xc0006a2501?})
	/Users/vinairachakonda/go/src/dolthub/go-mysql-server/sql/expression/unresolved.go:91 +0x27
github.com/dolthub/go-mysql-server/sql.(*ColumnDefaultValue).CheckType(0xc00079b590, 0xc0006a2540?)
	/Users/vinairachakonda/go/src/dolthub/go-mysql-server/sql/columndefault.go:170 +0x4c
github.com/dolthub/go-mysql-server/sql/analyzer.resolveColumnDefaultsOnWrapper(0xc00079b560?, 0xc0003d0310, 0xc0004fd040)
	/Users/vinairachakonda/go/src/dolthub/go-mysql-server/sql/analyzer/resolve_column_defaults.go:712 +0x645
github.com/dolthub/go-mysql-server/sql/analyzer.resolveColumnDefaults.func1.6({0x2bd1a10?, 0xc0004fd040?})
	/Users/vinairachakonda/go/src/dolthub/go-mysql-server/sql/analyzer/resolve_column_defaults.go:555 +0x6d
github.com/dolthub/go-mysql-server/sql/plan.TransformExpressionsUp.func1({0x2bd4a80?, 0xc0004fd010?}, {0x2bd1a10?, 0xc0004fd040?})
	/Users/vinairachakonda/go/src/dolthub/go-mysql-server/sql/plan/transform.go:114 +0x2d
github.com/dolthub/go-mysql-server/sql/expression.TransformUpWithNode({0x2bd4a80, 0xc000117360}, {0x2bd1a10, 0xc0004fcee0}, 0xc00056c7b0)
	/Users/vinairachakonda/go/src/dolthub/go-mysql-server/sql/expression/transform.go:108 +0x185
github.com/dolthub/go-mysql-server/sql/plan.TransformExpressionsWithNode({0x2bd4a80, 0xc000117360}, 0xc0003d0310?)
	/Users/vinairachakonda/go/src/dolthub/go-mysql-server/sql/plan/transform.go:141 +0xf6
github.com/dolthub/go-mysql-server/sql/plan.TransformExpressionsUpWithNode.func1({0x2bd4a80?, 0xc000117360?})
	/Users/vinairachakonda/go/src/dolthub/go-mysql-server/sql/plan/transform.go:106 +0x27
github.com/dolthub/go-mysql-server/sql/plan.TransformUp.func1({{0x2bd4a80, 0xc000117360}, {0x0, 0x0}, 0xffffffffffffffff, {0x3a0b748, 0x0, 0x0}})
	/Users/vinairachakonda/go/src/dolthub/go-mysql-server/sql/plan/transform.go:98 +0x4f
github.com/dolthub/go-mysql-server/sql/plan.transformUpCtx({{0x2bd4a80, 0xc000117310}, {0x0, 0x0}, 0xffffffffffffffff, {0x3a0b748, 0x0, 0x0}}, 0x0, 0xc00056c740)
	/Users/vinairachakonda/go/src/dolthub/go-mysql-server/sql/plan/transform.go:91 +0x6ae
github.com/dolthub/go-mysql-server/sql/plan.TransformUpCtx({0x2bd4a80?, 0xc000117310?}, 0xc000117310?, 0x0?)
	/Users/vinairachakonda/go/src/dolthub/go-mysql-server/sql/plan/transform.go:53 +0xb1
github.com/dolthub/go-mysql-server/sql/plan.TransformUp({0x2bd4a80?, 0xc000117310?}, 0xc00056c820?)
	/Users/vinairachakonda/go/src/dolthub/go-mysql-server/sql/plan/transform.go:97 +0x45
github.com/dolthub/go-mysql-server/sql/plan.TransformExpressionsUpWithNode({0x2bd4a80?, 0xc000117310?}, 0x0?)
	/Users/vinairachakonda/go/src/dolthub/go-mysql-server/sql/plan/transform.go:105 +0x3f
github.com/dolthub/go-mysql-server/sql/plan.TransformExpressionsUp({0x2bd4a80?, 0xc000117310?}, 0x1?)
	/Users/vinairachakonda/go/src/dolthub/go-mysql-server/sql/plan/transform.go:113 +0x3f
github.com/dolthub/go-mysql-server/sql/analyzer.resolveColumnDefaults.func1({0x2bd4a80, 0xc000117310})
	/Users/vinairachakonda/go/src/dolthub/go-mysql-server/sql/analyzer/resolve_column_defaults.go:538 +0x25e
github.com/dolthub/go-mysql-server/sql/plan.TransformUp.func1({{0x2bd4a80, 0xc000117310}, {0x0, 0x0}, 0xffffffffffffffff, {0x3a0b748, 0x0, 0x0}})
	/Users/vinairachakonda/go/src/dolthub/go-mysql-server/sql/plan/transform.go:98 +0x4f
github.com/dolthub/go-mysql-server/sql/plan.transformUpCtx({{0x2bd4a80, 0xc0001172c0}, {0x0, 0x0}, 0xffffffffffffffff, {0x3a0b748, 0x0, 0x0}}, 0x0, 0xc00056cb08)
	/Users/vinairachakonda/go/src/dolthub/go-mysql-server/sql/plan/transform.go:91 +0x6ae
github.com/dolthub/go-mysql-server/sql/plan.TransformUpCtx({0x2bd4a80?, 0xc0001172c0?}, 0x20462ab?, 0x0?)
	/Users/vinairachakonda/go/src/dolthub/go-mysql-server/sql/plan/transform.go:53 +0xb1
github.com/dolthub/go-mysql-server/sql/plan.TransformUp({0x2bd4a80?, 0xc0001172c0?}, 0x15?)
	/Users/vinairachakonda/go/src/dolthub/go-mysql-server/sql/plan/transform.go:97 +0x45
github.com/dolthub/go-mysql-server/sql/analyzer.resolveColumnDefaults(0xc000694640, 0x2872224?, {0x2bd4a80, 0xc0001172c0}, 0xc0001172c0?)
	/Users/vinairachakonda/go/src/dolthub/go-mysql-server/sql/analyzer/resolve_column_defaults.go:447 +0xe8
github.com/dolthub/go-mysql-server/sql/analyzer.(*Batch).evalOnce(0x2bd4a80?, 0xc0001bc190?, 0xc00013a140, {0x2bd4a80?, 0xc000116e60?}, 0x3a0b140?)
	/Users/vinairachakonda/go/src/dolthub/go-mysql-server/sql/analyzer/batch.go:94 +0x1e7
github.com/dolthub/go-mysql-server/sql/analyzer.(*Batch).Eval(0xc0000c82d0, 0x28a0581?, 0xc00013a140, {0x2bd4a80, 0xc000116e60}, 0x1?)
	/Users/vinairachakonda/go/src/dolthub/go-mysql-server/sql/analyzer/batch.go:54 +0x14d
github.com/dolthub/go-mysql-server/sql/analyzer.(*Analyzer).analyzeWithSelector(0xc00013a140, 0xc0006941e0?, {0x2bd4a80?, 0xc0001bc190}, 0xc000554000?, 0x290a7e8)
	/Users/vinairachakonda/go/src/dolthub/go-mysql-server/sql/analyzer/analyzer.go:378 +0x314
github.com/dolthub/go-mysql-server/sql/analyzer.(*Analyzer).Analyze(...)
	/Users/vinairachakonda/go/src/dolthub/go-mysql-server/sql/analyzer/analyzer.go:350
github.com/dolthub/go-mysql-server.(*Engine).QueryNodeWithBindings(0xc000917b80, 0xc000189da0?, {0xc000189da0?, 0xc000390000?}, {0x0?, 0x0?}, 0x0)
	/Users/vinairachakonda/go/src/dolthub/go-mysql-server/engine.go:181 +0x153
github.com/dolthub/go-mysql-server.(*Engine).QueryWithBindings(...)
	/Users/vinairachakonda/go/src/dolthub/go-mysql-server/engine.go:139
github.com/dolthub/go-mysql-server.(*Engine).Query(0xc000189da0?, 0x2f?, {0xc000189da0?, 0xc0007b5028?})
	/Users/vinairachakonda/go/src/dolthub/go-mysql-server/engine.go:130 +0x26
github.com/dolthub/dolt/go/cmd/dolt/commands/engine.(*SqlEngine).Query(...)
	/Users/vinairachakonda/go/src/dolthub/dolt/go/cmd/dolt/commands/engine/sqlengine.go:182
github.com/dolthub/dolt/go/cmd/dolt/commands.processQuery(0x2bc58f8?, {0xc000189da0, 0x2f}, 0xc0009fcc60)
	/Users/vinairachakonda/go/src/dolthub/dolt/go/cmd/dolt/commands/sql.go:1006 +0x270
github.com/dolthub/dolt/go/cmd/dolt/commands.runShell.func3.1({0x2bc4900, 0xc0000ba630}, 0xc0009fcc60, 0xc000aa8ed0, 0xc00094d4a0, 0xc00091c000, {0xc000189da0, 0x2f}, 0xc00056d278, 0xc00056d238, ...)
	/Users/vinairachakonda/go/src/dolthub/dolt/go/cmd/dolt/commands/sql.go:839 +0x256
github.com/dolthub/dolt/go/cmd/dolt/commands.runShell.func3(0xc00091c000?)
	/Users/vinairachakonda/go/src/dolthub/dolt/go/cmd/dolt/commands/sql.go:851 +0x48c
github.com/dolthub/ishell.handleUninterpretedInput(0xc00091c000, {0xc000189da0, 0x30})
	/Users/vinairachakonda/go/pkg/mod/github.com/dolthub/ishell@v0.0.0-20220112232610-14e753f0f371/ishell.go:288 +0x144
github.com/dolthub/ishell.(*Shell).run(0xc00091c000)
	/Users/vinairachakonda/go/pkg/mod/github.com/dolthub/ishell@v0.0.0-20220112232610-14e753f0f371/ishell.go:245 +0x306
github.com/dolthub/ishell.(*Shell).Run(0xc00091c000?)
	/Users/vinairachakonda/go/pkg/mod/github.com/dolthub/ishell@v0.0.0-20220112232610-14e753f0f371/ishell.go:139 +0x28
github.com/dolthub/dolt/go/cmd/dolt/commands.runShell({0x2bc4900?, 0xc0000ba630}, 0xc0009fcc60, 0x2bc4900?)
	/Users/vinairachakonda/go/src/dolthub/dolt/go/cmd/dolt/commands/sql.go:861 +0x765
github.com/dolthub/dolt/go/cmd/dolt/commands.execShell({0x2bc4900, 0xc0000ba630}, 0x2857eb9?, 0x4?, {0xc00005c8ec?, 0x4b8?})
	/Users/vinairachakonda/go/src/dolthub/dolt/go/cmd/dolt/commands/sql.go:383 +0xd2
github.com/dolthub/dolt/go/cmd/dolt/commands.SqlCmd.Exec({{0x2859d59?, 0xc000ca7910?}}, {0x2bc4900, 0xc0000ba630}, {0xc000980b00, 0x8}, {0xc0001a0010, 0x0, 0x0}, 0xc0004e6000)
	/Users/vinairachakonda/go/src/dolthub/dolt/go/cmd/dolt/commands/sql.go:233 +0x6c7
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.handleCommand({{0x2857e3d, 0x4}, {0x2870f30, 0x11}, {0x0, 0x0}, {0xc0001542c0, 0x2b, 0x2b}, 0x0}, ...)
	/Users/vinairachakonda/go/src/dolthub/dolt/go/cmd/dolt/cli/command.go:222 +0x29e
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.Exec({{0x2857e3d, 0x4}, {0x2870f30, 0x11}, {0x0, 0x0}, {0xc0001542c0, 0x2b, 0x2b}, 0x0}, ...)
	/Users/vinairachakonda/go/src/dolthub/dolt/go/cmd/dolt/cli/command.go:179 +0x47f
main.runMain()
	/Users/vinairachakonda/go/src/dolthub/dolt/go/cmd/dolt/dolt.go:345 +0x6a5
main.main()
	/Users/vinairachakonda/go/src/dolthub/dolt/go/cmd/dolt/dolt.go:131 +0x19
```

**Comment by VinaiRachakonda** [comment]
No longer panics
