### ISSUE TITLE
Dolt table import OOM panic

### ISSUE THREAD

**Issue by CaptainStabs** [dolthub/dolt#3143]
```
Rows Processed: 4,915,200, Additions: 4,865,125, Modifications: 22,998, Had No Effect: 27,077fatal error: runtime: cannot allocate memory

runtime stack:
runtime.throw({0x276ead1, 0xf6ab77})
        /usr/local/go/src/runtime/panic.go:1198 +0x76
runtime.persistentalloc1(0x4000, 0xc000000000, 0x3a4da68)
        /usr/local/go/src/runtime/malloc.go:1411 +0x24f
runtime.persistentalloc.func1()
        /usr/local/go/src/runtime/malloc.go:1365 +0x2e
runtime.persistentalloc(0x1, 0xd65dff5c8, 0xf0bd2e)
        /usr/local/go/src/runtime/malloc.go:1364 +0x6f
runtime.(*fixalloc).alloc(0x3a20780)
        /usr/local/go/src/runtime/mfixalloc.go:80 +0x85
runtime.(*mheap).allocMSpanLocked(0x3a09d40)
        /usr/local/go/src/runtime/mheap.go:1078 +0xa5
runtime.(*mheap).allocSpan(0x3a09d40, 0x1, 0x0, 0xb)
        /usr/local/go/src/runtime/mheap.go:1192 +0x1b7
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:913 +0x69
runtime.systemstack()
        /usr/local/go/src/runtime/asm_amd64.s:383 +0x4e

goroutine 314 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:350 fp=0xc1aeac74f8 sp=0xc1aeac74f0 pc=0xf68b20
runtime.(*mheap).alloc(0x102a259, 0x6, 0x0, 0x1)
        /usr/local/go/src/runtime/mheap.go:907 +0x73 fp=0xc1aeac7548 sp=0xc1aeac74f8 pc=0xf26bb3
runtime.(*mcentral).grow(0x2000)
        /usr/local/go/src/runtime/mcentral.go:241 +0x65 fp=0xc1aeac7590 sp=0xc1aeac7548 pc=0xf18165
runtime.(*mcentral).cacheSpan(0x3a1a9c0)
        /usr/local/go/src/runtime/mcentral.go:161 +0x69e fp=0xc1aeac7608 sp=0xc1aeac7590 pc=0xf17f9e
runtime.(*mcache).refill(0x18090cc0eb8, 0xb)
        /usr/local/go/src/runtime/mcache.go:162 +0xaf fp=0xc1aeac7658 sp=0xc1aeac7608 pc=0xf171af
runtime.(*mcache).nextFree(0x18090cc0eb8, 0xb)
        /usr/local/go/src/runtime/malloc.go:880 +0x85 fp=0xc1aeac76a0 sp=0xc1aeac7658 pc=0xf0cf25
runtime.mallocgc(0x21, 0x0, 0x0)
        /usr/local/go/src/runtime/malloc.go:1071 +0x4e8 fp=0xc1aeac7720 sp=0xc1aeac76a0 pc=0xf0d5a8
runtime.slicebytetostring(0xc7d31e9f50, 0xc7d31e9f80, 0x21)
        /usr/local/go/src/runtime/string.go:110 +0x50 fp=0xc1aeac7758 sp=0xc1aeac7720 pc=0xf51d70
math/big.(*Int).Text(...)
        /usr/local/go/src/math/big/intconv.go:25
math/big.(*Int).String(...)
        /usr/local/go/src/math/big/intconv.go:40
github.com/shopspring/decimal.Decimal.string({0xc7d31f0ea0, 0x0}, 0x0)
        /go/pkg/mod/github.com/shopspring/decimal@v1.2.0/decimal.go:1076 +0x1ec fp=0xc1aeac7830 sp=0xc1aeac7758 pc=0x136256c
github.com/shopspring/decimal.Decimal.StringFixed({0xc7d31f0e40, 0x398c450}, 0xd31f4800)
        /go/pkg/mod/github.com/shopspring/decimal@v1.2.0/decimal.go:764 +0x25 fp=0xc1aeac7858 sp=0xc1aeac7830 pc=0x13611a5
github.com/dolthub/go-mysql-server/sql.decimalType.Convert({{0xc0000811a0, 0x38}, 0xaa, 0xaa}, {0x23eb920, 0xc7d2d219d0})
        /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220316231244-f2f8808feb31/sql/decimal.go:127 +0x47 fp=0xc1aeac7898 sp=0xc1aeac7858 pc=0x14ccf07
github.com/dolthub/go-mysql-server/sql.(*decimalType).Convert(0x398f890, {0x23eb920, 0xc7d2d219d0})
        <autogenerated>:1 +0x55 fp=0xc1aeac78d0 sp=0xc1aeac7898 pc=0x1550fb5
github.com/dolthub/go-mysql-server/sql/expression.convertValue({0x23eb920, 0xc7d2d219d0}, {0x2739216, 0xc7d31cab40})
        /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220316231244-f2f8808feb31/sql/expression/convert.go:182 +0x38e fp=0xc1aeac7910 sp=0xc1aeac78d0 pc=0x1c11b8e
github.com/dolthub/go-mysql-server/sql/expression.convertLeftAndRight({0x23eb920, 0xc7d2d219d0}, {0x23eb060, 0x38dde60}, {0x2739216, 0x7})
        /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220316231244-f2f8808feb31/sql/expression/comparison.go:230 +0x45 fp=0xc1aeac7950 sp=0xc1aeac7910 pc=0x1c0d765
github.com/dolthub/go-mysql-server/sql/expression.(*comparison).castLeftAndRight(0xc00acdb5a0, {0x23eb920, 0xc7d2d219d0}, {0x23eb060, 0x38dde60})
        /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220316231244-f2f8808feb31/sql/expression/comparison.go:174 +0x185 fp=0xc1aeac7a00 sp=0xc1aeac7950 pc=0x1c0ce85
github.com/dolthub/go-mysql-server/sql/expression.(*comparison).Compare(0xc00acdb5a0, 0x23d65a0, {0xc7d31cab40, 0x0, 0x0})
        /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220316231244-f2f8808feb31/sql/expression/comparison.go:88 +0x2ce fp=0xc1aeac7a80 sp=0xc1aeac7a00 pc=0x1c0c6ee
github.com/dolthub/go-mysql-server/sql/expression.(*GreaterThanOrEqual).Eval(0xc1aeac7b18, 0x2193091, {0xc7d31cab40, 0xc7d31b5000, 0xc7d2d219f0})
        /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220316231244-f2f8808feb31/sql/expression/comparison.go:666 +0x25 fp=0xc1aeac7ac8 sp=0xc1aeac7a80 pc=0x1c10085
github.com/dolthub/go-mysql-server/sql.EvaluateCondition(0x0, {0x2ace230, 0xc00acdb5a0}, {0xc7d31cab40, 0x1d63112, 0x0})
        /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220316231244-f2f8808feb31/sql/core.go:970 +0x3c fp=0xc1aeac7b00 sp=0xc1aeac7ac8 pc=0x14ca2dc
github.com/dolthub/go-mysql-server/sql/plan.(*insertIter).evaluateChecks(0xc00ac2bba0, 0x23eb920, {0xc7d31cab40, 0x9, 0x9})
        /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220316231244-f2f8808feb31/sql/plan/insert.go:617 +0x91 fp=0xc1aeac7b78 sp=0xc1aeac7b00 pc=0x1d50c31
github.com/dolthub/go-mysql-server/sql/plan.(*insertIter).Next(0xc00ac2bba0, 0x5d)
        /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220316231244-f2f8808feb31/sql/plan/insert.go:340 +0x15e fp=0xc1aeac7d78 sp=0xc1aeac7b78 pc=0x1d4ef1e
github.com/dolthub/go-mysql-server/sql/plan.(*tableEditorIter).Next(0xc00ac33e00, 0xc000711040)
        /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220316231244-f2f8808feb31/sql/plan/table_editor.go:51 +0x78 fp=0xc1aeac7de0 sp=0xc1aeac7d78 pc=0x1d85538
github.com/dolthub/dolt/go/libraries/doltcore/mvdata.(*SqlEngineTableWriter).WriteRows(0xc00abee0e0, {0x23eb060, 0x38dde68}, 0xc00010a730, 0xc000284150)
        /src/libraries/doltcore/mvdata/engine_table_writer.go:222 +0x34c fp=0xc1aeac7f40 sp=0xc1aeac7de0 pc=0x2194fcc
github.com/dolthub/dolt/go/cmd/dolt/commands/tblcmds.move.func3()
        /src/cmd/dolt/commands/tblcmds/import.go:548 +0x2d fp=0xc1aeac7f78 sp=0xc1aeac7f40 pc=0x22da54d
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67 fp=0xc1aeac7fe0 sp=0xc1aeac7f78 pc=0x14c0ac7
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc1aeac7fe8 sp=0xc1aeac7fe0 pc=0xf6aea1
created by golang.org/x/sync/errgroup.(*Group).Go
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x92

goroutine 1 [semacquire, 22 minutes]:
sync.runtime_Semacquire(0xc000072000)
        /usr/local/go/src/runtime/sema.go:56 +0x25
sync.(*WaitGroup).Wait(0xc000965c68)
        /usr/local/go/src/sync/waitgroup.go:130 +0x71
golang.org/x/sync/errgroup.(*Group).Wait(0xc000284120)
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:40 +0x27
github.com/dolthub/dolt/go/cmd/dolt/commands/tblcmds.move({0x2aabe30, 0xc00038a9c0}, {0x2aab340, 0xc0005ede60}, 0xc00abee0e0, 0xc000550700)
        /src/cmd/dolt/commands/tblcmds/import.go:556 +0x31c
github.com/dolthub/dolt/go/cmd/dolt/commands/tblcmds.ImportCmd.Exec({}, {0x2aabe30, 0xc00038a9c0}, {0xc000816708, 0x11}, {0xc0000ba030, 0x3, 0x5}, 0x2aaadc8)
        /src/cmd/dolt/commands/tblcmds/import.go:393 +0x56b
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.handleCommand({{0x27362bc, 0x5}, {0x27a4533, 0x3f}, {0x0, 0x0}, {0xc00010a2d0, 0x5, 0x5}, 0x0}, ...)
        /src/cmd/dolt/cli/command.go:222 +0x282
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.Exec({{0x27362bc, 0x5}, {0x27a4533, 0x3f}, {0x0, 0x0}, {0xc00010a2d0, 0x5, 0x5}, 0x0}, ...)
        /src/cmd/dolt/cli/command.go:179 +0x47f
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.handleCommand({{0x27347a8, 0x4}, {0x274deef, 0x11}, {0x0, 0x0}, {0xc0001f6dc0, 0x2b, 0x2b}, 0x0}, ...)
        /src/cmd/dolt/cli/command.go:222 +0x282
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.Exec({{0x27347a8, 0x4}, {0x274deef, 0x11}, {0x0, 0x0}, {0xc0001f6dc0, 0x2b, 0x2b}, 0x0}, ...)
        /src/cmd/dolt/cli/command.go:179 +0x47f
main.runMain()
        /src/cmd/dolt/dolt.go:345 +0x6e5
main.main()
        /src/cmd/dolt/dolt.go:131 +0x19

goroutine 6 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x0)
        /go/pkg/mod/github.com/golang/glog@v0.0.0-20210429001901-424d2337a529/glog.go:882 +0x6a
created by github.com/golang/glog.init.0
        /go/pkg/mod/github.com/golang/glog@v0.0.0-20210429001901-424d2337a529/glog.go:410 +0x1c5

goroutine 50 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0006d6000)
        /go/pkg/mod/go.opencensus.io@v0.22.4/stats/view/worker.go:276 +0xb9
created by go.opencensus.io/stats/view.init.0
        /go/pkg/mod/go.opencensus.io@v0.22.4/stats/view/worker.go:34 +0x92

goroutine 10 [chan receive, 22 minutes]:
github.com/dolthub/dolt/go/libraries/events.NewCollector.func1()
        /src/libraries/events/collector.go:66 +0xbd
created by github.com/dolthub/dolt/go/libraries/events.NewCollector
        /src/libraries/events/collector.go:62 +0x136

goroutine 66 [chan receive, 22 minutes]:
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.(*asyncLookups).workerFunc.func1()
        /src/libraries/doltcore/sqle/index/async_indexed_lookups.go:89 +0x205
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.(*asyncLookups).workerFunc(0x0)
        /src/libraries/doltcore/sqle/index/async_indexed_lookups.go:102 +0x33
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.(*asyncLookups).start.func1()
        /src/libraries/doltcore/sqle/index/async_indexed_lookups.go:62 +0x1d
created by github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.(*asyncLookups).start
        /src/libraries/doltcore/sqle/index/async_indexed_lookups.go:61 +0x30

goroutine 67 [chan receive, 22 minutes]:
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.(*asyncLookups).workerFunc.func1()
        /src/libraries/doltcore/sqle/index/async_indexed_lookups.go:89 +0x205
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.(*asyncLookups).workerFunc(0x0)
        /src/libraries/doltcore/sqle/index/async_indexed_lookups.go:102 +0x33
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.(*asyncLookups).start.func1()
        /src/libraries/doltcore/sqle/index/async_indexed_lookups.go:62 +0x1d
created by github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.(*asyncLookups).start
        /src/libraries/doltcore/sqle/index/async_indexed_lookups.go:61 +0x30

goroutine 68 [chan receive, 22 minutes]:
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.(*asyncLookups).workerFunc.func1()
        /src/libraries/doltcore/sqle/index/async_indexed_lookups.go:89 +0x205
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.(*asyncLookups).workerFunc(0x0)
        /src/libraries/doltcore/sqle/index/async_indexed_lookups.go:102 +0x33
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.(*asyncLookups).start.func1()
        /src/libraries/doltcore/sqle/index/async_indexed_lookups.go:62 +0x1d
created by github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.(*asyncLookups).start
        /src/libraries/doltcore/sqle/index/async_indexed_lookups.go:61 +0x30

goroutine 69 [chan receive, 22 minutes]:
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.(*asyncLookups).workerFunc.func1()
        /src/libraries/doltcore/sqle/index/async_indexed_lookups.go:89 +0x205
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.(*asyncLookups).workerFunc(0x0)
        /src/libraries/doltcore/sqle/index/async_indexed_lookups.go:102 +0x33
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.(*asyncLookups).start.func1()
        /src/libraries/doltcore/sqle/index/async_indexed_lookups.go:62 +0x1d
created by github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.(*asyncLookups).start
        /src/libraries/doltcore/sqle/index/async_indexed_lookups.go:61 +0x30

goroutine 70 [chan receive, 22 minutes]:
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.(*asyncLookups).workerFunc.func1()
        /src/libraries/doltcore/sqle/index/async_indexed_lookups.go:89 +0x205
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.(*asyncLookups).workerFunc(0x0)
        /src/libraries/doltcore/sqle/index/async_indexed_lookups.go:102 +0x33
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.(*asyncLookups).start.func1()
        /src/libraries/doltcore/sqle/index/async_indexed_lookups.go:62 +0x1d
created by github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.(*asyncLookups).start
        /src/libraries/doltcore/sqle/index/async_indexed_lookups.go:61 +0x30

goroutine 71 [chan receive, 22 minutes]:
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.(*asyncLookups).workerFunc.func1()
        /src/libraries/doltcore/sqle/index/async_indexed_lookups.go:89 +0x205
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.(*asyncLookups).workerFunc(0x0)
        /src/libraries/doltcore/sqle/index/async_indexed_lookups.go:102 +0x33
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.(*asyncLookups).start.func1()
        /src/libraries/doltcore/sqle/index/async_indexed_lookups.go:62 +0x1d
created by github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.(*asyncLookups).start
        /src/libraries/doltcore/sqle/index/async_indexed_lookups.go:61 +0x30

goroutine 72 [chan receive, 22 minutes]:
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.(*asyncLookups).workerFunc.func1()
        /src/libraries/doltcore/sqle/index/async_indexed_lookups.go:89 +0x205
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.(*asyncLookups).workerFunc(0x0)
        /src/libraries/doltcore/sqle/index/async_indexed_lookups.go:102 +0x33
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.(*asyncLookups).start.func1()
        /src/libraries/doltcore/sqle/index/async_indexed_lookups.go:62 +0x1d
created by github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.(*asyncLookups).start
        /src/libraries/doltcore/sqle/index/async_indexed_lookups.go:61 +0x30

goroutine 73 [chan receive, 22 minutes]:
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.(*asyncLookups).workerFunc.func1()
        /src/libraries/doltcore/sqle/index/async_indexed_lookups.go:89 +0x205
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.(*asyncLookups).workerFunc(0x0)
        /src/libraries/doltcore/sqle/index/async_indexed_lookups.go1020x33620x1d610x30
goroutine 11 [chan receive22github.com/klauspost/compress/zstd.(*blockDec).startDecoder0xc00065f2b02150x941180x16712220xc00065f3802150x94
1180x16713220xc00065f4502150x941180x16714220xc00065f5202150x941180x167

goroutine 15 [22 minutes]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc00065f5f0)
        /go/pkg/mod/github.com/klauspost/compress@v1.10.10/zstd/blockdec.go2150x941180x16716 [22github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc00065f6c0)
        /go/pkg/mod/github.com/klauspost/compress@v1.10.10/zstd/blockdec.go:215 +0x94
created by github.com/klauspost/compress/zstd.newBlockDec
        /go/pkg/mod/github.com/klauspost/compress@v1.10.10/zstd/blockdec.go:118 +0x167

goroutine 82 [chan receive, 22 minutes]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc00065f790)
        /go/pkg/mod/github.com/klauspost/compress@v1.10.10/zstd/blockdec.go:215 +0x94
created by github.com/klauspost/compress/zstd.newBlockDec
        /go/pkg/mod/github.com/klauspost/compress@v1.10.10/zstd/blockdec.go:118 +0x167

goroutine 83 [chan receive, 22 minutes]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc00065f860)
        /go/pkg/mod/github.com/klauspost/compress@v1.10.10/zstd/blockdec.go:215 +0x94
created by github.com/klauspost/compress/zstd.newBlockDec
        /go/pkg/mod/github.com/klauspost/compress@v1.10.10/zstd/blockdec.go:118 +0x167

goroutine 54 [select, 22 minutes]:
os/signal.NotifyContext.func1()
        /usr/local/go/src/os/signal/signal.go:288 +0x76
created by os/signal.NotifyContext
        /usr/local/go/src/os/signal/signal.go:287 +0x169

goroutine 52 [syscall, 22 minutes]:
os/signal.signal_recv()
        /usr/local/go/src/runtime/sigqueue.go:169 +0x98
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:24 +0x19
created by os/signal.Notify.func1.1
        /usr/local/go/src/os/signal/signal.go:151 +0x2c

goroutine 53 [select, 22 minutes]:
os/signal.NotifyContext.func1()
        /usr/local/go/src/os/signal/signal.go:288 +0x76
created by os/signal.NotifyContext
        /usr/local/go/src/os/signal/signal.go:287 +0x169

goroutine 313 [select]:
github.com/dolthub/dolt/go/cmd/dolt/commands/tblcmds.moveRows({0x2aaadc8, 0xc00abf4640}, 0xc00abee0e0, {0x2aab340, 0xc0005ede60}, 0xc000550700, 0xc000569800, 0xc000284150)
        /src/cmd/dolt/commands/tblcmds/import.go:607 +0x46c
github.com/dolthub/dolt/go/cmd/dolt/commands/tblcmds.move.func2()
        /src/cmd/dolt/commands/tblcmds/import.go:543 +0x7a
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x92
```

**Comment by VinaiRachakonda** [comment]
Thanks for the bug. Would be great for you to pm your data

**Comment by CaptainStabs** [comment]
It's 2.15 Gb, can't really send that easily

**Comment by VinaiRachakonda** [comment]
I've been consistently running `dolt table import` with imports in the GB range against very large databases and I have not seen an error like this in the past 2 months.  I'm closing this issue for now, but if it shows again please feel free to re-open.
