### ISSUE TITLE
Dolt panic on attempt to push to branch without permission

### ISSUE THREAD

**Issue by CaptainStabs** [dolthub/dolt#3160]
```
>dolt push origin HPI --force
- Tree Level: 1, Percent Buffered: 99.91%, Files Created: 1, Files Uploaded: 0, Current Upload Speed: 0 B/s
error: push failed
cause: unknown push error; rpc error: code = PermissionDenied desc = permission denied
panic: send on closed channel

goroutine 345 [running]:
github.com/dolthub/dolt/go/store/datas/pull.(*Puller).addEvent(...)
        /src/store/datas/pull/puller.go:493
github.com/dolthub/dolt/go/store/datas/pull.(*Puller).uploadTempTableFile.func2.1({0xc0004edfb0?, 0xc0004edf90?, 0x3663240?})
        /src/store/datas/pull/puller.go:226 +0xe5
github.com/dolthub/dolt/go/libraries/utils/iohelp.(*ReaderWithStats).Start.func1()
        /src/libraries/utils/iohelp/read_with_stats.go:62 +0x4e
created by github.com/dolthub/dolt/go/libraries/utils/iohelp.(*ReaderWithStats).Start
        /src/libraries/utils/iohelp/read_with_stats.go:49 +0xa5
```

**Comment by fulghum** [comment]
Thanks for the report CaptainStabs. Looks like this case could be handled more gracefully with a better error message and without the panic. Not as high priority as some other behavioral bugs, but still a good one for us to track.

**Comment by timsehn** [comment]
I'm going to close this.
