### ISSUE TITLE
JSON output might be broken due to invalid escapes in the data

### ISSUE THREAD

**Issue by rl1987** [dolthub/dolt#3334]
How to reproduce:

```
$ dolt init
Successfully initialized dolt data repository.
$ dolt sql
# Welcome to the DoltSQL shell.
# Statements must be terminated with ';'.
# "exit" or "quit" (or Ctrl-D) to exit.
tmp> CREATE TABLE `t` (`col` TEXT);
tmp> INSERT INTO `t` (`col`) VALUES ("aaa\N111");
Query OK, 1 row affected
tmp> SELECT * FROM `t`;
+---------+
| col     |
+---------+
| aaaN111 |
+---------+
tmp> INSERT INTO `t` (`col`) VALUES ("aaa\\N111");
Query OK, 1 row affected
tmp> SELECT * FROM `t`;
+----------+
| col      |
+----------+
| aaa\N111 |
| aaaN111  |
+----------+
tmp> exit
Bye
$ dolt sql --query "SELECT * FROM t;"
+----------+
| col      |
+----------+
| aaa\N111 |
| aaaN111  |
+----------+
$ dolt sql --query "SELECT * FROM t;" --result-format json
{"rows": [{"col":"aaa\N111"},{"col":"aaaN111"}]}$ 
$ dolt sql --query "SELECT * FROM t;" --result-format json | python3 -m json.tool
Invalid \escape: line 1 column 22 (char 21)
$ 
```

**Comment by timsehn** [comment]
What do you expect there? The string is quoted so it should be valid JSON no?

**Comment by rl1987** [comment]
At the very least, this is interoperability problem. I would expect dolt to **always** output JSON strings that Python `json` module could parse successfully when `--result-format json` is used with SQL query.

Note that this also causes a crash in `doltcli` module that parses the JSON string:

```
$ python3
Python 3.9.10 (main, Jan 15 2022, 11:48:04) 
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import doltcli as dolt
>>> db = dolt.Dolt(".")
>>> db.sql("SELECT * FROM t;", result_format="json")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/doltcli/dolt.py", line 618, in sql
    return SQL_OUTPUT_PARSERS[result_format](fh)
  File "/usr/local/lib/python3.9/site-packages/doltcli/dolt.py", line 30, in <lambda>
    "json": lambda fh: json.load(fh),
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 1 column 22 (char 21)
```

So we have two bugs in one.

The `\N` thing came from real scraped data and was crashing my code that depended on dolt through the `doltcli` module. There two characters: `\` and `N`.

Furthermore, the JSON string from this example (``) fails [JSONLint](https://jsonlint.com/) validation with the following error:

```
Error: Parse error on line 3:
..."rows": [{		"col": "aaa\N111"	}, {		"
----------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'
```

Validation passes when slash character is properly escaped by prepending another backslash character:

```
{
	"rows": [{
		"col": "aaa\\N111"
	}, {
		"col": "aaaN111"
	}]
}
```

More formally, dolt seems to violate the following from [RFC8529](https://datatracker.ietf.org/doc/rfc8259/) Section 7:

```
   Alternatively, there are two-character sequence escape
   representations of some popular characters.  So, for example, a
   string containing only a single reverse solidus character may be
   represented more compactly as "\\".

<...>

      string = quotation-mark *char quotation-mark

      char = unescaped /
          escape (
              %x22 /          ; "    quotation mark  U+0022
              %x5C /          ; \    reverse solidus U+005C
              %x2F /          ; /    solidus         U+002F
              %x62 /          ; b    backspace       U+0008
              %x66 /          ; f    form feed       U+000C
              %x6E /          ; n    line feed       U+000A
              %x72 /          ; r    carriage return U+000D
              %x74 /          ; t    tab             U+0009
              %x75 4HEXDIG )  ; uXXXX                U+XXXX

      escape = %x5C              ; \

      quotation-mark = %x22      ; "

      unescaped = %x20-21 / %x23-5B / %x5D-10FFFF
```

**Comment by timsehn** [comment]
OK. We will go implement the spec. Thanks for the report.
