### ISSUE TITLE
Dolt log panics under concurrency

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#3420]
I was running a very simple test against dolt (ab -n 100 -c 5) that would run a query for the last 10 entries in dolt_log, and ran into this:

```
2022-05-16T09:24:40-04:00 ERROR [conn %!d(<nil>)] mysql_server caught panic:
runtime error: invalid memory address or nil pointer dereference
runtime/panic.go:220 (0x104cf35)
runtime/signal_unix.go:818 (0x104cf05)
github.com/dolthub/go-mysql-server@v0.11.1-0.20220504224111-9517b2597834/sql/plan/call.go:131 (0x1f6c745)
```

And then this:
```
2022-05-16T09:26:36-04:00 INFO [conn 12] NewConnection {DisableClientMultiStatements=false}
fatal error: concurrent map writes

goroutine 2461155 [running]:
runtime.throw({0x2a21050?, 0x287c840?})
    runtime/panic.go:992 +0x71 fp=0xc002aea490 sp=0xc002aea460 pc=0x1036a71
runtime.mapassign_faststr(0x2734660, 0xc003ed63f0, {0xc000572715, 0x4})
    runtime/map_faststr.go:295 +0x38b fp=0xc002aea4f8 sp=0xc002aea490 pc=0x1014bab
```

The test was run against a single node.js koa server, where the route simply does (against a local dolt server):

```
Call dolt_checkout('-b', 'main');
select * from dolt_log order by date desc limit 10;
```

**Comment by wvl** [comment]
Full stack trace:

```
2022-05-16T10:26:44-04:00 ERROR [conn %!d(<nil>)] mysql_server caught panic:
runtime error: invalid memory address or nil pointer dereference
runtime/panic.go:220 (0x104cf35)
runtime/signal_unix.go:818 (0x104cf05)
github.com/dolthub/go-mysql-server@v0.11.1-0.20220504224111-9517b2597834/sql/plan/call.go:131 (0x1f6c745)
github.com/dolthub/go-mysql-server@v0.11.1-0.20220504224111-9517b2597834/sql/plan/transaction_committing_iter.go:59 (0x1fe0791)
github.com/dolthub/go-mysql-server@v0.11.1-0.20220504224111-9517b2597834/sql/plan/process.go:66 (0x1fb6097)
github.com/dolthub/go-mysql-server@v0.11.1-0.20220504224111-9517b2597834/engine.go:200 (0x21f62b4)
github.com/dolthub/go-mysql-server@v0.11.1-0.20220504224111-9517b2597834/server/handler.go:343 (0x24c3a96)
github.com/dolthub/go-mysql-server@v0.11.1-0.20220504224111-9517b2597834/server/handler.go:607 (0x24c66a7)
github.com/dolthub/go-mysql-server@v0.11.1-0.20220504224111-9517b2597834/server/handler.go:169 (0x24c1b65)
github.com/dolthub/vitess@v0.0.0-20220504220708-70dd916eb224/go/mysql/conn.go:1288 (0x153362f)
github.com/dolthub/vitess@v0.0.0-20220504220708-70dd916eb224/go/mysql/conn.go:930 (0x1530018)
github.com/dolthub/vitess@v0.0.0-20220504220708-70dd916eb224/go/mysql/server.go:479 (0x154940a)
runtime/asm_amd64.s:1571 (0x106a100)
 {}
 ```

**Comment by zachmu** [comment]
Fixed in latest release. Please reopen if you encounter again.
