### ISSUE TITLE
Server error while inserting records and querying dolt_log in parallel

### ISSUE THREAD

**Issue by wvl** [dolthub/dolt#3435]
I was running a scenario to test/verify dolt, and ran into this issue.

Setup: Local dolt server with simple node.js koa app server in front

The scenario:
Process 1 is running a series of inserts into one branch
Process 2 is running an `ab -n 100 -c 10` process that queries the `dolt_branches` table from a different branch head

This is the start of the errors that gets spit out of the server:

```
fatal error: concurrent map iteration and map write

goroutine 38887781 [running]:
runtime.throw({0x2a4af4a?, 0xc001416340?})
	runtime/panic.go:992 +0x71 fp=0xc000832358 sp=0xc000832328 pc=0x1036a71
runtime.mapiternext(0x2?)
	runtime/map.go:871 +0x4eb fp=0xc0008323c8 sp=0xc000832358 pc=0x101160b
runtime.mapiterinit(0x2734660?, 0x0?, 0xc000b32685?)
	runtime/map.go:861 +0x228 fp=0xc0008323e8 sp=0xc0008323c8 pc=0x10110c8
github.com/dolthub/go-mysql-server/sql/analyzer.(*ProcedureCache).AllForDatabase(0xc002f66e70, {0xc000b32685?, 0xc000193600?})
	github.com/dolthub/go-mysql-server@v0.11.1-0.20220504224111-9517b2597834/sql/analyzer/procedure_cache.go:76 +0xaa fp=0xc000832548 sp=0xc0008323e8 pc=0x21ac02a
github.com/dolthub/go-mysql-server/sql/analyzer.assignRoutines.func1({0x2db73b0, 0xc008d9dd70})
	github.com/dolthub/go-mysql-server@v0.11.1-0.20220504224111-9517b2597834/sql/analyzer/assign_routines.go:50 +0x285 fp=0xc000832608 sp=0xc000832548 pc=0x2184825
github.com/dolthub/go-mysql-server/sql/transform.Node({0x2db73b0, 0xc008d9dd70}, 0xc000832768)
	github.com/dolthub/go-mysql-server@v0.11.1-0.20220504224111-9517b2597834/sql/transform/node.go:304 +0x91 fp=0xc000832680 sp=0xc000832608 pc=0x1ea8671
github.com/dolthub/go-mysql-server/sql/transform.Node({0x2db7130, 0xc008d9de60}, 0xc000832768)
	github.com/dolthub/go-mysql-server@v0.11.1-0.20220504224111-9517b2597834/sql/transform/node.go:314 +0x115 fp=0xc0008326f8 sp=0xc000832680 pc=0x1ea86f5
github.com/dolthub/go-mysql-server/sql/analyzer.assignRoutines(0xc0061143c0, 0xc0000ba960, {0x2db7130, 0xc008d9de60}, 0x0?, 0x2abd6c0?)
	github.com/dolthub/go-mysql-server@v0.11.1-0.20220504224111-9517b2597834/sql/analyzer/assign_routines.go:37 +0x113 fp=0xc000832798 sp=0xc0008326f8 pc=0x21844d3
github.com/dolthub/go-mysql-server/sql/analyzer.(*Batch).evalOnce(0x2db7130?, 0xc006851dd0?, 0xc0000ba960, {0x2db7130?, 0xc006851dd0?}, 0x2da49b8?, 0x2abd6c0)
	github.com/dolthub/go-mysql-server@v0.11.1-0.20220504224111-9517b2597834/sql/analyzer/batch.go:120 +0x238 fp=0xc000832878 sp=0xc000832798 pc=0x2186178
github.com/dolthub/go-mysql-server/sql/analyzer.(*Batch).EvalWithSelector(0xc0004af4d0, 0x2a49879?, 0xc0000ba960, {0x2db7130, 0xc006851dd0}, 0x1?, 0xc0068504b0?)
	github.com/dolthub/go-mysql-server@v0.11.1-0.20220504224111-9517b2597834/sql/analyzer/batch.go:66 +0x15f fp=0xc000832938 sp=0xc000832878 pc=0x2185b7f
github.com/dolthub/go-mysql-server/sql/analyzer.(*Batch).Eval(...)
	github.com/dolthub/go-mysql-server@v0.11.1-0.20220504224111-9517b2597834/sql/analyzer/batch.go:56
github.com/dolthub/go-mysql-server/sql/analyzer.(*Analyzer).analyzeWithSelector(0xc0000ba960?, 0x2db7130?, {0x2db7130?, 0xc006850390?}, 0xc00063e3c0?, 0x2abd6c8?, 0x0?)
	github.com/dolthub/go-mysql-server@v0.11.1-0.20220504224111-9517b2597834/sql/analyzer/analyzer.go:524 +0x347 fp=0xc000832aa0 sp=0xc000832938 pc=0x21790e7
github.com/dolthub/go-mysql-server/sql/analyzer.(*Analyzer).Analyze(...)
	github.com/dolthub/go-mysql-server@v0.11.1-0.20220504224111-9517b2597834/sql/analyzer/analyzer.go:374
github.com/dolthub/go-mysql-server.(*Engine).analyzeQuery(0xc0000baa00, 0x2dc7dc8?, {0xc00081c2d0?, 0x2da49b8?}, {0x2db7130?, 0xc006850390?}, 0x0)
	github.com/dolthub/go-mysql-server@v0.11.1-0.20220504224111-9517b2597834/engine.go:280 +0xb5 fp=0xc000832b00 sp=0xc000832aa0 pc=0x21f6bd5
github.com/dolthub/go-mysql-server.(*Engine).QueryNodeWithBindings(0xc000b26320?, 0xc006114320, {0xc00081c2d0, 0x21}, {0x2db7130, 0xc006850390}, 0x1?)
	github.com/dolthub/go-mysql-server@v0.11.1-0.20220504224111-9517b2597834/engine.go:180 +0x10c fp=0xc000832bc0 sp=0xc000832b00 pc=0x21f61cc
github.com/dolthub/go-mysql-server/server.(*Handler).doQuery(0xc000625780, 0xc002942780, {0xc00081c2d0, 0x21}, 0x0, 0x0, 0xc006850000)
	github.com/dolthub/go-mysql-server@v0.11.1-0.20220504224111-9517b2597834/server/handler.go:343 +0x657 fp=0xc000833428 sp=0xc000832bc0 pc=0x24c3a97
github.com/dolthub/go-mysql-server/server.(*Handler).errorWrappedDoQuery(0xc000625780, 0x40?, {0xc00081c2d0, 0x21}, 0x30?, 0x28d0ea0?, 0x1074501?)
	github.com/dolthub/go-mysql-server@v0.11.1-0.20220504224111-9517b2597834/server/handler.go:607 +0xc8 fp=0xc0008334c8 sp=0xc000833428 pc=0x24c66a8
github.com/dolthub/go-mysql-server/server.(*Handler).ComQuery(0x100c004692daf?, 0xc000833540?, {0xc00081c2d0?, 0x5442fe8?}, 0x2617cc0?)
	github.com/dolthub/go-mysql-server@v0.11.1-0.20220504224111-9517b2597834/server/handler.go:169 +0x26 fp=0xc000833510 sp=0xc0008334c8 pc=0x24c1b66
github.com/dolthub/vitess/go/mysql.(*Conn).execQuery(0xc002942780, {0xc00081c2d0, 0x21}, {0x2dba990?, 0xc000625780}, 0x0)
	github.com/dolthub/vitess@v0.0.0-20220504220708-70dd916eb224/go/mysql/conn.go:1288 +0x170 fp=0xc0008335a0 sp=0xc000833510 pc=0x1533630
github.com/dolthub/vitess/go/mysql.(*Conn).handleNextCommand(0xc002942780, {0x2dba990, 0xc000625780})
	github.com/dolthub/vitess@v0.0.0-20220504220708-70dd916eb224/go/mysql/conn.go:930 +0x179 fp=0xc000833a58 sp=0xc0008335a0 pc=0x1530019
github.com/dolthub/vitess/go/mysql.(*Listener).handle(0xc0007aad80, {0x2db9aa8?, 0xc0046fac98?}, 0x2b, {0xc0990c6cc9f76c10?, 0x4cfacc3574?, 0x4152ce0?})
	github.com/dolthub/vitess@v0.0.0-20220504220708-70dd916eb224/go/mysql/server.go:479 +0x192b fp=0xc000833f98 sp=0xc000833a58 pc=0x154940b
github.com/dolthub/vitess/go/mysql.(*Listener).Accept.func1()
	github.com/dolthub/vitess@v0.0.0-20220504220708-70dd916eb224/go/mysql/server.go:273 +0x3d fp=0xc000833fe0 sp=0xc000833f98 pc=0x1547abd
runtime.goexit()
	runtime/asm_amd64.s:1571 +0x1 fp=0xc000833fe8 sp=0xc000833fe0 pc=0x106a101
created by github.com/dolthub/vitess/go/mysql.(*Listener).Accept
	github.com/dolthub/vitess@v0.0.0-20220504220708-70dd916eb224/go/mysql/server.go:273 +0x25

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0xd446740, 0x72)
	runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc0005a2f00?, 0x4?, 0x0)
	internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Accept(0xc0005a2f00)
	internal/poll/fd_unix.go:614 +0x22c
net.(*netFD).accept(0xc0005a2f00)
	net/fd_unix.go:172 +0x35
net.(*TCPListener).accept(0xc00049aaf8)
	net/tcpsock_posix.go:139 +0x28
net.(*TCPListener).Accept(0xc00049aaf8)
	net/tcpsock.go:288 +0x3d
github.com/dolthub/go-mysql-server/server.(*Listener).Accept(0x254a8e7?)
	github.com/dolthub/go-mysql-server@v0.11.1-0.20220504224111-9517b2597834/server/listener.go:36 +0x22
github.com/dolthub/vitess/go/mysql.(*Listener).Accept(0xc0007aad80)
	github.com/dolthub/vitess@v0.0.0-20220504220708-70dd916eb224/go/mysql/server.go:255 +0x3b
github.com/dolthub/go-mysql-server/server.(*Server).Start(...)
	github.com/dolthub/go-mysql-server@v0.11.1-0.20220504224111-9517b2597834/server/server.go:102
github.com/dolthub/dolt/go/cmd/dolt/commands/sqlserver.Serve({0x2da49b8, 0xc000624040}, {0x29fe0c1, 0x6}, {0x2dc3df8?, 0xc000b2c000?}, 0x1?, 0xc00022ea50)
	github.com/dolthub/dolt/go/cmd/dolt/commands/sqlserver/server.go:233 +0x1469
github.com/dolthub/dolt/go/cmd/dolt/commands/sqlserver.startServer({0x2da49b8, 0xc000624040}, {0x29fe0c1, 0x6}, {0xc00048cf60, 0xf}, {0xc000136010, 0x0, 0x0}, 0xc00022ea50, ...)
	github.com/dolthub/dolt/go/cmd/dolt/commands/sqlserver/sqlserver.go:199 +0x42a
github.com/dolthub/dolt/go/cmd/dolt/commands/sqlserver.SqlServerCmd.Exec({{0x29fe0c1?, 0xc000067200?}}, {0x2da5c18?, 0xc00053fc00}, {0xc00048cf60, 0xf}, {0xc000136010, 0x0, 0x0}, 0xc00022ea50)
	github.com/dolthub/dolt/go/cmd/dolt/commands/sqlserver/sqlserver.go:173 +0x285
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.handleCommand({{0x29fbe38, 0x4}, {0x2a17c7a, 0x11}, {0x0, 0x0}, {0xc000b8c2c0, 0x2b, 0x2b}, 0x0}, ...)
	github.com/dolthub/dolt/go/cmd/dolt/cli/command.go:222 +0x29e
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.Exec({{0x29fbe38, 0x4}, {0x2a17c7a, 0x11}, {0x0, 0x0}, {0xc000b8c2c0, 0x2b, 0x2b}, 0x0}, ...)
	github.com/dolthub/dolt/go/cmd/dolt/cli/command.go:179 +0x47f
main.runMain()
	github.com/dolthub/dolt/go/cmd/dolt/dolt.go:345 +0x6a5
main.main()
	github.com/dolthub/dolt/go/cmd/dolt/dolt.go:131 +0x19

goroutine 19 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x0?)
	github.com/golang/glog@v0.0.0-20210429001901-424d2337a529/glog.go:882 +0x6a
created by github.com/golang/glog.init.0
	github.com/golang/glog@v0.0.0-20210429001901-424d2337a529/glog.go:410 +0x1bf

goroutine 10 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc000190000)
	go.opencensus.io@v0.22.4/stats/view/worker.go:276 +0xad
created by go.opencensus.io/stats/view.init.0
	go.opencensus.io@v0.22.4/stats/view/worker.go:34 +0x8d

goroutine 11 [chan receive, 5 minutes]:
github.com/dolthub/dolt/go/libraries/events.NewCollector.func1()
	github.com/dolthub/dolt/go/libraries/events/collector.go:66 +0xbd
created by github.com/dolthub/dolt/go/libraries/events.NewCollector
	github.com/dolthub/dolt/go/libraries/events/collector.go:62 +0x131

goroutine 12 [chan receive, 5 minutes]:
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.(*asyncLookups).workerFunc.func1()
	github.com/dolthub/dolt/go/libraries/doltcore/sqle/index/async_indexed_lookups.go:89 +0x1ec
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.(*asyncLookups).workerFunc(0x0?)
	github.com/dolthub/dolt/go/libraries/doltcore/sqle/index/async_indexed_lookups.go:102 +0x33
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.(*asyncLookups).start.func1()
	github.com/dolthub/dolt/go/libraries/doltcore/sqle/index/async_indexed_lookups.go:62 +0x1d
created by github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.(*asyncLookups).start
	github.com/dolthub/dolt/go/libraries/doltcore/sqle/index/async_indexed_lookups.go:61 +0x2b

goroutine 13 [chan receive, 5 minutes]:
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.(*asyncLookups).workerFunc.func1()
	github.com/dolthub/dolt/go/libraries/doltcore/sqle/index/async_indexed_lookups.go:89 +0x1ec
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.(*asyncLookups).workerFunc(0x0?)
	github.com/dolthub/dolt/go/libraries/doltcore/sqle/index/async_indexed_lookups.go:102 +0x33
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.(*asyncLookups).start.func1()
	github.com/dolthub/dolt/go/libraries/doltcore/sqle/index/async_indexed_lookups.go:62 +0x1d
created by github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.(*asyncLookups).start
	github.com/dolthub/dolt/go/libraries/doltcore/sqle/index/async_indexed_lookups.go:61 +0x2b

goroutine 14 [chan receive, 5 minutes]:
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.(*asyncLookups).workerFunc.func1()
	github.com/dolthub/dolt/go/libraries/doltcore/sqle/index/async_indexed_lookups.go:89 +0x1ec
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.(*asyncLookups).workerFunc(0x0?)
	github.com/dolthub/dolt/go/libraries/doltcore/sqle/index/async_indexed_lookups.go:102 +0x33
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.(*asyncLookups).start.func1()
	github.com/dolthub/dolt/go/libraries/doltcore/sqle/index/async_indexed_lookups.go:62 +0x1d
created by github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.(*asyncLookups).start
	github.com/dolthub/dolt/go/libraries/doltcore/sqle/index/async_indexed_lookups.go:61 +0x2b	```

**Comment by zachmu** [comment]
Probably has the same root cause as https://github.com/dolthub/dolt/issues/3420

The stored procedure analysis code isn't thread safe, and we're working on a fix now.

**Comment by zachmu** [comment]
This is fixed in source, will be in the release going out shortly.

**Comment by zachmu** [comment]
Fixed in the latest release. Please reopen if you encounter it again.
