### ISSUE TITLE
Panic with describe

### ISSUE THREAD

**Issue by VinaiRachakonda** [dolthub/dolt#3481]
Attaching the schema. Below is the error message after running `describe blocks`

```
bitcoin> describe blocks;
panic: unresolved column is a placeholder node, but Eval was called

goroutine 1 [running]:
github.com/dolthub/go-mysql-server/sql/expression.(*UnresolvedColumn).Eval(0xc000baa5a0, 0x100ef27?, {0x0?, 0x28c6ea0?, 0xc000152201?})
	/Users/vinairachakonda/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220519235058-86955e343071/sql/expression/unresolved.go:91 +0x27
github.com/dolthub/go-mysql-server/sql.(*ColumnDefaultValue).CheckType(0xc0000c9440, 0xc000152260?)
	/Users/vinairachakonda/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220519235058-86955e343071/sql/columndefault.go:178 +0x4c
github.com/dolthub/go-mysql-server/sql/analyzer.resolveColumnDefaultsOnWrapper(0x2de2de0?, 0xc0002159d0, 0xc000403160)
	/Users/vinairachakonda/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220519235058-86955e343071/sql/analyzer/resolve_column_defaults.go:714 +0x7d5
github.com/dolthub/go-mysql-server/sql/analyzer.resolveColumnDefaults.func1.1({0x2ddded0?, 0xc000403160?})
	/Users/vinairachakonda/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220519235058-86955e343071/sql/analyzer/resolve_column_defaults.go:473 +0x92
github.com/dolthub/go-mysql-server/sql/transform.NodeExprs.func1({0x2de2de0?, 0xc00065c870?}, {0x2ddded0?, 0xc000403160?})
	/Users/vinairachakonda/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220519235058-86955e343071/sql/transform/node.go:87 +0x2d
github.com/dolthub/go-mysql-server/sql/transform.ExprWithNode({0x2de2de0, 0xc00065c870}, {0x2ddded0?, 0xc000403160}, 0xc000baa8e8)
	/Users/vinairachakonda/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220519235058-86955e343071/sql/transform/expr.go:130 +0x219
github.com/dolthub/go-mysql-server/sql/transform.OneNodeExprsWithNode({0x2de2de0, 0xc00065c870}, 0xc0001359b0?)
	/Users/vinairachakonda/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220519235058-86955e343071/sql/transform/node.go:111 +0x131
github.com/dolthub/go-mysql-server/sql/transform.NodeExprsWithNode.func1({0x2de2de0?, 0xc00065c870?})
	/Users/vinairachakonda/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220519235058-86955e343071/sql/transform/node.go:79 +0x27
github.com/dolthub/go-mysql-server/sql/transform.Node({0x2de2de0, 0xc00065c870}, 0xc000baa8b0)
	/Users/vinairachakonda/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220519235058-86955e343071/sql/transform/node.go:337 +0x212
github.com/dolthub/go-mysql-server/sql/transform.NodeExprsWithNode({0x2de2de0?, 0xc00065c870?}, 0x203000?)
	/Users/vinairachakonda/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220519235058-86955e343071/sql/transform/node.go:78 +0x3f
github.com/dolthub/go-mysql-server/sql/transform.NodeExprs({0x2de2de0?, 0xc00065c870?}, 0x0?)
	/Users/vinairachakonda/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220519235058-86955e343071/sql/transform/node.go:86 +0x3f
github.com/dolthub/go-mysql-server/sql/analyzer.resolveColumnDefaults.func1({0x2de2de0, 0xc00065c870})
	/Users/vinairachakonda/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220519235058-86955e343071/sql/analyzer/resolve_column_defaults.go:459 +0x2f3
github.com/dolthub/go-mysql-server/sql/transform.Node({0x2de2de0, 0xc00065c870}, 0xc000baaad0)
	/Users/vinairachakonda/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220519235058-86955e343071/sql/transform/node.go:337 +0x212
github.com/dolthub/go-mysql-server/sql/analyzer.resolveColumnDefaults(0xc0002f8be0, 0x2a3d5b7?, {0x2de2de0, 0xc00065c870}, 0xc00065c870?, 0x0?)
	/Users/vinairachakonda/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220519235058-86955e343071/sql/analyzer/resolve_column_defaults.go:448 +0xed
github.com/dolthub/go-mysql-server/sql/analyzer.(*Batch).evalOnce(0x2de2de0?, 0xc000634000?, 0xc000b92af0, {0x2de2de0?, 0xc000635900?}, 0x2dd10d8?, 0x2ae2698)
	/Users/vinairachakonda/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220519235058-86955e343071/sql/analyzer/batch.go:120 +0x23d
github.com/dolthub/go-mysql-server/sql/analyzer.(*Batch).EvalWithSelector(0xc0000e7f50, 0x2a6deeb?, 0xc000b92af0, {0x2de2de0, 0xc000635900}, 0x1?, 0xc00019897c?)
	/Users/vinairachakonda/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220519235058-86955e343071/sql/analyzer/batch.go:66 +0x16d
github.com/dolthub/go-mysql-server/sql/analyzer.(*Batch).Eval(...)
	/Users/vinairachakonda/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220519235058-86955e343071/sql/analyzer/batch.go:56
github.com/dolthub/go-mysql-server/sql/analyzer.(*Analyzer).analyzeWithSelector(0xc000b92af0?, 0x2de2de0?, {0x2de2de0?, 0xc000634000?}, 0xc00019b8f8?, 0x2ae26a0?, 0x0?)
	/Users/vinairachakonda/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220519235058-86955e343071/sql/analyzer/analyzer.go:521 +0x351
github.com/dolthub/go-mysql-server/sql/analyzer.(*Analyzer).Analyze(...)
	/Users/vinairachakonda/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220519235058-86955e343071/sql/analyzer/analyzer.go:371
github.com/dolthub/go-mysql-server.(*Engine).analyzeQuery(0xc000b92b90, 0x2df35a0?, {0xc0005f0090?, 0xc000634000?}, {0x2de2de0?, 0xc000634000?}, 0x0)
	/Users/vinairachakonda/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220519235058-86955e343071/engine.go:324 +0xb5
github.com/dolthub/go-mysql-server.(*Engine).QueryNodeWithBindings(0x149a245?, 0xc0002f80a0, {0xc0005f0090, 0xf}, {0x0?, 0x0?}, 0xc0006260b0?)
	/Users/vinairachakonda/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220519235058-86955e343071/engine.go:193 +0x16f
github.com/dolthub/go-mysql-server.(*Engine).QueryWithBindings(...)
	/Users/vinairachakonda/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220519235058-86955e343071/engine.go:160
github.com/dolthub/go-mysql-server.(*Engine).Query(0xc0005f0090?, 0xf?, {0xc0005f0090?, 0xc000baafe0?})
	/Users/vinairachakonda/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220519235058-86955e343071/engine.go:155 +0x26
github.com/dolthub/dolt/go/cmd/dolt/commands/engine.(*SqlEngine).Query(...)
	/Users/vinairachakonda/go/src/dolthub/dolt/go/cmd/dolt/commands/engine/sqlengine.go:182
github.com/dolthub/dolt/go/cmd/dolt/commands.processQuery(0x2dd10d8?, {0xc0005f0090, 0xf}, 0xc0000d7d70)
	/Users/vinairachakonda/go/src/dolthub/dolt/go/cmd/dolt/commands/sql.go:1028 +0x4f3
github.com/dolthub/dolt/go/cmd/dolt/commands.runShell.func3.1({0x2dcff20, 0xc00041e510}, 0xc0000d7d70, 0xc0001703b0, 0xc0006bb530, 0xc0001ee280, {0xc0005f0090, 0xf}, 0xc000bab230, 0xc000bab1f0, ...)
	/Users/vinairachakonda/go/src/dolthub/dolt/go/cmd/dolt/commands/sql.go:834 +0x256
github.com/dolthub/dolt/go/cmd/dolt/commands.runShell.func3(0xc0001ee280?)
	/Users/vinairachakonda/go/src/dolthub/dolt/go/cmd/dolt/commands/sql.go:846 +0x48c
github.com/dolthub/ishell.handleUninterpretedInput(0xc0001ee280, {0xc0005f0090, 0x10})
	/Users/vinairachakonda/go/pkg/mod/github.com/dolthub/ishell@v0.0.0-20220112232610-14e753f0f371/ishell.go:288 +0x144
github.com/dolthub/ishell.(*Shell).run(0xc0001ee280)
	/Users/vinairachakonda/go/pkg/mod/github.com/dolthub/ishell@v0.0.0-20220112232610-14e753f0f371/ishell.go:245 +0x306
github.com/dolthub/ishell.(*Shell).Run(0xc0001ee280?)
	/Users/vinairachakonda/go/pkg/mod/github.com/dolthub/ishell@v0.0.0-20220112232610-14e753f0f371/ishell.go:139 +0x28
github.com/dolthub/dolt/go/cmd/dolt/commands.runShell({0x2dcff20?, 0xc00041e510}, 0xc0000d7d70, 0x2dcff20?)
	/Users/vinairachakonda/go/src/dolthub/dolt/go/cmd/dolt/commands/sql.go:856 +0x765
github.com/dolthub/dolt/go/cmd/dolt/commands.execShell({0x2dcff20, 0xc00041e510}, 0x2a20319?, 0x4?, {0xc00019897c?, 0x4a8?})
	/Users/vinairachakonda/go/src/dolthub/dolt/go/cmd/dolt/commands/sql.go:386 +0xd2
github.com/dolthub/dolt/go/cmd/dolt/commands.SqlCmd.Exec({{0x2a22537?, 0xc000bab8c8?}}, {0x2dcff20, 0xc00041e510}, {0xc00019a778, 0x8}, {0xc0001ac010, 0x0, 0x0}, 0xc000b860b0)
	/Users/vinairachakonda/go/src/dolthub/dolt/go/cmd/dolt/commands/sql.go:236 +0x6c7
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.handleCommand({{0x2a20299, 0x4}, {0x2a3c199, 0x11}, {0x0, 0x0}, {0xc00028edc0, 0x2c, 0x2c}, 0x0}, ...)
	/Users/vinairachakonda/go/src/dolthub/dolt/go/cmd/dolt/cli/command.go:238 +0x502
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.Exec({{0x2a20299, 0x4}, {0x2a3c199, 0x11}, {0x0, 0x0}, {0xc00028edc0, 0x2c, 0x2c}, 0x0}, ...)
	/Users/vinairachakonda/go/src/dolthub/dolt/go/cmd/dolt/cli/command.go:187 +0x47f
main.runMain()
	/Users/vinairachakond
[blocks.txt](https://github.com/dolthub/dolt/files/8766693/blocks.txt)
a/go/src/dolthub/dolt/go/cmd/dolt/dolt.go:345 +0x6a5
main.main()
	/Users/vinairachakonda/go/src/dolthub/dolt/go/cmd/dolt/dolt.go:131 +0x19
```
[blocks.txt](https://github.com/dolthub/dolt/files/8766694/blocks.txt)

**Comment by jennifersp** [comment]
This issue does not panic anymore in the current version of Dolt (0.40.12), but hex default value defined for binary type is handled as blob type when converting it to literal expr. Easier repro:
```
> create table blocks(number bigint PRIMARY KEY, merkle_root BINARY(32) default X'0000000000000000000000000000000000000000000000000000000000000000');
> describe blocks;
Invalid default value for 'merkel_root'
```
OR
```
> create table t (id int primary key, b binary(2) default 0x00);
> describe t;
Invalid default value for 'b'
```
