### ISSUE TITLE
Panic trying to insert longblob in new format

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#3494]
```
test-blob $ dolt sql -q "create table foo (pk int, myblob longblob, primary key(pk))";                                 
test-blob $ dolt sql -q "INSERT INTO foo values (0, LOAD_FILE('/Users/timsehn/Desktop/Screenshots/p2p-dbs.png'))"
panic: runtime error: index out of range [99490] with length 33955

goroutine 1 [running]:
github.com/dolthub/dolt/go/store/val.writeByteString(...)
	/Users/timsehn/liquidata/git/dolt/go/store/val/codec.go:470
github.com/dolthub/dolt/go/store/val.(*TupleBuilder).PutByteString(0xc0008b4000?, 0x184a2?, {0xc000a80000?, 0x184a2?, 0x0?})
	/Users/timsehn/liquidata/git/dolt/go/store/val/tuple_builder.go:213 +0x1cc
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.PutField(0xc0008b4000, 0x0, {0x26a8940?, 0xc000c1bdf0?})
	/Users/timsehn/liquidata/git/dolt/go/libraries/doltcore/sqle/index/prolly_fields.go:145 +0x11a7
github.com/dolthub/dolt/go/libraries/doltcore/sqle/writer.prollyIndexWriter.Insert({{0x0, 0x0}, {{0xc0005ebad0, {{...}, {...}, {...}}}, {{0xc0008946d0, _, _}, {_, ...}, ...}, ...}, ...}, ...)
	/Users/timsehn/liquidata/git/dolt/go/libraries/doltcore/sqle/writer/prolly_index_writer.go:126 +0x334
github.com/dolthub/dolt/go/libraries/doltcore/sqle/writer.(*prollyTableWriter).Insert(0xc00041e500, 0x2684a20?, {0xc000721d00, 0x2, 0x2})
	/Users/timsehn/liquidata/git/dolt/go/libraries/doltcore/sqle/writer/prolly_table_writer.go:126 +0x5e
github.com/dolthub/go-mysql-server/sql/plan.(*insertIter).Next(0xc000361e10, 0x29bc000?)
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220524215156-3b5eff887f13/sql/plan/insert.go:401 +0x598
github.com/dolthub/go-mysql-server/sql/plan.(*tableEditorIter).Next(0xc00014ef40, 0xc0000e3720)
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220524215156-3b5eff887f13/sql/plan/table_editor.go:51 +0x78
github.com/dolthub/go-mysql-server/sql/plan.(*accumulatorIter).Next(0xc0005ebb60, 0xc0000e3720)
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220524215156-3b5eff887f13/sql/plan/row_update_accumulator.go:314 +0x1f9
github.com/dolthub/go-mysql-server/sql/plan.transactionCommittingIter.Next(...)
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220524215156-3b5eff887f13/sql/plan/transaction_committing_iter.go:106
github.com/dolthub/go-mysql-server/sql/plan.(*trackedRowIter).Next(0xc000392be0, 0x0?)
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.11.1-0.20220524215156-3b5eff887f13/sql/plan/process.go:381 +0x2e
github.com/dolthub/dolt/go/cmd/dolt/commands/engine.printOKResult(0x41497c8?, {0x2dd36c8?, 0xc000392be0?})
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/commands/engine/sql_print.go:87 +0x42
github.com/dolthub/dolt/go/cmd/dolt/commands/engine.PrettyPrintResults(0xc0000e3720, 0x0, {0x41497c8, 0x1, 0x1}, {0x2dd36c8, 0xc000392be0}, 0x10?)
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/commands/engine/sql_print.go:61 +0x2c8
github.com/dolthub/dolt/go/cmd/dolt/commands.runMultiStatementMode(0x2de0660?, 0xc000734f90, {0x2dce600?, 0xc0007204c0}, 0x0)
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/commands/sql.go:665 +0x4c5
github.com/dolthub/dolt/go/cmd/dolt/commands.execMultiStatements({0x2de0660, 0xc00041acc0}, 0x3c?, 0x8?, {0x2dce600, 0xc0007204c0}, 0xb0?, {0xc0003216d0?, 0x207a73d?})
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/commands/sql.go:447 +0x14a
github.com/dolthub/dolt/go/cmd/dolt/commands.queryMode({0x2de0660, 0xc00041acc0}, 0x2a303ac?, 0x4a8?, 0xc00065cd80, {0x7ff7bfeffa2c, 0x57}, {0xc0003216d0, 0x9}, 0x0, ...)
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/commands/sql.go:344 +0x25f
github.com/dolthub/dolt/go/cmd/dolt/commands.SqlCmd.Exec({{0x2a303ac?, 0xc000b8f8c8?}}, {0x2de0660, 0xc00041acc0}, {0xc0003202d8, 0x8}, {0xc00004e060, 0x2, 0x2}, 0xc000236c60)
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/commands/sql.go:205 +0x90b
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.handleCommand({{0x2a2e109, 0x4}, {0x2a4a0bd, 0x11}, {0x0, 0x0}, {0xc000c11340, 0x2c, 0x2c}, 0x0}, ...)
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/cli/command.go:238 +0x502
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.Exec({{0x2a2e109, 0x4}, {0x2a4a0bd, 0x11}, {0x0, 0x0}, {0xc000c11340, 0x2c, 0x2c}, 0x0}, ...)
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/cli/command.go:187 +0x47f
main.runMain()
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/dolt.go:345 +0x6a5
main.main()
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/dolt.go:131 +0x19
```

Image here:

<img width="550" alt="p2p-dbs" src="https://user-images.githubusercontent.com/5376236/170583143-b97bbf69-a7de-4af1-9749-aefd24e0f859.png">

**Comment by timsehn** [comment]
Don't use the image i put in the issue. GitHub shrank it.

Make a screenshot and that will be bigger that 32KB.

**Comment by timsehn** [comment]
It looks like I accidentally made this in the new format.

**Comment by timsehn** [comment]
@max-hoffman did you not fix this one?

**Comment by max-hoffman** [comment]
I temporarily prevented panics in the new format. Currently adding enginetests for blobs.

**Comment by timsehn** [comment]
Error is fine. I'll resolve.
