### ISSUE TITLE
Corrupted Database from inserts on dolt_branch table

### ISSUE THREAD

**Issue by VinaiRachakonda** [dolthub/dolt#3511]
Leaving this here along with saved repo.

```
PS C:\Users\Owner> dolt sql-server
Starting server with Config HP="localhost:3306"|U="root"|P=""|T="28800000"|R="false"|L="info"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x18ebc69]

goroutine 1 [running]:
github.com/dolthub/dolt/go/libraries/doltcore/env.(*RepoState).CWBHeadRef(...)
        /src/libraries/doltcore/env/repo_state.go:206
github.com/dolthub/dolt/go/libraries/doltcore/env.(*repoStateReader).CWBHeadRef(0x2826d6d8563?)
        /src/libraries/doltcore/env/environment.go:621 +0x9
github.com/dolthub/dolt/go/libraries/doltcore/sqle.GetInitialDBState({0x26592b0, 0xc0004f2ac0}, {0x266e6a8, 0xc000908000})
        /src/libraries/doltcore/sqle/database.go:190 +0x1d1
github.com/dolthub/dolt/go/cmd/dolt/commands/engine.NewSqlEngine({0x26592b0, 0xc0004f2ac0}, 0xc000143540, 0x0, {0x0, 0x0}, 0x0, {0xc00013d1c0, 0x1, 0x1}, ...)
        /src/cmd/dolt/commands/engine/sqlengine.go:92 +0xa93
github.com/dolthub/dolt/go/cmd/dolt/commands/sqlserver.Serve({0x26592b0, 0xc0004f2ac0}, {0x229f61a, 0x6}, {0x26787f0?, 0xc000808000?}, 0x1?, 0xc000790000)
        /src/cmd/dolt/commands/sqlserver/server.go:182 +0xefb
github.com/dolthub/dolt/go/cmd/dolt/commands/sqlserver.startServer({0x26592b0, 0xc0004f2ac0}, {0x229f61a, 0x6}, {0xc0008517f0, 0xf}, {0xc0001923b0, 0x0, 0x0}, 0xc000790000, ...)
        /src/cmd/dolt/commands/sqlserver/sqlserver.go:199 +0x42a
github.com/dolthub/dolt/go/cmd/dolt/commands/sqlserver.SqlServerCmd.Exec({{0x229f61a?, 0xc000206f60?}}, {0x265a4d8?, 0xc0004f2a40}, {0xc0008517f0, 0xf}, {0xc0001923b0, 0x0, 0x0}, 0xc000790000)
        /src/cmd/dolt/commands/sqlserver/sqlserver.go:173 +0x285
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.handleCommand({{0x229d393, 0x4}, {0x22b9c81, 0x11}, {0x0, 0x0}, {0xc0001e22c0, 0x2c, 0x2c}, 0x0}, ...)
        /src/cmd/dolt/cli/command.go:238 +0x502
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.Exec({{0x229d393, 0x4}, {0x22b9c81, 0x11}, {0x0, 0x0}, {0xc0001e22c0, 0x2c, 0x2c}, 0x0}, ...)
        /src/cmd/dolt/cli/command.go:187 +0x47f
main.runMain()
        /src/cmd/dolt/dolt.go:345 +0x6a5
main.main()
        /src/cmd/dolt/dolt.go:131 +0x19
```
[dolt.tar.gz](https://github.com/dolthub/dolt/files/8815259/dolt.tar.gz)

**Comment by VinaiRachakonda** [comment]
Unable to reproduce anymore
