### ISSUE TITLE
Panic in SQL when calling functions on `*`

### ISSUE THREAD

**Issue by andrew-wm-arthur** [dolthub/dolt#398]
```
andys-mbp:cannabis-testing-wa andyarthur$ dolt sql -q 'select avg(*) from tests;'
panic: star is just a placeholder node, but Eval was called

goroutine 100 [running]:
github.com/src-d/go-mysql-server/sql/expression.(*Star).Eval(0xc000252cd0, 0xc0003bc660, 0xc00003e420, 0x16, 0x16, 0x21357a0, 0x21ab260, 0x1062901, 0x43b23f0)
	/Users/andyarthur/go/pkg/mod/github.com/liquidata-inc/go-mysql-server@v0.5.1-0.20200213191913-709d6546a1d8/sql/expression/star.go:55 +0x39
github.com/src-d/go-mysql-server/sql/expression/function/aggregation.(*Avg).Update(0xc0002535d0, 0xc0003bc660, 0xc00056cb70, 0x3, 0x3, 0xc00003e420, 0x16, 0x16, 0x3139d00, 0x51429a2)
	/Users/andyarthur/go/pkg/mod/github.com/liquidata-inc/go-mysql-server@v0.5.1-0.20200213191913-709d6546a1d8/sql/expression/function/aggregation/avg.go:82 +0x9d
github.com/src-d/go-mysql-server/sql/plan.updateBuffer(0xc0003bc660, 0xc0005df1a0, 0x1, 0x1, 0x0, 0x25f4420, 0xc0002535d0, 0xc00003e420, 0x16, 0x16, ...)
	/Users/andyarthur/go/pkg/mod/github.com/liquidata-inc/go-mysql-server@v0.5.1-0.20200213191913-709d6546a1d8/sql/plan/group_by.go:351 +0x27c
github.com/src-d/go-mysql-server/sql/plan.updateBuffers(0xc0003bc660, 0xc0005df1a0, 0x1, 0x1, 0xc0002535e0, 0x1, 0x1, 0xc00003e420, 0x16, 0x16, ...)
	/Users/andyarthur/go/pkg/mod/github.com/liquidata-inc/go-mysql-server@v0.5.1-0.20200213191913-709d6546a1d8/sql/plan/group_by.go:334 +0xcc
github.com/src-d/go-mysql-server/sql/plan.(*groupByIter).Next(0xc0003a74f0, 0xda6be2, 0x3139d00, 0x0, 0x0, 0x0)
	/Users/andyarthur/go/pkg/mod/github.com/liquidata-inc/go-mysql-server@v0.5.1-0.20200213191913-709d6546a1d8/sql/plan/group_by.go:192 +0x18b
github.com/src-d/go-mysql-server/sql.(*spanIter).Next(0xc0003a7540, 0x0, 0x0, 0x0, 0x0, 0x12)
	/Users/andyarthur/go/pkg/mod/github.com/liquidata-inc/go-mysql-server@v0.5.1-0.20200213191913-709d6546a1d8/sql/session.go:374 +0x5d
github.com/src-d/go-mysql-server/sql/plan.(*trackedRowIter).Next(0xc0005df1c0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/andyarthur/go/pkg/mod/github.com/liquidata-inc/go-mysql-server@v0.5.1-0.20200213191913-709d6546a1d8/sql/plan/process.go:176 +0x37
github.com/liquidata-inc/dolt/go/cmd/dolt/commands.(*sqlEngine).prettyPrintResults.func1(0xc0003141e0, 0x25c81e0, 0xc0005df1c0, 0xc0002538b0, 0x310c920, 0x25d5ae0, 0xc0005df2a0)
	/Users/andyarthur/LD/dolt/go/cmd/dolt/commands/sql.go:701 +0x86
created by github.com/liquidata-inc/dolt/go/cmd/dolt/commands.(*sqlEngine).prettyPrintResults
	/Users/andyarthur/LD/dolt/go/cmd/dolt/commands/sql.go:698 +0x1e1
```

**Comment by VinaiRachakonda** [comment]
This no longer panics
