### ISSUE TITLE
`panic: unknown encoding` when running `dolt diff --summary`

### ISSUE THREAD

**Issue by abmyii** [dolthub/dolt#4059]
DB: https://www.dolthub.com/repositories/dolthub/us-housing-prices-v2/
CSV: https://gofile.io/d/JINMoV

I'm getting a very weird error when running dolt diff --summary after importing:

```sql
diff --dolt a/sales b/sales
--- a/sales @ 7lj7okcumb2fmms58alhhm32ee4bo9hh
+++ b/sales @ 3e1oq7j23a52ce6bd3bsjse6vs5cb2ft
prev size: 86937691, new size: 87241033, adds: 301240, deletes: 0, modifications: 68760
panic: unknown encoding

goroutine 258 [running]:
github.com/dolthub/dolt/go/store/val.compare({0xb5?, 0x9d?}, {0xc05ed88995?, 0xc05ed8796c?, 0xeaa?}, {0xc05ed89db5?, 0xc05ed8794c?, 0x1c?})
	/src/store/val/tuple_compare.go:122 +0x1005
github.com/dolthub/dolt/go/store/val.defaultCompare.Compare({}, {0xc05ed88995, 0x23, 0x8f}, {0xc05ed89db5, 0x23, 0x8f}, {{0xc000667b28, 0x3, 0x4}, ...})
	/src/store/val/tuple_compare.go:45 +0x2b5
github.com/dolthub/dolt/go/store/val.TupleDesc.Compare({{0xc000667b28, 0x3, 0x4}, {0x21fbd60, 0x3611ca8}, {0xc000667b40, 0x0, 0x3}}, {0xc05ed88995, 0x23, ...}, ...)
	/src/store/val/tuple_descriptor.go:120 +0xd1
github.com/dolthub/dolt/go/store/prolly.orderedTree[...].compareItems(...)
	/src/store/prolly/ordered_tree.go:265
github.com/dolthub/dolt/go/store/prolly/tree.Differ.Next({0xc05ed18300?, 0xc05ed186c0?, 0xc05ed20ad0?}, {0x2206a68, 0xc000137fc0})
	/src/store/prolly/tree/diff.go:61 +0x2f0
github.com/dolthub/dolt/go/store/prolly.diffOrderedTrees[...]({_, _}, {{{{0xc00041f1b4, 0x2b5, 0x2d0}, {0xc00041f188, 0x28, 0x2fc}}, {{0xc00041f008, 0x17c, ...}, ...}, ...}, ...}, ...)
	/src/store/prolly/ordered_tree.go:58 +0x1ec
github.com/dolthub/dolt/go/store/prolly.DiffMaps(...)
	/src/store/prolly/map.go:124
github.com/dolthub/dolt/go/libraries/doltcore/diff.diffProllyTrees({0x2206a68, 0xc000137fc0}, 0xc0007a43c0, 0x0, {0x220e3c0, 0xc05ed0c000}, {0x220e3c0, 0xc05ed0c180?}, {0x2217c58, 0xc00014da90}, ...)
	/src/libraries/doltcore/diff/diff_summary.go:112 +0x657
github.com/dolthub/dolt/go/libraries/doltcore/diff.SummaryForTableDelta({0x2206a68, 0xc000137fc0}, 0x4418c5?, {{0xc0005288c0, 0x5}, {0xc05ebf34c8, 0x5}, 0xc00025e3b0, 0xc00011ec80, {0x2217c58, ...}, ...})
	/src/libraries/doltcore/diff/diff_summary.go:84 +0x427
github.com/dolthub/dolt/go/cmd/dolt/commands.printDiffSummary.func1()
	/src/cmd/dolt/commands/diff.go:732 +0xb8
created by github.com/dolthub/dolt/go/cmd/dolt/commands.printDiffSummary
	/src/cmd/dolt/commands/diff.go:730 +0x1fb
```

I ran a normal dolt diff which worked just fine.

**Comment by timsehn** [comment]
Fixed by #4064
