### ISSUE TITLE
`dolt ls --verbose` panics in the new format

### ISSUE THREAD

**Issue by abmyii** [dolthub/dolt#4103]
DB: https://www.dolthub.com/repositories/dolthub/us-housing-prices-v2

Error:
```go
Tables in working set:
panic: interface conversion: durable.Index is durable.prollyIndex, not durable.nomsIndex

goroutine 1 [running]:
github.com/dolthub/dolt/go/libraries/doltcore/doltdb/durable.NomsMapFromIndex(...)
	/src/libraries/doltcore/doltdb/durable/index.go:167
github.com/dolthub/dolt/go/libraries/doltcore/doltdb.(*Table).GetNomsRowData(0xc0003a8480?, {0x2211b68?, 0xc0002a8bc0?})
	/src/libraries/doltcore/doltdb/table.go:460 +0xa5
github.com/dolthub/dolt/go/cmd/dolt/commands.listTableVerbose({0x2211b68, 0xc0002a8bc0}, {0xc000126718, 0x5}, 0xc000a7f670?)
	/src/cmd/dolt/commands/ls.go:186 +0x33c
github.com/dolthub/dolt/go/cmd/dolt/commands.printUserTables({0x2211b68, 0xc0002a8bc0}, 0x1e566c3?, {0x1e5eb84, 0xb}, 0x1)
	/src/cmd/dolt/commands/ls.go:160 +0x396
github.com/dolthub/dolt/go/cmd/dolt/commands.LsCmd.Exec({}, {0x2211b68, 0xc0002a8bc0}, {0xc0005a2d98, 0x7}, {0xc000122170, 0x1, 0x1}, 0xc000390000)
	/src/cmd/dolt/commands/ls.go:103 +0x490
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.handleCommand({{0x1e50261, 0x4}, {0x1e6b4fb, 0x11}, {0x0, 0x0}, {0xc0001ce300, 0x2e, 0x2e}, 0x0}, ...)
	/src/cmd/dolt/cli/command.go:237 +0x502
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.Exec({{0x1e50261, 0x4}, {0x1e6b4fb, 0x11}, {0x0, 0x0}, {0xc0001ce300, 0x2e, 0x2e}, 0x0}, ...)
	/src/cmd/dolt/cli/command.go:186 +0x47e
main.runMain()
	/src/cmd/dolt/dolt.go:393 +0x7a5
main.main()
	/src/cmd/dolt/dolt.go:138 +0x19
```

**Comment by timsehn** [comment]
Can repro in any new format database:
```
dolt_new $ cd test/
test $ dolt ls --verbose
Tables in working set:
panic: interface conversion: durable.Index is durable.prollyIndex, not durable.nomsIndex

goroutine 1 [running]:
github.com/dolthub/dolt/go/libraries/doltcore/doltdb/durable.NomsMapFromIndex(...)
	/Users/timsehn/liquidata/git/dolt/go/libraries/doltcore/doltdb/durable/index.go:167
github.com/dolthub/dolt/go/libraries/doltcore/doltdb.(*Table).GetNomsRowData(0xc0001802d0?, {0x2ddf518?, 0xc0009586c0?})
	/Users/timsehn/liquidata/git/dolt/go/libraries/doltcore/doltdb/table.go:460 +0xa5
github.com/dolthub/dolt/go/cmd/dolt/commands.listTableVerbose({0x2ddf518, 0xc0009586c0}, {0xc0001220e8, 0x4}, 0xc000d4d670?)
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/commands/ls.go:186 +0x33c
github.com/dolthub/dolt/go/cmd/dolt/commands.printUserTables({0x2ddf518, 0xc0009586c0}, 0x2a315eb?, {0x2a39862, 0xb}, 0x1)
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/commands/ls.go:160 +0x396
github.com/dolthub/dolt/go/cmd/dolt/commands.LsCmd.Exec({}, {0x2ddf518, 0xc0009586c0}, {0xc00055e268, 0x7}, {0xc0001961a0, 0x1, 0x1}, 0xc000e8e000)
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/commands/ls.go:103 +0x490
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.handleCommand({{0x2a2b1d0, 0x4}, {0x2a46009, 0x11}, {0x0, 0x0}, {0xc000225200, 0x2e, 0x2e}, 0x0}, ...)
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/cli/command.go:237 +0x502
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.Exec({{0x2a2b1d0, 0x4}, {0x2a46009, 0x11}, {0x0, 0x0}, {0xc000225200, 0x2e, 0x2e}, 0x0}, ...)
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/cli/command.go:186 +0x47f
main.runMain()
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/dolt.go:393 +0x7a5
main.main()
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/dolt.go:138 +0x19
```

**Comment by andrew-wm-arthur** [comment]
addressed in https://github.com/dolthub/dolt/pull/4192
