### ISSUE TITLE
dolt panics on importing parquet file

### ISSUE THREAD

**Issue by alecstein** [dolthub/dolt#4175]
Creating a table with this schema:

```sql
create table negotiated_rates (
    reporting_entity_name varchar(255),
    negotiation_arrangement enum("ffs", "bundle", "capitation"),
    provider_reference int,
    billing_code_type enum("CPT","NDC","HCPCS","RC","ICD","MS-DRG","R-DRG","S-DRG","APS-DRG","AP-DRG","APR-DRG","APC","LOCAL","EAPG","HIPPS","CDT","CSTM-ALL"),
    billing_code varchar(255),
    service_code char(2), 
    negotiated_rate float,
    negotiated_type enum("negotiated", "derived", "fee schedule", "percentage", "per diem"),
    expiration_date date,
    billing_code_type_version varchar(255)
)
```

And trying to import this file (NB: you'll need to change the file extension to .parquet for this to work -- GitHub doesn't accept .parquet files):

[change_to_dot_parquet.txt](https://github.com/dolthub/dolt/files/9409836/test.txt)
 
Results in a panic:

```sh
~ dolt table import -u negotiated_rates test.parquet                                                                      
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x1014a9930]

goroutine 1 [running]:
github.com/dolthub/dolt/go/libraries/doltcore/table/typed/parquet.(*ParquetReader).GetSchema(0x101f4a2e8?)
    /src/libraries/doltcore/table/typed/parquet/reader.go:128
github.com/dolthub/dolt/go/cmd/dolt/commands/tblcmds.ImportCmd.Exec({}, {0x101f4a2e8, 0x1400081a0c0}, {0x14000e2e018, 0x11}, {0x1400004c210, 0x3, 0x3}, 0x10332f400?)
    /src/cmd/dolt/commands/tblcmds/import.go:395 +0x450
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.handleCommand({{0x1016270e8, 0x5}, {0x101698a1c, 0x3f}, {0x0, 0x0}, {0x1400012e280, 0x5, 0x5}, 0x0}, ...)
    /src/cmd/dolt/cli/command.go:237 +0x450
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.Exec({{0x1016270e8, 0x5}, {0x101698a1c, 0x3f}, {0x0, 0x0}, {0x1400012e280, 0x5, 0x5}, 0x0}, ...)
    /src/cmd/dolt/cli/command.go:186 +0x390
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.handleCommand({{0x10162525c, 0x4}, {0x10164050d, 0x11}, {0x0, 0x0}, {0x14000152300, 0x2e, 0x2e}, 0x0}, ...)
    /src/cmd/dolt/cli/command.go:237 +0x450
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.Exec({{0x10162525c, 0x4}, {0x10164050d, 0x11}, {0x0, 0x0}, {0x14000152300, 0x2e, 0x2e}, 0x0}, ...)
    /src/cmd/dolt/cli/command.go:186 +0x390
main.runMain()
    /src/cmd/dolt/dolt.go:393 +0x6f0
main.main()
    /src/cmd/dolt/dolt.go:138 +0x1c
```

Notably the file was created with Polars, which uses Arrow2's parquet reader/writer.

**Comment by jennifersp** [comment]
[This](https://github.com/dolthub/dolt/pull/4206) fixes the panic, 
Currently, dolt parquet format if not compatible with Apache Arrow parquet data. We will be migrating to Apache Arrow parquet format.
