### ISSUE TITLE
Panic on "conflicting" result types in `IF()` function

### ISSUE THREAD

**Issue by knutwannheden** [dolthub/dolt#4306]
The following SQL script results in a panic:

```sql
create table t(i int);
insert into t(i) values (1), (2);

select if(i > 1, i, '?') from t;
```

The panic reported is:
```
panic: unexpected type ?

goroutine 1432 [running]:
github.com/dolthub/go-mysql-server/sql.mustInt64({0x2605e60?, 0xc000beb140?})
        /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.12.1-0.20220908194409-edcfbd91cf62/sql/numbertype.go:1073 +0x26d
github.com/dolthub/go-mysql-server/sql.numberTypeImpl.SQL({0x0?}, 0x1d972270598?, {0x0, 0x0, 0x0}, {0x2605e60?, 0xc000beb140?})
        /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.12.1-0.20220908194409-edcfbd91cf62/sql/numbertype.go:404 +0x9e

github.com/dolthub/go-mysql-server/server.rowToSQL(0xc000e73f08?, {0xc00052c880, 0x1, 0x0?}, {0xc001109470, 0x1, 0xc000d3cca0?})
        /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.12.1-0.20220908194409-edcfbd91cf62/server/handler.go:723 +0x123
github.com/dolthub/go-mysql-server/server.(*Handler).doQuery.func4()
        /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.12.1-0.20220908194409-edcfbd91cf62/server/handler.go:503 +0x66f
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x8d
```

While the type of the second and third `IF()` parameters are different, they do have a common denominator and should in any case not result in a panic. In MySQL 8 this works fine: https://www.db-fiddle.com/f/d5XiHLxriLrioArW6yCDbN/0

**Comment by timsehn** [comment]
Good bug. We'll get it scheduled Monday.

**Comment by knutwannheden** [comment]
Similarly the `CASE` expression also doesn't like this (e.g. `case when i > 1 then i else '?' end`), but it doesn't cause a panic. Instead there is a dedicated error: `[HY000][1105] expecting all case branches to return values of type longtext, but found value "t.i" of type int on CASE WHEN (t.i > 1) THEN t.i ELSE '?' END`

**Comment by JCOR11599** [comment]
Fix has been merged to main, expect a release later tonight
