### ISSUE TITLE
Panic using `dolt push --set-upstream`

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#442]
```
Timothys-MacBook-Pro:corona-virus timsehn$ dolt push --set-upstream origin add-characteristics
Tree Level: 58 has 7 new chunks of which 6 already exist in the database. Buffering 1 chunks.
Tree Level: 58. 100.00% of new chunks buffered.
Tree Level: 1 has 2 new chunks of which 0 already exist in the database. Buffering 2 chunks.
Tree Level: 1. 100.00% of new chunks buffered.
Successfully uploaded 1 of 1 file(s).    
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/liquidata-inc/dolt/go/cmd/dolt/commands.PushCmd.Exec(0x264b720, 0xc0009720c0, 0xc0000e64e0, 0x9, 0xc0000e2020, 0x3, 0x3, 0xc0000f1970, 0x9)
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/commands/push.go:216 +0x661
github.com/liquidata-inc/dolt/go/cmd/dolt/cli.SubCommandHandler.Exec(0x22b6df5, 0x4, 0x22c9425, 0x11, 0xc00033a000, 0x1c, 0x1c, 0x264b720, 0xc0009720c0, 0x22b6df5, ...)
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/cli/command.go:149 +0x4f1
main.runMain(0x0)
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/dolt.go:187 +0xad3
main.main()
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/dolt.go:90 +0x22
Timothys-MacBook-Pro:corona-virus timsehn$ dolt push --set-upstream origin add-characteristics

Everything up-to-date
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/liquidata-inc/dolt/go/cmd/dolt/commands.PushCmd.Exec(0x264b720, 0xc0005e4420, 0xc00030c160, 0x9, 0xc0000e2020, 0x3, 0x3, 0xc00032e580, 0x9)
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/commands/push.go:216 +0x661
github.com/liquidata-inc/dolt/go/cmd/dolt/cli.SubCommandHandler.Exec(0x22b6df5, 0x4, 0x22c9425, 0x11, 0xc00035a000, 0x1c, 0x1c, 0x264b720, 0xc0005e4420, 0x22b6df5, ...)
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/cli/command.go:149 +0x4f1
main.runMain(0x0)
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/dolt.go:187 +0xad3
main.main()
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/dolt.go:90 +0x22
Timothys-MacBook-Pro:corona-virus timsehn$ dolt push origin add-characteristics

Everything up-to-date
```

**Comment by timsehn** [comment]
Could not produce simple repo in #443

**Comment by zachmu** [comment]
Closing this out since it's very old and we have no repro
