### ISSUE TITLE
panic on `dolt table import -u --continue`

### ISSUE THREAD

**Issue by druvv** [dolthub/dolt#4653]
> in https://www.dolthub.com/repositories/post-no-preference/stocks, post dolt migrate, when i do
$ dolt table import -u --continue ohlcv ohlcv-2022-10-27.csv
i get the following error/stack trace

```
panic: interface conversion: interface {} is string, not decimal.Decimal

goroutine 513 [running]:
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.PutField({0x2424a98, 0xc0005cf220}, {0x242a280, 0xc0008ce5a0}, 0xc0005e1000, 0x0, {0x1c718a0?, 0xc001afb040?})
    /src/libraries/doltcore/sqle/index/prolly_fields.go:161 +0x180a
github.com/dolthub/dolt/go/libraries/doltcore/sqle/writer.prollyIndexWriter.Insert({0xc00188bc20, 0xc0005e0f00, {0xc000827490, 0x2, 0x2}, 0xc0005e1000, {0xc000d16660, 0x5, 0x5}}, {0x2424a98, ...}, ...)
    /src/libraries/doltcore/sqle/writer/prolly_index_writer.go:144 +0x206
github.com/dolthub/dolt/go/libraries/doltcore/sqle/writer.(*prollyTableWriter).Insert(0xc00188bd40, 0x1c718a0?, {0xc001af8bd0, 0x7, 0x7})
    /src/libraries/doltcore/sqle/writer/prolly_table_writer.go:144 +0x25d
github.com/dolthub/go-mysql-server/sql/plan.(*insertIter).Next(0xc000d19a00, 0x3a47858?)
    /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.12.1-0.20221025150822-7d1a405cef1f/sql/plan/insert.go:407 +0x888
github.com/dolthub/go-mysql-server/sql/plan.checkpointingTableEditorIter.Next({{0x7fb125423918?, 0xc00188bd40?}, {0x24162f8?, 0xc000d19a00?}}, 0xc000320cf0?)
    /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.12.1-0.20221025150822-7d1a405cef1f/sql/plan/table_editor.go:104 +0x72
github.com/dolthub/dolt/go/libraries/doltcore/mvdata.(*SqlEngineTableWriter).WriteRows(0xc000ce1dc0, {0x0?, 0x0?}, 0x0?, 0xc0002fd350)
...
```

Sample of the csv
```csv
date,act_symbol,open,high,low,close,volume
2022-10-27,A,137.2600,137.9900,135.3300,136.4900,930704
2022-10-27,AA,42.5800,42.8100,41.1900,41.4100,5169067
2022-10-27,AAA,24.2050,24.2050,24.2050,24.2050,3
```

**Comment by druvv** [comment]
Here is a simple repro:

```bash
$ dolt sql -q "create table t (pk int primary key, col1 decimal(7,2));"
$ dolt commit -am "create table"
$ echo 'pk,col1\n1,a' > test.csv
$ dolt table import -u --continue t test.csv
panic: interface conversion: interface {} is string, not decimal.Decimal

goroutine 129 [running]:
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.PutField({0x1023c8820, 0x14000ce0c80}, {0x1023cdf20, 0x14000d9e000}, 0x140005b4380, 0x0, {0x101fe00a0?, 0x1400050c8e0?})
	/Users/dhruv/dolt/go/libraries/doltcore/sqle/index/prolly_fields.go:161 +0x1814
github.com/dolthub/dolt/go/libraries/doltcore/sqle/writer.prollyIndexWriter.Insert({0x140006e6240, 0x140005b4300, {0x14000d8a7d0, 0x1, 0x1}, 0x140005b4380, {0x14000d8a7d8, 0x1, 0x1}}, {0x1023c8820, ...}, ...)
	/Users/dhruv/dolt/go/libraries/doltcore/sqle/writer/prolly_index_writer.go:144 +0x134
github.com/dolthub/dolt/go/libraries/doltcore/sqle/writer.(*prollyTableWriter).Insert(0x140006e6360, 0x14000691b60?, {0x14000637a00, 0x2, 0x2})
	/Users/dhruv/dolt/go/libraries/doltcore/sqle/writer/prolly_table_writer.go:144 +0x1c4
github.com/dolthub/go-mysql-server/sql/plan.(*insertIter).Next(0x1400047ef70, 0x14000060060?)
	/Users/dhruv/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.12.1-0.20221025150822-7d1a405cef1f/sql/plan/insert.go:407 +0x678
github.com/dolthub/go-mysql-server/sql/plan.checkpointingTableEditorIter.Next({{0x10b9e1f90?, 0x140006e6360?}, {0x1023ba0f0?, 0x1400047ef70?}}, 0x0?)
	/Users/dhruv/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.12.1-0.20221025150822-7d1a405cef1f/sql/plan/table_editor.go:104 +0x60
github.com/dolthub/dolt/go/libraries/doltcore/mvdata.(*SqlEngineTableWriter).WriteRows(0x140004e2460, {0x100b19420?, 0x140005b6640?}, 0x1400058f7d0?, 0x1400065f470)
	/Users/dhruv/dolt/go/libraries/doltcore/mvdata/engine_table_writer.go:254 +0x2a0
github.com/dolthub/dolt/go/cmd/dolt/commands/tblcmds.move.func3()
	/Users/dhruv/dolt/go/cmd/dolt/commands/tblcmds/import.go:551 +0x30
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/Users/dhruv/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x60
created by golang.org/x/sync/errgroup.(*Group).Go
	/Users/dhruv/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x8c
```

**Comment by druvv** [comment]
fixed in the latest version of dolt.
