### ISSUE TITLE
HashLookup on byte slice causes panic

### ISSUE THREAD

**Issue by fulghum** [dolthub/dolt#4682]
When joining two tables and using the `binary` keyword in the join condition, Dolt panics when trying to create a hash key out of a `[]uint8` data type returned by the `binary` function. 

Sample query: 
`select uv.u from uv join xy on binary xy.x = binary uv.u;`

Error trace: 
```
panic: runtime error: hash of unhashable type []uint8

goroutine 1 [running]:
github.com/dolthub/go-mysql-server/sql/plan.(*HashLookup).RowIter(0x140009febc0, 0x10105f7c0?, {0x14000e98100, 0x1, 0x1})
	/Users/jason/Projects/secondary-go-mysql-server/sql/plan/hash_lookup.go:112 +0x398
github.com/dolthub/go-mysql-server/sql/plan.(*joinIter).loadSecondary(0x1400047b7a0, 0x14000e8a100?)
	/Users/jason/Projects/secondary-go-mysql-server/sql/plan/join_iters.go:96 +0x48
github.com/dolthub/go-mysql-server/sql/plan.(*joinIter).Next(0x1400047b7a0, 0x140001270f0?)
	/Users/jason/Projects/secondary-go-mysql-server/sql/plan/join_iters.go:128 +0x50
```

**Comment by JCOR11599** [comment]
the fix has been merged to main
