### ISSUE TITLE
panic on large `varbinary` insert

### ISSUE THREAD

**Issue by coffeegoddd** [dolthub/dolt#5059]
Dolt version `v0.51.14`.
Table Schema:
```sql
CREATE TABLE `t1` (
  `sample` varbinary(1073741824) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin
```
Result:
```bash
panic: runtime error: index out of range [158939] with length 27868

goroutine 1 [running]:
github.com/dolthub/dolt/go/store/val.writeByteString(...)
	/Users/dustin/src/dolt/go/store/val/codec.go:575
github.com/dolthub/dolt/go/store/val.(*TupleBuilder).PutByteString(0x14000560900, 0x1?, {0x14000d30000?, 0x26cdb, 0x0?})
	/Users/dustin/src/dolt/go/store/val/tuple_builder.go:276 +0x1f0
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.PutField({0x1025471d8, 0x14001056820}, {0x10254ffc0, 0x14001020140}, 0x14000560900, 0x1, {0x10215a760?, 0x1400057e900})
	/Users/dustin/src/dolt/go/libraries/doltcore/sqle/index/prolly_fields.go:183 +0x16f4
github.com/dolthub/dolt/go/libraries/doltcore/sqle/writer.prollyKeylessWriter.tuplesFromRow({{0x0, 0x0}, 0x140011110e0, 0x14000560880, 0x14000560900, {0x140010142b0, 0x1, 0x1}}, {0x1025471d8, 0x14001056820}, ...)
	/Users/dustin/src/dolt/go/libraries/doltcore/sqle/writer/prolly_index_writer_keyless.go:140 +0x138
github.com/dolthub/dolt/go/libraries/doltcore/sqle/writer.prollyKeylessWriter.Insert({{0x0, 0x0}, 0x140011110e0, 0x14000560880, 0x14000560900, {0x140010142b0, 0x1, 0x1}}, {0x1025471d8, 0x14001056820}, ...)
	/Users/dustin/src/dolt/go/libraries/doltcore/sqle/writer/prolly_index_writer_keyless.go:54 +0x60
github.com/dolthub/dolt/go/libraries/doltcore/sqle/writer.(*prollyTableWriter).Insert(0x14001111200, 0x10217f160?, {0x140004ee370, 0x1, 0x1})
	/Users/dustin/src/dolt/go/libraries/doltcore/sqle/writer/prolly_table_writer.go:145 +0x1c4
github.com/dolthub/go-mysql-server/sql/plan.(*insertIter).Next(0x1400104e270, 0x101550e58?)
	/Users/dustin/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20221227195451-7bf43515f1ef/sql/plan/insert.go:419 +0x6e4
github.com/dolthub/go-mysql-server/sql/plan.(*tableEditorIter).Next(0x1400107e8c0, 0x14001056820)
	/Users/dustin/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20221227195451-7bf43515f1ef/sql/plan/table_editor.go:51 +0x70
github.com/dolthub/go-mysql-server/sql/plan.(*accumulatorIter).Next(0x14001105c80, 0x14001056820)
	/Users/dustin/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20221227195451-7bf43515f1ef/sql/plan/row_update_accumulator.go:329 +0x164
github.com/dolthub/go-mysql-server/sql/plan.transactionCommittingIter.Next(...)
	/Users/dustin/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20221227195451-7bf43515f1ef/sql/plan/transaction_committing_iter.go:112
github.com/dolthub/go-mysql-server/sql/plan.(*trackedRowIter).Next(0x1400100a550, 0x0?)
	/Users/dustin/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20221227195451-7bf43515f1ef/sql/plan/process.go:381 +0x30
github.com/dolthub/dolt/go/cmd/dolt/commands/engine.printOKResult(0x103480448?, {0x102539458?, 0x1400100a550?}, {0x103480448?, 0x14000d3f178?, 0x1034d9fc0?})
	/Users/dustin/src/dolt/go/cmd/dolt/commands/engine/sql_print.go:199 +0x44
github.com/dolthub/dolt/go/cmd/dolt/commands/engine.prettyPrintResultsWithSummary(0x14001056820, 0x0, {0x103480448?, 0x1, 0x1}, {0x102539458, 0x1400100a550}, 0x0)
	/Users/dustin/src/dolt/go/cmd/dolt/commands/engine/sql_print.go:74 +0x5c0
github.com/dolthub/dolt/go/cmd/dolt/commands/engine.PrettyPrintResults(...)
	/Users/dustin/src/dolt/go/cmd/dolt/commands/engine/sql_print.go:54
github.com/dolthub/dolt/go/cmd/dolt/commands.runMultiStatementMode(0x1400100afa0?, 0x14001105740, {0x1025311e0?, 0x14001000300}, 0x0)
	/Users/dustin/src/dolt/go/cmd/dolt/commands/sql.go:838 +0x5ec
github.com/dolthub/dolt/go/cmd/dolt/commands.execMultiStatements({0x102546a30, 0x140010047b0}, 0xd3?, 0x8?, {0x1025311e0, 0x14001000300}, 0x1?, 0x14000d3f708)
	/Users/dustin/src/dolt/go/cmd/dolt/commands/sql.go:584 +0x168
github.com/dolthub/dolt/go/cmd/dolt/commands.queryMode({0x102546a30, 0x140010047b0}, 0x101af93ff?, 0x5?, 0x14001042db0, {0x16f714b04, 0x26d02}, 0x2?, 0x14000d3f488?, 0x14000d3f708)
	/Users/dustin/src/dolt/go/cmd/dolt/commands/sql.go:448 +0x1f0
github.com/dolthub/dolt/go/cmd/dolt/commands.SqlCmd.Exec({{0x101afb978?, 0x101659a0c?}}, {0x102546a30, 0x140010047b0}, {0x14001014248, 0x8}, {0x1400004e0a0, 0x2, 0x2}, 0x14000408cf0)
	/Users/dustin/src/dolt/go/cmd/dolt/commands/sql.go:301 +0xedc
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.handleCommand({{0x101af78be, 0x4}, {0x101b11ae0, 0x11}, {0x0, 0x0}, {0x140001b4300, 0x2f, 0x2f}, 0x0}, ...)
	/Users/dustin/src/dolt/go/cmd/dolt/cli/command.go:237 +0x450
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.Exec({{0x101af78be, 0x4}, {0x101b11ae0, 0x11}, {0x0, 0x0}, {0x140001b4300, 0x2f, 0x2f}, 0x0}, ...)
	/Users/dustin/src/dolt/go/cmd/dolt/cli/command.go:186 +0x390
main.runMain()
	/Users/dustin/src/dolt/go/cmd/dolt/dolt.go:393 +0x6dc
main.main()
	/Users/dustin/src/dolt/go/cmd/dolt/dolt.go:139 +0x1c
```

File has steps to repro:
[panic-repro.md](https://github.com/dolthub/dolt/files/10311286/panic-repro.md)

**Comment by JCOR11599** [comment]
this doesn't work in MySQL
```sql
mysql> create table t1 (sample varbinary(1073741824) not null);
ERROR: 1074: Column length too big for column 'sample' (max = 65535); use BLOB or TEXT instead
```

but this does
```sql
mysql> create table t1 (sample blob(1073741824) not null);
```

Will add change to make dolt error.

**Comment by JCOR11599** [comment]
Merged in a fix that prevents tables with a large varbinary column to be created.
