### ISSUE TITLE
Join between `dolt_log` and `dolt_commit_ancestors` results in go panic

### ISSUE THREAD

**Issue by crisp-snakey** [dolthub/dolt#5166]
The break was introduced in version `0.52.1`. `0.52.0` gives the expected result.

Querying either table is fine but trying to join them results in a panic, example:init_empty_test_repo

```       
 % dolt sql --query 'select * from dolt_log'
+----------------------------------+----------------+----------------------+------------------------+----------------------------+
| commit_hash                      | committer      | email                | date                   | message                    |
+----------------------------------+----------------+----------------------+------------------------+----------------------------+
| gaoko4rud07ko80lot15qrr5g6drebug | <username>     | <email>              | 2023-01-19 07:55:22.44 | Initialize data repository |
+----------------------------------+----------------+----------------------+------------------------+----------------------------+
```

```
 % dolt sql --query 'select * from dolt_commit_ancestors' 
+----------------------------------+-------------+--------------+
| commit_hash                      | parent_hash | parent_index |
+----------------------------------+-------------+--------------+
| gaoko4rud07ko80lot15qrr5g6drebug | NULL        | 0            |
+----------------------------------+-------------+--------------+
```

Then trying to join them on version `0.52.1` results in a panic:
```
 % dolt sql --query 'select * from dolt_log as dc join dolt_commit_ancestors as dca on dc.commit_hash = dca.commit_hash' 
panic: unknown message id 

goroutine 1 [running]:
github.com/dolthub/dolt/go/store/prolly/message.GetTreeCount({0x0, 0x0, 0x0})
        /src/store/prolly/message/message.go:130 +0x1bd
github.com/dolthub/dolt/go/store/prolly/tree.Node.TreeCount(...)
        /src/store/prolly/tree/node.go:136
github.com/dolthub/dolt/go/store/prolly/tree.StaticMap[...].Count({{{0x0, 0x0, 0x0, 0x0, 0x0}, {0x0, 0x0, 0x0, 0x0, 0x0}, ...}, ...})
        /src/store/prolly/tree/map.go:189 +0x53
github.com/dolthub/dolt/go/store/prolly.CommitClosure.Count(...)
        /src/store/prolly/commit_closure.go:70
github.com/dolthub/dolt/go/libraries/doltcore/sqle/dtables.(*LogTable).RowCount(0xc0005b4470?, 0x2343358?)
        /src/libraries/doltcore/sqle/dtables/log_table.go:54 +0x11f
github.com/dolthub/go-mysql-server/sql/information_schema.(*defaultStatsTable).RowCount(0xc0002f69b0, 0x2343358?, {0xc0005b4470, 0xc}, {0x1f6552b, 0x8})
        /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230117184403-00346c423e7f/sql/information_schema/information_schema.go:2228 +0xec
github.com/dolthub/go-mysql-server/sql/analyzer.(*coster).costRead(0xc0005b6d68, {0x2343358, 0xc0002f76d0})
        /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230117184403-00346c423e7f/sql/analyzer/coster.go:91 +0xb9
github.com/dolthub/go-mysql-server/sql/analyzer.(*coster).costTableAlias(0x4?, 0x0?)
        /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230117184403-00346c423e7f/sql/analyzer/coster.go:75 +0x48
github.com/dolthub/go-mysql-server/sql/analyzer.(*coster).costRel(0xc0002f4ff0?, {0x233ec20?, 0xc0002f4cf0?})
        /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230117184403-00346c423e7f/sql/analyzer/coster.go:34 +0x3d4
github.com/dolthub/go-mysql-server/sql/analyzer.(*Memo).optimizeMemoGroup(0xc001238e40, 0xc001324050)
        /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230117184403-00346c423e7f/sql/analyzer/memo.go:104 +0xc6
github.com/dolthub/go-mysql-server/sql/analyzer.(*Memo).optimizeMemoGroup(0xc001238e40, 0xc0013240f0)
        /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230117184403-00346c423e7f/sql/analyzer/memo.go:98 +0x12c
github.com/dolthub/go-mysql-server/sql/analyzer.(*Memo).optimizeRoot(...)
        /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230117184403-00346c423e7f/sql/analyzer/memo.go:78
github.com/dolthub/go-mysql-server/sql/analyzer.replanJoin(0x20?, 0xc0005cbcc0, 0xc0005caff0, 0xc00131a540?)
        /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230117184403-00346c423e7f/sql/analyzer/indexed_joins.go:180 +0x207
github.com/dolthub/go-mysql-server/sql/analyzer.inOrderReplanJoin(0x234cf80?, 0xc00131aae0?, 0x0?, {0x0?, 0x0, 0x0}, {0x234ca80, 0xc0005cbcc0?}, 0x1, 0x0)
        /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230117184403-00346c423e7f/sql/analyzer/indexed_joins.go:117 +0x10d
github.com/dolthub/go-mysql-server/sql/analyzer.inOrderReplanJoin(0xc00131aae0?, 0x13?, 0x0?, {0x0?, 0x0, 0x0}, {0x234cf80, 0xc00131aae0?}, 0x1, 0x0)
        /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230117184403-00346c423e7f/sql/analyzer/indexed_joins.go:92 +0x71b
github.com/dolthub/go-mysql-server/sql/analyzer.constructJoinPlan(0x0?, 0x1f799f4?, {0x234cf80, 0xc00131aae0}, 0xc00131aae0?, 0x201dbf0?)
        /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230117184403-00346c423e7f/sql/analyzer/indexed_joins.go:68 +0x7af
github.com/dolthub/go-mysql-server/sql/analyzer.(*Batch).evalOnce(0x234cf80?, 0xc00131aae0?, 0xc0005caff0, {0x234cf80?, 0xc00131aae0?}, 0xc000f3ec40?, 0x201dbf0)
        /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230117184403-00346c423e7f/sql/analyzer/batch.go:121 +0x248
github.com/dolthub/go-mysql-server/sql/analyzer.(*Batch).EvalWithSelector(0xc0012268d0, 0x1faa3e3?, 0xc0005caff0, {0x234cf80, 0xc00131aae0}, 0x0?, 0x0?)
        /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230117184403-00346c423e7f/sql/analyzer/batch.go:65 +0x171
github.com/dolthub/go-mysql-server/sql/analyzer.(*Batch).Eval(...)
        /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230117184403-00346c423e7f/sql/analyzer/batch.go:56
github.com/dolthub/go-mysql-server/sql/analyzer.(*Analyzer).analyzeWithSelector(0xc0005caff0?, 0x234cf80?, {0x234cf80?, 0xc001227c80?}, 0x0?, 0x201dbf8?, 0x2359d30?)
        /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230117184403-00346c423e7f/sql/analyzer/analyzer.go:603 +0x3c5
github.com/dolthub/go-mysql-server/sql/analyzer.(*Analyzer).Analyze(...)
        /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230117184403-00346c423e7f/sql/analyzer/analyzer.go:442
github.com/dolthub/go-mysql-server.(*Engine).analyzeQuery(0xc0005cb090, 0xc001202960, {0xc0005ec070?, 0x62?}, {0x234cf80?, 0xc001227c80?}, 0x0)
        /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230117184403-00346c423e7f/engine.go:443 +0x6bf
github.com/dolthub/go-mysql-server.(*Engine).QueryNodeWithBindings(0xc0005cb090, 0xc001202960, {0xc0005ec070, 0x62}, {0x0?, 0x0?}, 0xc000100000?)
        /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230117184403-00346c423e7f/engine.go:260 +0x1e8
github.com/dolthub/go-mysql-server.(*Engine).QueryWithBindings(...)
        /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230117184403-00346c423e7f/engine.go:212
github.com/dolthub/go-mysql-server.(*Engine).Query(0x62?, 0xc000f3f190?, {0xc0005ec070?, 0xe8?})
        /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230117184403-00346c423e7f/engine.go:207 +0x26
github.com/dolthub/dolt/go/cmd/dolt/commands/engine.(*SqlEngine).Query(...)
        /src/cmd/dolt/commands/engine/sqlengine.go:222
github.com/dolthub/dolt/go/cmd/dolt/commands.processParsedQuery(0xc0005ec070?, {0xc0005ec070?, 0x62?}, 0xc0005ec070?, {0x232ee48?, 0xc0005ee500?})
        /src/cmd/dolt/commands/sql.go:1214 +0x3d3
github.com/dolthub/dolt/go/cmd/dolt/commands.runMultiStatementMode(0xc0005cae60?, 0xc001227800, {0x23260a0?, 0xc0005cc300}, 0x0)
        /src/cmd/dolt/commands/sql.go:820 +0x36a
github.com/dolthub/dolt/go/cmd/dolt/commands.execMultiStatements({0x233bad0, 0xc0005a6720}, 0xdb?, 0x8?, {0x23260a0, 0xc0005cc300}, 0x1?, 0xc000f3f718)
        /src/cmd/dolt/commands/sql.go:584 +0x1d9
github.com/dolthub/dolt/go/cmd/dolt/commands.queryMode({0x233bad0, 0xc0005a6720}, 0x5?, 0x34aad50?, 0xc0005f6d20, {0x7ffceace5e46, 0x62}, 0xd8?, 0xc000f3f4a0?, 0xc000f3f718)
        /src/cmd/dolt/commands/sql.go:448 +0x245
github.com/dolthub/dolt/go/cmd/dolt/commands.SqlCmd.Exec({{0x1f60453?, 0xc000f3f818?}}, {0x233bad0, 0xc0005a6720}, {0xc0005b8288, 0x8}, {0xc0000500a0, 0x2, 0x2}, 0xc00030c090)
        /src/cmd/dolt/commands/sql.go:301 +0x130b
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.handleCommand({{0x1f5e25c, 0x4}, {0x1f78642, 0x11}, {0x0, 0x0}, {0xc0001c4300, 0x2f, 0x2f}, 0x0}, ...)
        /src/cmd/dolt/cli/command.go:237 +0x502
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.Exec({{0x1f5e25c, 0x4}, {0x1f78642, 0x11}, {0x0, 0x0}, {0xc0001c4300, 0x2f, 0x2f}, 0x0}, ...)
        /src/cmd/dolt/cli/command.go:186 +0x47e
main.runMain()
        /src/cmd/dolt/dolt.go:393 +0x787
main.main()
        /src/cmd/dolt/dolt.go:139 +0x19
```

While version `0.52.0` gives the expected result:
```
 % ./dolt sql --query 'select * from dolt_log as dc join dolt_commit_ancestors as dca on dc.commit_hash = dca.commit_hash'
+----------------------------------+----------------+----------------------+------------------------+----------------------------+----------------------------------+-------------+--------------+
| commit_hash                      | committer      | email                | date                   | message                    | commit_hash                      | parent_hash | parent_index |
+----------------------------------+----------------+----------------------+------------------------+----------------------------+----------------------------------+-------------+--------------+
| gaoko4rud07ko80lot15qrr5g6drebug | <username>     | <email>              | 2023-01-19 07:55:22.44 | Initialize data repository | gaoko4rud07ko80lot15qrr5g6drebug | NULL        | 0            |
+----------------------------------+----------------+----------------------+------------------------+----------------------------+----------------------------------+-------------+--------------+
```

Might be related to #5136

**Comment by timsehn** [comment]
@max-hoffman has been poking around in Dolt system tables. This might be a good fix for him.

**Comment by crisp-snakey** [comment]
Thanks @max-hoffman, that fixes my problem!

**Comment by fulghum** [comment]
Resolving this one now that the fix is out. Thanks again for reporting this so we could fix it! Let us know if you hit any other snags and we'll be happy to help out.
