### ISSUE TITLE
`dolt sql ... --result-format=json` fails to return a valid JSON when result set is empty

### ISSUE THREAD

**Issue by rl1987** [dolthub/dolt#5236]
Consider the following situation.

```
root@dhdb-quest:~/data/quest-v3# dolt sql -q 'SELECT * FROM file;'

root@dhdb-quest:~/data/quest-v3# dolt sql -q 'SELECT * FROM file;' --result-format=json

root@dhdb-quest:~/data/quest-v3# dolt sql -q 'SELECT * FROM file;' --result-format=json | python3 -m json.tool
Expecting value: line 2 column 1 (char 1)
root@dhdb-quest:~/data/quest-v3# python3
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import doltcli as dolt
>>> db = dolt.Dolt(".")
>>> db.sql('SELECT * FROM file;', result_format="json")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/doltcli/dolt.py", line 618, in sql
    return SQL_OUTPUT_PARSERS[result_format](fh)
  File "/usr/local/lib/python3.9/dist-packages/doltcli/dolt.py", line 30, in <lambda>
    "json": lambda fh: json.load(fh),
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
>>> db.sql('SELECT * FROM file;', result_format="csv")
[]
>>> exit()
root@dhdb-quest:~/data/quest-v3# dolt sql
# Welcome to the DoltSQL shell.
# Statements must be terminated with ';'.
# "exit" or "quit" (or Ctrl-D) to exit.
quest_v3> SELECT * FROM file;
Empty set (0.00 sec)

quest_v3>  

```

When result set is empty `dolt sql ... --result-format=json` should return empty JSON array (`[]`). This would not crash Python JSON parser and SQL query via `doltcli` module. Empty or whitespace-only string is not a valid JSON string.

**Comment by timsehn** [comment]
Thanks. Agreed we should fix this.

**Comment by jennifersp** [comment]
Hi @rl1987, thank you for reporting this issue. The fix for this issue has been merged into main and will be out in the next Dolt release.
