### ISSUE TITLE
Can create empty column name using appropriately formatted CSV

### ISSUE THREAD

**Issue by oscarbatori** [dolthub/dolt#53]
With an appropriately formatted CSV, I am able to create an empty column name. This came up because `Pandas` by default inserts a column without a name (i.e. prepends a `,` to the list of columns that form the first line), and then prefixes each line with its index location from the `DataFrame` used to produce the `CSV`.

Here is a reproduction that can be run locally:
```[oscarbatori:empty-column-error] >> dolt init
Successfully initialized dolt data repository.
[oscarbatori:empty-column-error] >> cat > test_data.csv
,first,last
0,BoJack,Horeseman
1,Mr,Peanutbutter
2,Diane,Nguyen
^C
[oscarbatori:empty-column-error] >> dolt table import people --pk=first -c test_data.csv
Rows Processed: 3, Additions: 3, Modifications: 0, Had No Effect: 0
Import completed successfully.
[oscarbatori:empty-column-error] >> dolt sql
# Welcome to the DoltSQL shell.
# Statements must be terminated with ';'.
# "exit" or "quit" (or Ctrl-D) to exit.
doltsql> select * from people ;
+---+--------+--------------+
|   | first  | last         |
+---+--------+--------------+
| 0 | BoJack | Horeseman    |
| 2 | Diane  | Nguyen       |
| 1 | Mr     | Peanutbutter |
+---+--------+--------------+

**Comment by oscarbatori** [comment]
I believe that we have "resolved" this in the sense that we can no longer create a "ghost column", but I don't think the error message is very useful:
```[oscarbatori:dolt(master)] >> dolt table import people --pk=first -c test_data.csv
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1964892]

goroutine 1 [running]:
github.com/liquidata-inc/dolt/go/libraries/doltcore/table/untyped/csv.getColHeaders(0xc0005c3200, 0xc00004f140, 0x40000, 0xc0002ce000, 0xc0000e8780, 0x0, 0x0)
	/Users/oscarbatori/Documents/dolt/go/libraries/doltcore/table/untyped/csv/reader.go:95 +0x192
github.com/liquidata-inc/dolt/go/libraries/doltcore/table/untyped/csv.NewCSVReader(0x2e29fb0, 0x23ce940, 0xc0000e8780, 0xc00004f140, 0xc0000e8780, 0x0, 0x0)
	/Users/oscarbatori/Documents/dolt/go/libraries/doltcore/table/untyped/csv/reader.go:63 +0xba
github.com/liquidata-inc/dolt/go/libraries/doltcore/table/untyped/csv.OpenCSVReader(0x2e29fb0, 0x7ffeefbff85f, 0xd, 0x69087a0, 0x2e74fe0, 0xc00004f140, 0x0, 0x0, 0x0)
	/Users/oscarbatori/Documents/dolt/go/libraries/doltcore/table/untyped/csv/reader.go:57 +0xa7
github.com/liquidata-inc/dolt/go/libraries/doltcore/mvdata.FileDataLocation.NewReader(0x7ffeefbff85f, 0xd, 0x212e7fb, 0x4, 0x23e5d00, 0xc0000d1a10, 0xc0000f0240, 0x69087a0, 0x2e74fe0, 0x0, ...)
	/Users/oscarbatori/Documents/dolt/go/libraries/doltcore/mvdata/file_data_loc.go:95 +0x1de
github.com/liquidata-inc/dolt/go/libraries/doltcore/mvdata.NewDataMover(0x23e5d00, 0xc0000d1a10, 0xc0000f0240, 0x23fe240, 0x2e74fe0, 0xc0003be990, 0x2192f48, 0x0, 0x0)
	/Users/oscarbatori/Documents/dolt/go/libraries/doltcore/mvdata/data_mover.go:103 +0x141
github.com/liquidata-inc/dolt/go/cmd/dolt/commands/tblcmds.executeMove(0x23e5d00, 0xc0000d1a10, 0xc00048e000, 0x0, 0xc0003be990, 0x0)
	/Users/oscarbatori/Documents/dolt/go/cmd/dolt/commands/tblcmds/import.go:316 +0x151
github.com/liquidata-inc/dolt/go/cmd/dolt/commands/tblcmds.Import(0x23e5d00, 0xc0000d1a10, 0xc0004b64e0, 0x11, 0xc000104030, 0x4, 0x4, 0xc00048e000, 0x11)
	/Users/oscarbatori/Documents/dolt/go/cmd/dolt/commands/tblcmds/import.go:223 +0xa4
github.com/liquidata-inc/dolt/go/cmd/dolt/cli.GenSubCommandHandler.func1(0x23e5d00, 0xc0000d1a10, 0xc0000f6516, 0xa, 0xc000104020, 0x5, 0x5, 0xc00048e000, 0xa)
	/Users/oscarbatori/Documents/dolt/go/cmd/dolt/cli/command.go:93 +0x1f7
github.com/liquidata-inc/dolt/go/cmd/dolt/cli.GenSubCommandHandler.func1(0x23e5c80, 0xc0000d6000, 0x212eda7, 0x4, 0xc000104010, 0x6, 0x6, 0xc00048e000, 0xc0000d1980)
	/Users/oscarbatori/Documents/dolt/go/cmd/dolt/cli/command.go:93 +0x1f7
main.runMain(0x0)
	/Users/oscarbatori/Documents/dolt/go/cmd/dolt/dolt.go:176 +0x9cd
main.main()
	/Users/oscarbatori/Documents/dolt/go/cmd/dolt/dolt.go:84 +0x22```

Changing this to "documentation".

**Comment by KIC** [comment]
Hmmm .. this is actually making the import functionality worse. Now I can not load serialized data frames anymore. The dolt table import function would need to allow excluding or mapping of "ghost" columns as you call them

**Comment by oscarbatori** [comment]
@KIC can you elaborate here? Do you mean you are serializing `pandas.DataFrame` objects with `index=True` (default) and then you are unable to load them.

**Comment by zachmu** [comment]
Closing as obsolete, doltpy has had many revisions since this was filed. Please reopen a new issue as appropriate.
