### ISSUE TITLE
Running a GetRepoMetadata request against the remotesrv within the sql-server, without data crashes the sql-server

### ISSUE THREAD

**Issue by santidhammo** [dolthub/dolt#5379]
Running:

dolt sql-server --remotesapi-port=8080
Starting server with Config HP="localhost:3306"|T="28800000"|R="false"|L="info"|S="/tmp/mysql.sock"
2023-02-17T21:56:20+01:00 WARN [no conn] unix socket set up failed: file already in use: /tmp/mysql.sock {}
2023-02-17T21:56:20+01:00 INFO [no conn] Starting http server on :8080 {}

Then running:

ChunkStoreService/GetRepoMetadata

Without any data

Would expect some kind of error returned, instead:

2023-02-17T22:05:25+01:00 INFO [no conn] starting request {method=GetRepoMetadata, request_num=1, service=dolt.services.remotesapi.v1alpha1.ChunkStoreServiceServer}
2023-02-17T22:05:25+01:00 ERROR [no conn] Failed to retrieve chunkstore {error=database not found: proident anim, method=GetRepoMetadata, repo_path=proident anim, request_num=1, service=dolt.services.remotesapi.v1alpha1.ChunkStoreServiceServer}
2023-02-17T22:05:25+01:00 INFO [no conn] finished {method=GetRepoMetadata, repo_path=proident anim, request_num=1, service=dolt.services.remotesapi.v1alpha1.ChunkStoreServiceServer}
2023-02-17T22:07:34+01:00 INFO [no conn] starting request {method=GetRepoMetadata, request_num=2, service=dolt.services.remotesapi.v1alpha1.ChunkStoreServiceServer}
2023-02-17T22:07:34+01:00 INFO [no conn] finished {method=GetRepoMetadata, repo_path=, request_num=2, service=dolt.services.remotesapi.v1alpha1.ChunkStoreServiceServer}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x17fad3d]

goroutine 355 [running]:
github.com/dolthub/dolt/go/libraries/doltcore/remotesrv.(*RemoteChunkStore).GetRepoMetadata(0xc000c8bce0, {0x23b2820, 0xc000c402d0}, 0xc000654780)
	/src/libraries/doltcore/remotesrv/grpc.go:484 +0x1bd
github.com/dolthub/dolt/go/gen/proto/dolt/services/remotesapi/v1alpha1._ChunkStoreService_GetRepoMetadata_Handler({0x1f2bda0?, 0xc000026500}, {0x23b2820, 0xc000c402d0}, 0xc000c94000, 0x0)
	/src/gen/proto/dolt/services/remotesapi/v1alpha1/chunkstore_grpc.pb.go:256 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc001bb6000, {0x23c8620, 0xc001820000}, 0xc000734120, 0xc001b65320, 0x353b700, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.49.0/server.go:1301 +0xb2b
google.golang.org/grpc.(*Server).handleStream(0xc001bb6000, {0x23c8620, 0xc001820000}, 0xc000734120, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.49.0/server.go:1642 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/go/pkg/mod/google.golang.org/grpc@v1.49.0/server.go:938 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/pkg/mod/google.golang.org/grpc@v1.49.0/server.go:936 +0x28a

And the server went down

**Comment by timsehn** [comment]
Wow. This is deep :-)

@reltuk

**Comment by reltuk** [comment]
Thanks for the great report! We are adding some sanity checks on incoming messages and some InvalidArgument responses here:

#5474.

I will close this issue when it lands and it will be in the next dolt release :).
