### ISSUE TITLE
panic on stored procedure call

### ISSUE THREAD

**Issue by zachmu** [dolthub/dolt#5390]
```bash
% dolt sql <<SQL
delimiter //
CREATE PROCEDURE dorepeat(p1 INT)
       BEGIN
          SET @x = 0;
          REPEAT SET @x = @x + 1; UNTIL @x > p1 END REPEAT;
       END
//
SQL
```

```bash
% dolt sql -q "call dorepeat(1)"
panic: unresolved column is a placeholder node, but Eval was called

goroutine 1 [running]:
github.com/dolthub/go-mysql-server/sql/expression.(*UnresolvedColumn).Eval(0xc0007e7900, 0xc00181eb08?, {0x0?, 0x2?, 0x0?})
        /c/Users/zachmu/liquidata/go-workspace/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230215204931-638b126c00f4/sql/expression/unresolved.go:91 +0x27
github.com/dolthub/go-mysql-server/sql/expression.(*comparison).evalLeftAndRight(0xc000554160, 0xc00181eb28?, {0x0, 0x0, 0x0})
        /c/Users/zachmu/liquidata/go-workspace/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230215204931-638b126c00f4/sql/expression/comparison.go:144 +0x42
github.com/dolthub/go-mysql-server/sql/expression.(*comparison).Compare(0xc000554160, 0xc0001b94c0?, {0x0?, 0x0?, 0x40c7b5?})
        /c/Users/zachmu/liquidata/go-workspace/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230215204931-638b126c00f4/sql/expression/comparison.go:78 +0x3b
github.com/dolthub/go-mysql-server/sql/expression.(*GreaterThan).Eval(0x0?, 0xc00181ec18?, {0x0?, 0xc0001b94c0?, 0x0?})
        /c/Users/zachmu/liquidata/go-workspace/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230215204931-638b126c00f4/sql/expression/comparison.go:519 +0x25
github.com/dolthub/go-mysql-server/sql/expression.(*Not).Eval(0x0?, 0x1?, {0x0?, 0xc0001b86d0?, 0xc0001b94c0?})
        /c/Users/zachmu/liquidata/go-workspace/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230215204931-638b126c00f4/sql/expression/boolean.go:41 +0x2a
github.com/dolthub/go-mysql-server/sql/plan.(*loopIter).Next(0xc000b9d3b0, 0xc000014e08?)
        /c/Users/zachmu/liquidata/go-workspace/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230215204931-638b126c00f4/sql/plan/loop.go:176 +0x62
github.com/dolthub/go-mysql-server/sql/plan.(*Block).RowIter.func1(0xc0007e7900, 0xc00181edd0, {0x0, 0x0, 0x0}, 0xc00181ed8f, 0xc00181ede0, 0xc00181edf0, 0xc00181ee08)
        /c/Users/zachmu/liquidata/go-workspace/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230215204931-638b126c00f4/sql/plan/block.go:157 +0x32d
github.com/dolthub/go-mysql-server/sql/plan.(*Block).RowIter(0xc001689d40, 0x7fdeacbc0108?, {0x0, 0x0, 0x0})
        /c/Users/zachmu/liquidata/go-workspace/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230215204931-638b126c00f4/sql/plan/block.go:177 +0x28b
github.com/dolthub/go-mysql-server/sql/plan.(*BeginEndBlock).RowIter(0xc0005541a0, 0xc000553078?, {0x0, 0x0, 0x0})
        /c/Users/zachmu/liquidata/go-workspace/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230215204931-638b126c00f4/sql/plan/begin_end_block.go:116 +0x11d
github.com/dolthub/go-mysql-server/sql/plan.(*Procedure).RowIter(...)
        /c/Users/zachmu/liquidata/go-workspace/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230215204931-638b126c00f4/sql/plan/procedure.go:172
github.com/dolthub/go-mysql-server/sql/plan.(*Call).RowIter(0xc0000bfc80, 0xc77054?, {0x0, 0x0, 0x0})
        /c/Users/zachmu/liquidata/go-workspace/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230215204931-638b126c00f4/sql/plan/call.go:182 +0x147
github.com/dolthub/go-mysql-server/sql/plan.(*TransactionCommittingNode).RowIter(0xc00181f028?, 0xc00181f028?, {0x0?, 0x23b4a50?, 0xc0007e7b80?})
```

**Comment by timsehn** [comment]
@Hydrocharged seems you missed this case in your testing.
