### ISSUE TITLE
dolt panic with ON DUPLICATE KEY UPDATE

### ISSUE THREAD

**Issue by PavelSafronov** [dolthub/dolt#5442]
SQL:
```sql
use db;

CREATE TABLE test (
  id int UNIQUE,
  conflict varchar(250)
);

insert into test (id) values (1) ON DUPLICATE KEY UPDATE conflict = 'conflict-1';
select * from test;

insert into test (id) values (1) ON DUPLICATE KEY UPDATE conflict = 'conflict-2';
select * from test;
```

MySQL execution:
```txt
+------+----------+
| id   | conflict |
+------+----------+
|    1 | NULL     |
+------+----------+
+------+------------+
| id   | conflict   |
+------+------------+
|    1 | conflict-2 |
+------+------------+
```

dolt execution:
```txt
Database changed
Query OK, 1 row affected (0.00 sec)
+----+----------+
| id | conflict |
+----+----------+
| 1  | NULL     |
+----+----------+

panic: interface conversion: interface {} is int32, not string

goroutine 1 [running]:
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.PutField({0x104439c28, 0x14000a664d0}, {0x104442400, 0x14000164140}, 0x14000f2fb80, 0x2, {0x104064720?, 0x1052f7d68})
        github.com/dolthub/dolt/go/libraries/doltcore/sqle/index/prolly_fields.go:177 +0x173c
github.com/dolthub/dolt/go/libraries/doltcore/sqle/writer.prollyKeylessWriter.tuplesFromRow({{0x0, 0x0}, 0x14000f67200, 0x14000f2fb00, 0x14000f2fb80, {0x14000f68480, 0x2, 0x2}}, {0x104439c28, 0x14000a664d0}, ...)
        github.com/dolthub/dolt/go/libraries/doltcore/sqle/writer/prolly_index_writer_keyless.go:140 +0x138
github.com/dolthub/dolt/go/libraries/doltcore/sqle/writer.prollyKeylessSecondaryWriter.Delete({{0x14000dc0cf8, 0x2}, 0x14000f67440, {{0x0, 0x0}, 0x14000f67200, 0x14000f2fb00, 0x14000f2fb80, {0x14000f68480, 0x2, ...}}, ...}, ...)
        github.com/dolthub/dolt/go/libraries/doltcore/sqle/writer/prolly_index_writer_keyless.go:298 +0x80
github.com/dolthub/dolt/go/libraries/doltcore/sqle/writer.prollyKeylessSecondaryWriter.Update({{0x14000dc0cf8, 0x2}, 0x14000f67440, {{0x0, 0x0}, 0x14000f67200, 0x14000f2fb00, 0x14000f2fb80, {0x14000f68480, 0x2, ...}}, ...}, ...)
        github.com/dolthub/dolt/go/libraries/doltcore/sqle/writer/prolly_index_writer_keyless.go:333 +0x5c
github.com/dolthub/dolt/go/libraries/doltcore/sqle/writer.(*prollyTableWriter).Update(0x14000f2ab40, 0x14000a664d0?, {0x14000f6c4e0, 0x2, 0x2}, {0x14000f6c520, 0x2, 0x2})
        github.com/dolthub/dolt/go/libraries/doltcore/sqle/writer/prolly_table_writer.go:176 +0xbc
github.com/dolthub/go-mysql-server/sql/plan.(*insertIter).handleOnDuplicateKeyUpdate(0x14000f25930, 0x104423ec0?, {0x14000f6c4a0, 0x2, 0x2}, {0x14000f6c4e0, 0x2, 0x2})
        github.com/dolthub/go-mysql-server@v0.14.1-0.20230224003957-abbe846042ce/sql/plan/insert.go:467 +0x2fc
github.com/dolthub/go-mysql-server/sql/plan.(*insertIter).Next(0x14000f25930, 0x103416b38?)
        github.com/dolthub/go-mysql-server@v0.14.1-0.20230224003957-abbe846042ce/sql/plan/insert.go:427 +0x7fc
github.com/dolthub/go-mysql-server/sql/plan.(*tableEditorIter).Next(0x14000f56a00, 0x14000a664d0)
        github.com/dolthub/go-mysql-server@v0.14.1-0.20230224003957-abbe846042ce/sql/plan/table_editor.go:51 +0x70
github.com/dolthub/go-mysql-server/sql/plan.(*accumulatorIter).Next(0x14000f746f0, 0x14000a664d0)
        github.com/dolthub/go-mysql-server@v0.14.1-0.20230224003957-abbe846042ce/sql/plan/row_update_accumulator.go:330 +0x164
github.com/dolthub/go-mysql-server/sql/plan.transactionCommittingIter.Next(...)
        github.com/dolthub/go-mysql-server@v0.14.1-0.20230224003957-abbe846042ce/sql/plan/transaction_committing_iter.go:112
github.com/dolthub/go-mysql-server/sql/plan.(*trackedRowIter).Next(0x14000f553b0, 0x0?)
        github.com/dolthub/go-mysql-server@v0.14.1-0.20230224003957-abbe846042ce/sql/plan/process.go:381 +0x30
github.com/dolthub/dolt/go/cmd/dolt/commands/engine.printOKResult(0x1053d2c48?, {0x10442c0e8?, 0x14000f553b0?}, {0x1053d2c48?, 0x1400129b168?, 0x1054332e0?})
        github.com/dolthub/dolt/go/cmd/dolt/commands/engine/sql_print.go:195 +0x44
github.com/dolthub/dolt/go/cmd/dolt/commands/engine.prettyPrintResultsWithSummary(0x14000a664d0, 0x0, {0x1053d2c48?, 0x1, 0x1}, {0x10442c0e8, 0x14000f553b0}, 0x0)
        github.com/dolthub/dolt/go/cmd/dolt/commands/engine/sql_print.go:75 +0x33c
github.com/dolthub/dolt/go/cmd/dolt/commands/engine.PrettyPrintResults(...)
        github.com/dolthub/dolt/go/cmd/dolt/commands/engine/sql_print.go:55
github.com/dolthub/dolt/go/cmd/dolt/commands.runMultiStatementMode(0x14000a664d0, 0x140001bafc0, {0x104424760?, 0x140000fa340}, 0x0)
        github.com/dolthub/dolt/go/cmd/dolt/commands/sql.go:843 +0x480
github.com/dolthub/dolt/go/cmd/dolt/commands.execMultiStatements({0x104439480, 0x1400002a810}, 0x1e?, 0x8?, {0x104424760, 0x140000fa340}, 0x1?, 0x1400129b6f8)
        github.com/dolthub/dolt/go/cmd/dolt/commands/sql.go:587 +0x168
github.com/dolthub/dolt/go/cmd/dolt/commands.queryMode({0x104439480, 0x1400002a810}, 0x1039ff8ec?, 0x5?, 0x140001150e0, {0x16d86753c, 0x116}, 0xa0?, 0x1400129b478?, 0x1400129b6f8)
        github.com/dolthub/dolt/go/cmd/dolt/commands/sql.go:451 +0x1e8
github.com/dolthub/dolt/go/cmd/dolt/commands.SqlCmd.Exec({{0x1039fffcd?, 0x103547094?}}, {0x104439480, 0x1400002a810}, {0x1400011e7f0, 0x8}, {0x1400012e060, 0x2, 0x2}, 0x1400018e1b0)
        github.com/dolthub/dolt/go/cmd/dolt/commands/sql.go:304 +0xea4
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.handleCommand({{0x1039fde4d, 0x4}, {0x103a18808, 0x11}, {0x0, 0x0}, {0x105411820, 0x2f, 0x2f}, 0x0}, ...)
        github.com/dolthub/dolt/go/cmd/dolt/cli/command.go:237 +0x42c
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.Exec({{0x1039fde4d, 0x4}, {0x103a18808, 0x11}, {0x0, 0x0}, {0x105411820, 0x2f, 0x2f}, 0x0}, ...)
        github.com/dolthub/dolt/go/cmd/dolt/cli/command.go:186 +0x248
main.runMain()
        github.com/dolthub/dolt/go/cmd/dolt/dolt.go:393 +0x6b0
main.main()
        github.com/dolthub/dolt/go/cmd/dolt/dolt.go:139 +0x1c
```

**Comment by JCOR11599** [comment]
fix for this is merged in, it will no longer panic
