### ISSUE TITLE
Panics while executing queries

### ISSUE THREAD

**Issue by macneale4** [dolthub/dolt#5656]
A couple examples of crashing the server being too easy with SQL. May be two different root causes, but both result in panics.

Setup:
```sql
CREATE TABLE t (a int NOT NULL PRIMARY KEY);
INSERT INTO t VALUES (34),(42),(77);
```

Fail 1:
```
$ dolt sql -q 'UPDATE t SET a = IF(SUM(*) % 2 = 0, 42, a)'
panic: star is just a placeholder node, but Type was called

goroutine 1 [running]:
github.com/dolthub/go-mysql-server/sql/expression.(*Star).Type(0x14000e09401)
        /Users/neil/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230323180110-e8b040614c18/sql/expression/star.go:57 +0x2c
github.com/dolthub/go-mysql-server/sql/expression/function/aggregation.(*Sum).Type(0x20?)
        /Users/neil/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230323180110-e8b040614c18/sql/expression/function/aggregation/unary_aggs.og.go:847 +0x28
github.com/dolthub/go-mysql-server/sql/expression.(*Mod).Type(0x140001e1680)
        /Users/neil/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230323180110-e8b040614c18/sql/expression/mod.go:80 +0x64
github.com/dolthub/go-mysql-server/sql/analyzer.validateOperands.func1.1({0x10649e860, 0x14000e08da0})
...
```

Fail 2:
```
$ dolt sql -q 'UPDATE t SET a = IF(ROW_NUMBER() OVER() % 2 = 0, 42, a)'
panic: eval called on window function

goroutine 1 [running]:
github.com/dolthub/go-mysql-server/sql/expression/function/aggregation/window.(*RowNumber).Eval(0x1?, 0x0?, {0x140011a6ab8?, 0x103ecb0fc?, 0x104e27f40?})
        /Users/neil/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230323180110-e8b040614c18/sql/expression/function/aggregation/window/row_number.go:90 +0x2c
github.com/dolthub/go-mysql-server/sql/expression.(*Mod).evalLeftRight(0x14000029260, 0x14000050aa0?, {0x14000660f20, 0x1, 0x1})
        /Users/neil/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230323180110-e8b040614c18/sql/expression/mod.go:123 +0x40
github.com/dolthub/go-mysql-server/sql/expression.(*Mod).Eval(0x105e9c120?, 0x2?, {0x14000660f20?, 0x1?, 0x140011a6a88?})
        /Users/neil/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230323180110-e8b040614c18/sql/expression/mod.go:104 +0x28
github.com/dolthub/go-mysql-server/sql/expression.(*comparison).evalLeftAndRight(0x14000666b80, 0x102f5d8dc?, {0x14000660f20, 0x1, 0x1})
```

**Comment by nicktobey** [comment]
So while these are syntactically valid SQL commands, they aren't semantically meaningful: you can't call aggregate functions like SUM or window functions like ROW_NUMBER inside an UPDATE statement.

Preumably the parser doesn't know whether SUM and ROW_NUMBER are aggregate/window functions, so the detection gets deferred until query execution, when the function names are resolved.

A server panic isn't very desirable though: we should prefer cleanly aborting with a useful error message.

Bonus points: we could suggest the correct statement to the user. Despite these commands being semantically invalid, the intent is clear, and the issue can be worked around with a sub-select and JOIN, so for the second one something like

```
UPDATE t JOIN
(
    SELECT a, IF(row_number() over() % 2 = 0, 42, a) AS new_value
    FROM t
) as temp_table on t.a = temp_table.a
SET t.a = temp_table.new_value;
```

or equivalently

```
UPDATE t JOIN
(
    SELECT a, row_number() over() AS new_value
    FROM t
) as temp_table on t.a = temp_table.a
SET t.a = IF(temp_table.new_value % 2 = 0, 42, a);
```

There's probably a more readable/succinct way to word the command though.

**Comment by timsehn** [comment]
Nick fixed this!
