### ISSUE TITLE
Crash when trying column change

### ISSUE THREAD

**Issue by alecstein** [dolthub/dolt#5689]
On Macbook Pro M1.

Checkout this repo at this commit hash:

repo: https://www.dolthub.com/repositories/dolthub/transparency-in-pricing/commits/main
hash: vlfom9bssiq4ud1ainkf5sccvd994cgs

Run `dolt sql`:

`> transparency_in_pricing> alter table rates change column quantity quantity_desc varchar(20);`

You get

```
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/dolthub/dolt/go/libraries/doltcore/schema.(*ColCollection).GetByIndex(...)
	/src/libraries/doltcore/schema/col_coll.go:225
github.com/dolthub/dolt/go/libraries/doltcore/schema.(*schemaImpl).SetPkOrdinals(0x14000ccbbc0, {0x14000f8ce70?, 0x0?, 0x0?})
	/src/libraries/doltcore/schema/schema_impl.go:301 +0x2f4
github.com/dolthub/dolt/go/libraries/doltcore/schema.NewSchema(0x140000fe000?, {0x14000f8ce70, 0xd, 0xd}, 0x5?, {0x0?, 0x0}, {0x0?, 0x0})
	/src/libraries/doltcore/schema/schema_impl.go:63 +0x70
github.com/dolthub/dolt/go/libraries/doltcore/sqle/sqlutil.ToDoltSchema({0x1029a45c0, 0x14000cd6000}, 0x1406ffae534?, {0x140006a13c0, 0x5}, {{0x14004e11560, 0x24, 0x24}, {0x14000f8ce70, 0xd, ...}}, ...)
	/src/libraries/doltcore/sqle/sqlutil/convert.go:112 +0x4a8
github.com/dolthub/dolt/go/libraries/doltcore/sqle.(*AlterableDoltTable).getNewSch(0x14000cd6140, {0x1029a45c0, 0x14000cd6000}, 0x14004e1a980, 0x14000598400, {0x1029bfea0, 0x14000ccb8c0}, {{0x14004e11560, 0x24, 0x24}, ...}, ...)
	/src/libraries/doltcore/sqle/tables.go:1520 +0x264
github.com/dolthub/dolt/go/libraries/doltcore/sqle.(*AlterableDoltTable).RewriteInserter(0x14000cd6140, 0x14000cd6000, {{0x1400047f9e0, 0x24, 0x24}, {0x14000f8ce00, 0xd, 0xd}}, {{0x14004e11560, 0x24, ...}, ...}, ...)
	/src/libraries/doltcore/sqle/tables.go:1372 +0x220
github.com/dolthub/go-mysql-server/sql/plan.(*modifyColumnIter).rewriteTable(0x140002d6500, 0x12bbff798?, {0x12bbff988?, 0x14000cd6140})
	/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20221214210115-e28aad108618/sql/plan/alter_table.go:1361 +0x45c
github.com/dolthub/go-mysql-server/sql/plan.(*modifyColumnIter).Next(0x140002d6500, 0x100bfa0e0?)
	/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20221214210115-e28aad108618/sql/plan/alter_table.go:1298 +0x6c0
github.com/dolthub/go-mysql-server/sql/plan.transactionCommittingIter.Next(...)
	/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20221214210115-e28aad108618/sql/plan/transaction_committing_iter.go:107
github.com/dolthub/go-mysql-server/sql/plan.(*trackedRowIter).Next(0x14000210dc0, 0x102996818?)
	/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20221214210115-e28aad108618/sql/plan/process.go:381 +0x30
github.com/dolthub/go-mysql-server/sql.RowIterToRows(0x140002b6c38?, {0x0, 0x0, 0x0}, {0x102996818, 0x14000210dc0})
	/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20221214210115-e28aad108618/sql/row.go:115 +0xf4
github.com/dolthub/dolt/go/cmd/dolt/commands.processParsedQuery(0x140006a63c0?, {0x140006a63c0?, 0x140002b6ce8?}, 0x101f5f2d0?, {0x102996fc0?, 0x14000406e40?})
	/src/cmd/dolt/commands/sql.go:1222 +0x3dc
github.com/dolthub/dolt/go/cmd/dolt/commands.processQuery(0x1029a4e10?, {0x140006a63c0, 0x42}, 0x2?)
	/src/cmd/dolt/commands/sql.go:1198 +0xc8
github.com/dolthub/dolt/go/cmd/dolt/commands.runShell.func3.1({0x1029a3d70, 0x14000592ab0}, 0x14000aaa690, 0x14000156848, 0x1400095aec0, 0x140003d03c0, {0x140006a63c0, 0x42}, 0x140002b6f00, 0x140002b6ec0, ...)
	/src/cmd/dolt/commands/sql.go:1039 +0x234
github.com/dolthub/dolt/go/cmd/dolt/commands.runShell.func3(0x140003d03c0?)
	/src/cmd/dolt/commands/sql.go:1057 +0x3a0
github.com/dolthub/ishell.handleUninterpretedInput(0x140003d03c0, {0x140006a63c0, 0x43})
	/go/pkg/mod/github.com/dolthub/ishell@v0.0.0-20220112232610-14e753f0f371/ishell.go:288 +0x130
github.com/dolthub/ishell.(*Shell).run(0x140003d03c0)
	/go/pkg/mod/github.com/dolthub/ishell@v0.0.0-20220112232610-14e753f0f371/ishell.go:245 +0x30c
github.com/dolthub/ishell.(*Shell).Run(0x140003d03c0?)
	/go/pkg/mod/github.com/dolthub/ishell@v0.0.0-20220112232610-14e753f0f371/ishell.go:139 +0x28
github.com/dolthub/dolt/go/cmd/dolt/commands.runShell({0x1029a3d70?, 0x14000592ab0}, 0x14000aaa690, 0x100cd9500?, 0x140002b7708)
	/src/cmd/dolt/commands/sql.go:1067 +0x728
github.com/dolthub/dolt/go/cmd/dolt/commands.execShell({0x1029a3d70, 0x14000592ab0}, 0x10200f261?, 0x4?, 0x103919ae0?)
	/src/cmd/dolt/commands/sql.go:500 +0x78
github.com/dolthub/dolt/go/cmd/dolt/commands.SqlCmd.Exec({{0x102013274?, 0x101b7525c?}}, {0x1029a3d70, 0x14000592ab0}, {0x140006a0fd8, 0x8}, {0x1400004c050, 0x0, 0x0}, 0x140003f3290)
	/src/cmd/dolt/commands/sql.go:343 +0xdf8
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.handleCommand({{0x10200f1dd, 0x4}, {0x102029626, 0x11}, {0x0, 0x0}, {0x140001a2900, 0x2f, 0x2f}, 0x0}, ...)
	/src/cmd/dolt/cli/command.go:237 +0x450
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.Exec({{0x10200f1dd, 0x4}, {0x102029626, 0x11}, {0x0, 0x0}, {0x140001a2900, 0x2f, 0x2f}, 0x0}, ...)
	/src/cmd/dolt/cli/command.go:186 +0x390
main.runMain()
	/src/cmd/dolt/dolt.go:393 +0x6dc
main.main()
	/src/cmd/dolt/dolt.go:139 +0x1c
```

**Comment by PavelSafronov** [comment]
Minimal repro:
```sql
use db;

CREATE TABLE rates (
  filename varchar(200), 
  quantity varchar(50), 
  PRIMARY KEY (
    filename, quantity
  )
);

alter table rates change column quantity quantity_desc varchar(20);
```

This works in MySQL, and the table seems to be updated correctly:
```sql
show create table rates;
```

```txt
Table   Create Table
rates   CREATE TABLE `rates` (
  `filename` varchar(200) NOT NULL,
  `quantity_desc` varchar(20) NOT NULL,
  PRIMARY KEY (`filename`,`quantity_desc`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
```

**Comment by alecstein** [comment]
I get the same error trying a different change command:

```
transparency_in_pricing> alter table rates CHANGE COLUMN code_type code_meta ENUM('drg', 'eap', 'erx', 'sup') COLLATE utf8mb4_general_ci;
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/dolthub/dolt/go/libraries/doltcore/schema.(*ColCollection).GetByIndex(...)
	/src/libraries/doltcore/schema/col_coll.go:225
github.com/dolthub/dolt/go/libraries/doltcore/schema.(*schemaImpl).SetPkOrdinals(0x14000699440, {0x14000652ee0?, 0x0?, 0x0?})
	/src/libraries/doltcore/schema/schema_impl.go:301 +0x2f4
github.com/dolthub/dolt/go/libraries/doltcore/schema.NewSchema(0x140000fe150?, {0x14000652ee0, 0xd, 0xd}, 0x5?, {0x0?, 0x0}, {0x0?, 0x0})
	/src/libraries/doltcore/schema/schema_impl.go:63 +0x70
github.com/dolthub/dolt/go/libraries/doltcore/sqle/sqlutil.ToDoltSchema({0x10435c5c0, 0x14000d74000}, 0x140fd721c9a?, {0x140004099b0, 0x5}, {{0x140003c9a40, 0x26, 0x26}, {0x14000652ee0, 0xd, ...}}, ...)
	/src/libraries/doltcore/sqle/sqlutil/convert.go:112 +0x4a8
github.com/dolthub/dolt/go/libraries/doltcore/sqle.(*AlterableDoltTable).getNewSch(0x14000d74140, {0x10435c5c0, 0x14000d74000}, 0x1400554ac80, 0x140000ecd80, {0x104377ea0, 0x14000699140}, {{0x140003c9a40, 0x26, 0x26}, ...}, ...)
	/src/libraries/doltcore/sqle/tables.go:1520 +0x264
github.com/dolthub/dolt/go/libraries/doltcore/sqle.(*AlterableDoltTable).RewriteInserter(0x14000d74140, 0x14000d74000, {{0x140003c8500, 0x26, 0x26}, {0x14000652e70, 0xd, 0xd}}, {{0x140003c9a40, 0x26, ...}, ...}, ...)
	/src/libraries/doltcore/sqle/tables.go:1372 +0x220
github.com/dolthub/go-mysql-server/sql/plan.(*modifyColumnIter).rewriteTable(0x1400554c260, 0x12b5a5830?, {0x12b5a5a20?, 0x14000d74140})
	/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20221214210115-e28aad108618/sql/plan/alter_table.go:1361 +0x45c
github.com/dolthub/go-mysql-server/sql/plan.(*modifyColumnIter).Next(0x1400554c260, 0x1025b20e0?)
	/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20221214210115-e28aad108618/sql/plan/alter_table.go:1298 +0x6c0
github.com/dolthub/go-mysql-server/sql/plan.transactionCommittingIter.Next(...)
	/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20221214210115-e28aad108618/sql/plan/transaction_committing_iter.go:107
github.com/dolthub/go-mysql-server/sql/plan.(*trackedRowIter).Next(0x1400550c6e0, 0x10434e818?)
	/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20221214210115-e28aad108618/sql/plan/process.go:381 +0x30
github.com/dolthub/go-mysql-server/sql.RowIterToRows(0x14000ef0c38?, {0x0, 0x0, 0x0}, {0x10434e818, 0x1400550c6e0})
	/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20221214210115-e28aad108618/sql/row.go:115 +0xf4
github.com/dolthub/dolt/go/cmd/dolt/commands.processParsedQuery(0x140000f0f50?, {0x140000f0f50?, 0x14000ef0ce8?}, 0x1039172d0?, {0x10434efc0?, 0x14000d76080?})
	/src/cmd/dolt/commands/sql.go:1222 +0x3dc
github.com/dolthub/dolt/go/cmd/dolt/commands.processQuery(0x10435ce10?, {0x140000f0f50, 0x6f}, 0x2?)
	/src/cmd/dolt/commands/sql.go:1198 +0xc8
github.com/dolthub/dolt/go/cmd/dolt/commands.runShell.func3.1({0x10435bd70, 0x140002dedb0}, 0x14000a76060, 0x14000e849e0, 0x1400007fd50, 0x14000638000, {0x140000f0f50, 0x6f}, 0x14000ef0f00, 0x14000ef0ec0, ...)
	/src/cmd/dolt/commands/sql.go:1039 +0x234
github.com/dolthub/dolt/go/cmd/dolt/commands.runShell.func3(0x14000638000?)
	/src/cmd/dolt/commands/sql.go:1057 +0x3a0
github.com/dolthub/ishell.handleUninterpretedInput(0x14000638000, {0x140000f0f50, 0x70})
	/go/pkg/mod/github.com/dolthub/ishell@v0.0.0-20220112232610-14e753f0f371/ishell.go:288 +0x130
github.com/dolthub/ishell.(*Shell).run(0x14000638000)
	/go/pkg/mod/github.com/dolthub/ishell@v0.0.0-20220112232610-14e753f0f371/ishell.go:245 +0x30c
github.com/dolthub/ishell.(*Shell).Run(0x14000638000?)
	/go/pkg/mod/github.com/dolthub/ishell@v0.0.0-20220112232610-14e753f0f371/ishell.go:139 +0x28
github.com/dolthub/dolt/go/cmd/dolt/commands.runShell({0x10435bd70?, 0x140002dedb0}, 0x14000a76060, 0x102691500?, 0x14000ef1708)
	/src/cmd/dolt/commands/sql.go:1067 +0x728
github.com/dolthub/dolt/go/cmd/dolt/commands.execShell({0x10435bd70, 0x140002dedb0}, 0x1039c7261?, 0x4?, 0x1052d1ae0?)
	/src/cmd/dolt/commands/sql.go:500 +0x78
github.com/dolthub/dolt/go/cmd/dolt/commands.SqlCmd.Exec({{0x1039cb274?, 0x10352d25c?}}, {0x10435bd70, 0x140002dedb0}, {0x14000663488, 0x8}, {0x1400004c030, 0x0, 0x0}, 0x140003eb4d0)
	/src/cmd/dolt/commands/sql.go:343 +0xdf8
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.handleCommand({{0x1039c71dd, 0x4}, {0x1039e1626, 0x11}, {0x0, 0x0}, {0x1400019a900, 0x2f, 0x2f}, 0x0}, ...)
	/src/cmd/dolt/cli/command.go:237 +0x450
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.Exec({{0x1039c71dd, 0x4}, {0x1039e1626, 0x11}, {0x0, 0x0}, {0x1400019a900, 0x2f, 0x2f}, 0x0}, ...)
	/src/cmd/dolt/cli/command.go:186 +0x390
main.runMain()
	/src/cmd/dolt/dolt.go:393 +0x6dc
main.main()
	/src/cmd/dolt/dolt.go:139 +0x1c
```

**Comment by alecstein** [comment]
The workaround is to do a RENAME followed by a MODIFY.
