### ISSUE TITLE
dolt panic on SUM(*)

### ISSUE THREAD

**Issue by max-hoffman** [dolthub/dolt#5703]
`SUM(*)` is not a valid aggregation, even over single column sources, but we still should not panic:
```sql
select sum(*) from (select x from xy);
panic: star is just a placeholder node, but Type was called

goroutine 1 [running]:
github.com/dolthub/go-mysql-server/sql/expression.(*Star).Type(0xc00140e3e0)
	/Users/max-hoffman/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230404162646-66af813a4f2b/sql/expression/star.go:60 +0x27
github.com/dolthub/go-mysql-server/sql/expression/function/aggregation.(*Sum).Type(0x293cee0?)
	/Users/max-hoffman/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230404162646-66af813a4f2b/sql/expression/function/aggregation/unary_aggs.og.go:859 +0x22
github.com/dolthub/go-mysql-server/sql/analyzer.replaceAggregatesWithGetFieldProjections.func1({0x30490c0?, 0xc001239f90})
	/Users/max-hoffman/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230404162646-66af813a4f2b/sql/analyzer/aggregations.go:100 +0x194
github.com/dolthub/go-mysql-server/sql/transform.Expr({0x30490c0, 0xc001239f90}, 0xc00140e390)
	/Users/max-hoffman/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230404162646-66af813a4f2b/sql/transform/expr.go:63 +0x1b5
github.com/dolthub/go-mysql-server/sql/transform.Expr({0x3045920, 0xc000053580}, 0xc00140e390)
	/Users/max-hoffman/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230404162646-66af813a4f2b/sql/transform/expr.go:41 +0xb9
github.com/dolthub/go-mysql-server/sql/analyzer.replaceAggregatesWithGetFieldProjections(0xc0005acc48?, 0xc00140e4e0?, {0xc0011128d0, 0x1, 0xc000053580?})
	/Users/max-hoffman/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230404162646-66af813a4f2b/sql/analyzer/aggregations.go:94 +0x1b1
github.com/dolthub/go-mysql-server/sql/analyzer.flattenedGroupBy(0xc001104b00?, 0x100f347?, {0xc0011128d0?, 0x288c480?, 0x2a37a01?}, {0x42a52a8, 0x0, 0x0}, {0x304c220, 0xc001104b00})
	/Users/max-hoffman/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230404162646-66af813a4f2b/sql/analyzer/aggregations.go:60 +0x3d
github.com/dolthub/go-mysql-server/sql/analyzer.flattenAggregationExpressions.func1({0x304b5f0?, 0xc001104b40?})
	/Users/max-hoffman/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230404162646-66af813a4f2b/sql/analyzer/aggregations.go:52 +0xc5
github.com/dolthub/go-mysql-server/sql/transform.Node({0x304b5f0, 0xc001104b40}, 0xc00140e658)
	/Users/max-hoffman/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230404162646-66af813a4f2b/sql/transform/node.go:353 +0x212
github.com/dolthub/go-mysql-server/sql/analyzer.flattenAggregationExpressions(0xc001245900?, 0x2c53e24?, {0x304b5f0, 0xc001104b40}, 0x0, 0x0?)
	/Users/max-hoffman/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230404162646-66af813a4f2b/sql/analyzer/aggregations.go:39 +0x12e
github.com/dolthub/go-mysql-server/sql/analyzer.(*Batch).evalOnce(0x304b5f0?, 0xc001104680?, 0xc00124af00, {0x304b5f0?, 0xc001104880?}, 0x287da00?, 0x2cffc20)
	/Users/max-hoffman/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230404162646-66af813a4f2b/sql/analyzer/batch.go:121 +0x248
github.com/dolthub/go-mysql-server/sql/analyzer.(*Batch).EvalWithSelector(0xc0005a1470, 0x2c8684b?, 0xc00124af00, {0x304b5f0, 0xc001104880}, 0x0?, 0x7668e545c647ad43?)
	/Users/max-hoffman/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230404162646-66af813a4f2b/sql/analyzer/batch.go:65 +0x171
github.com/dolthub/go-mysql-server/sql/analyzer.(*Batch).Eval(...)
	/Users/max-hoffman/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230404162646-66af813a4f2b/sql/analyzer/batch.go:56
github.com/dolthub/go-mysql-server/sql/analyzer.(*Analyzer).analyzeWithSelector(0xc00124af00?, 0x304b5f0?, {0x304b5f0?, 0xc001104680?}, 0x0?, 0x2cffc28?, 0x3033b50?)
	/Users/max-hoffman/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230404162646-66af813a4f2b/sql/analyzer/analyzer.go:613 +0x3c5
github.com/dolthub/go-mysql-server/sql/analyzer.(*Analyzer).Analyze(...)
	/Users/max-hoffman/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230404162646-66af813a4f2b/sql/analyzer/analyzer.go:454
github.com/dolthub/go-mysql-server.(*Engine).analyzeQuery(0xc0012399f0, 0xc001245900, {0xc0012c01e0?, 0x21?}, {0x304b5f0?, 0xc001104680?}, 0x0)
	/Users/max-hoffman/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230404162646-66af813a4f2b/engine.go:444 +0x6d7
github.com/dolthub/go-mysql-server.(*Engine).QueryNodeWithBindings(0xc0012399f0, 0xc001245900, {0xc0012c01e0, 0x21}, {0x0?, 0x0?}, 0xc000580000?)
	/Users/max-hoffman/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230404162646-66af813a4f2b/engine.go:261 +0x1e8
```

**Comment by timsehn** [comment]
Resolving in favor of #5656
