### ISSUE TITLE
Dolt panics on a chained alter of adding a column and adding a unique key to the same column

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#5786]
Repro:
```
$ mkdir test_chained_alters
$ dolt init --fun
Successfully initialized dolt data repository.
$ dolt sql -q "create table t (c1 int primary key, c2 int, c3 int)"
$ dolt sql -q "alter table t add column c4 int null, add unique index uniq(c4)"
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/dolthub/dolt/go/libraries/doltcore/sqle.validateSchemaChange({0x4150d20, 0x1}, {{0xc0006d9ce0, 0x3, 0x3}, {0xc04b46c230, 0x1, 0x1}}, {{0xc0006d9ce0, 0x3, ...}, ...}, ...)
	/Users/timsehn/dolthub/git/dolt/go/libraries/doltcore/sqle/tables.go:1495 +0x332
github.com/dolthub/dolt/go/libraries/doltcore/sqle.(*AlterableDoltTable).RewriteInserter(0xc000735760, 0xc000c354a0, {{0xc0006d9ce0, 0x3, 0x3}, {0xc04b46c230, 0x1, 0x1}}, {{0xc0006d9ce0, 0x3, ...}, ...}, ...)
	/Users/timsehn/dolthub/git/dolt/go/libraries/doltcore/sqle/tables.go:1243 +0x139
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).executeAlterIndex(0xc000ec47b0?, 0xc000c354a0, 0xc0002861e0)
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.15.1-0.20230419220841-24dded8c61ef/sql/rowexec/ddl_iters.go:1777 +0xbf3
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildAlterIndex(0x0?, 0x203000?, 0x203000?, {0x0?, 0x8?, 0xc04b1ff0e0?})
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.15.1-0.20230419220841-24dded8c61ef/sql/rowexec/dml.go:252 +0x1d
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildNodeExec(0xc04b281e00?, 0xc04b3c3fb0?, {0x3069e88?, 0xc0002861e0?}, {0x0?, 0x0, 0x0})
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.15.1-0.20230419220841-24dded8c61ef/sql/rowexec/node_builder.gen.go:211 +0x1929
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildBlock.func1(0xc000c354a0, 0xc000ec4b00?, 0xc000ec4b18, {0x0, 0x0, 0x0}, 0xc000ec4acf, 0xc000ec4b28, 0xc000ec4b38, 0xc000ec4b50)
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.15.1-0.20230419220841-24dded8c61ef/sql/rowexec/other.go:258 +0xf0
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildBlock(0x2b4af00?, 0xc04b3c01b0?, 0xc04b3c0c00, {0x0, 0x0, 0x0})
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.15.1-0.20230419220841-24dded8c61ef/sql/rowexec/other.go:298 +0x2b2
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildNodeExec(0x3069ff0?, 0x1?, {0x3069ff0?, 0xc04b3c0c00?}, {0x0?, 0x0, 0x0})
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.15.1-0.20230419220841-24dded8c61ef/sql/rowexec/node_builder.gen.go:189 +0x165a
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).Build(...)
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.15.1-0.20230419220841-24dded8c61ef/sql/rowexec/builder.go:33
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildTransactionCommittingNode(0x0?, 0x0?, 0x2c6570c?, {0x0?, 0x1?, 0x1?})
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.15.1-0.20230419220841-24dded8c61ef/sql/rowexec/transaction.go:312 +0x3b
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildNodeExec(0x3069ff0?, 0x3069ff0?, {0x306c798?, 0xc04b3c3c00?}, {0x0?, 0x0, 0x0})
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.15.1-0.20230419220841-24dded8c61ef/sql/rowexec/node_builder.gen.go:37 +0x1f1a
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).Build(...)
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.15.1-0.20230419220841-24dded8c61ef/sql/rowexec/builder.go:33
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildQueryProcess(0x98?, 0x2bc0760?, 0xc0001c4168, {0x0?, 0x239782a?, 0xc0001da0f0?})
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.15.1-0.20230419220841-24dded8c61ef/sql/rowexec/other.go:350 +0x45
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildNodeExec(0xa?, 0xc04b1ff190?, {0x306b940?, 0xc0001c4168?}, {0x0?, 0x0, 0x0})
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.15.1-0.20230419220841-24dded8c61ef/sql/rowexec/node_builder.gen.go:43 +0xd8d
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).Build(0xc04b2ca0a0?, 0xc000c354a0?, {0x306b940?, 0xc0001c4168?}, {0x0?, 0xc04b2b9500?, 0x0?})
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.15.1-0.20230419220841-24dded8c61ef/sql/rowexec/builder.go:33 +0x28
github.com/dolthub/go-mysql-server.(*Engine).QueryNodeWithBindings(0xc04b2ca0a0, 0xc000c354a0, {0xc0002bd680, 0x3f}, {0x0?, 0x0?}, 0xc000ec52b8?)
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.15.1-0.20230419220841-24dded8c61ef/engine.go:270 +0x2ae
github.com/dolthub/go-mysql-server.(*Engine).QueryWithBindings(...)
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.15.1-0.20230419220841-24dded8c61ef/engine.go:212
github.com/dolthub/go-mysql-server.(*Engine).Query(0xc000ec52c8?, 0x105a8bf?, {0xc0002bd680?, 0xe8?})
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.15.1-0.20230419220841-24dded8c61ef/engine.go:207 +0x26
github.com/dolthub/dolt/go/cmd/dolt/commands/engine.(*SqlEngine).Query(...)
	/Users/timsehn/dolthub/git/dolt/go/cmd/dolt/commands/engine/sqlengine.go:253
github.com/dolthub/dolt/go/cmd/dolt/commands.processParsedQuery(0xc0002bd680?, {0xc0002bd680?, 0x3f?}, 0xc0002bd680?, {0x3054728?, 0xc04b281f00?})
	/Users/timsehn/dolthub/git/dolt/go/cmd/dolt/commands/sql.go:1111 +0x352
github.com/dolthub/dolt/go/cmd/dolt/commands.execMultiStatements(0xc000c354a0, 0xc04b2b8e70, {0x304b800?, 0xc0012cf880}, 0x0)
	/Users/timsehn/dolthub/git/dolt/go/cmd/dolt/commands/sql.go:757 +0x395
github.com/dolthub/dolt/go/cmd/dolt/commands.queryMode(0x295df80?, 0xc0001d39b0?, 0xc0001d39e0, {0x208a66a74, 0x3f}, 0x1069efb?)
	/Users/timsehn/dolthub/git/dolt/go/cmd/dolt/commands/sql.go:463 +0x16a
github.com/dolthub/dolt/go/cmd/dolt/commands.SqlCmd.Exec({{0x2c5ee3b?, 0xc000573800?}}, {0x30616e0, 0xc000561950}, {0xc000c56d58, 0x8}, {0xc00012c020, 0x2, 0x2}, 0xc000479320, ...)
	/Users/timsehn/dolthub/git/dolt/go/cmd/dolt/commands/sql.go:280 +0xadc
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.handleCommand({{0x2c5aca8, 0x4}, {0x2c75cf1, 0x11}, {0x0, 0x0}, {0xc000353180, 0x32, 0x32}, 0x0}, ...)
	/Users/timsehn/dolthub/git/dolt/go/cmd/dolt/cli/command.go:237 +0x4b8
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.Exec({{0x2c5aca8, 0x4}, {0x2c75cf1, 0x11}, {0x0, 0x0}, {0xc000353180, 0x32, 0x32}, 0x0}, ...)
	/Users/timsehn/dolthub/git/dolt/go/cmd/dolt/cli/command.go:186 +0x47e
main.runMain()
	/Users/timsehn/dolthub/git/dolt/go/cmd/dolt/dolt.go:406 +0x80a
main.main()
	/Users/timsehn/dolthub/git/dolt/go/cmd/dolt/dolt.go:144 +0x19
```

The same queries in succession succeed:
```
$ dolt sql -q "alter table t add column c4 int null"                           
$ dolt sql -q "alter table t add unique index uniq(c4)"
$
```

**Comment by JCOR11599** [comment]
Fix for this is merged to main, need one more auto-bump to resolve GMS references
