### ISSUE TITLE
Incorrect output when trying to pull from an empty remote

### ISSUE THREAD

**Issue by oscarbatori** [dolthub/dolt#59]
Attaching to an empty remote and then trying to pull produces an unhelpful error message:
```
[oscarbatori:mta(master)] >> dolt pull origin master
usage: dolt pull <remote>
```

**Comment by oscarbatori** [comment]
This is still not resolved, taking [this](https://www.dolthub.com/repositories/tim/Test) random empty repository as an example:
```
[oscarbatori:dolt(master)] >> dolt clone tim/Test
cloning https://doltremoteapi.dolthub.com/tim/Test
0 of 0 chunks complete. 0 chunks being downloaded currently.
panic: nil commit spec

goroutine 1 [running]:
github.com/liquidata-inc/dolt/go/libraries/doltcore/doltdb.(*DoltDB).Resolve(0xc0006860a0, 0x23e5d00, 0xc0002d0090, 0x0, 0x0, 0x23bd3a0, 0xc00037c8b0)
	/Users/oscarbatori/Documents/dolt/go/libraries/doltcore/doltdb/doltdb.go:261 +0x4bb
github.com/liquidata-inc/dolt/go/cmd/dolt/commands.cloneRemote(0x23e5d00, 0xc0002d0090, 0xc000752000, 0x21317bf, 0x6, 0x0, 0x0, 0xc00033e000, 0x1, 0x1)
	/Users/oscarbatori/Documents/dolt/go/cmd/dolt/commands/clone.go:276 +0x1db
github.com/liquidata-inc/dolt/go/cmd/dolt/commands.Clone(0x23e5d00, 0xc0002d0090, 0xc0002d2020, 0xa, 0xc0000d8050, 0x1, 0x1, 0xc00033e000, 0xa)
	/Users/oscarbatori/Documents/dolt/go/cmd/dolt/commands/clone.go:96 +0xa3f
github.com/liquidata-inc/dolt/go/cmd/dolt/cli.GenSubCommandHandler.func1(0x23e5d00, 0xc0002d0090, 0x212eda7, 0x4, 0xc0000d8040, 0x2, 0x2, 0xc000492150, 0xc0002d0000)
	/Users/oscarbatori/Documents/dolt/go/cmd/dolt/cli/command.go:93 +0x1f7
main.runMain(0x0)
	/Users/oscarbatori/Documents/dolt/go/cmd/dolt/dolt.go:176 +0x9cd
main.main()
	/Users/oscarbatori/Documents/dolt/go/cmd/dolt/dolt.go:84 +0x22
```
