### ISSUE TITLE
`dolt stash --help` causes SIGSEV

### ISSUE THREAD

**Issue by nicktobey** [dolthub/dolt#5920]
```
nick@Nicks-MBP ~ % dolt stash --help
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x28 pc=0x1021a4d20]

goroutine 1 [running]:
github.com/dolthub/dolt/go/libraries/doltcore/doltdb.(*DoltDB).Format(...)
	/Users/nick/Documents/dolt/go/libraries/doltcore/doltdb/doltdb.go:779
github.com/dolthub/dolt/go/cmd/dolt/commands/stashcmds.StashCmd.Exec({}, {0x102c2a0a0, 0x14000e040c0}, {0x14000cd6f70, 0xa}, {0x1400004c080, 0x1, 0x1}, 0x140003e8f30, {0x14000e00001?, ...})
	/Users/nick/Documents/dolt/go/cmd/dolt/commands/stashcmds/stash.go:94 +0x40
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.handleCommand({{0x1021badf5, 0x5}, {0x1022286de, 0x34}, {0x102c33020, 0x103cedf20}, {0x14000677500, 0x4, 0x4}, 0x0}, ...)
	/Users/nick/Documents/dolt/go/cmd/dolt/cli/command.go:244 +0x3fc
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.Exec({{0x1021badf5, 0x5}, {0x1022286de, 0x34}, {0x102c33020, 0x103cedf20}, {0x14000677500, 0x4, 0x4}, 0x0}, ...)
	/Users/nick/Documents/dolt/go/cmd/dolt/cli/command.go:197 +0x3a4
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.handleCommand({{0x1021b903f, 0x4}, {0x1021d42b1, 0x11}, {0x0, 0x0}, {0x103c82ba0, 0x32, 0x32}, 0x0}, ...)
	/Users/nick/Documents/dolt/go/cmd/dolt/cli/command.go:244 +0x3fc
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.Exec({{0x1021b903f, 0x4}, {0x1021d42b1, 0x11}, {0x0, 0x0}, {0x103c82ba0, 0x32, 0x32}, 0x0}, ...)
	/Users/nick/Documents/dolt/go/cmd/dolt/cli/command.go:193 +0x258
main.runMain()
	/Users/nick/Documents/dolt/go/cmd/dolt/dolt.go:457 +0xa5c
main.main()
	/Users/nick/Documents/dolt/go/cmd/dolt/dolt.go:152 +0x1c
```

**Comment by timsehn** [comment]
Does not repro easily so it's something about your environment or build:
```
$ dolt stash --help
NAME
	dolt stash - Stash the changes in a dirty working directory away.

SYNOPSIS
	dolt stash 
	dolt stash list
	dolt stash pop <stash>
	dolt stash clear
	dolt stash drop <stash>

DESCRIPTION
	Use dolt stash when you want to record the current state of the working directory and the index, but want to go back to a clean working directory. 
	
	The command saves your local modifications away and reverts the working directory to match the HEAD commit. The stash entries that are saved away can
	be listed with 'dolt stash list'.
	

OPTIONS
	-u, --include-untracked
	  Untracked tables are also stashed.
	
	-a, --all
	  All tables are stashed, including untracked and ignored tables.
	  
```

**Comment by nicktobey** [comment]
@timsehn 

Turns out this only happens if you run `dolt stash --help` outside of a dolt repo.

**Comment by timsehn** [comment]
Indeed!
```
$ cd ..
$ dolt stash --help
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x279a5aa]

goroutine 1 [running]:
github.com/dolthub/dolt/go/libraries/doltcore/doltdb.(*DoltDB).Format(...)
	/Users/timsehn/dolthub/git/dolt/go/libraries/doltcore/doltdb/doltdb.go:779
github.com/dolthub/dolt/go/cmd/dolt/commands/stashcmds.StashCmd.Exec({}, {0x30a1be0, 0xc001a07fc0}, {0xc0005b8520, 0xa}, {0xc0001941a0, 0x1, 0x1}, 0xc000562120, {0x0, ...})
	/Users/timsehn/dolthub/git/dolt/go/cmd/dolt/commands/stashcmds/stash.go:94 +0x6a
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.handleCommand({{0x2c9a18b, 0x5}, {0x2d06bf7, 0x34}, {0x30ab240, 0x43350e0}, {0xc00074e2c0, 0x4, 0x4}, 0x0}, ...)
	/Users/timsehn/dolthub/git/dolt/go/cmd/dolt/cli/command.go:244 +0x4ec
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.Exec({{0x2c9a18b, 0x5}, {0x2d06bf7, 0x34}, {0x30ab240, 0x43350e0}, {0xc00074e2c0, 0x4, 0x4}, 0x0}, ...)
	/Users/timsehn/dolthub/git/dolt/go/cmd/dolt/cli/command.go:197 +0x2d7
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.handleCommand({{0x2c98431, 0x4}, {0x2cb3242, 0x11}, {0x0, 0x0}, {0x42ceba0, 0x32, 0x32}, 0x0}, ...)
	/Users/timsehn/dolthub/git/dolt/go/cmd/dolt/cli/command.go:244 +0x4ec
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.Exec({{0x2c98431, 0x4}, {0x2cb3242, 0x11}, {0x0, 0x0}, {0x42ceba0, 0x32, 0x32}, 0x0}, ...)
	/Users/timsehn/dolthub/git/dolt/go/cmd/dolt/cli/command.go:193 +0x4b8
main.runMain()
	/Users/timsehn/dolthub/git/dolt/go/cmd/dolt/dolt.go:457 +0xb69
main.main()
	/Users/timsehn/dolthub/git/dolt/go/cmd/dolt/dolt.go:152 +0x19
```
