### ISSUE TITLE
LOAD Data into a table with column defaults panics

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#5983]
Schema and data repro is private. 

Will try for a minimal repro.

```
2023-05-17T18:52:49-07:00 DEBUG [conn 2] Starting query {connectTime=2023-05-17T18:51:04-07:00, connectionDb=test_subra, query=LOAD DATA local infile 'foo.csv' into table foo FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES}
panic: UnresolvedColumnDefault is a placeholder node, but Eval() was called

goroutine 23 [running]:
github.com/dolthub/go-mysql-server/sql.UnresolvedColumnDefault.Eval(...)
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.15.1-0.20230517042856-2405a8d89854/sql/columndefault.go:252
github.com/dolthub/go-mysql-server/sql.(*ColumnDefaultValue).Eval(0xc00012c690, 0xc000274280?, {0xc0004a9b20?, 0x31d78b8?, 0xc000f8fab8?})
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.15.1-0.20230517042856-2405a8d89854/sql/columndefault.go:73 +0x3e
github.com/dolthub/go-mysql-server/sql/rowexec.loadDataIter.Next({0xc00023e000, {0x31f0c50, 0xc00063bb80}, {0x31d78b8, 0xc000f8fab8}, 0x0, {0xc0001feb60, 0xe, 0xe}, {0x437fa60, ...}, ...}, ...)
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.15.1-0.20230517042856-2405a8d89854/sql/rowexec/ddl_iters.go:89 +0x288
github.com/dolthub/go-mysql-server/sql/rowexec.(*projectIter).Next(0xc000276180, 0x0?)
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.15.1-0.20230517042856-2405a8d89854/sql/rowexec/rel_iters.go:329 +0x2f
github.com/dolthub/go-mysql-server/sql/rowexec.(*insertIter).Next(0xc000572820, 0xc00057a780)
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.15.1-0.20230517042856-2405a8d89854/sql/rowexec/insert.go:62 +0x4a
github.com/dolthub/go-mysql-server/sql/plan.(*tableEditorIter).Next(0xc0000679f0, 0xc00057a780)
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.15.1-0.20230517042856-2405a8d89854/sql/plan/table_editor.go:55 +0x78
github.com/dolthub/go-mysql-server/sql/rowexec.(*accumulatorIter).Next(0xc0002761b0, 0xc00057a780)
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.15.1-0.20230517042856-2405a8d89854/sql/rowexec/dml_iters.go:511 +0x202
github.com/dolthub/go-mysql-server/sql/rowexec.transactionCommittingIter.Next(...)
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.15.1-0.20230517042856-2405a8d89854/sql/rowexec/transaction_iters.go:78
github.com/dolthub/go-mysql-server/sql/plan.(*trackedRowIter).Next(0xc00063be00, 0x0?)
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.15.1-0.20230517042856-2405a8d89854/sql/plan/process.go:324 +0x2e
github.com/dolthub/go-mysql-server/server.(*Handler).doQuery.func2()
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.15.1-0.20230517042856-2405a8d89854/server/handler.go:401 +0x138
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/Users/timsehn/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	/Users/timsehn/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
```

**Comment by max-hoffman** [comment]
This will repro with any default on a LOAD DATA node (including a literal):
```sql
create table t (
  i int primary key,
  `created_at` timestamp(6) DEFAULT NOW()
);
```

```csv
i,created_at
0,,
```

```sql
> set global local_infile=1;
Query OK, 1 row affected (0.00 sec)

> LOAD DATA local infile '/Users/max-hoffman/Documents/dolthub/databases/merkel-labs/data.csv' into table t FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;
ERROR 1105 (HY000): UnresolvedColumnDefault is a placeholder node, but Eval() was called: (NOW())
```

We do not call `parseColumnDefaults` or `resolveColumnDefaults` for `*plan.LoadData` nodes. Additionally, `UnresolvedColumnDefault.Eval()` should probably do this:

```diff
 func (u UnresolvedColumnDefault) Eval(ctx *Context, row Row) (interface{}, error) {
-       panic("UnresolvedColumnDefault is a placeholder node, but Eval() was called")
+       return nil, fmt.Errorf("UnresolvedColumnDefault is a placeholder node, but Eval() was called: %s", u.exprString)
 }
```

**Comment by timsehn** [comment]
The problem with the panic is that it's mot visible in the hosted logs and it crashes the server.

**Comment by timsehn** [comment]
I can't get the repro to panic now. Defaults still not applied.

```
$ cat <<CSV > in.csv                                                          
0,NULL,0
CSV
$ dolt sql -q "create table t (pk int primary key, c1 int default 1, c2 int)" 
$ dolt sql <<SQL                                                              
load data infile 'in.csv' into table t
fields terminated by ','
lines terminated by '\n'
SQL
Query OK, 1 row affected (0.00 sec)
$ dolt sql -q "select * from t"                                               
+----+------+----+
| pk | c1   | c2 |
+----+------+----+
| 0  | NULL | 0  |
+----+------+----+

$
$ dolt sql -q "create table t (pk int primary key, c1 int default (1+1), c2 int)"
$ dolt sql <<SQL                                                                 
load data infile 'in.csv' into table t
fields terminated by ','
lines terminated by '\n'
SQL
Query OK, 1 row affected (0.00 sec)
$ dolt sql -q "select * from t"                                                  
+----+------+----+
| pk | c1   | c2 |
+----+------+----+
| 0  | NULL | 0  |
+----+------+----+
$ dolt sql -q "drop table t"
$ dolt sql -q "create table t (pk int primary key, c1 varchar(5) default 'a', c2 int)"
$ dolt sql <<SQL                                                                      
load data infile 'in.csv' into table t
fields terminated by ','
lines terminated by '\n'
SQL
Query OK, 1 row affected (0.00 sec)
$ dolt sql -q "select * from t"                                                       
+----+------+----+
| pk | c1   | c2 |
+----+------+----+
| 0  | NULL | 0  |
+----+------+----+
$ dolt sql -q "drop table t"
$ dolt sql -q "create table t (
  i int primary key,
  created_at timestamp(6) DEFAULT NOW() 
)"
$ dolt sql <<SQL                                                              
load data infile 'in.csv' into table t
fields terminated by ','
lines terminated by '\n'
SQL
Query OK, 1 row affected (0.00 sec)
$ dolt sql -q "select * from t"                                               
+---+------------+
| i | created_at |
+---+------------+
| 0 | NULL       |
+---+------------+
```

**Comment by timsehn** [comment]
I'm going to resolve this one as we tested around the edges and could not repro the panic.
