### ISSUE TITLE
Compatibility issue with sqlalchemy table class, table manipulation

### ISSUE THREAD

**Issue by parrisimi** [dolthub/dolt#5991]
Although you can access the table with sqlalchemy, with the tables defined as a class , the changes made with these table class are not detected by dolt to make a commit on that change.
Example :
```
from sqlalchemy.engine import Engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import create_engine, Column, Integer, String,MetaData,Table,select,update,text,JSON
conn_string_base = "mysql+mysqlconnector://"
engine = create_engine(conn_string_base +"{user}@125.1.1.1:{port}/{db}".format(user=user,port=port,db=db)
# Create a session factory
Session = sessionmaker(bind=engine)

# Create a session
session = Session()
conn = engine.connect()

Base = declarative_base()
Base.metadata.create_all(engine)
metadata_obj = MetaData()
class TableEmployee(Base):
    __tablename__ = "employee"

    id = Column(Integer, primary_key=True)
    name = Column(String)
    position_id= Column(String)
employee = session.query(TableEmployee).filter(TableEmployee.position_id == '10').first()
# Change the name
employee.name = "New Name"


# Commit the changes to the database
session.commit()
# if we do not do session.commit no changes are saved in table and changes are also not detected by dolt. if we do the session.commit also then we can't access this change in dolt to do the dolt_commit, also the changes are not detected.
conn.execute(text("call dolt_add('employee')"))
conn.execute(text("call dolt_commit('-m','your commit message')"))
```
Error I got:
sqlalchemy.exc.DatabaseError: (mysql.connector.errors.DatabaseError) 1105 (HY000): nothing to commit.
Although the change was made in table, dolt was not able to access this change as it was made with table classs.
Question : How can we change the value of tables with SQLalchemy table class and also commit this changes in dolt so that we can track these changes?
There is definitely a way around, using the SQL code directly like Update with conn.execute(text("Update bla bla "). But Using SQL alchemy would be better if we can access the tables with class object and also manipulate them in same way.

**Comment by bpf120** [comment]
@parrisimi Thanks for filing. We'd love to learn what your Dolt use case is too. Feel free to [email me](mailto:brianf@dolthub.com) or swing by our [Discord](https://discord.gg/gqr7K4VNKe if you want to share.

**Comment by timsehn** [comment]
So I was able to reproduce with my local Python environment. Here's what I did:

1. Set up dolt for the example

```
$ mkdir test_sql_alchemy
$ cd test_sql_alchemy 
$ dolt init --fun
Successfully initialized dolt data repository.
$ dolt sql -q "create table employee(id int primary key, name varchar(max), position_id varchar(max))"
$ dolt sql -q "insert into employee values (10, 'Tim', '10');
```

2. Start a `dolt sql-server` in debug mode

```
$ dolt sql-server --loglevel=debug
Starting server with Config HP="localhost:3306"|T="28800000"|R="false"|L="debug"|S="/tmp/mysql.sock"
```

3. Modify the script to work with my Python env.

I had to change the location of the declarative base function and add my own connection arguments.

```python
from sqlalchemy.engine import Engine
from sqlalchemy.orm import sessionmaker, declarative_base
from sqlalchemy import create_engine, Column, Integer, String,MetaData,Table,select,update,text,JSON


conn_string_base = "mysql+mysqlconnector://"
engine = create_engine(conn_string_base +"root@127.0.0.1:3306/test_sql_alchemy")
                       
# Create a session factory
Session = sessionmaker(bind=engine)

# Create a session
session = Session()
conn = engine.connect()

Base = declarative_base()
Base.metadata.create_all(engine)
metadata_obj = MetaData()
class TableEmployee(Base):
    __tablename__ = "employee"

    id = Column(Integer, primary_key=True)
    name = Column(String)
    position_id= Column(String)

employee = session.query(TableEmployee).filter(TableEmployee.position_id == '10').first()
# Change the name
employee.name = "New Name"

# Commit the changes to the database
session.commit()
# if we do not do session.commit no changes are saved in table and changes are also not detected by dolt. if we do the session.commit also then we can't access this change in dolt to do the dolt_commit, also the changes are not detected.
conn.execute(text("call dolt_add('employee')"))
conn.execute(text("call dolt_commit('-m','your commit message')"))
```

4. Run the script
```
$ python test.py
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/mysql/connector/connection_cext.py", line 608, in cmd_query
    self._cmysql.query(
_mysql_connector.MySQLInterfaceError: nothing to commit

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/homebrew/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/homebrew/lib/python3.11/site-packages/mysql/connector/cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
             ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mysql/connector/connection_cext.py", line 616, in cmd_query
    raise get_mysql_exception(
mysql.connector.errors.DatabaseError: 1105 (HY000): nothing to commit

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/timsehn/dolthub/dolt/test_sql_alchemy/test.py", line 34, in <module>
    conn.execute(text("call dolt_commit('-m','your commit message')"))
  File "/opt/homebrew/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1414, in execute
    return meth(
           ^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 486, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "/opt/homebrew/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2326, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/opt/homebrew/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/homebrew/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/homebrew/lib/python3.11/site-packages/mysql/connector/cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
             ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mysql/connector/connection_cext.py", line 616, in cmd_query
    raise get_mysql_exception(
sqlalchemy.exc.DatabaseError: (mysql.connector.errors.DatabaseError) 1105 (HY000): nothing to commit
[SQL: call dolt_commit('-m','your commit message')]
(Background on this error at: https://sqlalche.me/e/20/4xp6)
```

It indeed says nothing to commit.

5. Examine the dolt debiug logs to see what actual queries SQL Alchemy is running.

```
2023-05-19T11:18:09-07:00 INFO [conn 3] NewConnection {DisableClientMultiStatements=false}
2023-05-19T11:18:09-07:00 DEBUG [conn 3] Starting query {connectTime=2023-05-19T11:18:09-07:00, connectionDb=test_sql_alchemy, query=SET NAMES 'utf8mb4' COLLATE 'utf8mb4_general_ci'}
2023-05-19T11:18:09-07:00 DEBUG [conn 3] Query finished in 0 ms {connectTime=2023-05-19T11:18:09-07:00, connectionDb=test_sql_alchemy, query=SET NAMES 'utf8mb4' COLLATE 'utf8mb4_general_ci'}
2023-05-19T11:18:09-07:00 DEBUG [conn 3] Starting query {connectTime=2023-05-19T11:18:09-07:00, connectionDb=test_sql_alchemy, query=SET NAMES utf8mb4}
2023-05-19T11:18:09-07:00 DEBUG [conn 3] Query finished in 0 ms {connectTime=2023-05-19T11:18:09-07:00, connectionDb=test_sql_alchemy, query=SET NAMES utf8mb4}
2023-05-19T11:18:09-07:00 DEBUG [conn 3] Starting query {connectTime=2023-05-19T11:18:09-07:00, connectionDb=test_sql_alchemy, query=set autocommit=0}
2023-05-19T11:18:09-07:00 DEBUG [conn 3] Query finished in 0 ms {connectTime=2023-05-19T11:18:09-07:00, connectionDb=test_sql_alchemy, query=set autocommit=0}
2023-05-19T11:18:09-07:00 DEBUG [conn 3] Starting query {connectTime=2023-05-19T11:18:09-07:00, connectionDb=test_sql_alchemy, query=SELECT VERSION()}
2023-05-19T11:18:09-07:00 DEBUG [conn 3] Query finished in 0 ms {connectTime=2023-05-19T11:18:09-07:00, connectionDb=test_sql_alchemy, query=SELECT VERSION()}
2023-05-19T11:18:09-07:00 DEBUG [conn 3] Starting query {connectTime=2023-05-19T11:18:09-07:00, connectionDb=test_sql_alchemy, query=SELECT DATABASE()}
2023-05-19T11:18:09-07:00 DEBUG [conn 3] Query finished in 0 ms {connectTime=2023-05-19T11:18:09-07:00, connectionDb=test_sql_alchemy, query=SELECT DATABASE()}
2023-05-19T11:18:09-07:00 DEBUG [conn 3] Starting query {connectTime=2023-05-19T11:18:09-07:00, connectionDb=test_sql_alchemy, query=SELECT @@transaction_isolation}
2023-05-19T11:18:09-07:00 DEBUG [conn 3] Query finished in 0 ms {connectTime=2023-05-19T11:18:09-07:00, connectionDb=test_sql_alchemy, query=SELECT @@transaction_isolation}
2023-05-19T11:18:09-07:00 DEBUG [conn 3] Starting query {connectTime=2023-05-19T11:18:09-07:00, connectionDb=test_sql_alchemy, query=SELECT @@sql_mode}
2023-05-19T11:18:09-07:00 DEBUG [conn 3] Query finished in 0 ms {connectTime=2023-05-19T11:18:09-07:00, connectionDb=test_sql_alchemy, query=SELECT @@sql_mode}
2023-05-19T11:18:09-07:00 DEBUG [conn 3] Starting query {connectTime=2023-05-19T11:18:09-07:00, connectionDb=test_sql_alchemy, query=SELECT @@lower_case_table_names}
2023-05-19T11:18:09-07:00 DEBUG [conn 3] Query finished in 0 ms {connectTime=2023-05-19T11:18:09-07:00, connectionDb=test_sql_alchemy, query=SELECT @@lower_case_table_names}
2023-05-19T11:18:09-07:00 DEBUG [conn 3] Starting query {connectTime=2023-05-19T11:18:09-07:00, connectionDb=test_sql_alchemy, query=rollback}
2023-05-19T11:18:09-07:00 DEBUG [conn 3] Query finished in 0 ms {connectTime=2023-05-19T11:18:09-07:00, connectionDb=test_sql_alchemy, query=rollback}
2023-05-19T11:18:09-07:00 INFO [conn 4] NewConnection {DisableClientMultiStatements=false}
2023-05-19T11:18:09-07:00 DEBUG [conn 4] Starting query {connectTime=2023-05-19T11:18:09-07:00, connectionDb=test_sql_alchemy, query=SET NAMES 'utf8mb4' COLLATE 'utf8mb4_general_ci'}
2023-05-19T11:18:09-07:00 DEBUG [conn 4] Query finished in 0 ms {connectTime=2023-05-19T11:18:09-07:00, connectionDb=test_sql_alchemy, query=SET NAMES 'utf8mb4' COLLATE 'utf8mb4_general_ci'}
2023-05-19T11:18:09-07:00 DEBUG [conn 4] Starting query {connectTime=2023-05-19T11:18:09-07:00, connectionDb=test_sql_alchemy, query=SET NAMES utf8mb4}
2023-05-19T11:18:09-07:00 DEBUG [conn 4] Query finished in 0 ms {connectTime=2023-05-19T11:18:09-07:00, connectionDb=test_sql_alchemy, query=SET NAMES utf8mb4}
2023-05-19T11:18:09-07:00 DEBUG [conn 4] Starting query {connectTime=2023-05-19T11:18:09-07:00, connectionDb=test_sql_alchemy, query=set autocommit=0}
2023-05-19T11:18:09-07:00 DEBUG [conn 4] Query finished in 0 ms {connectTime=2023-05-19T11:18:09-07:00, connectionDb=test_sql_alchemy, query=set autocommit=0}
2023-05-19T11:18:09-07:00 DEBUG [conn 4] Starting query {connectTime=2023-05-19T11:18:09-07:00, connectionDb=test_sql_alchemy, query=commit}
2023-05-19T11:18:09-07:00 DEBUG [conn 4] Query finished in 0 ms {connectTime=2023-05-19T11:18:09-07:00, connectionDb=test_sql_alchemy, query=commit}
2023-05-19T11:18:09-07:00 DEBUG [conn 4] Starting query {connectTime=2023-05-19T11:18:09-07:00, connectionDb=test_sql_alchemy, query=rollback}
2023-05-19T11:18:09-07:00 DEBUG [conn 4] Query finished in 0 ms {connectTime=2023-05-19T11:18:09-07:00, connectionDb=test_sql_alchemy, query=rollback}
2023-05-19T11:18:09-07:00 DEBUG [conn 4] Starting query {connectTime=2023-05-19T11:18:09-07:00, connectionDb=test_sql_alchemy, query=SELECT employee.id AS employee_id, employee.name AS employee_name, employee.position_id AS employee_position_id FROM employee WHERE employee.position_id = '10' LIMIT 1}
2023-05-19T11:18:09-07:00 DEBUG [conn 4] Query finished in 0 ms {connectTime=2023-05-19T11:18:09-07:00, connectionDb=test_sql_alchemy, query=SELECT employee.id AS employee_id, employee.name AS employee_name, employee.position_id AS employee_position_id FROM employee WHERE employee.position_id = '10' LIMIT 1}
2023-05-19T11:18:09-07:00 DEBUG [conn 4] Starting query {connectTime=2023-05-19T11:18:09-07:00, connectionDb=test_sql_alchemy, query=commit}
2023-05-19T11:18:09-07:00 DEBUG [conn 4] Query finished in 0 ms {connectTime=2023-05-19T11:18:09-07:00, connectionDb=test_sql_alchemy, query=commit}
2023-05-19T11:18:09-07:00 DEBUG [conn 4] Starting query {connectTime=2023-05-19T11:18:09-07:00, connectionDb=test_sql_alchemy, query=rollback}
2023-05-19T11:18:09-07:00 DEBUG [conn 4] Query finished in 0 ms {connectTime=2023-05-19T11:18:09-07:00, connectionDb=test_sql_alchemy, query=rollback}
2023-05-19T11:18:09-07:00 DEBUG [conn 3] Starting query {connectTime=2023-05-19T11:18:09-07:00, connectionDb=test_sql_alchemy, query=call dolt_add('employee')}
2023-05-19T11:18:09-07:00 DEBUG [conn 3] Query finished in 0 ms {connectTime=2023-05-19T11:18:09-07:00, connectionDb=test_sql_alchemy, query=call dolt_add('employee')}
2023-05-19T11:18:09-07:00 DEBUG [conn 3] Starting query {connectTime=2023-05-19T11:18:09-07:00, connectionDb=test_sql_alchemy, query=call dolt_commit('-m','your commit message')}
2023-05-19T11:18:09-07:00 WARN [conn 3] error running query {connectTime=2023-05-19T11:18:09-07:00, connectionDb=test_sql_alchemy, error=nothing to commit, query=call dolt_commit('-m','your commit message')}
2023-05-19T11:18:09-07:00 DEBUG [conn 3] Starting query {connectTime=2023-05-19T11:18:09-07:00, connectionDb=test_sql_alchemy, query=rollback}
2023-05-19T11:18:09-07:00 DEBUG [conn 3] Query finished in 0 ms {connectTime=2023-05-19T11:18:09-07:00, connectionDb=test_sql_alchemy, query=rollback}
2023-05-19T11:18:09-07:00 INFO [conn 3] ConnectionClosed {}
2023-05-19T11:18:09-07:00 INFO [conn 4] ConnectionClosed {}
```

**Comment by timsehn** [comment]
So from the debug logs, no update query for that record is ever being issued. Relevant log lines:

```
2023-05-19T11:18:09-07:00 DEBUG [conn 4] Starting query {connectTime=2023-05-19T11:18:09-07:00, connectionDb=test_sql_alchemy, query=SELECT employee.id AS employee_id, employee.name AS employee_name, employee.position_id AS employee_position_id FROM employee WHERE employee.position_id = '10' LIMIT 1}
2023-05-19T11:18:09-07:00 DEBUG [conn 4] Query finished in 0 ms {connectTime=2023-05-19T11:18:09-07:00, connectionDb=test_sql_alchemy, query=SELECT employee.id AS employee_id, employee.name AS employee_name, employee.position_id AS employee_position_id FROM employee WHERE employee.position_id = '10' LIMIT 1}
2023-05-19T11:18:09-07:00 DEBUG [conn 4] Starting query {connectTime=2023-05-19T11:18:09-07:00, connectionDb=test_sql_alchemy, query=commit}
2023-05-19T11:18:09-07:00 DEBUG [conn 4] Query finished in 0 ms {connectTime=2023-05-19T11:18:09-07:00, connectionDb=test_sql_alchemy, query=commit}
2023-05-19T11:18:09-07:00 DEBUG [conn 4] Starting query {connectTime=2023-05-19T11:18:09-07:00, connectionDb=test_sql_alchemy, query=rollback}
2023-05-19T11:18:09-07:00 DEBUG [conn 4] Query finished in 0 ms {connectTime=2023-05-19T11:18:09-07:00, connectionDb=test_sql_alchemy, query=rollback}
2023-05-19T11:18:09-07:00 DEBUG [conn 3] Starting query {connectTime=2023-05-19T11:18:09-07:00, connectionDb=test_sql_alchemy, query=call dolt_add('employee')}

Trying to figure out how this is supposed to work in SQLAlchemy. I am not an expert.

**Comment by timsehn** [comment]
I can confirm from the binlog that MySQL is getting an update query and for some reason Dolt is not.

**Comment by timsehn** [comment]
With Verbose, I can see the actual query:
```
#230519 12:24:39 server id 1  end_log_pos 2184 CRC32 0xc078a0eb     Query    thread_id=11    exec_time=0    error_code=0
SET TIMESTAMP=1684524279/*!*/;
BEGIN
/*!*/;
# at 2184
#230519 12:24:39 server id 1  end_log_pos 2261 CRC32 0x11742d9e     Table_map: `test_sql_alchemy`.`employee` mapped to number 89
# has_generated_invisible_primary_key=0
# at 2261
#230519 12:24:39 server id 1  end_log_pos 2326 CRC32 0xdaa449dd     Update_rows: table id 89 flags: STMT_END_F

BINLOG '
98xnZBMBAAAATQAAANUIAAAAAFkAAAAAAAEAEHRlc3Rfc3FsX2FsY2hlbXkACGVtcGxveWVlAAMD
Dw8EUABQAAYBAQACA/z/AJ4tdBE=
98xnZB8BAAAAQQAAABYJAAAAAFkAAAAAAAEAAgAD//8ACgAAAANUaW0CMTAACgAAAAhOZXcgTmFt
ZQIxMN1JpNo=
'/*!*/;
### UPDATE `test_sql_alchemy`.`employee`
### WHERE
###   @1=10
###   @2='Tim'
###   @3='10'
### SET
###   @1=10
###   @2='New Name'
###   @3='10'
# at 2326
#230519 12:24:39 server id 1  end_log_pos 2357 CRC32 0xb1d1cef3     Xid = 63
COMMIT/*!*/;
SET @@SESSION.GTID_NEXT= 'AUTOMATIC' /* added by mysqlbinlog */ /*!*/;
DELIMITER ;
# End of log file
/*!50003 SET COMPLETION_TYPE=@OLD_COMPLETION_TYPE*/;
/*!50530 SET @@SESSION.PSEUDO_SLAVE_MODE=0*/;
```

**Comment by JCOR11599** [comment]
The script posted by @timsehn works fine for me
This is my sqlalchemy version
```shell
james@JAMES-LAPTOP MINGW64 ~/dolt_workspace/alch
$ pip show sqlalchemy
Name: SQLAlchemy
Version: 1.3.18
Summary: Database Abstraction Library 
Home-page: http://www.sqlalchemy.org  
Author: Mike Bayer
Author-email: mike_mp@zzzcomputing.com
License: MIT
Location: c:\users\james\appdata\local\programs\python\python310\lib\site-packages
Requires:
Required-by: doltpy
```

Will continue debugging with a more recent version of sqlalchemy
@mgedigian could you tell us which version of python and sqlalchemy you're using? also your OS?

**Comment by timsehn** [comment]
I am also now able to get this to work using this:
```
import random
import string

from sqlalchemy.engine import Engine
from sqlalchemy.orm import sessionmaker, declarative_base
from sqlalchemy import create_engine, Column, Integer, String,MetaData,Table,se\
lect,update,text,JSON


conn_string_base = "mysql+mysqlconnector://"
engine = create_engine(conn_string_base +"root@127.0.0.1:3306/test_sql_alchemy"\
)

# Create a session factory                                                      
Session = sessionmaker(engine)

# Create a session                                                              
session = Session()

Base = declarative_base()
Base.metadata.create_all(engine)
metadata_obj = MetaData()
class TableEmployee(Base):
    __tablename__ = "employee"

    id = Column(Integer, primary_key=True)
    name = Column(String)
    position_id= Column(String)

#employee = session.query(TableEmployee).filter(TableEmployee.position_id == '1\
0').first()                                                                     
employee = session.get(TableEmployee, 10)

# Change the name                                                               
letters = string.ascii_lowercase
employee.name = ''.join(random.choice(letters) for i in range(10))

# Commit the changes to the database                                            
session.commit()

# if we do not do session.commit no changes are saved in table and changes are \
also not detected by dolt. if we do the session.commit also then we can't acces\
s this change in dolt to do the dolt_commit, also the changes are not detected. 
session.execute(text("call dolt_add('employee')"))
session.execute(text("call dolt_commit('-m','your commit message')"))
```

We are trying to figure out what is wrong with the orginal. We think it might be the mixing of `conn`  and `session` because `conn` makes a new connection. This makes a new working set in Dolt.

**Comment by timsehn** [comment]
@JCOR11599  claims this works and I also tested. The only difference is the connection string and randomizing the input. I think what happens is the second time you run it, the data is there so it's east to be fooled (like I was).

```
import random
import string

from sqlalchemy.engine import Engine
from sqlalchemy.orm import sessionmaker, declarative_base
from sqlalchemy import create_engine, Column, Integer, String,MetaData,Table,select,update,text,JSON

conn_string_base = "mysql+mysqlconnector://"
engine = create_engine(conn_string_base +"root@127.0.0.1:3306/test_sql_alchemy"\
)

# Create a session factory
Session = sessionmaker(bind=engine)

# Create a session
session = Session()
conn = engine.connect()

Base = declarative_base()
Base.metadata.create_all(engine)
metadata_obj = MetaData()

class TableEmployee(Base):
    __tablename__ = "employee"

    id = Column(Integer, primary_key=True)
    name = Column(String)
    position_id= Column(String)

employee = session.query(TableEmployee).filter(TableEmployee.position_id == '10').first()

# Change the name
letters = string.ascii_lowercase
employee.name = ''.join(random.choice(letters) for i in range(10))

# Commit the changes to the database
session.commit()

# if we do not do session.commit no changes are saved in table and changes are also not detected by dolt. if we do the session.commit also then we can't access this change in dolt to do the dolt_commit, also the changes are not detected.
conn.execute(text("call dolt_add('employee')"))
conn.execute(text("call dolt_commit('-m','your commit message')"))
```

If you want the commit to succeed every time you can just change the last line to:
```
conn.execute(text("call dolt_commit('allow-empty','-m','your commit message')"))
```

**Comment by timsehn** [comment]
I'm going to resolve. Reopen or make a new issue if issues persist.

**Comment by parrisimi** [comment]
> yes That seems to be the problem in my case. Thank for the quick response. And I am using the sqlalchemy version 2.0.15 and it seems to work there as well. It is solved for me now.
