### ISSUE TITLE
Dolt does not appear to support all MySQL FK and Table valid naming characters

### ISSUE THREAD

**Issue by drepamig** [dolthub/dolt#6156]
Hello,

I'm testing out replacing a MySQL database (running on version `8.0.33`) with the Dolt equivalent because the git-like features would be perfect for my usage case. The original MySQL database was created with EF Core and works fine. However, when I try to target Dolt launched with `dolt sql-server` and apply the init migration, I get the following error:

```
MySqlConnector.MySqlException (0x80004005): invalid foreign key name `FK_TooLongKeyNameItems_OtherLongItems_Co~` as it must match the regular expression ^[-$_0-9a-zA-Z]+$
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 43
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 130
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 468
```

It appears to be caused by the trailing `~` in the key name which is hard-coded in the EF Core truncate method.

If I manually change all of the key names to remove the trailing `~` and apply the migration, I get a new error:

```
MySqlConnector.MySqlException (0x80004005): Invalid table name AdditionalBlock<AConcreteType>. Table names must match the regular expression ^[a-zA-Z]{1}$|^[a-zA-Z_]+[-_0-9a-zA-Z]*[0-9a-zA-Z]+$
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 43
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 130
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 468
```

Which points to the `<` and `>` characters being invalid.

I've also tried to use MySQL as the source and Dolt as [a version control for the database](https://docs.dolthub.com/introduction/getting-started/database), but the same errors happen in Dolt during replication and cause it to fail (even though the separate MySQL instance is working fine).

Since these naming conventions work with MySQL, is there any way to get them to work with Dolt's MySQL implementation?

Thanks for your help!

**Comment by timsehn** [comment]
@JCOR11599 is on this right now.

**Comment by timsehn** [comment]
https://github.com/dolthub/dolt/pull/6158

If you'd like to follow along.

**Comment by drepamig** [comment]
What an incredibly quick response! Thanks @timsehn and @JCOR11599!

**Comment by bpf120** [comment]
@drepamig let us know if you’d like to chat more about your use case sometime. You can email me or swing by our discord. 

Brianf@dolthub.com
