### ISSUE TITLE
Process.Progress (map[string]TableProgress) race condition

### ISSUE THREAD

**Issue by max-hoffman** [dolthub/dolt#6332]
`Process.Progress` should be mutex protected:

```sql
SELECT COUNT(ID) as total, MAX(time) as max_age
        FROM information_schema.processlist
        WHERE (user = 'root' AND @@max_user_connections > 0) OR true;
 ```
```
...
 2023-07-13 21:39:09 fatal error: concurrent map iteration and map write
2023-07-13 21:39:09 
2023-07-13 21:39:09 goroutine 79863 [running]:
2023-07-13 21:39:09 github.com/dolthub/go-mysql-server/sql/information_schema.processListRowIter(0x40d8df?, {0xc00cafdbc0?, 0x20?})
2023-07-13 21:39:09     /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.16.1-0.20230711191608-1f366da42701/sql/information_schema/information_schema.go:1068 +0x53b
2023-07-13 21:39:09 github.com/dolthub/go-mysql-server/sql/information_schema.(*informationSchemaTable).PartitionRows(0xc004186f40, 0x2ef5dc0?, {0x2ec5680, 0xc0140ed5c0})
2023-07-13 21:39:09     /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.16.1-0.20230711191608-1f366da42701/sql/information_schema/information_schema.go:2563 +0xe2
2023-07-13 21:39:09 github.com/dolthub/go-mysql-server/sql/plan.(*ProcessTable).PartitionRows(0xc015a3c1b0, 0xffffffff00000000?, {0x2ec5680, 0xc0140ed5c0})
2023-07-13 21:39:09     /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.16.1-0.20230711191608-1f366da42701/sql/plan/process.go:208 +0x37
2023-07-13 21:39:09 github.com/dolthub/go-mysql-server/sql.(*TableRowIter).Next(0xc0163b8040, 0xc018de75e0)

...
```

**Comment by JCOR11599** [comment]
Fix is merged to dolt main.
