### ISSUE TITLE
Can't get hosted replication to work. And got a Panic after trying for a while.

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#6498]
Series of Workbench and DoltHub screenshots:

![image](https://github.com/dolthub/dolt/assets/5376236/88ab208e-16e1-4f51-84e1-8488a24bea00)

![image](https://github.com/dolthub/dolt/assets/5376236/015f0d39-125a-4b36-b1e5-2dc2109d141f)

![image](https://github.com/dolthub/dolt/assets/5376236/bff1553d-06b4-493a-a36c-8064ec620438)

![image](https://github.com/dolthub/dolt/assets/5376236/1c8b7157-7d91-4415-afea-d6e3ee297ed7)

![image](https://github.com/dolthub/dolt/assets/5376236/217462fd-0a11-41ed-b6a5-0502a2093c09)

![image](https://github.com/dolthub/dolt/assets/5376236/3497e335-0429-437a-9eaf-81eeb906537c)

Then in the SQL shell to hosted:

```
MySQL [(none)]> select @@dolt_replicate_to_remote, @@dolt_replicate_all_heads
    -> ;
+------------------------------------+------------------------------------+
| @@SESSION.dolt_replicate_to_remote | @@SESSION.dolt_replicate_all_heads |
+------------------------------------+------------------------------------+
| origin                             |                                  1 |
+------------------------------------+------------------------------------+
1 row in set (0.037 sec)

MySQL [(none)]> show databases;
+---------------------+
| Database            |
+---------------------+
| information_schema  |
| mysql               |
| replication_example |
+---------------------+
3 rows in set (0.036 sec)

MySQL [(none)]> use replication_example;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MySQL [replication_example]> insert into test values (3,3);
Query OK, 1 row affected (0.041 sec)

MySQL [replication_example]> call dolt_commit('-am', 'from shell');
+----------------------------------+
| hash                             |
+----------------------------------+
| ul2h6os9egn6nu1qkpq69lbepmsupjt0 |
+----------------------------------+
1 row in set (0.040 sec)
```

Did not replicate.

Then removing hosted and cloning the database:

```
$ dolt remote remove origin                                                                                            
$ dolt remote add origin timsehn/replication_example
$ dolt pull -f
Updating 4ihij49ioche70qb9jj16t9jle8apuvb..ul2h6os9egn6nu1qkpq69lbepmsupjt0
Already up to date.
cannot fast forward from a to b. a is ahead of b already
$ dolt log
commit 4ihij49ioche70qb9jj16t9jle8apuvb (HEAD -> main) 
Author: yw27k5u93wulc7gj <yw27k5u93wulc7gj@%>
Date:  Fri Aug 11 13:02:53 -0700 2023

        another change from shell

commit ul2h6os9egn6nu1qkpq69lbepmsupjt0 (origin/main) 
Author: yw27k5u93wulc7gj <yw27k5u93wulc7gj@%>
Date:  Fri Aug 11 12:57:26 -0700 2023

        from shell

commit 40oimupqh15bv1ark8ol9t0suc4aujuc 
Author: timsehn <tim@dolthub.com>
Date:  Fri Aug 11 12:50:54 -0700 2023

        2,2

commit t92rtvrfhib49cld9ivct9jpl2ie9kue 
Author: timsehn <tim@dolthub.com>
Date:  Fri Aug 11 12:43:09 -0700 2023

        Changes to test from main

commit fdnps9tsbbojsmnqgkonp6fq90oab3vp 
Author: timsehn <tim@dolthub.com>
Date:  Fri Aug 11 12:41:21 -0700 2023

        inserted row

commit 1e6321q5s1ta827pbjh79j0qt731foau 
Author: timsehn <tim@dolthub.com>
Date:  Fri Aug 11 12:39:04 -0700 2023

        Added table and row

commit fmdlrlg0kd17uff5fpio1po3g60eksml 
Author: Dolt System Account <doltuser@dolthub.com>
Date:  Fri Aug 11 12:00:38 -0700 2023

        Initialize data repository

$ dolt push
Uploaded 965 B of 965 B @ 7.81 kB/s.

$ dolt sql -q "select * from test"
+----+----+
| pk | c1 |
+----+----+
| 0  | 0  |
| 1  | 1  |
| 2  | 2  |
| 3  | 3  |
| 4  | 4  |
+----+----+

$ dolt sql -q "insert into test values (5,5)"
Query OK, 1 row affected (0.61 sec)
$ dolt commit -am "not hosted insert"       
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x2bf746e]

goroutine 1 [running]:
github.com/dolthub/dolt/go/cmd/dolt/commands.printCommitInfo(0x100efdf?, 0x167258d?, 0xc0?, {0x3286693?, 0xc00014d3f8?}, 0x2914b06?)
	/Users/timsehn/dolthub/git/dolt/go/cmd/dolt/commands/show.go:400 +0x2e
github.com/dolthub/dolt/go/cmd/dolt/commands.performCommit.func1()
	/Users/timsehn/dolthub/git/dolt/go/cmd/dolt/commands/commit.go:180 +0x77
github.com/dolthub/dolt/go/cmd/dolt/cli.InitIO.func2(0x3b5db40?)
	/Users/timsehn/dolthub/git/dolt/go/cmd/dolt/cli/stdio.go:84 +0xd6
github.com/dolthub/dolt/go/cmd/dolt/commands.performCommit({0x3b7c2c8, 0xc000dcc540}, {0xc00047c590, 0xb}, {0xc0000520a0, 0x2, 0x2}, {0x3b77d10, 0xc00014e300}, 0xc0004ba750)
	/Users/timsehn/dolthub/git/dolt/go/cmd/dolt/commands/commit.go:176 +0x7ea
github.com/dolthub/dolt/go/cmd/dolt/commands.CommitCmd.Exec({}, {0x3b7c2c8?, 0xc000dcc540?}, {0xc00047c590?, 0x100cd9d?}, {0xc0000520a0?, 0x30c14e0?, 0xc000dcc401?}, 0x659bcc0?, {0x3b77d10, ...})
	/Users/timsehn/dolthub/git/dolt/go/cmd/dolt/commands/commit.go:88 +0x5f
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.handleCommand({{0x32867d7, 0x4}, {0x32a65ca, 0x11}, {0x0, 0x0}, {0x651bfa0, 0x33, 0x33}, 0x0}, ...)
	/Users/timsehn/dolthub/git/dolt/go/cmd/dolt/cli/command.go:244 +0x4ec
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.Exec({{0x32867d7, 0x4}, {0x32a65ca, 0x11}, {0x0, 0x0}, {0x651bfa0, 0x33, 0x33}, 0x0}, ...)
	/Users/timsehn/dolthub/git/dolt/go/cmd/dolt/cli/command.go:193 +0x4b8
main.runMain()
	/Users/timsehn/dolthub/git/dolt/go/cmd/dolt/dolt.go:586 +0x2b7e
main.main()
	/Users/timsehn/dolthub/git/dolt/go/cmd/dolt/dolt.go:228 +0x19
```

**Comment by timsehn** [comment]
This is weird. In same shell:
```
$ dolt sql -q "select @@dolt_replicate_to_remote, @@dolt_replicate_all_heads, @@dolt_replicate_heads"                  
error on line 1 for query select @@dolt_replicate_to_remote, @@dolt_replicate_all_heads, @@dolt_replicate_heads: replication error: dataset head is not ancestor of commit
```

**Comment by timsehn** [comment]
It's not completely busted:
```
$ rm -r replication_example
$ dolt clone timsehn/replication_example
cloning https://doltremoteapi.dolthub.com/timsehn/replication_example
$ cd replication_example 
$ dolt sql -q "set @@persist.dolt_replicate_to_remote = 'origin'"
$ dolt sql -q "set @@persist.dolt_replicate_all_heads = 1"       
$ dolt sql -q "select @@dolt_replicate_to_remote, @@dolt_replicate_all_heads, @@dolt_replicate_heads"
+------------------------------------+------------------------------------+--------------------------------+
| @@SESSION.dolt_replicate_to_remote | @@SESSION.dolt_replicate_all_heads | @@SESSION.dolt_replicate_heads |
+------------------------------------+------------------------------------+--------------------------------+
| origin                             | 1                                  |                                |
+------------------------------------+------------------------------------+--------------------------------+

$ dolt sql -q "select * from test"                                                                   
+----+----+
| pk | c1 |
+----+----+
| 0  | 0  |
| 1  | 1  |
| 2  | 2  |
| 3  | 3  |
| 4  | 4  |
+----+----+

$ dolt sql -q "insert into test values (5,5)"                                                        
Query OK, 1 row affected (0.01 sec)
$ dolt commit -am "not hosted insert"                                                                
commit ot2dlhvpr7pe255ln5dcjpu9cef1lfcm (HEAD -> main) 
Author: timsehn <tim@dolthub.com>
Date:  Fri Aug 11 13:19:41 -0700 2023

        not hosted insert

$ 
```

![image](https://github.com/dolthub/dolt/assets/5376236/f82525a1-b8e8-4873-b76e-6260316af0e0)

**Comment by timsehn** [comment]
Log level DEBUG on hosted gives me no clues.

**Comment by timsehn** [comment]
Weird. After changing the configuration on hosted it started working. Going to start from scratch and see if I can repro.

**Comment by timsehn** [comment]
So it looks like Dolt requires a restart when you set the replication variables via the server. Digging more locally.

**Comment by timsehn** [comment]
This is the problem. Server requires a restart after setting these variables to work. Making new smaller bug
