### ISSUE TITLE
Panic when inserting into prefix index on `TEXT` column

### ISSUE THREAD

**Issue by fulghum** [dolthub/dolt#6520]
Repro: 
```sql
CREATE table t (pk int primary key, col1 TEXT);
INSERT into t values (1, '123');
CREATE INDEX test_index2 ON t(col1(3));
INSERT into t values (2, '222');
```

This only seems to repro when a value is inserted before the prefix index is created. When looking at this in the debugger, it looks like the value inserted after the index was created shows up correctly as `222`, but value inserted before the index was created seems to be a pointer address, and not the real string contents. 

Output:
```
panic: runtime error: slice bounds out of range [-1:]

goroutine 21 [running]:
github.com/dolthub/dolt/go/libraries/doltcore/schema.compareCollatedStrings(0xac?, {0x14000742f80?, 0x2c8d9f5a46e33522?, 0x3ce9decb80a678e9?}, {0x1400162a060?, 0x1015e0b50?, 0x1400163c320?})
	/Users/jason/Projects/secondary-dolt/go/libraries/doltcore/schema/collation_comparator.go:143 +0x34c
github.com/dolthub/dolt/go/libraries/doltcore/schema.collationCompare({0x60?, 0xa0?}, 0x162?, {0x14000742f80?, 0x465ae3d53ce9decb?, 0x1031befb8?}, {0x1400162a060?, 0x1014dacc4?, 0x1400070e3f0?})
	/Users/jason/Projects/secondary-dolt/go/libraries/doltcore/schema/collation_comparator.go:111 +0x6c
github.com/dolthub/dolt/go/libraries/doltcore/schema.CollationTupleComparator.Compare({{0x14000742ed0?, 0x6?, 0x140014e4528?}}, {0x14000742f80, 0xc, 0xc}, {0x1400162a060, 0x1c, 0x1c}, {{0x14000742ea8, ...}, ...})
	/Users/jason/Projects/secondary-dolt/go/libraries/doltcore/schema/collation_comparator.go:46 +0x280
github.com/dolthub/dolt/go/store/val.TupleDesc.Compare({{0x14000742ea8, 0x2, 0x4}, {0x103132620, 0x14000756ed0}, {0x14000742ed8, 0x0, 0x2}}, {0x14000742f80?, 0xac?, ...}, ...)
	/Users/jason/Projects/secondary-dolt/go/store/val/tuple_descriptor.go:131 +0xa0
github.com/dolthub/dolt/go/store/prolly/tree.searchForKey[...].func1()
	/Users/jason/Projects/secondary-dolt/go/store/prolly/tree/node_cursor.go:226 +0x168
github.com/dolthub/dolt/go/store/prolly/tree.newCursorFromSearchFn({0x10312de18, 0x1400163c320}, {0x10313f718?, 0x1400015c8c0}, {{0x60, 0x1c, 0x58, 0x4, 0x0}, {0x50, ...}, ...}, ...)
	/Users/jason/Projects/secondary-dolt/go/store/prolly/tree/node_cursor.go:166 +0x12c
github.com/dolthub/dolt/go/store/prolly/tree.newCursorAtKey[...]({0x10312de18?, 0x1400163c320}, {0x10313f718, 0x1400015c8c0}, {{0x60, 0x1c, 0x58, 0x4, 0x0}, {0x50, ...}, ...}, ...)
	/Users/jason/Projects/secondary-dolt/go/store/prolly/tree/node_cursor.go:160 +0xc4
github.com/dolthub/dolt/go/store/prolly/tree.ApplyMutations[...]({0x10312de18, 0x1400163c320}, {0x10313f718, 0x1400015c8c0}, {{0x60, 0x1c, 0x58, 0x4, 0x0}, {0x50, ...}, ...}, ...)
	/Users/jason/Projects/secondary-dolt/go/store/prolly/tree/mutator.go:72 +0x100
github.com/dolthub/dolt/go/store/prolly.(*MutableMap).flushWithSerializer(_, {_, _}, {_, _})
	/Users/jason/Projects/secondary-dolt/go/store/prolly/tuple_mutable_map.go:84 +0x17c
github.com/dolthub/dolt/go/store/prolly.(*MutableMap).Map(_, {_, _})
	/Users/jason/Projects/secondary-dolt/go/store/prolly/tuple_mutable_map.go:77 +0x110
github.com/dolthub/dolt/go/libraries/doltcore/sqle/writer.prollySecondaryIndexWriter.Map(...)
	/Users/jason/Projects/secondary-dolt/go/libraries/doltcore/sqle/writer/prolly_index_writer.go:275
github.com/dolthub/dolt/go/libraries/doltcore/sqle/writer.(*prollyTableWriter).table(0x1400163b680, {0x10312de18, 0x1400163c320})
	/Users/jason/Projects/secondary-dolt/go/libraries/doltcore/sqle/writer/prolly_table_writer.go:333 +0x228
github.com/dolthub/dolt/go/libraries/doltcore/sqle/writer.(*prollyWriteSession).flush.func1()
	/Users/jason/Projects/secondary-dolt/go/libraries/doltcore/sqle/writer/prolly_write_session.go:151 +0x90
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/Users/jason/go/pkg/mod/golang.org/x/sync@v0.2.0/errgroup/errgroup.go:75 +0x5c
created by golang.org/x/sync/errgroup.(*Group).Go
	/Users/jason/go/pkg/mod/golang.org/x/sync@v0.2.0/errgroup/errgroup.go:72 +0xa4
```

**Comment by fulghum** [comment]
Debugging through this more... it looks like when we initially build the secondary index (or when we completely rebuild it) from existing data in the primary index, we don't account for blob/text field pointers and instead put the raw data (i.e. the pointer addresses) directly into the second index. For a secondary prefix index, the index contains the real content of the data (up to the prefix point), and not the pointer address, so we need to dereference the pointer to get the real content, and insert the correct prefix amount of that content to the secondary index. 

We must have custom code on the `INSERT` path that handles updating the secondary index, since the data inserted after the index was created seems to be being inserted into the secondary index correctly.
