### ISSUE TITLE
`dolt version` panics in some directories

### ISSUE THREAD

**Issue by bheni** [dolthub/dolt#6527]
```
~>dolt version
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x2196ab6]

goroutine 1 [running]:
github.com/dolthub/dolt/go/libraries/doltcore/ref.WorkingSetRefForHead({0x0, 0x0})
    /Users/brian/dev/dolt/go/libraries/doltcore/ref/workingset_ref.go:47 +0x36
github.com/dolthub/dolt/go/libraries/doltcore/env.WorkingSet({0x3ac13b8, 0xc00011e000}, 0xc000718400?, {0x3ac40a0?, 0xc000762078?})
    /Users/brian/dev/dolt/go/libraries/doltcore/env/environment.go:617 +0x45
github.com/dolthub/dolt/go/libraries/doltcore/env.(*DoltEnv).WorkingSet(0xc0000257a0, {0x3ac13b8, 0xc00011e000})
    /Users/brian/dev/dolt/go/libraries/doltcore/env/environment.go:609 +0x6c
github.com/dolthub/dolt/go/libraries/doltcore/env.Load({0x3ac13b8, 0xc00011e000}, 0xc00073aba0?, {0x3b577e0?, 0xc001034fb0}, {0xc00013b3b0, 0x13}, {0x322b755?, 0xc00073aba0?})
    /Users/brian/dev/dolt/go/libraries/doltcore/env/environment.go:201 +0x2a5
github.com/dolthub/dolt/go/libraries/doltcore/env.MultiEnvForDirectory.func1({0xc00073aba0?, 0x3a8ad30?}, 0x100da48?, 0x0?)
    /Users/brian/dev/dolt/go/libraries/doltcore/env/multi_repo_env.go:127 +0xfb
github.com/dolthub/dolt/go/libraries/utils/filesys.(*localFS).Iter(0x3ac13b8?, {0x3a8ad30?, 0x3a9c5b0?}, 0x0, 0xc000652200)
    /Users/brian/dev/dolt/go/libraries/utils/filesys/localfs.go:110 +0x1ba
github.com/dolthub/dolt/go/libraries/doltcore/env.MultiEnvForDirectory({0x3ac13b8?, 0xc00011e000}, {0x3ad36d0?, 0xc0005dc690}, {0x3b577e0?, 0xc000650170}, {0x322b755?, 0x6?}, 0x0, 0xc00071de60)
    /Users/brian/dev/dolt/go/libraries/doltcore/env/multi_repo_env.go:109 +0x3d1
main.runMain()
    /Users/brian/dev/dolt/go/cmd/dolt/dolt.go:533 +0x2345
main.main()
    /Users/brian/dev/dolt/go/cmd/dolt/dolt.go:228 +0x19
```

Tried running dolt version from my home directory and it panicked.  It works when run in most directories.

**Comment by timsehn** [comment]
I'm going to resolve this one as it's likely related to old databases lying around.
