### ISSUE TITLE
Adding fulltext index to a column with only null values panics.

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#6541]
Repro:
```
PS C:\Users\timse\dolthub\dolt\test_ft> dolt init --fun
Successfully initialized dolt data repository.
PS C:\Users\timse\dolthub\dolt\test_ft> dolt sql -q "create table ft (id int primary key, doc text)"
PS C:\Users\timse\dolthub\dolt\test_ft> dolt sql -q "insert into ft values (0, 'some text')"
Query OK, 1 row affected (0.00 sec)
PS C:\Users\timse\dolthub\dolt\test_ft> dolt sql -q "alter table ft add fulltext index ft(doc)"
error on line 1 for query alter table ft add fulltext index ft(doc): blob/text column 'doc' used in key specification without a key length
PS C:\Users\timse\dolthub\dolt\test_ft> dolt sql -q "alter table ft add column doc_string varchar(max)"
PS C:\Users\timse\dolthub\dolt\test_ft> dolt sql -q "alter table ft add fulltext index ft(doc_string)"
panic: Full-Text parser has encountered an unexpected type: <nil>

goroutine 1 [running]:
github.com/dolthub/go-mysql-server/sql/fulltext.NewDefaultParser(0x2d88840?, 0x135, {0xc0012148f0?, 0x3?, 0x3?})
        C:/Users/timse/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.16.1-0.20230818182125-d2f26d08e57d/sql/fulltext/default_parser.go:68 +0x1046
github.com/dolthub/go-mysql-server/sql/fulltext.TableEditor.Insert({{{0x2382b6f3818, 0xc000634900}, {0x0, 0x0}, {0xc000f595c0, 0x3, 0x3}}, {0xc000336f00, 0x1, 0x1}}, ...)
        C:/Users/timse/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.16.1-0.20230818182125-d2f26d08e57d/sql/fulltext/fulltext_editor.go:301 +0x51b
github.com/dolthub/go-mysql-server/sql/fulltext.CreateFulltextIndexes(0xc00055b5e0, {0x2382b6e4880, 0xc000008d50}, {0x2d00aa8?, 0xc0003c2180}, 0x4?, {0xc0010c0600, 0x1, 0xc00122c870?})
        C:/Users/timse/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.16.1-0.20230818182125-d2f26d08e57d/sql/fulltext/fulltext.go:718 +0x2129
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).executeAlterIndex(0x1ae567?, 0xc00055b5e0, 0xc00055be00)
        C:/Users/timse/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.16.1-0.20230818182125-d2f26d08e57d/sql/rowexec/ddl_iters.go:1871 +0xff4
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildAlterIndex(0x0?, 0x2cf0ad0?, 0xc000008d50?, {0x2d03b50?, 0xc000f60280?, 0xc00122c718?})
        C:/Users/timse/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.16.1-0.20230818182125-d2f26d08e57d/sql/rowexec/dml.go:253 +0x1d
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildNodeExec(0xc00055be00?, 0xc0010c0c10?, {0x2d01d38?, 0xc00055be00?}, {0x0?, 0x0, 0x0})
        C:/Users/timse/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.16.1-0.20230818182125-d2f26d08e57d/sql/rowexec/node_builder.gen.go:213 +0x1a69
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).Build(...)
        C:/Users/timse/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.16.1-0.20230818182125-d2f26d08e57d/sql/rowexec/builder.go:33
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildTransactionCommittingNode(0x18?, 0x21e82c0?, 0x2d01d01?, {0x0?, 0xc0010c0c90?, 0x1ae21f?})
        C:/Users/timse/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.16.1-0.20230818182125-d2f26d08e57d/sql/rowexec/transaction.go:305 +0x3b
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildNodeExec(0x1ae567?, 0x7c?, {0x2d04720?, 0xc0010d05d0?}, {0x0?, 0x0, 0x0})
        C:/Users/timse/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.16.1-0.20230818182125-d2f26d08e57d/sql/rowexec/node_builder.gen.go:37 +0x205a
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).Build(...)
        C:/Users/timse/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.16.1-0.20230818182125-d2f26d08e57d/sql/rowexec/builder.go:33
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildQueryProcess(0x0?, 0x0?, 0xc000009080, {0x0?, 0x24047ae?, 0xa?})
        C:/Users/timse/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.16.1-0.20230818182125-d2f26d08e57d/sql/rowexec/other.go:358 +0x45
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildNodeExec(0xc0004c2510?, 0xc00055bae0?, {0x2d03838?, 0xc000009080?}, {0x0?, 0x0, 0x0})
        C:/Users/timse/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.16.1-0.20230818182125-d2f26d08e57d/sql/rowexec/node_builder.gen.go:43 +0xeba
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).Build(0xc000008ca8?, 0x2d01d38?, {0x2d03838?, 0xc000009080?}, {0x0?, 0xc00055bae0?, 0xc0010c10a8?})
        C:/Users/timse/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.16.1-0.20230818182125-d2f26d08e57d/sql/rowexec/builder.go:33 +0x28
github.com/dolthub/go-mysql-server.(*Engine).QueryNodeWithBindings(0xc001230e10, 0xc00055b5e0, {0xc0004be3c0, 0x30}, 0x0)
        C:/Users/timse/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.16.1-0.20230818182125-d2f26d08e57d/engine.go:510 +0xbda
github.com/dolthub/go-mysql-server.(*Engine).QueryWithBindings(...)
        C:/Users/timse/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.16.1-0.20230818182125-d2f26d08e57d/engine.go:231
github.com/dolthub/go-mysql-server.(*Engine).Query(0xc0010c1224?, 0xc0010c1288?, {0xc0004be3c0?, 0xc0004be3c0?})
        C:/Users/timse/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.16.1-0.20230818182125-d2f26d08e57d/engine.go:226 +0x25
github.com/dolthub/dolt/go/cmd/dolt/commands/engine.(*SqlEngine).Query(0xc000d93200?, 0x600027005507c0?, {0xc0004be3c0?, 0x30?})
        C:/Users/timse/dolthub/git/dolt/go/cmd/dolt/commands/engine/sqlengine.go:263 +0x25
github.com/dolthub/dolt/go/cmd/dolt/commands.processParsedQuery(0xc0004be3c0?, {0xc0004be3c0?, 0x30?}, {0x2cd5c60?, 0xc000d92db0?}, {0x2ce5cd0?, 0xc000693f80?})
        C:/Users/timse/dolthub/git/dolt/go/cmd/dolt/commands/sql.go:989 +0x25d
github.com/dolthub/dolt/go/cmd/dolt/commands.execBatchMode(0xc00055b5e0, {0x2cd5c60, 0xc000d92db0}, {0x2cdc2c0?, 0xc0004c0920}, 0x0, 0x0?)
        C:/Users/timse/dolthub/git/dolt/go/cmd/dolt/commands/sql.go:643 +0x44c
github.com/dolthub/dolt/go/cmd/dolt/commands.queryMode(0x20714a0?, {0x2cd5c60, 0xc000d92db0}, 0x4?, {0xc000148030, 0x30}, 0x2?, 0x2?)
        C:/Users/timse/dolthub/git/dolt/go/cmd/dolt/commands/sql.go:391 +0xd3
github.com/dolthub/dolt/go/cmd/dolt/commands.SqlCmd.Exec({{0x23fa9c1?, 0xc0010c1680?}}, {0x2cf2b28, 0xc0005e93e0}, {0xc0005b5320, 0x8}, {0xc000150020, 0x2, 0x2}, 0xc000548870, ...)
        C:/Users/timse/dolthub/git/dolt/go/cmd/dolt/commands/sql.go:223 +0x61a
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.handleCommand({{0x23f8382, 0x4}, {0x2418d40, 0x11}, {0x0, 0x0}, {0x567c2c0, 0x33, 0x33}, 0x0}, ...)
        C:/Users/timse/dolthub/git/dolt/go/cmd/dolt/cli/command.go:244 +0x4ec
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.Exec({{0x23f8382, 0x4}, {0x2418d40, 0x11}, {0x0, 0x0}, {0x567c2c0, 0x33, 0x33}, 0x0}, ...)
        C:/Users/timse/dolthub/git/dolt/go/cmd/dolt/cli/command.go:193 +0x4b8
main.runMain()
        C:/Users/timse/dolthub/git/dolt/go/cmd/dolt/dolt.go:586 +0x2b7e
main.main()
        C:/Users/timse/dolthub/git/dolt/go/cmd/dolt/dolt.go:228 +0x19
```

This works if I add a value.
```
PS C:\Users\timse\dolthub\dolt\test_ft> dolt sql -q "update ft set doc_string=doc"
Query OK, 1 row affected (0.00 sec)
Rows matched: 1  Changed: 1  Warnings: 0
PS C:\Users\timse\dolthub\dolt\test_ft> dolt sql -q "alter table ft add fulltext index ft(doc_string)"
PS C:\Users\timse\dolthub\dolt\test_ft> dolt diff
diff --dolt a/ft b/ft
added table
+CREATE TABLE `ft` (
+  `id` int NOT NULL,
+  `doc` text,
+  `doc_string` varchar(16383),
+  PRIMARY KEY (`id`),
+  FULLTEXT KEY `ft` (`doc_string`)
+) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;
+---+----+-----------+------------+
|   | id | doc       | doc_string |
+---+----+-----------+------------+
| + | 0  | some text | some text  |
+---+----+-----------+------------+
```

**Comment by timsehn** [comment]
This is fixed.
