### ISSUE TITLE
Fulltext and autoincrement together causes Panic

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#6543]
Repro:

```sql
CREATE TABLE `descriptors` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` timestamp,
  `updated_at` timestamp,
  `deleted_at` timestamp,
  `restored_at` datetime,
  `created_by` bigint unsigned,
  `updated_by` bigint unsigned,
  `deleted_by` bigint unsigned,
  `restored_by` bigint unsigned,
  `namespace` varchar(255) COLLATE utf8mb4_unicode_ci,
  `subject` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `subject_type` tinyint NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` longtext COLLATE utf8mb4_unicode_ci,
  `icon` varchar(255) COLLATE utf8mb4_unicode_ci,
  `methods` json,
  `props` json,
  `events` json,
  `slots` json,
  `code` longtext COLLATE utf8mb4_unicode_ci,
  `is_live` tinyint NOT NULL DEFAULT '0',
  `file_path` varchar(255) COLLATE utf8mb4_unicode_ci,
  `file_last_modified` int,
  PRIMARY KEY (`id`),
  KEY `descriptors_created_by_index` (`created_by`),
  KEY `descriptors_deleted_by_index` (`deleted_by`),
  FULLTEXT KEY `descriptors_name_fulltext` (`name`),
  KEY `descriptors_restored_by_index` (`restored_by`),
  KEY `descriptors_subject_index` (`subject`),
  KEY `descriptors_subject_subject_type_index` (`subject`,`subject_type`),
  KEY `descriptors_subject_type_index` (`subject_type`),
  KEY `descriptors_updated_by_index` (`updated_by`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
insert into
  `descriptors` (
    `description`,
    `subject`,
    `namespace`,
    `subject_type`,
    `props`,
    `name`,
    `created_by`,
    `updated_at`,
    `created_at`
  )
values
  (null, 'DatabaseStatus', 'App\Domain\Databases\Enums', 4, '[{"key":"PENDING","name":"Pending","description":null,"type":"integer","value":1,"icon":null,"color":null,"required":false},{"key":"DISCONNECTED","name":"Disconnected","description":null,"type":"integer","value":2,"icon":null,"color":null,"required":false},{"key":"READY","name":"Ready","description":null,"type":"integer","value":3,"icon":null,"color":null,"required":false},{"key":"BUSY","name":"Busy","description":null,"type":"integer","value":4,"icon":null,"color":null,"required":false},{"key":"SUSPENDED","name":"Suspended","description":null,"type":"integer","value":5,"icon":null,"color":null,"required":false}]', '', null, '2023-08-20 21:14:02', '2023-08-20 21:14:02');
```

Panic
```
PS C:\Users\timse\dolthub\dolt\test_spacework> Get-Content -Path .\insert.sql | dolt sql
panic: interface conversion: fulltext.MultiTableEditor is not sql.AutoIncrementGetter: missing method GetNextAutoIncrementValue

goroutine 1 [running]:
github.com/dolthub/dolt/go/libraries/doltcore/sqle.(*WritableDoltTable).GetNextAutoIncrementValue(0x232ed071451?, 0x0?, {0x0, 0x0})
        C:/Users/timse/dolthub/git/dolt/go/libraries/doltcore/sqle/tables.go:810 +0x70
github.com/dolthub/go-mysql-server/sql/expression.(*AutoIncrement).Eval(0xc0000b91a0, 0x232ed2ee1b0?, {0xc000428a20?, 0x232e7130108?, 0x90?})
        C:/Users/timse/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.16.1-0.20230818182125-d2f26d08e57d/sql/expression/auto_increment.go:118 +0xef
github.com/dolthub/go-mysql-server/sql/rowexec.ProjectRow(0xc0010fd2c0?, {0xc0000d0d80, 0x17, 0x3918840?}, {0xc000428a20, 0x9, 0x9})
        C:/Users/timse/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.16.1-0.20230818182125-d2f26d08e57d/sql/rowexec/rel_iters.go:543 +0x409
github.com/dolthub/go-mysql-server/sql/rowexec.(*projectIter).Next(0xc000e6b020, 0xc00068ac60?)
        C:/Users/timse/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.16.1-0.20230818182125-d2f26d08e57d/sql/rowexec/rel_iters.go:517 +0x6e
github.com/dolthub/go-mysql-server/sql/rowexec.(*insertIter).Next(0xc0010de9c0, 0xc000f11c20)
        C:/Users/timse/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.16.1-0.20230818182125-d2f26d08e57d/sql/rowexec/insert.go:62 +0x4a
github.com/dolthub/go-mysql-server/sql/plan.(*tableEditorIter).Next(0xc0010e97c0, 0xc000f11c20)
        C:/Users/timse/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.16.1-0.20230818182125-d2f26d08e57d/sql/plan/table_editor.go:55 +0x78
github.com/dolthub/go-mysql-server/sql/rowexec.(*accumulatorIter).Next(0xc000e6b050, 0xc000f11c20)
        C:/Users/timse/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.16.1-0.20230818182125-d2f26d08e57d/sql/rowexec/dml_iters.go:511 +0x202
github.com/dolthub/go-mysql-server/sql/rowexec.transactionCommittingIter.Next(...)
        C:/Users/timse/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.16.1-0.20230818182125-d2f26d08e57d/sql/rowexec/transaction_iters.go:78
github.com/dolthub/go-mysql-server/sql/plan.(*trackedRowIter).Next(0xc00035fcc0, 0x0?)
        C:/Users/timse/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.16.1-0.20230818182125-d2f26d08e57d/sql/plan/process.go:324 +0x2e
github.com/dolthub/dolt/go/cmd/dolt/commands/engine.printOKResult(0x61c3c10?, {0x38750c8?, 0xc00035fcc0?}, {0x61c3c10?, 0x0?, 0x624e860?})
        C:/Users/timse/dolthub/git/dolt/go/cmd/dolt/commands/engine/sql_print.go:203 +0x59
github.com/dolthub/dolt/go/cmd/dolt/commands/engine.prettyPrintResultsWithSummary(0xc000f11c20, 0x0, {0x61c3c10?, 0x1, 0x1}, {0x38750c8, 0xc00035fcc0}, 0x0)
        C:/Users/timse/dolthub/git/dolt/go/cmd/dolt/commands/engine/sql_print.go:77 +0x515
github.com/dolthub/dolt/go/cmd/dolt/commands/engine.PrettyPrintResults(...)
        C:/Users/timse/dolthub/git/dolt/go/cmd/dolt/commands/engine/sql_print.go:57
github.com/dolthub/dolt/go/cmd/dolt/commands.execBatchMode(0xc000f11c20, {0x3865c60, 0xc000719980}, {0x386c120?, 0xc00014a000}, 0x0, 0x63?)
        C:/Users/timse/dolthub/git/dolt/go/cmd/dolt/commands/sql.go:662 +0x752
github.com/dolthub/dolt/go/cmd/dolt/commands.SqlCmd.Exec({{0x2f8a9c1?, 0xc001653680?}}, {0x3882b28, 0xc000c92cf0}, {0xc0010ee750, 0x8}, {0xc0001163b0, 0x0, 0x0}, 0xc001224480, ...)
        C:/Users/timse/dolthub/git/dolt/go/cmd/dolt/commands/sql.go:266 +0xb45
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.handleCommand({{0x2f88382, 0x4}, {0x2fa8d40, 0x11}, {0x0, 0x0}, {0x620c2c0, 0x33, 0x33}, 0x0}, ...)
        C:/Users/timse/dolthub/git/dolt/go/cmd/dolt/cli/command.go:244 +0x4ec
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.Exec({{0x2f88382, 0x4}, {0x2fa8d40, 0x11}, {0x0, 0x0}, {0x620c2c0, 0x33, 0x33}, 0x0}, ...)
        C:/Users/timse/dolthub/git/dolt/go/cmd/dolt/cli/command.go:193 +0x4b8
main.runMain()
        C:/Users/timse/dolthub/git/dolt/go/cmd/dolt/dolt.go:586 +0x2b7e
main.main()
        C:/Users/timse/dolthub/git/dolt/go/cmd/dolt/dolt.go:228 +0x19
```

**Comment by timsehn** [comment]
I can confirm this query fails with the new error:
```
PS C:\Users\timse\dolthub\dolt\test_spacework> Get-Content -Path .\insert.sql | dolt sql
error on line 1 for query insert into
  `descriptors` (
    `description`,
    `subject`,
    `namespace`,
    `subject_type`,
    `props`,
    `name`,
    `created_by`,
    `updated_at`,
    `created_at`
  )
values
  (null, 'DatabaseStatus', 'App\Domain\Databases\Enums', 4, '[{"key":"PENDING","name":"Pending","description":null,"type":"integer","value":1,"icon":null,"color":null,"required":false},{"key":"DISCONNECTED","name":"Disconnected","description":null,"type":"integer","value":2,"icon":null,"color":null,"required":false},{"key":"READY","name":"Ready","description":null,"type":"integer","value":3,"icon":null,"color":null,"required":false},{"key":"BUSY","name":"Busy","description":null,"type":"integer","value":4,"icon":null,"color":null,"required":false},{"key":"SUSPENDED","name":"Suspended","description":null,"type":"integer","value":5,"icon":null,"color":null,"required":false}]', '', null, '2023-08-20 21:14:02', '2023-08-20 21:14:02'): binary.Write: invalid type time.Time
```

@Hydrocharged can you confirm it no longer fails with your fix. It's embarrassing to tell someone their issue is fixed and have the same query fail for a different reason.

**Comment by macneale4** [comment]
https://github.com/dolthub/dolt/releases/tag/v1.13.1

**Comment by Hydrocharged** [comment]
It has been confirmed. I ended up creating a repro of the initial issue, and only tested against that for the original fix, which was my mistake.
