### ISSUE TITLE
Dolt revert panics after changing column from VARCHAR to TEXT

### ISSUE THREAD

**Issue by ricardoreiter** [dolthub/dolt#6660]
```
dolt sql -q "create table tableA (keyC varchar(255) not null, col1 varchar(255), PRIMARY KEY (keyC)) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"
dolt add .
dolt commit -m "new table"

dolt sql -q "insert into tableA (keyC, col1) values ('1', 'test')"
dolt add .
dolt commit -m "new row"

dolt sql -q "update tableA set col1 = 'test2'"
dolt add .
dolt commit -m "update row"

dolt checkout main
dolt sql -q "ALTER TABLE tableA MODIFY col1 TEXT"
dolt add .
dolt commit -m "change col"
```

Then trying to revert the "update row" commit throws
```
dolt revert qh11ueepqsnnvns4676g2at6ebqh3o87
panic: byte slice is not of expected size

goroutine 1 [running]:
github.com/dolthub/dolt/go/store/val.expectSize(...)
        github.com/dolthub/dolt/go/store/val/codec.go:610
github.com/dolthub/dolt/go/store/val.readAddr(...)
        github.com/dolthub/dolt/go/store/val/codec.go:604
github.com/dolthub/dolt/go/store/val.compare({0x84?, 0x0?}, {0x140001373c0?, 0x4c000800540000?, 0x100000004?}, {0x14000172500, 0x5, 0x30})
        github.com/dolthub/dolt/go/store/val/tuple_compare.go:145 +0x1218
github.com/dolthub/dolt/go/store/val.DefaultTupleComparator.CompareValues(...)
        github.com/dolthub/dolt/go/store/val/tuple_compare.go:65
github.com/dolthub/dolt/go/libraries/doltcore/merge.(*valueMerger).processColumn(0x1400090b970, 0x0, {0x140001373c0?, 0x1c?, 0x140001726d4?}, {0x14000172500?, 0x7?, 0x30?}, {0x140001726c0, 0x8, ...})
        github.com/dolthub/dolt/go/libraries/doltcore/merge/merge_prolly_rows.go:1546 +0x1a8
github.com/dolthub/dolt/go/libraries/doltcore/merge.(*valueMerger).tryMerge(0x1400090b970, {0x140001373c0, 0x16, 0x40}, {0x14000172500, 0x7, 0x30}, {0x140001726c0, 0x8, 0x30})
        github.com/dolthub/dolt/go/libraries/doltcore/merge/merge_prolly_rows.go:1523 +0x128
github.com/dolthub/dolt/go/store/prolly/tree.(*ThreeWayDiffer[...]).Next(0x102ebfca0, {0x102e323f8, 0x14000d5c6e0})
        github.com/dolthub/dolt/go/store/prolly/tree/three_way_differ.go:168 +0x580
github.com/dolthub/dolt/go/libraries/doltcore/merge.mergeProllyTableData(0x102ec7088?, 0x14000d5cb40, {0x102ec7088, 0x140008feae0}, 0x14000d7cf40, 0x1400090b970, 0x88?)
        github.com/dolthub/dolt/go/libraries/doltcore/merge/merge_prolly_rows.go:183 +0x6b8
github.com/dolthub/dolt/go/libraries/doltcore/merge.mergeProllyTable({0x102e323f8?, 0x14000d5c6e0}, 0x14000d5cb40, {0x102ec7088, 0x140008feae0}, 0x1)
        github.com/dolthub/dolt/go/libraries/doltcore/merge/merge_prolly_rows.go:102 +0x370
github.com/dolthub/dolt/go/libraries/doltcore/merge.(*RootMerger).MergeTable(0x14000a277c0, 0x14000d5c6e0?, {0x14000d308e0, 0x6}, {0x0, {0x0, 0x0}, {0x0, 0x0}}, {0x0?, ...})
        github.com/dolthub/dolt/go/libraries/doltcore/merge/merge_rows.go:151 +0x350
github.com/dolthub/dolt/go/libraries/doltcore/merge.MergeRoots(0x14000d5a700?, 0x14000dd0960, 0x14000dd1400, 0x14000dd1090, {0x102e221a0, 0x14000d5a700}, {0x102e221a0, 0x14000d5a380}, {0x0, {0x0, ...}, ...}, ...)
        github.com/dolthub/dolt/go/libraries/doltcore/merge/merge.go:208 +0x2a0
github.com/dolthub/dolt/go/libraries/doltcore/merge.Revert(0x14000d50690?, 0x102e323f8?, 0x14000e8a3b0?, {0x14000d98298, 0x1, 0x14000d7cbb0?}, {0x0, {0x0, 0x0}, {0x0, ...}})
        github.com/dolthub/dolt/go/libraries/doltcore/merge/revert.go:73 +0x2bc
github.com/dolthub/dolt/go/libraries/doltcore/sqle/dprocedures.doDoltRevert(0x14000d5c6e0, {0x14000e49ad0, 0x3, 0x3})
        github.com/dolthub/dolt/go/libraries/doltcore/sqle/dprocedures/dolt_revert.go:115 +0x4a0
github.com/dolthub/dolt/go/libraries/doltcore/sqle/dprocedures.doltRevert(0x14000a27cf8?, {0x14000e49ad0?, 0x2?, 0x2?})
        github.com/dolthub/dolt/go/libraries/doltcore/sqle/dprocedures/dolt_revert.go:34 +0x20
reflect.Value.call({0x102a787a0?, 0x102e0adb8?, 0x3fffffff?}, {0x101f5299b, 0x4}, {0x14000dadf20, 0x4, 0x102985e60?})
        reflect/value.go:596 +0x994
reflect.Value.Call({0x102a787a0?, 0x102e0adb8?, 0x102ed3390?}, {0x14000dadf20?, 0x102985e60?, 0x14000d7caa0?})
        reflect/value.go:380 +0x94
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildExternalProcedure(0x3?, 0x14000d5c6e0, 0x14000b44460, {0x4?, 0x14000a28618?, 0x100483d1c?})
        github.com/dolthub/go-mysql-server@v0.17.1-0.20230831170657-87fce68aac66/sql/rowexec/rel.go:585 +0x374
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildNodeExec(0x14000a28768?, 0x10048b990?, {0x102e46860?, 0x14000b44460?}, {0x0?, 0x0, 0x0})
        github.com/dolthub/go-mysql-server@v0.17.1-0.20230831170657-87fce68aac66/sql/rowexec/node_builder.gen.go:131 +0xe50
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildProcedure(...)
        github.com/dolthub/go-mysql-server@v0.17.1-0.20230831170657-87fce68aac66/sql/rowexec/rel.go:306
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildNodeExec(0x14000d7c850?, 0x14000d30788?, {0x102e46d10?, 0x1400090f450?}, {0x0?, 0x0, 0x0})
        github.com/dolthub/go-mysql-server@v0.17.1-0.20230831170657-87fce68aac66/sql/rowexec/node_builder.gen.go:219 +0x1924
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildCall(0xb?, 0x3?, 0x14000dade00, {0x0, 0x0, 0x0})
        github.com/dolthub/go-mysql-server@v0.17.1-0.20230831170657-87fce68aac66/sql/rowexec/proc.go:187 +0x1e8
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildNodeExec(0x102e442e0?, 0xc9f0?, {0x102e470d0?, 0x14000dade00?}, {0x0?, 0x14000a80000?, 0x14000d4e7c8?})
        github.com/dolthub/go-mysql-server@v0.17.1-0.20230831170657-87fce68aac66/sql/rowexec/node_builder.gen.go:81 +0x824
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).Build(...)
        github.com/dolthub/go-mysql-server@v0.17.1-0.20230831170657-87fce68aac66/sql/rowexec/builder.go:33
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildTransactionCommittingNode(0x14000a28c48?, 0x100483d1c?, 0x14000d7ca20?, {0x0?, 0x14000a28c18?, 0x10048b990?})
        github.com/dolthub/go-mysql-server@v0.17.1-0.20230831170657-87fce68aac66/sql/rowexec/transaction.go:305 +0x44
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildNodeExec(0x7c?, 0x6?, {0x102e442e0?, 0x14000d7c9f0?}, {0x0?, 0x100a5df10?, 0x1?})
        github.com/dolthub/go-mysql-server@v0.17.1-0.20230831170657-87fce68aac66/sql/rowexec/node_builder.gen.go:37 +0x114
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).Build(...)
        github.com/dolthub/go-mysql-server@v0.17.1-0.20230831170657-87fce68aac66/sql/rowexec/builder.go:33
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildQueryProcess(0x0?, 0x0?, 0x14000d4e7c8, {0x0?, 0x101f6009f?, 0xa?})
        github.com/dolthub/go-mysql-server@v0.17.1-0.20230831170657-87fce68aac66/sql/rowexec/other.go:358 +0x48
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildNodeExec(0x14000dca000?, 0x0?, {0x102e45dc0?, 0x14000d4e7c8?}, {0x0?, 0x102e098c8?, 0x14000a28f28?})
        github.com/dolthub/go-mysql-server@v0.17.1-0.20230831170657-87fce68aac66/sql/rowexec/node_builder.gen.go:43 +0x1a4
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).Build(0x14000b44150?, 0x102e45dc0?, {0x102e45dc0?, 0x14000d4e7c8?}, {0x0?, 0x14000dadbc0?, 0x14000a290c8?})
        github.com/dolthub/go-mysql-server@v0.17.1-0.20230831170657-87fce68aac66/sql/rowexec/builder.go:33 +0x28
github.com/dolthub/go-mysql-server.(*Engine).QueryWithBindings(0x14000dd00f0, 0x14000d5c6e0, {0x14000da4100, 0x62}, {0x0, 0x0}, 0x0)
        github.com/dolthub/go-mysql-server@v0.17.1-0.20230831170657-87fce68aac66/engine.go:518 +0xa20
github.com/dolthub/go-mysql-server.(*Engine).Query(...)
        github.com/dolthub/go-mysql-server@v0.17.1-0.20230831170657-87fce68aac66/engine.go:228
github.com/dolthub/dolt/go/cmd/dolt/commands/engine.(*SqlEngine).Query(0x14000d58090?, 0x22?, {0x14000da4100?, 0x2?})
        github.com/dolthub/dolt/go/cmd/dolt/commands/engine/sqlengine.go:267 +0x30
github.com/dolthub/dolt/go/cmd/dolt/commands.RevertCmd.Exec({}, {0x102e329e0, 0x14000d5a7c0}, {0x14000e8a4e0, 0xb}, {0x14000118230, 0x1, 0x1}, 0x102c40400?, {0x102e2af38, ...})
        github.com/dolthub/dolt/go/cmd/dolt/commands/revert.go:127 +0x694
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.handleCommand({{0x101f5272b, 0x4}, {0x101f70e4b, 0x11}, {0x0, 0x0}, {0x1057c9340, 0x34, 0x34}, 0x0}, ...)
        github.com/dolthub/dolt/go/cmd/dolt/cli/command.go:244 +0x3e4
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.Exec({{0x101f5272b, 0x4}, {0x101f70e4b, 0x11}, {0x0, 0x0}, {0x1057c9340, 0x34, 0x34}, 0x0}, ...)
        github.com/dolthub/dolt/go/cmd/dolt/cli/command.go:193 +0x254
main.runMain()
        github.com/dolthub/dolt/go/cmd/dolt/dolt.go:592 +0x23c8
main.main()
        github.com/dolthub/dolt/go/cmd/dolt/dolt.go:228 +0x1c
        ```

**Comment by timsehn** [comment]
Great repro steps. Thanks. We'll fix asap.

**Comment by nicktobey** [comment]
Hi Ricardo! Thank you so much for filing this issue.

We recently added the ability to perform merges and reverts in the presence of schema changes. Previously, trying to perform a merge or revert would fail with an error if one side of the merge altered a table's schema while the other side altered the table's rows. We now support this kind of merge in specific circumstances... although as you can see here, it appears the current implementation has some bugs.

The test case in the issue is simple enough that dolt should be able to automatically merge it unambiguously. I currently have a fix in the PR linked above, and I've confirmed it works for your use case. I'm in the process of cleaning up the implementation and adding more tests before I merge it into our main branch.

Thank you for patience. Issues like this help us make Dolt better.
