### ISSUE TITLE
Error when running large dump

### ISSUE THREAD

**Issue by medmond** [dolthub/dolt#6946]
I've cloned this database: [transparency-in-pricing](https://www.dolthub.com/repositories/dolthub/transparency-in-pricing/data/main/rate)

When I attempt to dump it, I eventually get the following error (after 197G have been written):

```
[~/dev/dolthub/transparency-in-pricing]$ dolt dump
panic: runtime error: index out of range [-1]
```

Any idea of what's happening? I've tried this twice, and this has happened at the same point each time. Thanks.

**Comment by timsehn** [comment]
That's not great. I'll try and repro locally.

**Comment by timsehn** [comment]
Do you need the SQL? A workaround may be to just export the tables as CSV. `dolt table export`:

https://docs.dolthub.com/cli-reference/cli#dolt-table-export

**Comment by medmond** [comment]
Thanks. Yeah, I'll give that a shot.

**Comment by timsehn** [comment]
```
$ dolt dump
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/dolthub/dolt/go/cmd/dolt/commands.dumpViews(0x14000acf2c0, 0x1408240f890, 0x14000da6b40?, {0x10579cc10?, 0x14000089178})
	/Users/timsehn/dolthub/git/dolt/go/cmd/dolt/commands/dump.go:429 +0x724
github.com/dolthub/dolt/go/cmd/dolt/commands.dumpSchemaElements({0x1057adef8, 0x14000da6b40}, 0x14000f6d320, {0x14000f50280?, 0x14000f50280?})
	/Users/timsehn/dolthub/git/dolt/go/cmd/dolt/commands/dump.go:233 +0xd4
github.com/dolthub/dolt/go/cmd/dolt/commands.DumpCmd.Exec({}, {0x1057adef8, 0x14000da6b40}, {0x1400002e600, 0x9}, {0x1400004e050, 0x0, 0x0}, 0x1055b2b00?, {0x14000d9aa01?, ...})
	/Users/timsehn/dolthub/git/dolt/go/cmd/dolt/commands/dump.go:192 +0xa24
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.handleCommand({{0x1048ab606, 0x4}, {0x1048ca128, 0x11}, {0x0, 0x0}, {0x10819da60, 0x34, 0x34}, 0x0}, ...)
	/Users/timsehn/dolthub/git/dolt/go/cmd/dolt/cli/command.go:244 +0x3e4
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.Exec({{0x1048ab606, 0x4}, {0x1048ca128, 0x11}, {0x0, 0x0}, {0x10819da60, 0x34, 0x34}, 0x0}, ...)
	/Users/timsehn/dolthub/git/dolt/go/cmd/dolt/cli/command.go:193 +0x254
main.runMain()
	/Users/timsehn/dolthub/git/dolt/go/cmd/dolt/dolt.go:592 +0x2408
main.main()
	/Users/timsehn/dolthub/git/dolt/go/cmd/dolt/dolt.go:225 +0x1c
```

Was able to repro.

**Comment by timsehn** [comment]
@jennifersp is going to look into this one.

**Comment by timsehn** [comment]
So, it's possible this has something to do with the dump finishing. I have a 200GB file on my disk and it terminates with what seems like a correct SQL statement.

**Comment by jennifersp** [comment]
Hi @medmond, thank you for reporting this issue. The fix is merged in and will be in the next Dolt release. 🙂
