### ISSUE TITLE
Update FK panic

### ISSUE THREAD

**Issue by max-hoffman** [dolthub/dolt#6963]
This repros prior to the FK changes I just made. Seems like we only miss this in TPC-C by turning off check constraints prior to running. Seems like this affects most FK checks on UPDATE queries with an IndexedTableAccess source.

repro:
```sql
Set foreign_key_checks = 0;

CREATE TABLE d (
  `d_id` tinyint NOT NULL,
  `d_w_id` smallint NOT NULL,
  `d_next_o_id` int,
  PRIMARY KEY (`d_w_id`,`d_id`),
  CONSTRAINT `fkey_district_1_2` FOREIGN KEY (`d_w_id`) REFERENCES w (`w_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE w (
  `w_id` smallint NOT NULL,
  PRIMARY KEY (`w_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

-- ok
UPDATE d SET d_next_o_id = 3002 WHERE d_id = 8 AND d_w_id= 2;

Set foreign_key_checks = 1;

UPDATE d SET d_next_o_id = 3002 WHERE d_id = 8 AND d_w_id= 2;
panic: called partitions on a lookup indexed table

goroutine 1 [running]:
github.com/dolthub/dolt/go/libraries/doltcore/sqle.(*WritableIndexedDoltTable).Partitions(0xc00012d258?, 0x100db9a?)
	/Users/max-hoffman/go/src/github.com/dolthub/dolt/go/libraries/doltcore/sqle/indexed_dolt_table.go:144 +0x25
github.com/dolthub/go-mysql-server/sql/plan.(*ForeignKeyReferenceHandler).CheckTable(0xc000055c98?, 0xc000ec8320, {0x7c4e5c8, 0xc001213ec0})
	/Users/max-hoffman/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.17.1-0.20231105071709-422c3fee20f6/sql/plan/foreign_key_editor.go:419 +0x55
github.com/dolthub/go-mysql-server/sql/plan.ResolveForeignKey(0xc000e84ac0?, {0x7c4e5c8?, 0xc001213ec0}, {0x7c4f6f8?, 0xc000cf2270}, {{0xc000055c98, 0x11}, {0xc00055911e, 0x6}, {0xc000e33100, ...}, ...}, ...)
	/Users/max-hoffman/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.17.1-0.20231105071709-422c3fee20f6/sql/plan/alter_foreign_key.go:226 +0x1725
github.com/dolthub/go-mysql-server/sql/analyzer.getForeignKeyReferences(0xc000bd5b80?, 0x100dc7d?, {0x7c4e5c8, 0xc001213ec0}, 0x245a498?, {0x0?, 0x0?, 0xc000bd5e70?})
	/Users/max-hoffman/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.17.1-0.20231105071709-422c3fee20f6/sql/analyzer/apply_foreign_keys.go:259 +0x5df
github.com/dolthub/go-mysql-server/sql/analyzer.getForeignKeyEditor(0x3c383b0?, 0x7c4e578?, {0x7c4e5c8, 0xc001213ec0}, 0x10c0385?, {0x0?, 0x0?, 0xc000bd5e70?})
	/Users/max-hoffman/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.17.1-0.20231105071709-422c3fee20f6/sql/analyzer/apply_foreign_keys.go:207 +0x5d
github.com/dolthub/go-mysql-server/sql/analyzer.applyForeignKeysToNodes(0xc000f89ec0?, 0xc00122c990, {0x3c385e0?, 0xc000cef860?}, 0xc000f89ec0?)
	/Users/max-hoffman/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.17.1-0.20231105071709-422c3fee20f6/sql/analyzer/apply_foreign_keys.go:124 +0x43b
github.com/dolthub/go-mysql-server/sql/analyzer.applyForeignKeys(0xc000ec8320, 0x3365909?, {0x3c385e0, 0xc000cef860}, 0x0?, 0x3885d78?)
	/Users/max-hoffman/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.17.1-0.20231105071709-422c3fee20f6/sql/analyzer/apply_foreign_keys.go:36 +0x18a
github.com/dolthub/go-mysql-server/sql/analyzer.(*Batch).evalOnce(0xc000ceed20?, 0xc000bd6790?, 0xc00122c990, {0x3c385e0?, 0xc000cef1d0?}, 0x44?, 0x3885d78)
	/Users/max-hoffman/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.17.1-0.20231105071709-422c3fee20f6/sql/analyzer/batch.go:89 +0x24b
github.com/dolthub/go-mysql-server/sql/analyzer.(*Batch).EvalWithSelector(0xc000ec8320?, 0x3c385e0?, 0xc00122c990, {0x3c385e0?, 0xc000cef1d0?}, 0x0?, 0xc000e11248?)
	/Users/max-hoffman/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.17.1-0.20231105071709-422c3fee20f6/sql/analyzer/batch.go:63 +0x12f
github.com/dolthub/go-mysql-server/sql/analyzer.(*Batch).Eval(...)
	/Users/max-hoffman/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.17.1-0.20231105071709-422c3fee20f6/sql/analyzer/batch.go:55
github.com/dolthub/go-mysql-server/sql/analyzer.(*Analyzer).analyzeWithSelector(0xc00122c990, 0xc00124c2d0?, {0x3c385e0, 0xc000cef110}, 0x0, 0x3885d80, 0xc000bd67c8?)
	/Users/max-hoffman/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.17.1-0.20231105071709-422c3fee20f6/sql/analyzer/analyzer.go:530 +0x3e5
github.com/dolthub/go-mysql-server/sql/analyzer.(*Analyzer).Analyze(...)
	/Users/max-hoffman/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.17.1-0.20231105071709-422c3fee20f6/sql/analyzer/analyzer.go:490
```

**Comment by JCOR11599** [comment]
Attempting to fix this led to the discovery of some other potential problems with our foreign key resolution, specifically when dealing with enabling/disabling `foreign_key_checks`.

```sql
set foreign_key_checks=0;
create table parent (i int primary key);
create table child (i int primary key, foreign key (i) references parent (i));
insert into child values (1), (2), (3);
set foreign_key_checks=1;

update child set i = 1 where i = 1; -- incorrectly error

insert into parent values (1);
update child set i = 1 where i = 1; -- incorrectly error

insert into parent values (4);
insert into child values (4); -- incorrectly error

insert into child values (100); -- correctly error
```

It appears that MySQL only throws constraint violations on new rows, and does not care about invalid values in the child table added before the foreign key constraint was resolved.

**Comment by max-hoffman** [comment]
Related important note, we run a full tablescan to check referential integrity during analysis of any DML statement, which seems unreasonable also for non-correctness reasons.
