### ISSUE TITLE
Panic caused by invalid result character set

### ISSUE THREAD

**Issue by fulghum** [dolthub/dolt#6972]
The Dolt sql-server will panic and crash if an invalid character set is specified. I used `character_set_results`, but we should protect other character set system variables from having invalid values set, too. 

repro:
```sql
mysql> show status where variable_Name like '%char%';
+--------------------------+---------+
| Variable_name            | Value   |
+--------------------------+---------+
| character_set_client     | utf8mb4 |
| character_set_connection | utf8mb4 |
| character_set_database   | utf8mb4 |
| character_set_filesystem | binary  |
| character_set_results    | utf8mb4 |
| character_set_server     | utf8mb4 |
+--------------------------+---------+
6 rows in set (0.01 sec)

mysql> set character_set_results='nope';
Query OK, 1 row affected (0.00 sec)

mysql> select "any string";
ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
ERROR 2003 (HY000): Can't connect to MySQL server on 'localhost:11229' (61)
ERROR: 
Can't connect to the server
```

Server logs:
```
2023-11-08T10:13:09-08:00 DEBUG [conn 1] Query finished in 0 ms {connectTime=2023-11-08T10:12:42-08:00, connectionDb=, query=set character_set_results='nope'}
2023-11-08T10:13:17-08:00 DEBUG [conn 1] Starting query {connectTime=2023-11-08T10:12:42-08:00, connectionDb=, query=select "any string"}
panic: Unknown character set: nope

goroutine 140 [running]:
github.com/dolthub/go-mysql-server/sql.(*BaseSession).GetCharacterSetResults(0x1400015b620?)
        /Users/jason/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.17.1-0.20231108012750-58555e791aa9/sql/base_session.go:258 +0x1b4
github.com/dolthub/go-mysql-server/sql/types.StringType.SQL({0x1813, 0x3fffffff, 0xffffffff, 0x135}, 0x14000648280, {0x0, 0x0, 0x0}, {0x1066862e0, 0x14000a29660})
        /Users/jason/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.17.1-0.20231108012750-58555e791aa9/sql/types/strings.go:500 +0x1e4
github.com/dolthub/go-mysql-server/server.rowToSQL(0x14000ec4f18?, {0x14000eae180, 0x1, 0x0?}, {0x140004baec0, 0x1, 0x0?})
        /Users/jason/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.17.1-0.20231108012750-58555e791aa9/server/handler.go:574 +0xc8
github.com/dolthub/go-mysql-server/server.(*Handler).doQuery.func4()
        /Users/jason/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.17.1-0.20231108012750-58555e791aa9/server/handler.go:356 +0x2e0
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /Users/jason/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x58

```

**Comment by timsehn** [comment]
@Hydrocharged can you fix this one quick?

**Comment by Hydrocharged** [comment]
Fixed in https://github.com/dolthub/go-mysql-server/pull/2138
