### ISSUE TITLE
Deleting from dolt_constraint_violations_ causes a panic when unique column constraint violation exists.

### ISSUE THREAD

**Issue by lly-c232733** [dolthub/dolt#7275]
When executing the following sequence of commands the dolt sql-server panics. I would like to be able to resolve the constraint violation and then commit the cherry pick. 

Is there something I'm doing wrong or is this a bug? Is there a good workaround?

**SQL Shell:**
```sh
 > \connect root@localhost
Creating a session to 'root@localhost'
Please provide the password for 'root@localhost':
Save password for 'root@localhost'? [Y]es/[N]o/Ne[v]er (default No): No
Fetching global names for auto-completion... Press ^C to stop.
Your MySQL connection id is 3
Server version: 8.0.11 Dolt
No default schema selected; type \use <schema> to set one.

 > CREATE SCHEMA `aSchema`;
Query OK, 1 row affected (0.0506 sec)

 > USE `aSchema`;
Default schema set to `aSchema`.
Fetching global names, object names from `aSchema` for auto-completion... Press ^C to stop.
 > CREATE TABLE `aSchema`.`aTable` (
 ->   `aColumn` INT NULL,
 ->   `bColumn` INT NULL,
 ->   UNIQUE INDEX `aColumn_UNIQUE` (`aColumn` ASC) VISIBLE,
 ->   UNIQUE INDEX `bColumn_UNIQUE` (`bColumn` ASC) VISIBLE);
Query OK, 0 rows affected (0.0041 sec)

 > CALL dolt_commit('-A','-m', 'add schema');
+----------------------------------+
| hash                             |
+----------------------------------+
| s7jl1i3hdadj9kveq96srqclbk5s8hbk |
+----------------------------------+
1 row in set (0.0139 sec)

 > CALL dolt_branch('side');
+--------+
| status |
+--------+
|      0 |
+--------+
1 row in set (0.0155 sec)

 > CALL dolt_checkout('side');
+--------+---------------------------+
| status | message                   |
+--------+---------------------------+
|      0 | Switched to branch 'side' |
+--------+---------------------------+
1 row in set (0.0007 sec)

 > INSERT INTO `aSchema`.`aTable`
 ->   (`aColumn`, `bColumn`)
 ->   VALUES
 ->   (1,2);
Query OK, 1 row affected (0.0140 sec)

 > CALL dolt_commit('-A','-m', 'add side data');
+----------------------------------+
| hash                             |
+----------------------------------+
| 36hsudhb9h3pqdf7ok1h8s7lffegtej1 |
+----------------------------------+
1 row in set (0.0151 sec)

 > CALL dolt_checkout('main');
+--------+---------------------------+
| status | message                   |
+--------+---------------------------+
|      0 | Switched to branch 'main' |
+--------+---------------------------+
1 row in set (0.0006 sec)

 > INSERT INTO `aSchema`.`aTable`
 ->   (`aColumn`,`bColumn`)
 ->   VALUES
 ->   (1,3);
Query OK, 1 row affected (0.0150 sec)

 > CALL dolt_commit('-A','-m', 'add main data');
+----------------------------------+
| hash                             |
+----------------------------------+
| 7fu7hhvq79lbbpi4lqjl05jgc17eo3rq |
+----------------------------------+
1 row in set (0.0140 sec)

 > SET @@dolt_force_transaction_commit=1;
Query OK, 1 row affected (0.0005 sec)

 > Select commit_hash into @commit_hash from dolt_log() order by date desc limit 1;
Query OK, 1 row affected (0.0010 sec)

 > Select @commit_hash;
+----------------------------------+
| @commit_hash                     |
+----------------------------------+
| 7fu7hhvq79lbbpi4lqjl05jgc17eo3rq |
+----------------------------------+
1 row in set (0.0005 sec)

 > CALL dolt_checkout('side');
+--------+---------------------------+
| status | message                   |
+--------+---------------------------+
|      0 | Switched to branch 'side' |
+--------+---------------------------+
1 row in set (0.0010 sec)

 > CALL DOLT_CHERRY_PICK(@commit_hash);
+------+----------------+------------------+-----------------------+
| hash | data_conflicts | schema_conflicts | constraint_violations |
+------+----------------+------------------+-----------------------+
|      |              0 |                0 |                     1 |
+------+----------------+------------------+-----------------------+
1 row in set (0.0143 sec)

 > SELECT * FROM aTable;
+---------+---------+
| aColumn | bColumn |
+---------+---------+
|       1 |       2 |
|       1 |       3 |
+---------+---------+
2 rows in set (0.0011 sec)

 > SELECT * FROM dolt_constraint_violations_aTable;
+----------------------------------+----------------+---------+---------+----------------------------------------------------+
| from_root_ish                    | violation_type | aColumn | bColumn | violation_info                                     |
+----------------------------------+----------------+---------+---------+----------------------------------------------------+
| 7fu7hhvq79lbbpi4lqjl05jgc17eo3rq | unique index   |       1 |       2 | {"Columns": ["aColumn"], "Name": "aColumn_UNIQUE"} |
| 7fu7hhvq79lbbpi4lqjl05jgc17eo3rq | unique index   |       1 |       3 | {"Columns": ["aColumn"], "Name": "aColumn_UNIQUE"} |
+----------------------------------+----------------+---------+---------+----------------------------------------------------+
2 rows in set (0.0010 sec)

 > UPDATE `aSchema`.`aTable`
 -> SET
 -> `aColumn` = 2
 -> WHERE bColumn = 2;
Query OK, 1 row affected (0.0149 sec)

Rows matched: 1  Changed: 1  Warnings: 0

 > DELETE FROM dolt_constraint_violations_aTable;
ERROR: 2013 (HY000): Lost connection to MySQL server during query
The global session got disconnected..
Attempting to reconnect to 'mysql://root@localhost:3306/aSchema'......
```

**Server Console:**
```sh
dolt sql-server
Starting server with Config HP="localhost:3306"|T="28800000"|R="false"|L="info"
time="2024-01-08T21:49:19-05:00" level=info msg="Server ready. Accepting connections."
time="2024-01-08T21:49:19-05:00" level=warning msg="secure_file_priv is set to \"\", which is insecure."
time="2024-01-08T21:49:19-05:00" level=warning msg="Any user with GRANT FILE privileges will be able to read any file which the sql-server process can read."
time="2024-01-08T21:49:19-05:00" level=warning msg="Please consider restarting the server with secure_file_priv set to a safe (or non-existent) directory."
time="2024-01-08T21:49:23-05:00" level=info msg=NewConnection DisableClientMultiStatements=false connectionID=1
time="2024-01-08T21:49:23-05:00" level=warning msg="error running query" connectTime="2024-01-08 21:49:23.6742786 -0500 EST m=+6.523358901" connectionDb= connectionID=1 error="database not found: aSchema"
panic: interface conversion: interface {} is int32, not []uint8

goroutine 335 [running]:
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.PutField({0x32bf990?, 0xc0010a2500?}, {0x32c65f8?, 0xc000e8e500?}, 0xc000d6578c?, 0x0?, {0x2524080?, 0x465bcc8?})
        github.com/dolthub/dolt/go/libraries/doltcore/sqle/index/prolly_fields.go:219 +0x1aa5
github.com/dolthub/dolt/go/libraries/doltcore/sqle/dtables.(*prollyCVDeleter).Delete(0xc000a7ee00, 0xc0010a2500?, {0xc0010b6280, 0x5, 0x0?})
        github.com/dolthub/dolt/go/libraries/doltcore/sqle/dtables/constraint_violations_prolly.go:250 +0x145
github.com/dolthub/go-mysql-server/sql/rowexec.(*deleteIter).Next(0xc0010b6140, 0xc0010a2500)
        github.com/dolthub/go-mysql-server@v0.17.1-0.20231220211427-3a776d88f2b1/sql/rowexec/delete.go:95 +0x17c
github.com/dolthub/go-mysql-server/sql/plan.(*TableEditorIter).Next(0xc0010b6190, 0xc0010a2500)
        github.com/dolthub/go-mysql-server@v0.17.1-0.20231220211427-3a776d88f2b1/sql/plan/table_editor.go:55 +0x72
github.com/dolthub/go-mysql-server/sql/rowexec.(*accumulatorIter).Next(0xc000cee930, 0xc0010a2500)
        github.com/dolthub/go-mysql-server@v0.17.1-0.20231220211427-3a776d88f2b1/sql/rowexec/dml_iters.go:513 +0x1f6
github.com/dolthub/go-mysql-server/sql/rowexec.transactionCommittingIter.Next(...)
        github.com/dolthub/go-mysql-server@v0.17.1-0.20231220211427-3a776d88f2b1/sql/rowexec/transaction_iters.go:78
github.com/dolthub/go-mysql-server/sql/plan.(*trackedRowIter).Next(0xc000cab100, 0x671b00?)
        github.com/dolthub/go-mysql-server@v0.17.1-0.20231220211427-3a776d88f2b1/sql/plan/process.go:347 +0x24
github.com/dolthub/go-mysql-server/server.(*Handler).doQuery.func2()
        github.com/dolthub/go-mysql-server@v0.17.1-0.20231220211427-3a776d88f2b1/server/handler.go:286 +0x125
golang.org/x/sync/errgroup.(*Group).Go.func1()
        golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 39
        golang.org/x/sync@v0.3.0/errgroup/errgroup.go:72 +0x96```

**Comment by lly-c232733** [comment]
Similar to #7031?

**Comment by timsehn** [comment]
@fulghum will dig into this today.

**Comment by fulghum** [comment]
Thanks for the extra info. I've got this repro'ed in the debugger now and just confirmed that this error doesn't happen when the table has a primary key. I'll keep debugging the keyless issue of course, but in the meantime, I think you can try out a UUID primary key. 

Instead of using a generated virtual column, will it work for you to use `uuid()` as the column default value? Here's a quick example:
```sql
CREATE TABLE new_table (
  `idnew_table` VARCHAR(36) DEFAULT(uuid()) primary key
);

insert into new_table values ();

select * from new_table;
```

I've verified that works and inserts the UUID on the database side. One thing to note here is that some ORMs struggle with primary identifiers that are generated on the database side. For example, I hit this recently when I was working on [a blog post for the .NET Core Entity Framework ORM](https://www.dolthub.com/blog/2023-12-04-works-with-dolt-efcore/#modeling-dolt-data-with-ef-core). Essentially... some ORMs need to know the unique identifier for a row it inserts, so it needs to either create the primary key identifier itself (such as generating the uuid in the application code like you mentioned), or it can use a trick with auto_increment columns to find out what the database generated. That may or may not apply to your application, but figured I'd mention it just in case. 

Let us know if that's helpful. I'll keep digging into this panic and figure out the right fix for it.

**Comment by lly-c232733** [comment]
Appreciate the information! Actually I'm not using an ORM, so I'll be okay. I will proceed in that direction! Thanks again

**Comment by bpf120** [comment]
@lly-c232733 Thanks for giving Dolt a go! We'd love to learn more about your use case sometime. Feel free to [email me](mailto:brianf@dolthub.com) or swing by our [Discord](https://discord.gg/gqr7K4VNKe) if you'd like to share.

**Comment by fulghum** [comment]
Glad we could help!

Quick status update on the original issue... this turned out to be a gap in our support for keyless tables recording constraint violation artifacts. I've got a fix prototyped in my workspace that is passing my repro test case. I'll work on cleaning it up and adding in a bunch of tests and then get it out for review. 

Thank you for helping us find this gap so we could fix it! 🙏

**Comment by fulghum** [comment]
Quick update that the fix is merged in and will go out in a release next week.

**Comment by lly-c232733** [comment]
thanks!
