### ISSUE TITLE
Unexpected results when comparing with empty string 

### ISSUE THREAD

**Issue by suyZhong** [dolthub/dolt#7323]
Considering the test case below:

```sql
CREATE TABLE t0(c0 BOOL, PRIMARY KEY(c0));
CREATE TABLE t1(c1 VARCHAR(500));
INSERT INTO t0 (c0) VALUES (true);
INSERT INTO t0 (c0) VALUES ('');
INSERT INTO t1 (c1) VALUES (true);

SELECT * FROM t1, t0; -- true 0, true 1
SELECT (t1.c1 = t0.c0) FROM t1, t0; -- 1, 0
SELECT * FROM t1, t0 WHERE t1.c1 = t0.c0;
-- Expected: true 1
-- Actual:   Empty
```

The third `SELECT` returns an empty result, which is surprising: If the result of second query contains `1`, the value of the `=` expression should be `1` for one row, and thus the third query should return one row in `t1,t0`.

Besides, if simply changing the type of `c0` to `INTEGER`, like this:

```sql
CREATE TABLE t0(c0 INTEGER, PRIMARY KEY(c0));
CREATE TABLE t1(c1 VARCHAR(500));
INSERT INTO t0 (c0) VALUES (true);
INSERT INTO t0 (c0) VALUES ('');
INSERT INTO t1 (c1) VALUES (true);

SELECT * FROM t1, t0; -- true 0, true 1
SELECT (t1.c1 = t0.c0) FROM t1, t0; -- 1, 0
SELECT * FROM t1, t0 WHERE t1.c1 = t0.c0;
```

the server would crash on the last query:

```
panic: runtime error: slice bounds out of range [:4] with capacity 2

goroutine 783 [running]:
github.com/dolthub/dolt/go/store/val.DefaultTupleComparator.Compare({}, {0xc003fef3d4, 0x2, 0x2}, {0xc002ca7b9a, 0x6, 0x66}, {{0xc003fef418, 0x1, 0x4}, ...})
        /home/suyang/Projects/sqlancer-scale/resources/dolt/go/store/val/tuple_compare.go:46 +0x306
github.com/dolthub/dolt/go/store/val.TupleDesc.Compare({{0xc003fef418, 0x1, 0x4}, {0x31a39a0, 0x5d79fc0}, {0xc003fef42c, 0x1, 0x1}}, {0xc003fef3d4, 0x2, ...}, ...)
        /home/suyang/Projects/sqlancer-scale/resources/dolt/go/store/val/tuple_descriptor.go:132 +0xcb
github.com/dolthub/dolt/go/store/prolly/tree.newLeafCursorAtKey[...]({0x31a0340, 0xc0043d8820}, {0x31a7020, _}, {{0x68, 0xc, 0x5c, 0x6, 0x0}, {0x54, ...}, ...}, ...)
        /home/suyang/Projects/sqlancer-scale/resources/dolt/go/store/prolly/tree/node_cursor.go:192 +0x529
github.com/dolthub/dolt/go/store/prolly/tree.StaticMap[...].GetPrefix(0x324d1c0, {0x31a0340?, 0xc0043d8820?}, {0xc003fef3d4, 0x2, _}, {{0xc003fef418, 0x1, 0x4}, {0x31a39a0, ...}, ...}, ...)
        /home/suyang/Projects/sqlancer-scale/resources/dolt/go/store/prolly/tree/map.go:246 +0x125
github.com/dolthub/dolt/go/store/prolly.Map.GetPrefix(...)
        /home/suyang/Projects/sqlancer-scale/resources/dolt/go/store/prolly/tuple_map.go:262
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.(*baseLookupBuilder).newPointLookup(0xc000ea0038?, 0x1?, {{0xc0043bbd60, 0x1, 0x1}, {{0xc003fee338, 0x1, 0x4}, {0x31a39a0, 0x5d79fc0}, ...}, ...})
        /home/suyang/Projects/sqlancer-scale/resources/dolt/go/libraries/doltcore/sqle/index/index_lookup.go:364 +0x1b7
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.(*baseLookupBuilder).rangeIter(0x0?, 0x0?, {0x3189a60?, 0xc0043d3680?})
        /home/suyang/Projects/sqlancer-scale/resources/dolt/go/libraries/doltcore/sqle/index/index_lookup.go:378 +0x23b
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.(*coveringLookupBuilder).NewRowIter(0xc0043bbe00, 0x9c5d200933122995?, {0x3189a60?, 0xc0043d3680?})
        /home/suyang/Projects/sqlancer-scale/resources/dolt/go/libraries/doltcore/sqle/index/index_lookup.go:403 +0x45
github.com/dolthub/dolt/go/libraries/doltcore/sqle.(*WritableIndexedDoltTable).PartitionRows(0xc0043d0c40, 0x7f9084af4108?, {0x3189a60, 0xc0043d3680})
        /home/suyang/Projects/sqlancer-scale/resources/dolt/go/libraries/doltcore/sqle/indexed_dolt_table.go:161 +0x28f
github.com/dolthub/go-mysql-server/sql.(*TableRowIter).Next(0xc0043d11c0, 0xc0043d8820)
        /home/suyang/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.17.1-0.20240113000130-47160a130d79/sql/table_iter.go:57 +0x137
github.com/dolthub/go-mysql-server/sql/rowexec.(*joinIter).loadSecondary(0xc0043d8fa0, 0x28ae79b?)
        /home/suyang/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.17.1-0.20240113000130-47160a130d79/sql/rowexec/join_iters.go:112 +0xd1
github.com/dolthub/go-mysql-server/sql/rowexec.(*joinIter).Next(0xc0043d8fa0, 0xc002d125e0?)
        /home/suyang/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.17.1-0.20240113000130-47160a130d79/sql/rowexec/join_iters.go:136 +0x70
github.com/dolthub/go-mysql-server/sql/rowexec.transactionCommittingIter.Next(...)
        /home/suyang/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.17.1-0.20240113000130-47160a130d79/sql/rowexec/transaction_iters.go:78
github.com/dolthub/go-mysql-server/sql/plan.(*trackedRowIter).Next(0xc0043d0f80, 0xc001708eb0?)
        /home/suyang/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.17.1-0.20240113000130-47160a130d79/sql/plan/process.go:347 +0x24
github.com/dolthub/go-mysql-server/server.(*Handler).doQuery.func2()
        /home/suyang/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.17.1-0.20240113000130-47160a130d79/server/handler.go:359 +0x125
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /home/suyang/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 56
        /home/suyang/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:72 +0x96
```

Kindly inform me if they are caused by different reasons.

I originally find this by building dolt from source version c9aa36be927491bea9abc352fd968674f2ad7cc5.

**Comment by jycor** [comment]
Fortunately, an in-flight PR has the fix for this issue:
https://github.com/dolthub/go-mysql-server/pull/2256

These tests have been added to the PR
