### ISSUE TITLE
Panic on comparison in Query generated by MediaWiki.

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#7578]
```
$ dolt sql -q "SELECT keyname,exptime FROM \`objectcache\` WHERE (exptime < '20240307185006') ORDER BY exptime ASC LIMIT 100"
panic: runtime error: comparing uncomparable type []uint8

goroutine 1 [running]:
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.(*doltIndex).prollyRangesFromSqlRanges(0x14000015a20, {0x1039180e0, 0x14000a47ea0}, {0x10391ef00, 0x14000e26c80}, {0x1400000f6f8?, 0x14000a3d838?, 0x100e2e5b0?}, 0x13?)
	/Users/timsehn/dolthub/git/dolt/go/libraries/doltcore/sqle/index/dolt_index.go:1211 +0x86c
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.(*doltIndex).prollyRanges(0x14000015a20?, 0x102383518?, {0x10391ef00?, 0x14000e26c80?}, {0x1400000f5c0?, 0x14000a3d8e8?, 0x2?})
	/Users/timsehn/dolthub/git/dolt/go/libraries/doltcore/sqle/index/dolt_index.go:662 +0x94
github.com/dolthub/dolt/go/libraries/doltcore/sqle/index.NewRangePartitionIter(0x1400000f5c0?, {0x1?, 0x1?}, {{0x1039ae200, 0x14000015a20}, {0x1400000f5c0, 0x1, 0x1}, 0x0, 0x0, ...}, ...)
	/Users/timsehn/dolthub/git/dolt/go/libraries/doltcore/sqle/index/index_lookup.go:108 +0xe4
github.com/dolthub/dolt/go/libraries/doltcore/sqle.(*WritableIndexedDoltTable).LookupPartitions(0x14000a47ea0?, 0x1029ad833?, {{0x1039ae200, 0x14000015a20}, {0x1400000f5c0, 0x1, 0x1}, 0x0, 0x0, 0x0, ...})
	/Users/timsehn/dolthub/git/dolt/go/libraries/doltcore/sqle/indexed_dolt_table.go:117 +0x80
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildIndexedTableAccess(0x2000?, 0x0?, 0x14000e74850, {0x0, 0x0, 0x0})
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.18.1-0.20240307182019-a8148e98959b/sql/rowexec/rel.go:784 +0xf4
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildNodeExecNoAnalyze(0x14000a3dc78?, 0x100e31500?, {0x103929e60?, 0x14000e74850?}, {0x0?, 0x0, 0x0})
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.18.1-0.20240307182019-a8148e98959b/sql/rowexec/node_builder.gen.go:128 +0xd14
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildNodeExec(0x14000a47ea0?, 0x102983f3e?, {0x103929e60, 0x14000e74850}, {0x0?, 0x0?, 0x10df9d850?})
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.18.1-0.20240307182019-a8148e98959b/sql/rowexec/node_builder.gen.go:27 +0x28
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildFilter(0x140009b2090?, 0x100000073?, 0x1400118b120, {0x0, 0x0, 0x0})
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.18.1-0.20240307182019-a8148e98959b/sql/rowexec/rel.go:424 +0x80
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildNodeExecNoAnalyze(0x107299ab0?, 0x106ec4108?, {0x10392c610?, 0x1400118b120?}, {0x0?, 0x0, 0x0})
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.18.1-0.20240307182019-a8148e98959b/sql/rowexec/node_builder.gen.go:184 +0x12f4
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildNodeExec(0x14000a47ea0?, 0x10298686e?, {0x10392c610, 0x1400118b120}, {0x0?, 0x1?, 0x14000a3e008?})
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.18.1-0.20240307182019-a8148e98959b/sql/rowexec/node_builder.gen.go:27 +0x28
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildProject(0x3014000a3e128?, 0x1?, 0x1400091f4a0, {0x0, 0x0, 0x0})
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.18.1-0.20240307182019-a8148e98959b/sql/rowexec/rel.go:317 +0x1b8
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildNodeExecNoAnalyze(0x107299ab0?, 0x106ec4108?, {0x10392aef0?, 0x1400091f4a0?}, {0x0?, 0x0, 0x0})
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.18.1-0.20240307182019-a8148e98959b/sql/rowexec/node_builder.gen.go:242 +0x1a74
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildNodeExec(0x14000a47ea0?, 0x1039295a0?, {0x10392aef0, 0x1400091f4a0}, {0x0?, 0x1?, 0x14000a3e3f8?})
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.18.1-0.20240307182019-a8148e98959b/sql/rowexec/node_builder.gen.go:27 +0x28
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildLimit(0x14000a3e4f8?, 0x1f?, 0x1400091f4d0, {0x0, 0x0, 0x0})
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.18.1-0.20240307182019-a8148e98959b/sql/rowexec/rel.go:478 +0x204
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildNodeExecNoAnalyze(0x140009b2501?, 0x10?, {0x10392a4a0?, 0x1400091f4d0?}, {0x0?, 0x0, 0x0})
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.18.1-0.20240307182019-a8148e98959b/sql/rowexec/node_builder.gen.go:164 +0x10b0
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildNodeExec(0x14000a3e818?, 0x100d378b8?, {0x10392a4a0, 0x1400091f4d0}, {0x0?, 0x0?, 0x1?})
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.18.1-0.20240307182019-a8148e98959b/sql/rowexec/node_builder.gen.go:27 +0x28
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).Build(...)
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.18.1-0.20240307182019-a8148e98959b/sql/rowexec/builder.go:33
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildTransactionCommittingNode(0x10392a4a0?, 0x1400091f4d0?, 0x14000a3e7f8?, {0x0?, 0x14000a3e818?, 0x100d37414?})
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.18.1-0.20240307182019-a8148e98959b/sql/rowexec/transaction.go:305 +0x44
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildNodeExecNoAnalyze(0x140001c1480?, 0x40?, {0x10392a180?, 0x140009b2530?}, {0x0?, 0xb090?, 0x10725fbc0?})
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.18.1-0.20240307182019-a8148e98959b/sql/rowexec/node_builder.gen.go:48 +0x114
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildNodeExec(0x40?, 0x103436de0?, {0x10392a180, 0x140009b2530}, {0x0?, 0x1023d0ffc?, 0x10392bc60?})
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.18.1-0.20240307182019-a8148e98959b/sql/rowexec/node_builder.gen.go:27 +0x28
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).Build(...)
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.18.1-0.20240307182019-a8148e98959b/sql/rowexec/builder.go:33
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildQueryProcess(0x0?, 0x0?, 0x1400000f698, {0x0?, 0x102980cfa?, 0xa?})
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.18.1-0.20240307182019-a8148e98959b/sql/rowexec/other.go:326 +0x48
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildNodeExecNoAnalyze(0x1400118f480?, 0x6b?, {0x10392bc60?, 0x1400000f698?}, {0x0?, 0x1038ecee0?, 0x14000a3ed68?})
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.18.1-0.20240307182019-a8148e98959b/sql/rowexec/node_builder.gen.go:58 +0x204
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildNodeExec(0x1400091e000?, 0x10392a4a0?, {0x10392bc60, 0x1400000f698}, {0x0?, 0x14000a47ea0?, 0x14000a7b080?})
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.18.1-0.20240307182019-a8148e98959b/sql/rowexec/node_builder.gen.go:27 +0x28
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).Build(0x14000a7b080?, 0x10392bc60?, {0x10392bc60?, 0x1400000f698?}, {0x0?, 0x1400091e000?, 0x0?})
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.18.1-0.20240307182019-a8148e98959b/sql/rowexec/builder.go:33 +0x28
github.com/dolthub/go-mysql-server.(*Engine).QueryWithBindings(0x14000a7b080, 0x14000a47ea0, {0x14000abc000?, 0x100d8375c?}, {0x0, 0x0}, 0x100d9b060?)
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.18.1-0.20240307182019-a8148e98959b/engine.go:402 +0x290
github.com/dolthub/go-mysql-server.(*Engine).Query(...)
	/Users/timsehn/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.18.1-0.20240307182019-a8148e98959b/engine.go:246
github.com/dolthub/dolt/go/cmd/dolt/commands/engine.(*SqlEngine).Query(0x14000a3ef78?, 0x100d96c80?, {0x14000abc000?, 0x6b?})
	/Users/timsehn/dolthub/git/dolt/go/cmd/dolt/commands/engine/sqlengine.go:301 +0x30
github.com/dolthub/dolt/go/cmd/dolt/commands.processParsedQuery(0x14000abc000?, {0x14000abc000?, 0x6b?}, {0x1038fa5a0?, 0x140007d60f0?}, {0x103906c20?, 0x140001369c0?})
	/Users/timsehn/dolthub/git/dolt/go/cmd/dolt/commands/sql.go:1091 +0x39c
github.com/dolthub/dolt/go/cmd/dolt/commands.execBatchMode(0x14000a47ea0, {0x1038fa5a0, 0x140007d60f0}, {0x1038f9840?, 0x140006dfdc0}, 0x0, 0x0?)
	/Users/timsehn/dolthub/git/dolt/go/cmd/dolt/commands/sql.go:643 +0x3b8
github.com/dolthub/dolt/go/cmd/dolt/commands.queryMode(0x1034e8a40?, {0x1038fa5a0, 0x140007d60f0}, 0x4?, {0x16f0d7974, 0x6b}, 0x2?, 0x2?)
	/Users/timsehn/dolthub/git/dolt/go/cmd/dolt/commands/sql.go:394 +0xc8
github.com/dolthub/dolt/go/cmd/dolt/commands.SqlCmd.Exec({{0x10297625c?, 0x141aefee37c47f9?}}, {0x103917d60, 0x14000b8ed80}, {0x14000e77be0, 0x8}, {0x140001c0020, 0x2, 0x2}, 0x140010b22d0, ...)
	/Users/timsehn/dolthub/git/dolt/go/cmd/dolt/commands/sql.go:223 +0x494
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.handleCommand({{0x102972eae, 0x4}, {0x102992967, 0x11}, {0x0, 0x0}, {0x106430040, 0x35, 0x35}, 0x0}, ...)
	/Users/timsehn/dolthub/git/dolt/go/cmd/dolt/cli/command.go:245 +0x3e4
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.Exec({{0x102972eae, 0x4}, {0x102992967, 0x11}, {0x0, 0x0}, {0x106430040, 0x35, 0x35}, 0x0}, ...)
	/Users/timsehn/dolthub/git/dolt/go/cmd/dolt/cli/command.go:194 +0x254
main.runMain()
	/Users/timsehn/dolthub/git/dolt/go/cmd/dolt/dolt.go:640 +0x2d9c
main.main()
	/Users/timsehn/dolthub/git/dolt/go/cmd/dolt/dolt.go:250 +0x1c
```

**Comment by fulghum** [comment]
Schema for `objectcache` table:
```sql
CREATE TABLE `objectcache` (
`keyname` varbinary(255) NOT NULL DEFAULT '',
`value` mediumblob DEFAULT NULL,
`exptime` binary(14) NOT NULL,
`modtoken` varbinary(17) NOT NULL DEFAULT '00000000000000000',
`flags` int unsigned DEFAULT NULL,
PRIMARY KEY (`keyname`),
KEY `exptime` (`exptime`)
);
```
