### ISSUE TITLE
date conversion panic

### ISSUE THREAD

**Issue by andrew-wm-arthur** [dolthub/dolt#779]
on [NVD](https://www.dolthub.com/repositories/Liquidata/NVD) repo
```
dolt sql -q 'select avg(impact_score) from cve where date_published > (now() - interval 1 month)'
panic: unresolved column is a placeholder node, but Type was called

goroutine 1 [running]:
github.com/liquidata-inc/go-mysql-server/sql/expression.(*UnresolvedColumn).Type(0xc000be26e0, 0x203000, 0xc00037ec80)
	/Users/andyarthur/go/pkg/mod/github.com/liquidata-inc/go-mysql-server@v0.5.1-0.20200626235830-808131cf28be/sql/expression/unresolved.go:46 +0x39
github.com/liquidata-inc/go-mysql-server/sql/analyzer.addDateConvert(0x27f7360, 0xc000be26e0, 0x27ef020, 0xc000d38f00, 0xc0009d6eb0, 0xc0009d6af8, 0xc0009d6ac8, 0xc00051de01, 0x3d407d0, 0x10, ...)
	/Users/andyarthur/go/pkg/mod/github.com/liquidata-inc/go-mysql-server@v0.5.1-0.20200626235830-808131cf28be/sql/analyzer/convert_dates.go:163 +0xd5
github.com/liquidata-inc/go-mysql-server/sql/analyzer.convertDates.func1.1(0x27f7360, 0xc000be26e0, 0x0, 0x0, 0x100ee68, 0x10)
	/Users/andyarthur/go/pkg/mod/github.com/liquidata-inc/go-mysql-server@v0.5.1-0.20200626235830-808131cf28be/sql/analyzer/convert_dates.go:52 +0x6e
github.com/liquidata-inc/go-mysql-server/sql/expression.TransformUp(0x27f7360, 0xc000be26e0, 0xc0009d6aa0, 0xc00051deb0, 0xd31bea8ac2ba21d, 0x7, 0xd0000c0009d68c8)
	/Users/andyarthur/go/pkg/mod/github.com/liquidata-inc/go-mysql-server@v0.5.1-0.20200626235830-808131cf28be/sql/expression/transform.go:12 +0x223
github.com/liquidata-inc/go-mysql-server/sql/expression.TransformUp(0x27f8b00, 0xc00051dde0, 0xc0009d6aa0, 0xc00051de90, 0xc0009d6c40, 0x10e1901, 0xc0007a24c4)
	/Users/andyarthur/go/pkg/mod/github.com/liquidata-inc/go-mysql-server@v0.5.1-0.20200626235830-808131cf28be/sql/expression/transform.go:17 +0xb8
github.com/liquidata-inc/go-mysql-server/sql/analyzer.convertDates.func1(0x27ef020, 0xc000d38f00, 0x1, 0x1, 0x27ef020, 0xc000d38f00)
	/Users/andyarthur/go/pkg/mod/github.com/liquidata-inc/go-mysql-server@v0.5.1-0.20200626235830-808131cf28be/sql/analyzer/convert_dates.go:51 +0x5e0
github.com/liquidata-inc/go-mysql-server/sql/plan.TransformUp(0x27ef020, 0xc000d38ec0, 0xc0009d6ea0, 0xc00040ea70, 0xe, 0xc00037ec80, 0x3)
	/Users/andyarthur/go/pkg/mod/github.com/liquidata-inc/go-mysql-server@v0.5.1-0.20200626235830-808131cf28be/sql/plan/transform.go:34 +0x1d6
github.com/liquidata-inc/go-mysql-server/sql/analyzer.convertDates(0xc000c303f0, 0xc00052eb90, 0x27ef020, 0xc000d38ec0, 0x27ef020, 0xc000d38ec0, 0x0, 0x0)
	/Users/andyarthur/go/pkg/mod/github.com/liquidata-inc/go-mysql-server@v0.5.1-0.20200626235830-808131cf28be/sql/analyzer/convert_dates.go:22 +0xe1
github.com/liquidata-inc/go-mysql-server/sql/analyzer.(*Batch).evalOnce(0xc00020c810, 0xc000c303f0, 0xc00052eb90, 0x27ef020, 0xc000d38bc0, 0x27ef020, 0xc000d38bc0, 0x0, 0x0)
	/Users/andyarthur/go/pkg/mod/github.com/liquidata-inc/go-mysql-server@v0.5.1-0.20200626235830-808131cf28be/sql/analyzer/batch.go:73 +0x10c
github.com/liquidata-inc/go-mysql-server/sql/analyzer.(*Batch).Eval(0xc00020c810, 0xc000c303f0, 0xc00052eb90, 0x27ef020, 0xc000d38bc0, 0x27ef020, 0xc000d38bc0, 0x0, 0x0)
	/Users/andyarthur/go/pkg/mod/github.com/liquidata-inc/go-mysql-server@v0.5.1-0.20200626235830-808131cf28be/sql/analyzer/batch.go:40 +0xcf
github.com/liquidata-inc/go-mysql-server/sql/analyzer.(*Analyzer).Analyze(0xc00052eb90, 0xc000c303f0, 0x27ef020, 0xc000364c00, 0x0, 0x0, 0x0, 0x0)
	/Users/andyarthur/go/pkg/mod/github.com/liquidata-inc/go-mysql-server@v0.5.1-0.20200626235830-808131cf28be/sql/analyzer/analyzer.go:217 +0x310
github.com/liquidata-inc/go-mysql-server.(*Engine).Query(0xc00052c380, 0xc000c302d0, 0x7ffeefbffb34, 0x53, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/andyarthur/go/pkg/mod/github.com/liquidata-inc/go-mysql-server@v0.5.1-0.20200626235830-808131cf28be/engine.go:150 +0x2a7
github.com/liquidata-inc/dolt/go/cmd/dolt/commands.(*sqlEngine).query(...)
	/Users/andyarthur/LD/dolt/go/cmd/dolt/commands/sql.go:1151
github.com/liquidata-inc/dolt/go/cmd/dolt/commands.processQuery(0xc000c30120, 0x7ffeefbffb34, 0x53, 0xc00052d0c0, 0x0, 0xc00052eaa0, 0x1, 0x1, 0xc00052d0c0, 0x0, ...)
	/Users/andyarthur/LD/dolt/go/cmd/dolt/commands/sql.go:823 +0x9c1
github.com/liquidata-inc/dolt/go/cmd/dolt/commands.execQuery(0xc000c30120, 0xc000be1f00, 0xc00020c450, 0xc0009d78e8, 0x7ffeefbffb34, 0x53, 0xc000123500, 0x0, 0x0, 0x0)
	/Users/andyarthur/LD/dolt/go/cmd/dolt/commands/sql.go:390 +0x123
github.com/liquidata-inc/dolt/go/cmd/dolt/commands.SqlCmd.Exec(0x241179d, 0x6, 0x27e1560, 0xc00011c300, 0xc000504b88, 0x8, 0xc000138020, 0x2, 0x2, 0xc000469c30, ...)
	/Users/andyarthur/LD/dolt/go/cmd/dolt/commands/sql.go:261 +0xd89
github.com/liquidata-inc/dolt/go/cmd/dolt/cli.SubCommandHandler.Exec(0x240fc89, 0x4, 0x2423310, 0x11, 0xc00000c3c0, 0x1e, 0x1e, 0x0, 0x27e1560, 0xc00011c300, ...)
	/Users/andyarthur/LD/dolt/go/cmd/dolt/cli/command.go:164 +0x475
main.runMain(0x0)
	/Users/andyarthur/LD/dolt/go/cmd/dolt/dolt.go:209 +0xbfe
main.main()
	/Users/andyarthur/LD/dolt/go/cmd/dolt/dolt.go:96 +0x22
```

**Comment by andrew-wm-arthur** [comment]
@zachmu @Hydrocharged

**Comment by zachmu** [comment]
That's bad, will fix

**Comment by VinaiRachakonda** [comment]
This no longer panics. Closing
