### ISSUE TITLE
Crash when refreshing statistics after a PK column change

### ISSUE THREAD

**Issue by fulghum** [dolthub/dolt#8504]
While testing another scenario, I changed the type of a column in a table's primary key, and the next time a stats refresh ran, the Dolt sql-server panic'ed and crashed with the following error:
```
DEBU[0240] starting statistics refresh check for 'db1': 2024-10-29 12:00:27.211707 -0700 PDT m=+240.228087043 
DEBU[0240] statistics refresh: new table hash: ge3hd5bhs3bli51hovhijn58a9ou1ioc 
DEBU[0240] statistics refresh index: db1.t.primary      
DEBU[0240] statistics current: 167, new: 163, delete: 167 
DEBU[0240] statistics updating: db1.t.primary           
panic: interface conversion: interface {} is int32, not string

goroutine 119 [running]:
github.com/dolthub/dolt/go/store/prolly/tree.PutField({0x103190e48, 0x14000dee6e0}, {0x10319e2f0, 0x14000a0e8c0}, 0x14000e507e0, 0x0, {0x102c4d2e0?, 0x1047828a0?})
	github.com/dolthub/dolt/go/store/prolly/tree/prolly_fields.go:225 +0x16e0
github.com/dolthub/dolt/go/libraries/doltcore/sqle/statsnoms.EncodeRow({0x103190e48, 0x14000dee6e0}, {0x10319e2f0, 0x14000a0e8c0}, {0x1400340f3c0?, 0x1, 0x103197000?}, 0x14000e507e0)
	github.com/dolthub/dolt/go/libraries/doltcore/sqle/statsnoms/write.go:163 +0x74
github.com/dolthub/dolt/go/libraries/doltcore/sqle/statsnoms.putIndexRows({0x103190e48, 0x14000dee6e0}, 0x14000276a80, 0x14000a18e10)
	github.com/dolthub/dolt/go/libraries/doltcore/sqle/statsnoms/write.go:130 +0x7bc
github.com/dolthub/dolt/go/libraries/doltcore/sqle/statsnoms.(*NomsStatsDatabase).replaceStats(0x14000b87560?, {0x103190e48, 0x14000dee6e0}, 0x14000276a80, 0x14000a18e10)
	github.com/dolthub/dolt/go/libraries/doltcore/sqle/statsnoms/write.go:45 +0x60
github.com/dolthub/dolt/go/libraries/doltcore/sqle/statsnoms.(*NomsStatsDatabase).setStat(0x14000b87560, {0x103190e48, 0x14000dee6e0}, {0x1400249d71b, 0x4}, {{0x1400059231e, 0x3}, {0x14000592322, 0x1}, {0x14000592324, ...}}, ...)
	github.com/dolthub/dolt/go/libraries/doltcore/sqle/statsnoms/database.go:214 +0x228
github.com/dolthub/dolt/go/libraries/doltcore/sqle/statsnoms.(*NomsStatsDatabase).ReplaceChunks(0x14000b87560, {0x103190e48, 0x14000dee6e0}, {0x1400249d71b, 0x4}, {{0x1400059231e, 0x3}, {0x14000592322, 0x1}, {0x14000592324, ...}}, ...)
	github.com/dolthub/dolt/go/libraries/doltcore/sqle/statsnoms/database.go:317 +0x4d8
github.com/dolthub/dolt/go/libraries/doltcore/sqle/statspro.(*Provider).checkRefresh(0x14000a19db0, 0x14000dee6e0, {0x10318ab60, 0x14000562e40}, {0x14000af9276, 0x3}, {0x1400249d71b, 0x4}, 0x3fe0000000000000)
	github.com/dolthub/dolt/go/libraries/doltcore/sqle/statspro/auto_refresh.go:226 +0x1240
github.com/dolthub/dolt/go/libraries/doltcore/sqle/statspro.(*Provider).InitAutoRefreshWithParams.func1({0x103190b28, 0x14000c779a0})
	github.com/dolthub/dolt/go/libraries/doltcore/sqle/statspro/auto_refresh.go:94 +0x430
github.com/dolthub/go-mysql-server/sql.(*BackgroundThreads).Add.func1()
	github.com/dolthub/go-mysql-server@v0.18.2-0.20241023223952-9322ec486dc1/sql/background_threads.go:67 +0x60
created by github.com/dolthub/go-mysql-server/sql.(*BackgroundThreads).Add in goroutine 114
	github.com/dolthub/go-mysql-server@v0.18.2-0.20241023223952-9322ec486dc1/sql/background_threads.go:65 +0x20c
```

Here's a simple repro for a fresh Dolt db in a running sql-server: 
```sql
create table t (pk int primary key, c1 varchar(100));
insert into t values (1, "one");
-- Wait for Dolt sql-server logs to show that stats refresh has run on table t
alter table t modify column pk varchar(200);
-- Wait for stats refresh to run again; should panic and crash dolt 
```

**Comment by timsehn** [comment]
@max-hoffman this would be a good ione to fix quick :-)
