### ISSUE TITLE
Bad error for `SELECT ... INTO ...`

### ISSUE THREAD

**Issue by max-hoffman** [dolthub/dolt#8539]
repro:
```sql
Create table rawdata (
  Id int primary key,
  name varchar(10),
  Metadata varchar(10),
  statistical enum('yes','no','uncertain'),
  Robustness enum('yes','no','uncertain')
);


CREATE TABLE data LIKE rawdata;

SELECT
id, name, metadata,
  CASE
    WHEN statistical = 'yes' THEN robustness
    ELSE NULL
  END as robustness
 from rawdata
INTO data;

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x28 pc=0x106557f6c]

goroutine 1 [running]:
github.com/dolthub/go-mysql-server/sql/planbuilder.(*Builder).BindOnly.func1()
	/Users/maxhoffman/go/github.com/dolthub/go-mysql-server/sql/planbuilder/parse.go:99 +0x98
panic({0x107a9ef40?, 0x1093e5c20?})
	/Users/maxhoffman/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.7.darwin-arm64/src/runtime/panic.go:770 +0x124
github.com/dolthub/go-mysql-server/sql/planbuilder.(*procCtx).GetVar(0x0, {0x14000011da0, 0x4})
	/Users/maxhoffman/go/github.com/dolthub/go-mysql-server/sql/planbuilder/proc.go:89 +0x6c
github.com/dolthub/go-mysql-server/sql/planbuilder.(*Builder).buildInto(0x14000943ad0?, 0x14000994780, 0x14000af3ce0)
	/Users/maxhoffman/go/github.com/dolthub/go-mysql-server/sql/planbuilder/dml.go:734 +0x680
github.com/dolthub/go-mysql-server/sql/planbuilder.(*Builder).buildSubquery(0x14000943ad0, 0x14000cecf00?, {0x107eab348, 0x140005b36c0}, {0x14000aa8630, 0x88}, {0x14000aa8630?, 0x88?})
	/Users/maxhoffman/go/github.com/dolthub/go-mysql-server/sql/planbuilder/builder.go:225 +0x2130
github.com/dolthub/go-mysql-server/sql/planbuilder.(*Builder).build(...)
	/Users/maxhoffman/go/github.com/dolthub/go-mysql-server/sql/planbuilder/builder.go:212
github.com/dolthub/go-mysql-server/sql/planbuilder.(*Builder).BindOnly(0x14000943ad0, {0x107eab348, 0x140005b36c0}, {0x14000aa8630, 0x88}, 0x0)
	/Users/maxhoffman/go/github.com/dolthub/go-mysql-server/sql/planbuilder/parse.go:111 +0x134
```

**Comment by jycor** [comment]
With stored procedure rewrite, this no longer panics, but throws a bad a error.
```sql
james@macbook tmp % dolt sql
# Welcome to the DoltSQL shell.
# Statements must be terminated with ';'.
# "exit" or "quit" (or Ctrl-D) to exit. "\help" for help.
tmp/main*> Create table rawdata (
        ->   Id int primary key,
        ->   name varchar(10),
        ->   Metadata varchar(10),
        ->   statistical enum('yes','no','uncertain'),
        ->   Robustness enum('yes','no','uncertain')
        -> );
tmp/main*> CREATE TABLE data LIKE rawdata;
tmp/main*> SELECT
        -> id, name, metadata,
        ->   CASE
        ->     WHEN statistical = 'yes' THEN robustness
        ->     ELSE NULL
        ->   END as robustness
        ->  from rawdata
        -> INTO data;
external stored procedures require the first parameter to be the context%!(EXTRA string=data)
```

This is expected MySQL output with simpler repro:
```sql
mysql> create table t (i int);
Query OK, 0 rows affected (0.01 sec)

mysql> select 1 into t;
ERROR 1327 (42000): Undeclared variable: t
```

Additionally, MySQL doesn't actually support `SELECT ... INTO ...` statements for tables.
Only user variables and variables defined within procedures. [Docs here](https://dev.mysql.com/doc/refman/8.0/en/select-into.html).

We should fix the error to match MySQL.
